import csv

T = {
    'ui#320': ('By Req. Level', ''),
    'ui#321': ('By Attack', ''),
    'ui#322': ('By M. Atk', ''),
    'ui#323': ('By Defense', ''),
    'ui#324': ('By M. Def', ''),
    'ui#325': ('By Rarity', ''),
    'ui#326': ('Alphabetical Asc', ''),
    'ui#327': ('Alphabetical Desc', ''),
    'ui#328': ('By Skill', ''),
    'ui#329': ('By Max HP Boost', ''),
    'ui#330': ('By Max TP Boost', ''),
    'ui#331': ('By P. Atk Boost', ''),
    'ui#332': ('By M. Atk Boost', ''),
    'ui#333': ('By P. Def Boost', ''),
    'ui#334': ('By M. Def Boost', ''),
    'ui#335': ('Monster Name', ''),
    'ui#336': ('???', ''),
    'ui#337': ('Standard', ''),
    'ui#338': ('Level: Low to High', ''),
    'ui#339': ('Level: High to Low', ''),
    'ui#340': ('Name: A to Z', ''),
    'ui#341': ('Name: Z to A', ''),
    'ui#342': ('Main Habitat', ''),
    'ui#343': ('Level', ''),
    'ui#344': ('HP', ''),
    'ui#345': ('P. Atk', ''),
    'ui#346': ('P. Def', ''),
    'ui#347': ('M. Atk', ''),
    'ui#348': ('M. Def', ''),
    'ui#349': ('Weakness', ''),
    'ui#350': ('Resist', ''),
    'ui#351': ('Agility', ''),
    'ui#352': ('Base EXP', ''),
    'ui#353': ('Gald', ''),
    'ui#354': ('Held Items', ''),
    'ui#355': ('Stealable Items', ''),
    'ui#356': ('Ineffective Items', ''),
    'ui#357': ('1H Sword', ''),
    'ui#358': ('2H Sword', ''),
    'ui#359': ('Dagger', ''),
    'ui#360': ('Gun', ''),
    'ui#361': ('Special Weapon', ''),
    'ui#362': ('Novelty Weapon', ''),
    'ui#363': ('Hat', ''),
    'ui#364': ('Face Equip', ''),
    'ui#365': ('Robe', ''),
    'ui#366': ('Gauntlets', ''),
    'ui#367': ('Bangle', ''),
    'ui#368': ('Legs Equip', ''),
    'ui#369': ('-----', ''),
    'ui#370': ('Defeated', ''),
    'ui#371': ('Unknown', ''),
    'ui#372': (' Weapon Book', ''),
    'ui#373': (' Armor Book', ''),
    'ui#374': ('Check weapon collection status.', ''),
    'ui#375': ('Check armor collection status.', ''),
    'ui#376': (' 1H Sword', ''),
    'ui#377': (' 2H Sword', ''),
    'ui#378': (' Dagger', ''),
    'ui#379': (' Axe', ''),
    'ui#380': (' Staff', ''),
    'ui#381': (' Fists', ''),
    'ui#382': (' Bow', ''),
    'ui#383': (' Gun', ''),
    'ui#384': (' Special Weapon', ''),
    'ui#385': (' Novelty Weapon', ''),
    'ui#386': (' Armor', ''),
    'ui#387': (' Clothes', ''),
    'ui#388': (' Robe', ''),
    'ui#389': (' Helm', ''),
    'ui#390': (' Hat', ''),
    'ui#391': (' Face Equip', ''),
    'ui#392': (' Gauntlets', ''),
    'ui#393': (' Bangle', ''),
    'ui#394': (' Legs Equip', ''),
    'ui#395': (' Shield', ''),
    'ui#396': ('Check 1H sword collection status.', ''),
    'ui#397': ('Check 2H sword collection status.', ''),
    'ui#398': ('Check dagger collection status.', ''),
    'ui#399': ('Check axe collection status.', ''),
    'ui#400': ('Check staff collection status.', ''),
    'ui#401': ('Check fists collection status.', ''),
    'ui#402': ('Check bow collection status.', ''),
    'ui#403': ('Check gun collection status.', ''),
    'ui#404': ('Check special weapon status.', ''),
    'ui#405': ('Check novelty weapon status.', ''),
    'ui#406': ('Check armor collection status.', ''),
    'ui#407': ('Check clothes collection status.', ''),
    'ui#408': ('Check robe collection status.', ''),
    'ui#409': ('Check helm collection status.', ''),
    'ui#410': ('Check hat collection status.', ''),
    'ui#411': ('Check face gear collection status.', ''),
    'ui#412': ('Check gauntlet collection status.', ''),
    'ui#413': ('Check bangle collection status.', ''),
    'ui#414': ('Check leg gear collection status.', ''),
    'ui#415': ('Check shield collection status.', ''),
    'ui#416': ('Equipment not yet acquired.', ''),
    'ui#417': ('Req. Lv', ''),
    'ui#418': ('Attack', ''),
    'ui#419': ('Defense', ''),
    'ui#420': ('Agi', ''),
    'ui#421': ('Rate', ''),
    'ui#422': ('All', ''),
    'ui#423': ('Info Rate', ''),
    'ui#424': ('Total Kills', ''),
    'ui#425': ('???', ''),
    'ui#426': ('Normal', ''),
    'ui#427': ('Hard', ''),
    'ui#428': ('Mania', ''),
    'ui#429': ('Do Not Apply', ''),
    'ui#430': ('Apply', ''),
    'ui#431': ('Reset', ''),
    'ui#432': ('Restore Default', ''),
    'ui#433': ('Message Speed', ''),
    'ui#434': ('Difficulty', ''),
    'ui#435': ('Sound Test', ''),
    'ui#436': ('Sound Select', ''),
    'ui#437': ('BGM Volume', ''),
    'ui#438': ('SE Volume', ''),
    'ui#439': ('Battle Voice Volume', ''),
    'ui#440': ('Event Voice Volume', ''),
    'ui#441': ('Encounter Camera', ''),
    'ui#442': ('Data Install', ''),
    'ui#443': ('Change Player Name', ''),
    'ui#444': ('Slow', ''),
    'ui#445': ('Normal', ''),
    'ui#446': ('Fast', ''),
    'ui#447': ('Instant', ''),
    'ui#448': ('Van Eltia', ''),
    'ui#449': ('Standard BGM', ''),
    'ui#450': ('Story Battle BGM', ''),
    'ui#451': ('Boss Battle BGM', ''),
    'ui#452': ('Final Battle 1', ''),
    'ui#453': ('Final Battle 2', ''),
    'ui#454': ('Default Play', ''),
    'ui#455': ('Random Play', ''),
    'ui#456': ('ON', ''),
    'ui#457': ('OFF', ''),
    'ui#458': ('Locked option.', ''),
    'ui#459': ('Displays messages slowly.', ''),
    'ui#460': ('Displays messages at normal speed.', ''),
    'ui#461': ('Displays messages quickly.', ''),
    'ui#462': ('Displays messages instantly.', ''),
    'ui#463': ('Standard battle difficulty.', ''),
    'ui#464': ('Sets battle difficulty to Hard.', ''),
    'ui#465': ('Sets battle difficulty to Mania.', ''),
    'ui#466': ('Changes battle music.', ''),
    'ui#467': ('Changes Van Eltia ship music.', ''),
    'ui#468': ('Changes normal battle music.', ''),
    'ui#469': ('Changes boss battle music.', ''),
    'ui#470': ('Changes final battle music.', ''),
    'ui#471': ('Adjusts game BGM volume.', ''),
    'ui#472': ('Adjusts game SE volume.', ''),
    'ui#473': ('Adjusts battle voice volume.', ''),
    'ui#474': ('Adjusts event voice volume.', ''),
    'ui#475': ('Enables camera motion on encounter.', ''),
    'ui#476': ('Disables camera motion on encounter.', ''),
    'ui#477': ('Uses installed game data.', ''),
    'ui#478': ('Does not use installed game data.', ''),
    'ui#479': ('Changes player name.', ''),
    'ui#480': ('Please enter player name.', ''),
    'ui#481': ('Unconfigured items remain.', ''),
    'ui#482': ('Displays messages slowly.', ''),
    'ui#483': ('Displays messages at normal speed.', ''),
    'ui#484': ('Displays messages quickly.', ''),
    'ui#485': ('Displays messages instantly.', ''),
    'ui#486': ('Standard difficulty.', ''),
    'ui#487': ('Affects combat difficulty and item drop rates.', ''),
    'ui#488': ('Changes battle music.', ''),
    'ui#489': ('Changes normal battle music.', ''),
    'ui#490': ('Changes boss battle music.', ''),
    'ui#491': ('Changes final battle music.', ''),
    'ui#492': ('Plays character voices during battle.', ''),
    'ui#493': ('Does not play voices during battle.', ''),
    'ui#494': ('Enables camera motion on encounter.', ''),
    'ui#495': ('Disables camera motion on encounter.', ''),
    'ui#496': ('Changes player name.', ''),
    'ui#497': ('Name has not been set.', ''),
    'ui#498': ('Class', ''),
    'ui#499': ('Level', ''),
    'ui#500': ('HP', ''),
    'ui#501': ('TP', ''),
    'ui#502': ('EXP', ''),
    'ui#503': ('To Next Level', ''),
    'ui#504': ('P. Atk', ''),
    'ui#505': ('P. Atk 2', ''),
    'ui#506': ('P. Def', ''),
    'ui#507': ('M. Atk', ''),
    'ui#508': ('M. Def', ''),
    'ui#509': ('Agility', ''),
    'ui#510': ('Inflict Poison', ''),
    'ui#511': ('Inflict Poison, W1', ''),
    'ui#512': ('Inflict Poison, W2', ''),
    'ui#513': ('Inflict Paralysis', ''),
    'ui#514': ('Inflict Paralysis, W1', ''),
    'ui#515': ('Inflict Paralysis, W2', ''),
    'ui#516': ('Guard Break', ''),
    'ui#517': ('Guard Break, W1', ''),
    'ui#518': ('Guard Break, W2', ''),
    'ui#519': ('Stun Resist Break', ''),
    'ui#520': ('Stun Resist Break, W1', ''),
    'ui#521': ('Stun Resist Break, W2', ''),
    'ui#522': ('Guard Boost', ''),
    'ui#523': ('Stun Resistance', ''),
    'ui#524': ('TP Consumption', ''),
    'ui#525': ('Result TP Recovery', ''),
    'ui#526': ('Normal Attack TP Gain', ''),
    'ui#527': ('Normal Attack TP Gain, W1', ''),
    'ui#528': ('Normal Attack TP Gain, W2', ''),
    'ui#529': ('Cast Time', ''),
    'ui#530': ('Critical Damage', ''),
    'ui#531': ('Critical Damage, W1', ''),
    'ui#532': ('Critical Damage, W2', ''),
    'ui#533': ('Overlimit Boost', ''),
    'ui#534': ('Overlimit Boost, W1', ''),
    'ui#535': ('Overlimit Boost, W2', ''),
    'ui#536': ('Gald Earned', ''),
    'ui#537': ('EXP Earned', ''),
    'ui#538': ('Grade Points Earned', ''),
    'ui#539': ('Item Drops', ''),
    'ui#540': ('Rare Drops', ''),
    'ui#541': ('Skill Slots Up', ''),
    'ui#542': ('Harvest Boost', ''),
    'ui#543': ('Mining Boost', ''),
    'ui#544': ('Chest Drop Effect', ''),
    'ui#545': ('Prevent Poison', ''),
    'ui#546': ('Prevent Weakness', ''),
    'ui#547': ('Prevent Stun', ''),
    'ui#548': ('Prevent Arte Seal', ''),
    'ui#549': ('Prevent Paralysis', ''),
    'ui#550': ('Prevent Petrifaction', ''),
    'ui#551': ('Water Defense', ''),
    'ui#552': ('Earth Defense', ''),
    'ui#553': ('Fire Defense', ''),
    'ui#554': ('Wind Defense', ''),
    'ui#555': ('Light Defense', ''),
    'ui#556': ('Dark Defense', ''),
    'ui#557': ('Escape Time Cut', ''),
    'ui#558': ('HP Recovery on Defeat', ''),
    'ui#559': ('TP Recovery on Defeat', ''),
    'ui#560': ('Enemy Aggro Rate', ''),
    'ui#561': ('Buy Weapons', ''),
    'ui#562': ('Buy Weapons by Category', ''),
    'ui#563': ('Buy Armor', ''),
    'ui#564': ('Buy Armor by Category', ''),
    'ui#565': ('Buy Items', ''),
    'ui#566': ('Buy Accessories', ''),
    'ui#567': ('Buy Craft Materials', ''),
    'ui#568': ('Synthesize Weapon', ''),
    'ui#569': ('Upgrade Weapon', ''),
    'ui#570': ('Synthesize Armor', ''),
    'ui#571': ('Upgrade Armor', ''),
    'ui#572': ('Sell', ''),
    'ui#573': ('Trade', ''),
    'ui#574': ('Trade by Category', ''),
    'ui#575': ('Price', ''),
    'ui#576': ('Quantity', ''),
    'ui#577': ('Sell Count', ''),
    'ui#578': ('In Bag', ''),
    'ui#579': ('Funds', ''),
    'ui#580': ('Total', ''),
    'ui#581': ('Purchase?', ''),
    'ui#582': ('Includes Radiant and unique gear. Still sell?', ''),
    'ui#583': ('Includes Radiant gear. Still sell?', ''),
    'ui#584': ('Includes unique gear. Still sell?', ''),
    'ui#585': ('Sell this?', ''),
    'ui#586': ('Grade Points Held', ''),
    'ui#587': ('Trade for this?', ''),
    'ui#588': ('Cannot trade due to insufficient Grade.', ''),
    'ui#589': ('Cannot Equip', ''),
    'ui#590': ('Equippable Class', ''),
    'ui#591': ('Equippable Characters', ''),
    'ui#592': ('Attack Change', ''),
    'ui#593': ('M. Atk Change', ''),
    'ui#594': ('Agility Change', ''),
    'ui#595': ('Defense Change', ''),
    'ui#596': ('M. Def Change', ''),
    'ui#597': ('Equip requirements not met.', ''),
    'ui#598': ('Cannot try on due to low level.', ''),
    'ui#599': ('Cannot try on with this class.', ''),
    'ui#600': ('Equip this?', ''),
    'ui#601': ('Cannot hold any more equipment.', ''),
    'ui#602': ('Taking this item allows you', ''),
    'ui#603': ('to restart the story from beginning, keeping level and gear.', ''),
    'ui#604': ('Some items will not carry over.', ''),
    'ui#605': ('Are you ready for this?', ''),
    'ui#606': ('Store Equipment', ''),
    'ui#607': ('Retrieve Equipment', ''),
    'ui#608': ('Withdraw Item', ''),
    'ui#609': ('Sell', ''),
    'ui#610': ('Newest', ''),
    'ui#611': ('Recently Added', ''),
    'ui#612': ('Strategy Config', ''),
    'ui#613': ('Select member to set general and priority actions.', ''),
    'ui#614': ('Fight Freely', ''),
    'ui#615': ('All-Out Attack', ''),
    'ui#616': ('Melee Combat', ''),
    'ui#617': ('Ranged Combat', ''),
    'ui#618': ('Support Combat', ''),
    'ui#619': ('Defensive Combat', ''),
    'ui#620': ('Conserve TP', ''),
    'ui#621': ('Attack', ''),
    'ui#622': ('Defense', ''),
    'ui#623': ('Recovery', ''),
    'ui#624': ('Support', ''),
    'ui#625': ('Other', ''),
    'ui#626': ('Fledgling', ''),
    'ui#627': ('Novice', ''),
    'ui#628': ('Intermediate', ''),
    'ui#629': ('Veteran', ''),
    'ui#630': ('Formation upon encounter', ''),
    'ui#631': ('Strategy Name', ''),
    'ui#632': ('Base Action', ''),
    'ui#633': ('Prioritize HP Heal', ''),
    'ui#634': ('Prioritize TP Heal', ''),
    'ui#635': ('Prioritize Status Cure', ''),
    'ui#636': ('Remove', ''),
    'ui#637': ('Toggle Usage', ''),
    'ui#638': ('Arte Usage', ''),
    'ui#639': ('Currently Equipped Title', ''),
}

with open('lotes_p68/UI-02.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

missing = []
for r in rows:
    rid = r['id']
    if rid not in T:
        missing.append(rid)
    else:
        tr, nt = T[rid]
        r['traducao'] = tr
        if nt:
            r['nota_do_tradutor'] = nt

if missing:
    print("MISSING:", len(missing), missing[:5])
else:
    out_p = 'lotes_p68/UI-02_retorno.tsv'
    with open(out_p, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
        w.writeheader()
        w.writerows(rows)
    print("Wrote", out_p)
