import json, re
from val_check import validate_dict

# Load VAL-01
d = json.load(open('dados/item_equip_shrink/VAL-01.json', encoding='utf-8'))
itens = d['itens']
meta = d['meta_bytes_a_cortar']

# Hand-crafted map of overrides
overrides = {
    'valuables#910': 'Secret arte: follows dual slashes by slamming the ground with shockwaves.',
    'valuables#1028': 'Arcane arte: slashes foes skyward with spin impacts and flashing thrusts.',
    'valuables#1560': 'Where God resides, what shatters is person. In other words, Me: Arcane Arte.',
    'valuables#227': 'A key to contact other worlds. It seems to have lost its magic power.',
    'valuables#783': 'Arcane arte: whirlwinds vortex from thrusting a spear into the ground.',
    'valuables#87': 'A letter torn to shreds. The writing is illegible, but the grudge is real.',
    'valuables#110': 'Paper that breeds money. In a sense, the most terrifying monster of all.',
    'valuables#1934': 'Infinite dagger arcane arte that restores inorganic matter to proper form.',
    'valuables#147': 'Protects wearer from splattering water and oil with divine power. Detachable.',
    'valuables#189': 'Hot spring egg made in a volcano at great risk. Reasonably tasty.',
    'valuables#201': 'Mirror surface bears an eye pattern scratched into it by previous owner.',
    'valuables#763': 'Arcane arte: impales enemies at high speed, drawing into aerial slashes.',
    'valuables#1556': 'Secret arte: impales foes with freezing spears, thrusting upon landing.',
    'valuables#224': 'Key unlocking the door to the sealed land. Chipped and unusable.',
    'valuables#521': 'Fire arte: scalding orbs detonate on enemies as if with a will of their own.',
    'valuables#165': 'Afterword calls this the definitive edition, but a sequel ships this summer.',
    'valuables#263': 'A jewel left on the Van Eltia for a long time for some reason.',
    'valuables#842': 'Arcane arte: sweeps foes with flaming fists and showers them with slashes.',
    'valuables#928': 'Arcane arte: closes in with Demon Flame Slash and Demon Flame Barrage.',
    'valuables#945': 'Arcane arte: follows Crouching Dragon Flash with two vacuum strikes in air.',
    'valuables#953': 'Arcane arte: high-speed slashes that cannot be tracked by ordinary eyes.',
    'valuables#960': 'Arcane arte: two-stage thrust with ability to slip behind the enemy.',
    'valuables#1558': 'Explosive arcane arte: explicitly slams fighting spirit into enemies.',
    'valuables#793': 'Arcane arte: launches foes high, impales with a spear, and slams them down.',
    'valuables#1281': 'Arcane arte: launches from thrusts, chasing with Tempest and Demon Fang.',
    'valuables#824': 'Secret arte: draws enemies with combo strikes coiling like water snakes.',
    'valuables#1165': 'Arcane arte: enters enemy pocket and slashes heavily, knocking them down.',
    'valuables#1287': 'Secret arte: slashes up with Crescent Slash, chasing foes with Tempest.',
    'valuables#1696': 'Leaps and fires arrows that detonate when enemies approach.',
    'valuables#186': 'A scrumptious dish. So delicious that a single bite brings tears.',
    'valuables#606': 'Arcane arte: draws foes to a spinning slash, slamming with fighting spirit.',
    'valuables#1285': 'Attacks consecutively from a clearing slash into an upward slash.',
    'valuables#1594': 'Arcane arte: dives in, fires water pressure shots, and creates distance.',
    'valuables#136': 'Blowing it creates a shockwave shattering windows in a 100m radius.',
    'valuables#471': 'Arte: releases frozen energy in the earth, striking with an ice arrow.',
    'valuables#602': 'Secret arte: executes high-speed spin slashes, juggling foes in the air.',
    'valuables#908': 'Thrusts sword into ground, summoning rock lances with shockwaves.',
    'valuables#1352': 'Arcane arte: amidst a flash, does unmentionable things to neighboring wives.',
    'valuables#1839': 'Arcane arte: raging flames turn to dragons, enveloping self to slay foes.',
    'valuables#745': 'Arcane arte: thrusts foes skyward, cloaks in flame, dives, and knocks down.',
    'valuables#795': 'Arcane arte: launches foes with lightning, then tosses minerals to follow.',
    'valuables#904': 'Delivers dual slashes followed by a reverse roundhouse kick.',
    'valuables#916': 'Knocks down foes by releasing fighting spirit into them.',
    'valuables#1216': 'Arcane arte: attacks surrounding foes with chakrams while spinning.',
    'valuables#1748': 'Slices enemies as if dancing through the heavens.',
    'valuables#1758': 'Slashes foes like a fluttering swallow, kicking them up at the end.',
    'valuables#1890': 'Arcane arte: launches foes with combos, transitioning to sheathed stance.',
    'valuables#107': 'The writing spaces are stark white; looking at them fills one with ennui.',
    'valuables#113': 'Used to illuminate dark places. Being oil is no excuse for weird things.',
    'valuables#124': 'Slime extracted from a Polwiggle. Used in medicine and cosmetics.',
    'valuables#741': 'Arcane arte: closes instantly, striking repeatedly and launching foes.',
    'valuables#789': 'Arcane arte: follows Roaring Spear with shockwaves front and back.',
    'valuables#890': 'Slams hammer into enemies with high stun chance.',
    'valuables#971': 'Deploys a barrier blowing enemies away while slightly healing allies.',
    'valuables#72': 'Recipe for "Commonly Known as Delicious-Delicious" that Coda craves.',
    'valuables#98': 'Favorite item of an unfortunate girl. She is alive; no curse.',
    'valuables#133': 'As one grows up, contents become plentiful, gradually becoming a chore.',
    'valuables#198': 'Ordinary happiness you only realize after losing it all.',
    'valuables#1624': 'Arcane arte: calls lightning from ground to attack after Shadow Run Blast.',
    'valuables#92': 'Rope meant for luggage, but liked by those who enjoy being tied up.',
    'valuables#127': 'Doctors use it to hear heartbeats. If pointed at you, you must undress.',
    'valuables#139': 'Comes with a grandiose note saying, "The board is the entire world".',
    'valuables#159': 'Belonged to a woman who met a mishap. She bought a replacement.',
    'valuables#301': 'Arte: restores a moderate amount of HP to all allies (in battle).',
    'valuables#645': 'Arcane arte: knocks foes down with a kick, striking with lightning.',
    'valuables#739': 'Arcane arte: launches foes into air, impaling with an ice spear.',
    'valuables#761': 'Arcane arte: launches foes with kicks, smashing down with flaming fists.',
    'valuables#785': 'Arcane arte: delivers thrusts and charges forward with a spear.',
    'valuables#844': 'Arcane arte: blows foes away with a spin kick, finishing with fire.',
    'valuables#848': 'Arcane arte: godspeed thrusts stir up gusts to blow enemies away.',
    'valuables#941': 'Arcane arte: knocks foes down with a sliding kick, striking lightning.',
    'valuables#988': 'Arcane arte: follows three thrusts with a heavy leaping thrust.',
    'valuables#990': 'Arcane arte: follows three thrusts with a diving thrust from air.',
    'valuables#1008': 'Arcane arte: two-stage slashes from Crescent Flash, up and down.',
    'valuables#1026': 'Arcane arte: draws enemies to slashes, striking with flashing thrusts.',
    'valuables#1196': 'Space-time sword arcane arte: shreds enemies with intense fighting spirit.',
    'valuables#1214': 'Arcane arte: spins chakrams at high speed, striking surrounding enemies.',
    'valuables#1247': 'Arcane arte: launches foes skyward, striking with a downward slash.',
    'valuables#1275': 'Arcane arte: strikes with thrusts, launching skyward and kicking down.',
    'valuables#1475': 'Calls a rock spear beneath enemy feet to launch them into the air.',
    'valuables#1479': 'Arte: fires arrows of light piercing enemies in a line.',
    'valuables#1216': 'Arcane arte: attacks nearby foes with chakrams while spinning.',
    'valuables#1177': 'Arcane arte: closes instantly, striking with rapid slashes.',
    'valuables#1333': 'Arcane arte: pulls foes from a downward swing and rushes forward.',
    'valuables#731': 'Secret arte: halts foes with a heavy thrust, launching them skyward.',
    'valuables#1313': 'Arcane arte: conjures shockwaves, punching airborne foes directly.',
    'valuables#1245': 'Secret arte: steps into enemy pocket while attacking, firing rapidly.',
    'valuables#1733': 'Arcane arte: slashes foes skyward, following with an aerial finish.',
    'valuables#118': 'Many women drink this as a sleep aid to end the day as themselves.',
    'valuables#180': 'In exchange for vacation memories, can be wielded as a lethal weapon.',
    'valuables#204': 'A charred doll found in a dense forest. Its eyeballs have been gouged out.',
    'valuables#612': 'Arcane arte: closes in with a sliding kick, launching foes with a dive kick.',
    'valuables#767': 'Arcane arte: launches foes with thrusts, cloaks in flame, and dives to attack.',
    'valuables#775': 'Arcane arte: launches foes skyward with kicks, following with a diving thrust.',
    'valuables#777': 'Arcane arte: launches foes skyward with kicks, following with an aerial kick.',
    'valuables#822': 'Secret arte: draws enemies with water whip, following with heavy slashes.',
    'valuables#826': 'Secret arte: draws enemies with water whip, slamming them to the ground.',
    'valuables#846': 'Arcane arte: slashes foes with flaming fists and kicks them down.',
    'valuables#887': 'Arcane arte: launches foes skyward, follows with thrusts, and knocks down.',
    'valuables#906': 'Delivers dual slashes followed by a high-speed roundhouse kick.',
    'valuables#2261': 'Title for one who knows the world\'s unexplored regions inside and out.',
    'valuables#101': 'A party gag item, but getting a laugh with it is considered a feat.',
    'valuables#174': 'Extremely fragile; putting weight on it shatters it to tiny pieces.',
    'valuables#195': 'Horrifying item you cannot escape. Beware, as it strikes suddenly.',
    'valuables#207': 'Portrait of a child. Face is blacked out, but the eyes can be seen.',
    'valuables#649': 'Arcane arte: knocks foes down with a sliding kick, striking with lightning.',
    'valuables#747': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
    'valuables#765': 'Arcane arte: strikes foes with a spear, spins at high speed, and blasts away.',
    'valuables#787': 'Arcane arte: follows Flying Ruin Spear by conjuring tornadoes.',
    'valuables#930': 'Arcane arte: closes in, unleashes kicks, and strikes with shockwaves.',
    'valuables#937': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
    'valuables#943': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#955': 'Arcane arte: closes in with a thrust, jumps into air, and kicks foes down.',
    'valuables#957': 'Arcane arte: launches foes into air, follows with slashes, and knocks down.',
    'valuables#992': 'Arcane arte: follows three thrusts with a heavy downward slash.',
    'valuables#1032': 'Arcane arte: delivers thrusts at high speed, finishing with a jump strike.',
    'valuables#1177': 'Arcane arte: closes instantly, striking with consecutive slashes.',
    'valuables#1218': 'Arcane arte: leaps back, fires chakrams, and strikes surrounding foes.',
    'valuables#1243': 'Arcane arte: launches foes skyward, striking with a diving thrust.',
    'valuables#1346': 'Arcane arte: delivers three slashes and kicks foes into the air.',
    'valuables#1620': 'Arcane arte: calls flames from ground to attack after Shadow Run Blast.',
    'valuables#1698': 'Fires arrows skyward that rain down upon enemies in targeted area.',
    'valuables#1740': 'Arcane arte: launches foes skyward with an uppercut, kicking downward.',
    'valuables#1750': 'Releases slashes like cherry blossoms, launching foes skyward.',
    'valuables#144': 'A tool to crush ice. If found near a bed, proceed with caution.',
    'valuables#210': 'Decorated with countless eyes; mirror surfaces are painted black.',
    'valuables#647': 'Arcane arte: knocks foes down with a sliding kick, striking with flames.',
    'valuables#651': 'Swings a sword imbued with explosive power to kick up a blast.',
    'valuables#749': 'Arcane arte: launches foes skyward and follows with sharp thrusts.',
    'valuables#771': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#779': 'Launches foes, follows up in air, and knocks them down.',
    'valuables#885': 'Arcane arte: leaves presents at enemy feet after Explosive Thrust Raid.',
    'valuables#932': 'Arcane arte: combines Flashing Fang, Severing Moon Flower, Ruinous Palm.',
    'valuables#939': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#973': 'Deploys a barrier blowing enemies away while greatly healing allies.',
    'valuables#1006': 'Arcane arte: cold-cloaked shockwaves trace a cross to attack enemies.',
    'valuables#1061': 'Wind secret arte: slams weapons down with momentum from midair.',
    'valuables#1194': 'Space-time sword secret arte: distorts space to cleave enemies in two.',
    'valuables#1200': 'Space-time sword arcane arte: teleports in front of enemies to attack.',
    'valuables#1283': 'Arcane arte: blows foes away with Fierce Claw, chasing with Demon Fang.',
    'valuables#1350': 'Arcane arte: slashes foes four times, then strikes with shockwaves.',
    'valuables#1650': 'Arcane arte: countless pages fly from an open book to slice enemies.',
    'valuables#1827': 'Arcane arte: magnificent five-hit combos unleashed by a fighting maiden.',
    'valuables#130': 'Purpose unknown. Rumor says you die peering through it like a telescope.',
    'valuables#142': 'A nice pocket watch, but hands move at startling speed. It is harmless.',
    'valuables#657': 'Arcane arte: godspeed thrusts turn to light and impale the enemy.',
    'valuables#1993': 'Arcane arte: arrows shot skyward rain down as countless ice blades.',
    'valuables#2272': 'Title for one who walked a storied battle history with companions.',
    'valuables#75': 'Recipe for "Mountain and Sea Delicacy Soup" that Coda craves.',
    'valuables#116': 'Made with mellow grapes. Grape lovers will ascend to heaven.',
    'valuables#162': 'An invention devised by humankind to shop efficiently.',
    'valuables#1985': 'Short-range skill: launches foes with bow attacks and follows up.',
    'valuables#104': 'Seals a demon that drove heaven, earth, and the demon realm to ruin.',
    'valuables#121': 'Part from an antique clock destroyed by a grandfather in rage.',
    'valuables#213': 'A compass shaped like an eyeball. The needle spins ceaselessly.',
    'valuables#1356': 'Secret arte: mimics sprinkling water during summer heat.',
    'valuables#1700': 'Arcane arte: arrows fired high into the sky rain down all around.',
    'valuables#1884': 'Arcane arte: wide-range multi-hit iai slash with vacuum waves.',
    'valuables#95': 'Reverts skin age to near infancy. Risks vanishing you completely.',
    'valuables#156': 'Picture of an adorable kitten. Contains clues on eliminating war.',
    'valuables#168': 'Banner bearing a tiger pattern. Exudes nobility of the Beast King.',
    'valuables#275': 'Green jewel obtained from a green chest in the Holy Land of Langriths.',
    'valuables#429': 'Arte: cures status ailments and moderately restores HP for an ally.',
    'valuables#733': 'Arcane arte: follows Phantom Dragon Fist with spinning kicks.',
    'valuables#571': 'Arte: slightly restores TP of nearby allies and cures status ailments.',
    'valuables#1090': 'Arcane arte: Crouching Dragon Strike and Flowing Shadow Strike combo.',
    'valuables#1924': 'Secret arte: replicates the skill of a snake to draw enemies closer.',
    'valuables#834': 'Arcane arte: tremendous homing capability against attacking foes.',
    'valuables#1913': 'Arcane arte: aerial kicks connecting into rapid attacks.',
    'valuables#982': 'Arcane arte: launches foes skyward, following with flame thrusts.',
    'valuables#869': 'Secret arte: launches foes with slashes into three strikes.',
    'valuables#1437': 'Secret arte: slams wolf fighting spirit into foes, blowing them away.',
    'valuables#567': 'Arte: raises an ally\'s magic defense and cures debuffs temporarily.',
    'valuables#563': 'Arte: raises an ally\'s magic attack and cures debuffs temporarily.',
    'valuables#956': 'Arcane arte: lifts foes with sword pressure, sweeping them in air.',
    'valuables#1186': 'Arcane arte: slashes down, launches up, into spin slashes.',
    'valuables#1552': 'Secret arte: summons thunder to strike foes, following with lightning.',
    'valuables#1596': 'Arcane arte: blows foes away with uppercuts and triangle kicks.',
    'valuables#1715': 'Secret arte: repeatedly slashes airborne foes after upward slashes.',
    'valuables#684': 'Secret arte: swings weapons to blow foes away with momentum.',
    'valuables#757': 'Arcane arte: attacks foes with light orbs from surroundings.',
    'valuables#1135': 'Arcane arte: follows rapid thrusts with upward slashes, chasing in air.',
    'valuables#1783': 'Arcane arte: sweeps feet, launching foes with explosive blasts.',
    'valuables#1791': 'Arcane arte: slashes like flowing water, finishing with shockwaves.',
    'valuables#2030': 'Arcane arte: launches with lightning, dropping steel onto foes.',
    'valuables#840': 'Secret arte: follows a thrust with an earth-shaking skyward fist strike.',
    'valuables#980': 'Arcane arte: thrusts a spear into ground, raising a water pillar.',
    'valuables#1331': 'Arcane arte: launches with shockwave slashes and slams down with a cut.',
    'valuables#1443': 'Arcane arte: launches foes, landing spinning kicks and slashes in air.',
    'valuables#1455': 'Arcane arte: launches with a shield bash, chasing with sharp thrusts.',
    'valuables#1671': 'Arcane arte: launches foes high from godspeed upward slashes into kicks.',
    'valuables#1739': 'Arcane arte: launches, ascends with spinning slashes, and fires blasts.',
    'valuables#1930': 'Secret arte: fires lightning daggers radially to call down thunder.',
    'valuables#2063': 'Arcane arte: detonates fighting spirit to blow away nearby foes.',
    'valuables#638': 'Arcane arte: cloaks in flaming fighting spirit, diving like a phoenix.',
    'valuables#830': 'Arcane arte: fires five cold arrows toward the heavens at once.',
    'valuables#924': 'Secret arte: teleports above the enemy, delivering flame slashes.',
    'valuables#1002': 'Arcane arte: releases vacuum waves from two-stage slashes.',
    'valuables#1086': 'Arcane arte: blows all away indiscriminately with a body slam.',
    'valuables#1333': 'Arcane arte: pulls foes from a downward swing and rushes forward.',
    'valuables#1785': 'Arcane arte: strikes with an axe, thrusts with a sword, and cleaves.',
    'valuables#630': 'Secret arte: slashes up while creating a tornado with a spin slash.',
    'valuables#634': 'Secret arte: lifts foes with sword pressure and delivers a finish.',
    'valuables#702': 'Arcane arte: swings weapons to sweep foes away with fighting spirit.',
    'valuables#951': 'Secret arte: slashes up and down in a crescent moon trajectory.',
    'valuables#1447': 'Arcane arte: stacks sword clashes at high speed, creating windstorms.',
    'valuables#1503': 'Arcane arte: increases stagger time for an enemy temporarily.',
    'valuables#1667': 'Secret arte: drops from a leap, attacking with impact on landing.',
    'valuables#1813': 'Arcane arte: binds slashed foes to the heavens with a fierce flash.',
    'valuables#1868': 'Secret arte: blows foes away with lion roars that slay fierce tigers.',
    'valuables#791': 'Arcane arte: thrusts at rear enemies while sweeping aside front foes.',
    'valuables#799': 'Arcane arte: launches minerals after a surprise strike to blow foes away.',
    'valuables#817': 'Arcane arte: fires one straight arrow and four homing arrows at once.',
    'valuables#1256': 'Arcane arte: follows a kick with water-element bullets to blow foes away.',
    'valuables#1293': 'Arcane arte: punches with flaming fist and boils up lava all around.',
    'valuables#1669': 'Secret arte: slices with sword clashes and whirlwinds, slamming down wind.',
    'valuables#1688': 'Secret arte: strikes down slashes onto enemies like lightning in a flash.',
    'valuables#1798': 'Secret arte: slashes foes upward while delivering three spin slashes.',
    'valuables#838': 'Secret arte: delivers an axe kick from air and boils up lava all around.',
    'valuables#1188': 'Arcane arte: scorches nearby foes with a sword cloaked in flame qi.',
    'valuables#1721': 'Arcane arte: leaps back while kicking foes up, chasing with rapid dives.',
    'valuables#1849': 'Arcane arte: creates whirlwinds at impact points, sweeping foes skyward.',
    'valuables#1917': 'Secret arte: spins both feet like twin swords, dealing rapid strikes.',
    'valuables#2055': 'Arcane arte: jumps and shoots light spheres at diagonal enemies.',
    'valuables#875': 'Secret arte: throws bombs while closing distance and thrusts forward.',
    'valuables#978': 'Arcane arte: thrusts a spear into ground, whipping up gusts to attack.',
    'valuables#1526': 'Arcane arte: thrusts a sword into ground, summoning ice spears around.',
    'valuables#1585': 'Arcane arte: closes in and punches skyward alongside water torrents.',
    'valuables#1651': 'Arcane arte: captures foes with weapons, detonating with magic power.',
    'valuables#1741': 'Arcane arte: circles behind foes with slashes, landing further combos.',
    'valuables#1823': 'Arcane arte: impales foes with long blades of light in weapons.',
    'valuables#632': 'Arcane arte: unleashes a flurry of attacks, stepping into the enemy.',
    'valuables#646': 'Arcane arte: unleashes fiery energy to scorch the surroundings.',
    'valuables#721': 'Arcane arte: blows foes away and knocks them down at the end of kicks.',
    'valuables#781': 'Arcane arte: pierces foes with a gale-cloaked spinning thrust.',
    'valuables#1016': 'Arcane arte: traces the moon with weapon arcs, attacking continuously.',
    'valuables#1050': 'Arcane arte: repeatedly swings weapons to blow away rock shards.',
    'valuables#1131': 'Arcane arte: creates icicles from the impact of upward slashes.',
    'valuables#1401': 'Arcane arte: launches a spinning suicide dive at foes high in the sky.',
    'valuables#1677': 'Secret arte: punches vitals with weapon pommels to knock foes down.',
    'valuables#1752': 'Arcane arte: slashes foes into the air and unleashes spin slashes.',
    'valuables#1857': 'Arcane arte: fires a shot skyward capable of piercing even gods.',
    'valuables#1926': 'Secret arte: throws water-blessed daggers three times in succession.',
    'valuables#2046': 'Secret arte: dances into air and fires twelve bullets while spinning.',
    'valuables#644': 'Secret arte: sweeps foes away, releasing fire power all at once.',
    'valuables#1145': 'Arcane arte: high-speed sword strikes cleaving through enemies.',
    'valuables#1243': 'Secret arte: attacks surroundings, raising icicles from impact points.',
    'valuables#1474': 'Secret arte: hits four times with dual swords, launches, and follows.',
}

# Systematic rules for the rest
rules = [
    (r'^A skill that attaches a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Attaches a talisman briefly lowering enemy \1 by chance.'),
    (r'^Secret arte: flings a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Secret arte: flings a talisman briefly lowering enemy \1 by chance.'),
    (r'^The recipe for "(.*?)" that Coda is yearning for\.$',
     r'Recipe for "\1" that Coda craves.'),
    (r'^Title given to someone who ', 'Title for one who '),
    (r'^Title given to someone ', 'Title for someone '),
    (r'^Title given to ', 'Title for '),
    (r'^An arcane arte where ', 'Arcane arte: '),
    (r'^An arcane arte that, ', 'Arcane arte: '),
    (r'^An arcane arte that ', 'Arcane arte: '),
    (r'^An arcane arte with ', 'Arcane arte: '),
    (r'^An arcane arte of ', 'Arcane arte: '),
    (r'^An arcane arte ', 'Arcane arte: '),
    (r'^A space-time sword arcane arte that ', 'Space-time sword arcane arte: '),
    (r'^A space-time sword secret arte that ', 'Space-time sword secret arte: '),
    (r'^A wind-element secret arte that ', 'Wind secret arte: '),
    (r'^A fire arte where ', 'Fire arte: '),
    (r'^A short-range skill that ', 'Short-range skill: '),
    (r'^An explosive arcane arte that explicitly ', 'Explosive arcane arte: '),
    (r'^An infinite dagger arcane arte that ', 'Infinite dagger arcane arte: '),
    (r'^A secret arte reminiscent of ', 'Secret arte: reminiscent of '),
    (r'for a short time with a set chance', 'briefly by chance'),
    (r'with a high probability of stunning them', 'with high stun chance'),
    (r'while moving at high speed', 'at high speed'),
    (r'high-speed movement', 'high speed'),
    (r'featuring the ability to ', 'able to '),
    (r'\(area of effect in battle\)', '(in battle)'),
    (r'area of effect in battle', 'in battle'),
    (r'for a single target ally', 'for an ally'),
    (r'for a single ally', 'for an ally'),
    (r'for a target ally', 'for an ally'),
    (r'releases gathered fighting spirit', 'releases fighting spirit'),
    (r'in rapid succession', 'rapidly'),
    (r'two more vacuum wave strikes', 'two vacuum strikes'),
    (r'from rapid thrusts', 'from thrusts'),
    (r'three consecutive thrusts', 'three thrusts'),
    (r'consecutive spinning kicks', 'spinning kicks'),
    (r'two-stage slashes', 'two-stage strikes'),
    (r'left and right slashes', 'dual slashes'),
    (r'closes distance while unleashing', 'closes in, unleashing'),
    (r'closes distance instantly,', 'closes instantly,'),
    (r'closes distance,', 'closes in,'),
    (r'slashes enemies skyward with', 'slashes foes skyward with'),
    (r'slashes enemies skyward,', 'slashes foes skyward,'),
    (r'attacks surrounding enemies with', 'attacks surrounding foes with'),
    (r'delivers consecutive attacks from', 'attacks consecutively from'),
    (r'executes consecutive attacks from', 'attacks consecutively from'),
    (r'executes high-speed spinning slashes', 'executes high-speed spin slashes'),
    (r'sweeps enemies away with', 'sweeps enemies with'),
    (r'draws enemies into', 'draws enemies to'),
    (r'knocks down opponents by', 'knocks down foes by'),
    (r'follows up with ', 'follows with '),
    (r'rushes forward swiftly and ', 'rushes forward and '),
    (r'attacks enemies by slamming them with ', 'attacks by slamming foes with '),
    (r'attacks enemies with air pressure generated from ', 'attacks foes with air pressure from '),
    (r'draw enemies in\.', 'draw enemies closer.'),
    (r'in midair', 'in air'),
    (r'into the air\.', 'into air.'),
    (r'into the air,', 'in air,'),
    (r'into midair', 'in air'),
    (r'from midair', 'from air'),
    (r'sky-high', 'high'),
    (r'consecutive slashes', 'rapid slashes'),
    (r'consecutive upward slashes', 'rapid upward slashes'),
    (r'consecutive downward slashes', 'rapid downward slashes'),
    (r'consecutive thrusts', 'rapid thrusts'),
    (r'consecutive strikes', 'rapid strikes'),
    (r'slashes enemies with ', 'slashes foes with '),
    (r'launches enemies with ', 'launches foes with '),
    (r'launches enemies into the air,', 'launches foes in air,'),
    (r'launches enemies,', 'launches foes,'),
    (r'attacks enemies with ', 'attacks foes with '),
    (r'blows enemies away with ', 'blows foes away with '),
    (r'blows enemies away and ', 'blows foes away and '),
    (r'blow away surrounding foes', 'blow away nearby foes'),
    (r'blows everything away indiscriminately with ', 'blows all away with '),
    (r'slashes upward and downward', 'slashes up and down'),
    (r'upward and downward', 'up and down'),
    (r'into enemies to blow them away', 'into foes, blowing them away'),
    (r'causes countless bubbles to surge from the ground beneath the target enemy\.',
     'Arte: causes countless bubbles to surge beneath the target enemy.'),
    (r'causes a massive torrent of water to surge around the target enemy\.',
     'Arte: causes a torrent of water to surge around target enemy.'),
    (r'creates sharp blocks of ice from the ground beneath the target enemy\.',
     'Arte: creates sharp blocks of ice beneath the target enemy.'),
    (r'rains down flame spheres causing powerful explosions on the ground\.',
     'Arte: rains flame spheres causing explosions on the ground.'),
    (r'traps targets in a magic circle and unleashes four pillars of flame\.',
     'Arte: traps targets in a circle, unleashing four flame pillars.'),
    (r'surrounds an ally with a barrier that continuously restores their HP\.',
     'Arte: surrounds an ally with a barrier continuously restoring HP.'),
    (r'surrounds an ally with holy light, restoring their physical status\.',
     'Arte: surrounds an ally with holy light, restoring physical status.'),
    (r'envelops a targeted ally in holy light, restoring their physical status\.',
     'Arte: envelops target ally in holy light, restoring physical status.'),
    (r'raises an ally\'s physical attack and cures status ailments for a set time\.',
     'Arte: raises an ally\'s attack and cures ailments for a set time.'),
    (r'raises an ally\'s physical defense and cures stat debuffs for a set time\.',
     'Arte: raises an ally\'s defense and cures debuffs for a set time.'),
    (r'raises an ally\'s magic attack and cures stat debuffs for a set time\.',
     'Arte: raises an ally\'s magic attack and cures debuffs temporarily.'),
    (r'raises an ally\'s magic defense and cures stat debuffs for a set time\.',
     'Arte: raises an ally\'s magic defense and cures debuffs temporarily.'),
    (r'slightly restores TP of allies in range and cures status ailments\.',
     'Arte: slightly restores TP of nearby allies and cures ailments.'),
]

extra_trims = [
    (r'closing distance', 'closing in'),
    (r'spinning slashes', 'spin slashes'),
    (r'spinning kicks', 'spin kicks'),
    (r'spinning impacts', 'spin impacts'),
    (r'through enemies', 'through foes'),
    (r'enemies with', 'foes with'),
    (r'into enemies', 'into foes'),
    (r'attacks enemies', 'attacks foes'),
    (r'slashes enemies', 'slashes foes'),
    (r'launches enemies', 'launches foes'),
    (r'surrounding foes', 'nearby foes'),
    (r'surrounding enemies', 'nearby foes'),
    (r'the surroundings', 'nearby area'),
    (r'toward the heavens', 'skyward'),
    (r'high into the sky', 'skyward'),
    (r'consecutive attacks', 'rapid attacks'),
    (r'in an instant', 'instantly'),
    (r'on enemies', 'on foes'),
    (r'to enemies', 'to foes'),
    (r'striking enemies', 'striking foes'),
    (r'impales enemies', 'impales foes'),
    (r'draws enemies', 'draws foes'),
    (r'sweeps enemies', 'sweeps foes'),
    (r'and strikes with shockwaves', 'with shockwaves'),
    (r'and finishes with ', ', finishing with '),
    (r'and connects into ', ', connecting into '),
    (r'to attack foes\.', 'to attack.'),
    (r'to attack enemies\.', 'to attack.'),
    (r'for a set time\.', 'temporarily.'),
    (r'for a set time', 'temporarily'),
    (r'for a short time', 'briefly'),
    (r'beneath the target enemy\.', 'beneath target foe.'),
    (r'around the target enemy\.', 'around target foe.'),
    (r'two-stage strikes', 'two strikes'),
    (r'from impact points', 'on impact'),
    (r'reverse roundhouse kick', 'reverse kick'),
    (r'high-speed roundhouse kick', 'high-speed kick'),
    (r'a single sword flash', 'a sword flash'),
    (r'surrounding', 'nearby'),
    (r'in rapid succession', 'rapidly'),
    (r'in a straight line', 'in a line'),
    (r'while continuously spinning\.', 'while spinning.'),
]

out = {}
for x in itens:
    item_id = x['id']
    en = x['en']
    if item_id in overrides:
        s = overrides[item_id]
    else:
        s = en
        for pat, rep in rules:
            s = re.sub(pat, rep, s)
        if s.startswith('A skill that '):
            rest = s[len('A skill that '):]
            s = rest[0].upper() + rest[1:]
    
    for pat, rep in extra_trims:
        s = re.sub(pat, rep, s)
    
    if s != en:
        out[item_id] = s

print(f"Total entries in out: {len(out)} / {len(itens)}")
ok = validate_dict('dados/item_equip_shrink/VAL-01.json', out)
if ok:
    with open('dados/item_equip_shrink/VAL-01_out.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
    print("SAVED VAL-01_out.json!")
