import csv

T = {
    'skit#320': 'Quiz! Eugene',
    'skit#321': "Ad Libitum's Song!",
    'skit#322': "Mao's Love Song",
    'skit#323': 'Precious Things & Love',
    'skit#324': 'Must I Remember?',
    'skit#325': 'Our Parents',
    'skit#326': "Mao's Father",
    'skit#327': 'Amazing, Sir Eugene',
    'skit#328': 'Ideal Woman Type',
    'skit#329': 'Just In Case, I Say',
    'skit#330': 'Heat is Nothing',
    'skit#331': 'Easily Tricked?',
    'skit#332': 'To Understand',
    'skit#333': 'Sad Reasons',
    'skit#334': 'Beauty Chat: Pt 2',
    'skit#335': 'Well-Bred Tytree',
    'skit#336': 'Van Eltia: Star Rating?',
    'skit#337': 'Magic Power',
    'skit#338': 'Ecologist Man',
    'skit#339': 'Kindred Minds',
    'skit#340': "Tytree's Query",
    'skit#341': 'Doc Pals',
    'skit#342': 'Study Session',
    'skit#343': "Annie's Worry",
    'skit#344': "Annie's Tarot",
    'skit#345': 'Fond Words',
    'skit#346': 'Why Be a Doctor',
    'skit#347': 'Secret Diary',
    'skit#348': 'Never Let Guard Down...',
    'skit#349': 'Will Never Join In!',
    'skit#350': 'Diary Murmurs',
    'skit#351': 'Thoughts on Arms',
    'skit#352': "Tear's Song",
    'skit#353': 'Not Very Honest',
    'skit#354': 'Cleared 300 Quests!',
    'skit#355': "Senel's Marks?",
    'skit#356': 'Catch Senel',
    'skit#357': 'Ask Senel',
    'skit#358': "Don't Overdo It",
    'skit#359': 'Who Is Elderly?',
    'skit#360': 'Accidental Peep',
    'skit#361': 'Lost Senel',
    'skit#362': "Rocks's Taste",
    'skit#363': "Rocks's Taste: Pt 2",
    'skit#364': 'Swimmer Facts',
    'skit#365': 'From Now On..',
    'skit#366': "It's Such a Waste!",
    'skit#367': 'Wild Curiosity',
    'skit#368': 'Crushed 800 Foes!',
    'skit#369': 'Caught That Thing',
    'skit#370': 'Peer Views',
    'skit#371': "What's Jay Like?",
    'skit#372': 'Teaching Is Hard',
    'skit#373': 'Trendy Fad',
    'skit#374': 'Not Scared At All...',
    'skit#375': 'Special: Pt 2',
    'skit#376': "Knight's Tale",
    'skit#377': 'Many Views',
    'skit#378': 'Knight Chloe',
    'skit#379': 'Sword Arc',
    'skit#380': 'Love Talk: Chloe',
    'skit#381': 'Shy Maiden',
    'skit#382': "Let's Go to Sea",
    'skit#383': 'Paragon',
    'skit#384': 'Forbidden!',
    'skit#385': 'Been a While!',
    'skit#386': 'Popular Rocks',
    'skit#387': 'In What Way?',
    'skit#388': 'Seeing Double',
    'skit#389': 'Asked the Bubble Girl',
    'skit#390': 'How Similar?',
    'skit#391': 'No Mere Man',
    'skit#392': 'So Many Kids',
    'skit#393': 'Correct, Kyu?',
    'skit#394': 'Tiny Ally',
    'skit#395': 'Another Shinobi',
    'skit#396': 'Memory Bell',
    'skit#397': 'Skin Secret',
    'skit#398': 'Fair Skin: Pt 2',
    'skit#399': 'That Accent...',
    'skit#400': 'Victory Dance!',
    'skit#401': "Luke's Habit",
    'skit#402': 'Murky Thoughts',
    'skit#403': 'Hidden Side?',
    'skit#404': "Luke's Diary",
    'skit#405': 'Rejoining Luke',
    'skit#406': 'Inedible!?',
    'skit#407': 'Butler Rocks Agony',
    'skit#408': 'Indistinct: Pt 2 (Unused)',
    'skit#409': 'Envious of Kanonno',
    'skit#410': 'Siblings from Below',
    'skit#411': 'Fabre: Pt 2',
    'skit#412': 'Bro Spat',
    'skit#413': 'My Childhood Friend',
    'skit#414': 'Staff Ties',
    'skit#415': 'Tough for Us Both',
    'skit#416': 'Mech Lovers!',
    'skit#417': 'In a Pinch!',
    'skit#418': 'Servant Bond: Pt 2',
    'skit#419': 'Servant Bond: Pt 3',
    'skit#420': 'Special: Pt 3',
    'skit#421': 'Silent Men...',
    'skit#422': 'Bang Bang!',
    'skit#423': 'Dawn Page',
    'skit#424': 'Seeing Essence',
    'skit#425': 'To Speak or Not to Speak?',
    'skit#426': 'Spiteful Jade',
    'skit#427': 'Clean Pals',
    'skit#428': 'Cleaning Pals: Pt 2',
    'skit#429': 'Cleaning Pals: Pt 3',
    'skit#430': 'Deep Worry',
    'skit#431': 'Young and Old',
    'skit#432': 'Either Way...',
    'skit#433': 'Which Is It?',
    'skit#434': 'Elite Butler',
    'skit#435': 'Dear Woodrow',
    'skit#436': 'Dear Woodrow: Pt 2',
    'skit#437': 'Dear Zelos',
    'skit#438': "Natalia's Worry",
    'skit#439': 'New Life, Old Ties',
    'skit#440': 'Fine View',
    'skit#441': 'Are We Clicking?',
    'skit#442': 'Holy Night Joy',
    'skit#443': 'Reunion: Natalia',
    'skit#444': 'Classic!?',
    'skit#445': "Asch's Motive",
    'skit#446': 'Fists Speak Louder',
    'skit#447': 'Fabre',
    'skit#448': "You're a Mystery",
    'skit#449': 'Reunion with Asch',
    'skit#450': 'Same As Ever',
    'skit#451': "Asch's Fury",
    'skit#452': 'Pesky Bro',
    'skit#453': 'Bang Bang!',
    'skit#454': 'Fated Future',
    'skit#455': 'Bittersweet',
    'skit#456': 'How to Use That?',
    'skit#457': 'Plural',
    'skit#458': 'Old Games',
    'skit#459': 'Rare Moment',
    'skit#460': 'Old Games: Pt 2',
    'skit#461': "Let's Make It",
    'skit#462': 'Where Was It?',
    'skit#463': 'Snow Promise: Pt 2',
    'skit#464': 'Quite Relaxed',
    'skit#465': "Caius's Night",
    'skit#466': 'What Peak?',
    'skit#467': 'Midnight Stir',
    'skit#468': 'Too Energetic?',
    'skit#469': 'Roommates',
    'skit#470': 'Why Join Guild?',
    'skit#471': 'Always Be Grateful',
    'skit#472': 'Only for Now',
    'skit#473': 'Shared Traits',
    'skit#474': 'Muscle Duel',
    'skit#475': 'Homesick',
    'skit#476': 'Read the Room',
    'skit#477': 'Our Dream',
    'skit#478': 'Stiff Neck?',
    'skit#479': 'Amazing, Sir Ruca',
    'skit#480': 'Key Realization',
    'skit#481': 'Foul Mouths',
    'skit#482': 'Glasses: Pt 2',
    'skit#483': 'Hot!: Pt 2',
    'skit#484': 'Solid Strategy',
    'skit#485': 'Great Hopes',
    'skit#486': "It's Over Now!",
    'skit#487': "Because I'm Bored!",
    'skit#488': 'RPS Showdown!',
    'skit#489': 'Dual Blades Rock!',
    'skit#490': "Spada's Plight",
    'skit#491': 'Gentle Soul',
    'skit#492': 'Gentle Soul: Pt 2',
    'skit#493': 'Why So Neat?',
    'skit#494': 'Evolved Human',
    'skit#495': 'Close Call, Spada',
    'skit#496': 'Tactics Theory: Pt 3',
    'skit#497': "Ange's Sorrow",
    'skit#498': 'Clashing Duo',
    'skit#499': 'Wary Person',
    'skit#500': 'To My Other Self',
    'skit#501': 'Cleared 100 Quests!',
    'skit#502': 'Cleared 500 Quests!',
    'skit#503': 'Cleared 800 Quests!',
    'skit#504': 'Cleared 1,000 Quests!!',
    'skit#505': 'Waiting for You to Heal',
    'skit#506': 'Discerning Man: Pt 2',
    'skit#507': 'Sour Task',
    'skit#508': 'Warrior Zeal!',
    'skit#509': 'Fine Weather',
    'skit#510': 'Worst House-Sitting',
    'skit#511': 'Untouchable Past',
    'skit#512': 'Kids Should Be Kids',
    'skit#513': 'Why Fight?',
    'skit#514': 'I Want to Eat',
    'skit#515': 'Shorten It: Pt 3',
    'skit#516': 'Quickie Friends: Pt 3',
    'skit#517': 'Word Sway',
    'skit#518': 'Villain Yuri!?',
    'skit#519': 'Kind of Unfair',
    'skit#520': 'Sweet-Tooth Blades',
    'skit#521': 'Uncharming Folks',
    'skit#522': 'Eating That Too?',
    'skit#523': 'Eating That Too: Pt 2',
    'skit#524': 'Swap Gear',
    'skit#525': 'Trim It',
    'skit#526': 'Quickie Friends',
    'skit#527': 'Quickie Friends: Pt 2',
    'skit#528': 'Reunion: Estelle',
    'skit#529': 'Looking Away',
    'skit#530': 'Noble Ambitions',
    'skit#531': 'Twin Souls',
    'skit#532': 'Make It Simpler',
    'skit#533': 'Quiz! Judith',
    'skit#534': 'Is Reusing Good: Pt 3',
    'skit#535': 'A Rare Sight!',
    'skit#536': 'Admired, But...',
    'skit#537': 'Shorten It: Pt 2',
    'skit#538': 'Glasses!',
    'skit#539': 'Study Group',
    'skit#540': 'Captain Joins',
    'skit#541': 'Need Books',
    'skit#542': 'I Really Want Books!',
    'skit#543': 'Stiff and Naive',
    'skit#544': 'Just Between Us',
    'skit#545': 'Silent Plea',
    'skit#546': "Raven's Gloom",
    'skit#547': 'How About You?',
    'skit#548': 'Talk Here?',
    'skit#549': 'Cynical Asch',
    'skit#550': 'Being Mindful?',
    'skit#551': 'Nothing Alike',
    'skit#552': 'Old Man Burst',
    'skit#553': 'Lovely, Right!?',
    'skit#554': 'How to Break Out?',
    'skit#555': 'Clear Skies, Yet...',
    'skit#556': 'What to Do...?',
    'skit#557': 'Holy Night Joy: Pt 2',
    'skit#558': 'Quiz! Flynn',
    'skit#559': 'Keep Ship Safe',
    'skit#560': 'Fact Versus Truth',
    'skit#561': "Flynn's Zeal",
    'skit#562': 'True Intent',
    'skit#563': 'Just Taking a Walk',
    'skit#564': 'Why So Hyped',
    'skit#565': "What's Hazel Like?",
    'skit#566': 'Amity Trial Redux',
    'skit#567': 'Airheaded',
    'skit#568': 'Cucumber & Things',
    'skit#569': 'First 100 Foes!',
    'skit#570': "What Is 'Hospitality'?",
    'skit#571': 'Lovely Legs',
    'skit#572': 'Top Flavor',
    'skit#573': 'Value Friends',
    'skit#574': 'Kohaku Wit',
    'skit#575': 'Words Are Fun',
    'skit#576': 'Crushed 300 Foes!',
    'skit#577': 'Road to Feasts: Pt 3',
    'skit#578': "Annie's Nursing",
    'skit#579': 'Dread Germ',
    'skit#580': 'Proud Siblings',
    'skit#581': 'Found Demon Lord',
    'skit#582': 'Unknown Word',
    'skit#583': 'Open Wide',
    'skit#584': 'Just Imagine',
    'skit#585': 'Siblings from Above',
    'skit#586': 'What Think?',
    'skit#587': 'Youth Folly',
    'skit#588': 'Seek Answers',
    'skit#589': "She's a XX Cook: Pt 4",
    'skit#590': "He's a XX Cook",
    'skit#591': 'Doubts Away',
    'skit#592': 'About Siblings',
    'skit#593': 'Respect, Captain Flynn',
    'skit#594': "Asbel's Father",
    'skit#595': 'Happy New Year!',
    'skit#596': 'Sophie Truly Is...',
    'skit#597': "Tree's Heart",
    'skit#598': 'Eating That Too: Pt 3',
    'skit#599': 'Omelet Holiday',
    'skit#600': 'Hunch',
    'skit#601': 'Job Roles',
    'skit#602': 'Love Talk: Roni',
    'skit#603': 'Love Talk: Keele',
    'skit#604': 'Bad Match?',
    'skit#605': "Let's Clean Up",
    'skit#606': 'Cheria is...',
    'skit#607': "Chloe's Charm",
    'skit#608': 'Mixed Views',
    'skit#609': 'Of Old',
    'skit#610': 'Kouki Lore',
    'skit#611': 'Beast Lore',
    'skit#612': 'Truth from Document',
    'skit#613': 'Alta Village',
    'skit#614': 'Rocks-Trained',
    'skit#615': 'Love',
    'skit#616': 'Another Form',
    'skit#617': 'Dislike Troops?',
    'skit#618': 'Chatty',
    'skit#619': 'Specialist',
    'skit#620': 'Journey Ahead',
    'skit#621': 'Painting You',
    'skit#622': 'Always, Everywhere',
    'skit#623': 'Voice of Life',
    'skit#624': 'Node',
    'skit#625': 'Other Vistas',
    'skit#626': 'A Hero?',
    'skit#627': "Niata's Body",
    'skit#628': 'Mystic Drink',
    'skit#629': 'Descender Boast',
    'skit#630': 'Sequel Changes!?',
    'skit#631': 'Dungeons Powered Up!',
    'skit#632': 'How Was Char Creation?',
    'skit#633': 'How Battles Work!?',
}

with open('lotes_p68/SKIT-02.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

for r in rows:
    rid = r['id']
    if rid in T:
        r['traducao'] = T[rid]
    else:
        print("MISSING:", rid)

out_p = 'lotes_p68/SKIT-02_retorno.tsv'
with open(out_p, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
    w.writeheader()
    w.writerows(rows)
print("Wrote", out_p)
