import csv, re

# Translation table for SKIT-01 (320 items)
T = {
    'skit#0': 'First Skit',
    'skit#1': 'Hurry to Ange!',
    'skit#2': 'Take on Quests',
    'skit#3': 'First Shopping',
    'skit#4': 'To Destination!',
    'skit#5': 'Quick Return: Handy',
    'skit#6': 'Now, the Travel Menu',
    'skit#7': 'Wait a Minute!',
    'skit#8': 'At Such Times?',
    'skit#9': 'Sparring',
    'skit#10': 'Hot!',
    'skit#11': 'Is Reusing Good?',
    'skit#12': 'More Allies!',
    'skit#13': 'Pure Evil',
    'skit#14': 'Shared Flaw',
    'skit#15': 'Best Fit',
    'skit#16': 'Nice Voice!',
    'skit#17': 'Ask Mint for Advice',
    'skit#18': 'Ask Mint for Advice: Pt 2',
    'skit#19': 'Curious One',
    'skit#20': 'Hardship Chat',
    'skit#21': 'Speaking Up',
    'skit#22': "She's a XX Cook: Pt 2",
    'skit#23': 'Amazing, Ms. Raine',
    'skit#24': 'Pretty Flower...',
    'skit#25': 'Love Talk: Chester',
    'skit#26': 'Quiz! Chester',
    'skit#27': 'Special!',
    'skit#28': 'Pot & Kettle!',
    'skit#29': 'In the Way?',
    'skit#30': 'Cheer Up!',
    'skit#31': "Arche's Broom",
    'skit#32': 'All Alone',
    'skit#33': "She's a XX Cook: Pt 3",
    'skit#34': "Arche's Prank",
    'skit#35': 'Miracle & Karma',
    'skit#36': 'Quiz! Arche',
    'skit#37': 'Ninja Way',
    'skit#38': 'Ninja Fit',
    'skit#39': 'New World',
    'skit#40': 'So Cool~',
    'skit#41': 'Wise Suzu',
    'skit#42': "That's Cheating!",
    'skit#43': 'No Spicy Food',
    'skit#44': 'Another Ninja?',
    'skit#45': 'Our Dream',
    'skit#46': 'Just Being Near...',
    'skit#47': '0 Gald Left',
    'skit#48': 'Even Fleeing...',
    'skit#49': "Stahn's Talent?",
    'skit#50': 'We Click',
    'skit#51': 'Board Talk?',
    'skit#52': "Let's Go Over There",
    'skit#53': 'The Real Truth?',
    'skit#54': 'For Future Beyond Now',
    'skit#55': "How's It Going?",
    'skit#56': 'So Rich!',
    'skit#57': '500,000 Gald',
    'skit#58': 'Chasing Girls',
    'skit#59': "Why Don't You Get It?",
    'skit#60': 'Special Menu Ideas',
    'skit#61': 'Clergy Romance',
    'skit#62': 'Priestly Affairs',
    'skit#63': 'Road to Feasts: Pt 2',
    'skit#64': "Roni's Worry",
    'skit#65': "Philia's Gaze",
    'skit#66': "Philia's Glasses",
    'skit#67': "Judas's Instinct?",
    'skit#68': 'Act Age',
    'skit#69': 'Ask Leon',
    'skit#70': 'Could It Be...?',
    'skit#71': "Let's Do It Together",
    'skit#72': 'Benefits of Tea',
    'skit#73': 'Feels Like Spring',
    'skit#74': 'Ultimate Tactics',
    'skit#75': 'Ultimate Tactics: Pt 2',
    'skit#76': "Let's All Go",
    'skit#77': 'Rose Swordsman',
    'skit#78': 'Unlikely Reunion?',
    'skit#79': 'Indistinguishable?',
    'skit#80': 'A Vast World',
    'skit#81': 'Call Me Casually',
    'skit#82': 'Wise King Dignity',
    'skit#83': 'Inheriting Crown',
    'skit#84': 'Dining Together',
    'skit#85': 'Just Imagination?',
    'skit#86': 'Despite Being Adult',
    'skit#87': 'Quiz! Chelsea',
    'skit#88': 'Wanna Ask?',
    'skit#89': 'Angel Colette',
    'skit#90': "Chelsea's Bias",
    'skit#91': 'Close Friends?',
    'skit#92': 'Not That Different',
    'skit#93': 'Special Lesson',
    'skit#94': 'Origin?',
    'skit#95': 'Looking Forward',
    'skit#96': 'Kongman is Strong',
    'skit#97': 'My Angel',
    'skit#98': 'Why That Hairstyle?',
    'skit#99': 'What With That Outfit?',
    'skit#100': 'Just My Body',
    'skit#101': 'As Expected of Rocks',
    'skit#102': 'Ultimate Ladle Legend',
    'skit#103': 'Ladle Legend: Pt 2',
    'skit#104': 'Ladle Legend: Pt 3',
    'skit#105': 'For Brother',
    'skit#106': 'First Meet',
    'skit#107': "Everyone's Rock",
    'skit#108': "Sister's Toil",
    'skit#109': 'Same Mind',
    'skit#110': "She's a XX Cook",
    'skit#111': 'Quiz! Kyle',
    'skit#112': 'Oh Nooo~',
    'skit#113': 'Is Lazaris Bad?',
    'skit#114': "Kyle's Sibling",
    'skit#115': "Asbel's Father: Pt 2",
    'skit#116': "Asbel's Father: Pt 3",
    'skit#117': 'Dyunamis',
    'skit#118': "Everyone's Joy",
    'skit#119': 'Quiz! Reala',
    'skit#120': 'Melancholy',
    'skit#121': 'Anise & Money',
    'skit#122': 'So Fluffy...',
    'skit#123': "Whose Feat? (Unused)",
    'skit#124': "Whose Feat?",
    'skit#125': 'Strange Voice',
    'skit#126': 'Shocking Truth',
    'skit#127': 'Shocking Truth: After',
    'skit#128': 'Beauty Chat',
    'skit#129': 'Similar, Yet Not...',
    'skit#130': 'Meaning of Name',
    'skit#131': 'Rumor Truth?',
    'skit#132': 'Troubled Roni',
    'skit#133': 'Leon Magnus',
    'skit#134': 'Cannot Accept',
    'skit#135': "Judas's Stress",
    'skit#136': 'Looks Way Hotter',
    'skit#137': 'When Together...?',
    'skit#138': 'Hone Skills',
    'skit#139': "Kyle's Concern",
    'skit#140': 'Familiar Figure',
    'skit#141': 'Remember Back Then?',
    'skit#142': 'Like Family',
    'skit#143': 'Like Family: Pt 2',
    'skit#144': 'Nanaly Cooks Well',
    'skit#145': 'Sudden Harm',
    'skit#146': 'Funny Nanaly',
    'skit#147': 'Reliable Nanaly',
    'skit#148': "Nanaly's Kin",
    'skit#149': 'Mutual Feeling, Right?',
    'skit#150': 'Way to Cheer Up',
    'skit#151': 'Crucial Study',
    'skit#152': "Harold's Invention",
    'skit#153': "Harold's Nature",
    'skit#154': 'Heart of Tree',
    'skit#155': 'Secret Medicine...',
    'skit#156': 'Emil Returns',
    'skit#157': 'Mind the Place',
    'skit#158': 'Tactics Theory: Pt 5',
    'skit#159': 'Unlucky Reid',
    'skit#160': "Mao's Scary Story",
    'skit#161': 'Is That Tasty?',
    'skit#162': 'Day Big Ota Born',
    'skit#163': 'Child & Adult',
    'skit#164': 'Take Study Serious',
    'skit#165': 'Peers',
    'skit#166': 'Sword, Soul, Creed',
    'skit#167': 'Last Night in Bath',
    'skit#168': 'No Fighting',
    'skit#169': 'Farah is Great',
    'skit#170': 'Ready to Die',
    'skit#171': 'Special Circumstances',
    'skit#172': "Farah's Pride!",
    'skit#173': 'Wellside Gossip',
    'skit#174': "Keele's Classroom",
    'skit#175': "Keele's Classroom: Pt 2",
    'skit#176': 'Just Exhausted',
    'skit#177': 'Hard Times',
    'skit#178': 'Treasure Your Food',
    'skit#179': 'Wanna Know the Tree',
    'skit#180': 'What Keele Lacks',
    'skit#181': 'Unseen Truth',
    'skit#182': "Meredy's Home",
    'skit#183': 'Big Bro Tytree',
    'skit#184': "Suzu's Scary Story",
    'skit#185': 'Punishment Game',
    'skit#186': 'Quiz! Meredy',
    'skit#187': 'Quiz! Keele',
    'skit#188': 'What Remains Unchanged',
    'skit#189': 'Poppo Translates',
    'skit#190': 'Animal Typhoon',
    'skit#191': 'My Van Eltia',
    'skit#192': 'This Again?',
    'skit#193': 'Emergency',
    'skit#194': 'More Allies!: Pt 2',
    'skit#195': "Who's Highest?",
    'skit#196': 'Hate It That Much!',
    'skit#197': 'I Know, But Still...',
    'skit#198': 'I Know, But Still: Pt 2',
    'skit#199': 'I Know, But Still: Pt 3',
    'skit#200': 'My Limit',
    'skit#201': 'Ice Woman',
    'skit#202': 'Ice Pair',
    'skit#203': 'I Warned You',
    'skit#204': 'Spirit Pathos',
    'skit#205': 'Not Bad At All...?',
    'skit#206': 'Fine Amity',
    'skit#207': 'Sparring: Pt 2',
    'skit#208': 'Boasting Teacher?',
    'skit#209': 'Lloyd Excites',
    'skit#210': 'Count on Me',
    'skit#211': 'Tactics Theory: Pt 4',
    'skit#212': 'Which One?',
    'skit#213': 'Kanonno Special?',
    'skit#214': "Kratos's Intent?",
    'skit#215': 'Soap Girl: Pt 2',
    'skit#216': 'Soap Girl: Pt 3',
    'skit#217': 'Handy Wings',
    'skit#218': "I'll Help Out",
    'skit#219': 'Bearing Angel Fate',
    'skit#220': 'Crush',
    'skit#221': 'Nice to Meet',
    'skit#222': 'Saw a Ghost!',
    'skit#223': 'Together Always',
    'skit#224': "Genis's Worry",
    'skit#225': 'Licanth',
    'skit#226': 'Sorry, Did Not Know',
    'skit#227': 'Words with Heart',
    'skit#228': 'That Means Being Kids',
    'skit#229': 'Did You Get It?',
    'skit#230': 'Anyone Does It',
    'skit#231': 'Anyone Does It: Pt 2',
    'skit#232': 'Eternal Time',
    'skit#233': 'Is Reusing Good: Pt 2',
    'skit#234': 'Qualities of Teacher',
    'skit#235': 'Tell Me, Kratos',
    'skit#236': 'Listen Up',
    'skit#237': "Kratos's Wish",
    'skit#238': 'Tonic',
    'skit#239': 'My Way',
    'skit#240': 'Congrats on 1,000!',
    'skit#241': 'What Worry Draws Near',
    'skit#242': 'Defining Good and Evil',
    'skit#243': 'Warrior Ennui',
    'skit#244': 'Door Device',
    'skit#245': 'Precious Days',
    'skit#246': 'Just Like Kyle',
    'skit#247': 'Thinking of It...',
    'skit#248': 'Melon Trouble (Unused)',
    'skit#249': 'Melon Trouble',
    'skit#250': 'Same Scent',
    'skit#251': 'Missed You, Honey!',
    'skit#252': 'Harassment',
    'skit#253': 'Jealousy',
    'skit#254': 'That Makes No Sense!',
    'skit#255': 'Crazy for Her',
    'skit#256': 'The Ninja Life',
    'skit#257': 'A True Mans Romance!',
    'skit#258': 'Sticking Close',
    'skit#259': 'So Quiet',
    'skit#260': 'Paw Club Boss Deploys',
    'skit#261': 'Silent Cleaning Duty',
    'skit#262': 'Amulet Power',
    'skit#263': 'Got an Amulet?',
    'skit#264': 'Boost Guard Duty',
    'skit#265': 'Act Like Aunt?',
    'skit#266': 'Come Anytime, Kyu!',
    'skit#267': 'Envious',
    'skit#268': 'Outlaw Lloyd Irving',
    'skit#269': 'Envious: Pt 2',
    'skit#270': 'Snowy Day Promise',
    'skit#271': 'Bad Timing',
    'skit#272': 'Nightmare Strikes',
    'skit#273': 'Nightmare Strikes: Pt 2',
    'skit#274': 'Gaining Trust',
    'skit#275': 'Strange Emil?',
    'skit#276': 'Tyrant Emil',
    'skit#277': 'Throws Me Off',
    'skit#278': 'Complex Ties',
    'skit#279': 'Ah, Sir Glasses!',
    'skit#280': 'Truth Is, With You...',
    'skit#281': 'Does Love Reach You?',
    'skit#282': 'Secret Drill',
    'skit#283': 'Secret Favor',
    'skit#284': 'Ouch!',
    'skit#285': 'Lost Something Precious',
    'skit#286': 'First Meeting... Yet?',
    'skit#287': 'Man of Distinction',
    'skit#288': 'Pies Together',
    'skit#289': 'Strengths & Flaws',
    'skit#290': 'Delicate Man',
    'skit#291': 'Truth of World',
    'skit#292': "Richter's Past",
    'skit#293': 'Cannot Imagine',
    'skit#294': 'Mapo Ordeal',
    'skit#295': 'Being Different',
    'skit#296': "Veigue's Charm",
    'skit#297': 'Not to Underestimate',
    'skit#298': 'Greatsword Dilemma',
    'skit#299': 'This Is Nothing',
    'skit#300': 'Devoted Rocks',
    'skit#301': "Veigue's Allies",
    'skit#302': 'More Allies!: Pt 3',
    'skit#303': 'Even If Cannot Fight',
    'skit#304': 'Battle Veterans',
    'skit#305': 'Salty and Sweet',
    'skit#306': 'Familiar Duo',
    'skit#307': 'Love Talk: Claire',
    'skit#308': 'Wipe Tears',
    'skit#309': 'Outcast Race',
    'skit#310': 'Road to Feasts!',
    'skit#311': "Claire's Path",
    'skit#312': 'Handy Things',
    'skit#313': 'Captain Eugene!',
    'skit#314': 'That Combination...',
    'skit#315': 'Mutual Respect',
    'skit#316': "Eugene's Grooming",
    'skit#317': 'Owing to Originality',
    'skit#318': 'New Teacher',
    'skit#319': 'Mutual Feeling',
}

with open('lotes_p68/SKIT-01.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

for r in rows:
    rid = r['id']
    if rid in T:
        r['traducao'] = T[rid]
    else:
        print("MISSING:", rid)

out_p = 'lotes_p68/SKIT-01_retorno.tsv'
with open(out_p, 'w', encoding='utf-8', newline='') as f:
    w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
    w.writeheader()
    w.writerows(rows)
print("Wrote", out_p)
