import csv

T = {
    'ui#640': ('Unlock Condition', ''),
    'ui#641': ('Title Effect', ''),
    'ui#642': ('???', ''),
    'ui#643': ('Revenge of Otaota 2', ''),
    'ui#644': ('Artes', ''),
    'ui#645': ('Equip', ''),
    'ui#646': ('Items', ''),
    'ui#647': ('Strategy', ''),
    'ui#648': ('Status', ''),
    'ui#649': ('Craft', ''),
    'ui#650': ('Library', ''),
    'ui#651': ('System', ''),
    'ui#652': ('Cooking', ''),
    'ui#653': ('Gels', ''),
    'ui#654': ('Bottles', ''),
    'ui#655': ('Quests', ''),
    'ui#656': ('Titles', ''),
    'ui#657': ('Equip Book', ''),
    'ui#658': ('Character Book', ''),
    'ui#659': ('Monster Book', ''),
    'ui#660': ('Synopsis', ''),
    'ui#661': ('Guidebook', ''),
    'ui#662': ('Save', ''),
    'ui#663': ('Load', ''),
    'ui#664': ('Delete Data', ''),
    'ui#665': ('Options', ''),
    'ui#666': ('Return to Title', ''),
    'ui#667': ('Funds', ''),
    'ui#668': ('Grade Points', ''),
    'ui#669': ('Play Time', ''),
    'ui#670': ('Set and check artes.', ''),
    'ui#671': ('Change and check gear.', ''),
    'ui#672': ('Use and check items.', ''),
    'ui#673': ('Configure battle strategy and line-up.', ''),
    'ui#674': ('View detailed character stats.', ''),
    'ui#675': ('Craft food, gels, and bottles.', ''),
    'ui#676': ('View quest and miscellaneous records.', ''),
    'ui#677': ('Configure data and game settings.', ''),
    'ui#678': ('Cook ingredients and eat meals.', ''),
    'ui#679': ('Use gel materials to brew gels.', ''),
    'ui#680': ('Use bottle ingredients to make bottles.', ''),
    'ui#681': ('View quest information.', ''),
    'ui#682': ('View acquired titles.', ''),
    'ui#683': ('View equipment details.', ''),
    'ui#684': ('View character details.', ''),
    'ui#685': ('View monster data.', ''),
    'ui#686': ('Review story synopsis.', ''),
    'ui#687': ('Consult the guidebook.', ''),
    'ui#688': ('Save game progress.', ''),
    'ui#689': ('Load saved data.', ''),
    'ui#690': ('Delete saved game data.', ''),
    'ui#691': ('Modify game settings.', ''),
    'ui#692': ('Quit game and return to title screen.', ''),
    'ui#693': ('Network Connect', ''),
    'ui#694': ('Connect to network site via Infrastructure Mode.', ''),
    'ui#695': ('Export', ''),
    'ui#696': ('Create data to upload to site.', ''),
    'ui#697': ('Import', ''),
    'ui#698': ('Delete Data', ''),
    'ui#699': ('Delete data saved on Memory Stick.', ''),
    'ui#700': ('Normal Connect', ''),
    'ui#701': ('First Connect', ''),
    'ui#702': ('Export Mercenary Data', ''),
    'ui#703': ('Create mercenary data to upload to the site.', ''),
    'ui#704': ('Export Auth Data', ''),
    'ui#705': ('Import Mercenary Data', ''),
    'ui#706': ('Import Item Data', ''),
    'ui#707': ('Importing item data......', ''),
    'ui#708': ('Import Prequel Save Bonus', ''),
    'ui#709': ('Create authentication data.', ''),
    'ui#710': ('Connection cancelled.', ''),
    'ui#711': ('Create mercenary data.', ''),
    'ui#712': ('Use existing authentication data?', ''),
    'ui#713': ('Could not create authentication data.', ''),
    'ui#714': ('Cancel connection?', ''),
    'ui#715': ('Could not read authentication data.', ''),
    'ui#716': ('Could not read save data.', ''),
    'ui#717': ('Failed to create.', ''),
    'ui#718': ('Mercenary data was not exported.', ''),
    'ui#719': ('Exported mercenary data.', ''),
    'ui#720': ('Did not create mercenary data.', ''),
    'ui#721': ('Failed to export mercenary data.', ''),
    'ui#722': ('No prequel save data found.', ''),
    'ui#723': ('Save data updated.', ''),
    'ui#724': ('Bonus equipment can be received at Storage.', ''),
    'ui#725': ('DL Quest Keys can be obtained from Rocks.', ''),
    'ui#726': ('DL Quest Keys already received from Rocks.', ''),
    'ui#727': ('Import cancelled.', ''),
    'ui#728': ('Failed to read item data.', ''),
    'ui#729': ('Item data is corrupted.', ''),
    'ui#730': ('This data has already been imported.', ''),
    'ui#731': ('Mercenary data read.', ''),
    'ui#732': ('Failed to read mercenary data.', ''),
    'ui#733': ('Mercenary data is corrupted.', ''),
    'ui#734': ('Failed to import data.', ''),
    'ui#735': ('Reading authentication data.', ''),
    'ui#736': ('Authentication data corrupted.', ''),
    'ui#737': ('Authentication data read.', ''),
    'ui#738': ('Authentication data already exists.', ''),
    'ui#739': ('Cancel import?', ''),
    'ui#740': ('Quit without saving data?', ''),
    'ui#741': ('Overwrite this?', ''),
    'ui#742': ('Create this?', ''),
    'ui#743': ('Could not create folder.', ''),
    'ui#744': ('Created folder.', ''),
    'ui#745': ('Site Link Data', ''),
    'ui#746': ('Auth Data', ''),
    'ui#747': ('Site Import Folder', ''),
    'ui#748': ('Almanac Ruins', ''),
    'ui#749': ('Mt. Absol', ''),
    'ui#750': ('Veratropa', ''),
    'ui#751': ('Brownie Mine', ''),
    'ui#752': ('Kadaif Desert', ''),
    'ui#753': ('Mt. Alterata', ''),
    'ui#754': ('Holy Langriths', ''),
    'ui#755': ('Elan Vital', ''),
    'ui#756': ('Mt. Rhubarb', ''),
    'ui#757': ('Sifno Spring', ''),
    'ui#758': ('Confeito Forest', ''),
    'ui#759': ('Vortex', ''),
    'ui#760': ('Crystal', '星晶 (max 9)'),
    'ui#761': ('Alta Village', ''),
    'ui#762': ('Black Jewel', ''),
    'ui#763': ('Dawn Servant', ''),
    'ui#764': ('Koukitanjutsu', ''),
    'ui#765': ('Kouki Scripture', ''),
    'ui#766': ('Soul Alchemy', ''),
    'ui#767': ('Document', ''),
    'ui#768': ('Progenitor', ''),
    'ui#769': ('Sealed Dimension', ''),
    'ui#770': ('Salt Crystal', ''),
    'ui#771': ('Bellflower Herb', ''),
    'ui#772': ('Spiral Fungus', ''),
    'ui#773': ("Copis's Rod", ''),
    'ui#774': ('Oil Tree', ''),
    'ui#775': ('Yurlung Tree', ''),
    'ui#776': ('Wanderweed', ''),
    'ui#777': ('Gibeon', ''),
    'ui#778': ('Transcript', ''),
    'ui#779': ('Quit without saving data?', ''),
    'ui#780': ('Game Clear', ''),
    'ui#781': ('Van Eltia', ''),
    'ui#782': ('World Map', ''),
    'ui#783': ('Play Time', ''),
    'ui#784': ('Lounge', ''),
    'ui#785': ('Bridge', ''),
    'ui#786': ('Hall', ''),
    'ui#787': ('Engine Room', ''),
    'ui#788': ('Cabin', ''),
    'ui#789': ('3F', ''),
    'ui#790': ('2F', ''),
    'ui#791': ('1F', ''),
    'ui#792': ('B1F', ''),
    'ui#793': ('B2F', ''),
    'ui#794': ('Shop', ''),
    'ui#795': ('1F Hallway A', ''),
    'ui#796': ('Room 2', ''),
    'ui#797': ('Room 1', ''),
    'ui#798': ('Mess Hall', ''),
    'ui#799': ('Deck', ''),
    'ui#800': ('Clinic', ''),
    'ui#801': ('Room 3', ''),
    'ui#802': ('Room 4', ''),
    'ui#803': ('1F Hallway B', ''),
    'ui#804': ('Lab', ''),
    'ui#805': ('B1F Hallway A', ''),
    'ui#806': ('Room 7', ''),
    'ui#807': ('Room 6', ''),
    'ui#808': ('Room 5', ''),
    'ui#809': ('Room 8', ''),
    'ui#810': ('Room 9', ''),
    'ui#811': ('Room 10', ''),
    'ui#812': ('B1F Hallway B', ''),
    'ui#813': ('Hold', ''),
    'ui#814': ('Room 14', ''),
    'ui#815': ('Room 13', ''),
    'ui#816': ('Room 12', ''),
    'ui#817': ('Room 11', ''),
    'ui#818': ('Room 15', ''),
    'ui#819': ('Room 16', ''),
    'ui#820': ('Room 17', ''),
    'ui#821': ('Room 18', ''),
    'ui#822': ('Ship Map', ''),
    'ui#823': ('Change Floor', ''),
    'ui#824': ('Change Room', ''),
    'ui#825': ('Back', ''),
    'ui#826': ('New Quests', ''),
    'ui#827': ('Quests', ''),
    'ui#828': ('Client', ''),
    'ui#829': ('Main Events', ''),
    'ui#830': ('Sub-Events', ''),
    'ui#831': ('Default Play', ''),
    'ui#832': ('Random Play', ''),
    'ui#833': ('Select All Battle BGM', ''),
    'ui#834': ('Choose from Standard BGM', ''),
    'ui#835': ('Choose from Boss BGM', ''),
    'ui#836': ('Filter by Series', ''),
    'ui#837': ('Filter by Artist', ''),
    'ui#838': ('Choose from All Ship BGM', ''),
    'ui#839': ('TOS: Dawn of New World', ''),
    'ui#840': ('Plays standard default music.', ''),
    'ui#841': ('Plays random track from available music.', ''),
    'ui#842': ('Select from all available tracks.', ''),
    'ui#843': ('Select from normal battle tracks.', ''),
    'ui#844': ('Select from boss battle tracks.', ''),
    'ui#845': ('Filters tracks by game series.', ''),
    'ui#846': ('Filters tracks by musical artist.', ''),
    'ui#847': ('Select from TOS: Dawn of New World battle tracks.', ''),
    'ui#848': ('Use installed game data?', ''),
    'ui#849': ('To the Van Eltia', ''),
    'ui#850': ('Return to the Van Eltia?', ''),
    'ui#851': ('Not your destination. Enter anyway?', ''),
    'ui#852': ('Select dungeon you wish to enter.', ''),
    'ui#853': ('Enter', ''),
    'ui#854': ('Move', ''),
    'ui#855': ('Shortcut', ''),
    'ui#856': ('Page Turn', ''),
    'ui#857': ('Select', ''),
    'ui#858': ('Decide', ''),
    'ui#859': ('Ship Elevator', ''),
    'ui#860': ('-----', ''),
}

with open('lotes_p68/UI-03.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

missing = []
for r in rows:
    rid = r['id']
    if rid not in T:
        missing.append(rid)
    else:
        tr, nt = T[rid]
        r['traducao'] = tr
        if nt:
            r['nota_do_tradutor'] = nt

if missing:
    print("MISSING:", len(missing), missing[:5])
else:
    out_p = 'lotes_p68/UI-03_retorno.tsv'
    with open(out_p, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
        w.writeheader()
        w.writerows(rows)
    print("Wrote", out_p)
