import json, re
from val_check import validate_dict, nomes_proprios, CAUDA

d = json.load(open('lotes_corte3/VAL3-01.json', encoding='utf-8'))
itens = d['itens']
meta = d['meta_bytes_a_cortar']

overrides = {
    # Key & Story items
    'valuables#227': 'Key used to contact other worlds. Seems to have lost magic power.',
    'valuables#87': 'A letter torn to shreds. Writing is illegible; grudge is palpable.',
    'valuables#110': 'Paper breeding money. In a sense, the most terrifying monster of all.',
    'valuables#147': 'Protects from splattering water and spitting oil. Detachable.',
    'valuables#189': 'Hot spring egg made in volcano at risk to life. Reasonably tasty.',
    'valuables#201': 'Mirror bears eye pattern, scratched into it by previous owner.',
    'valuables#224': 'Key unlocking door to sealed land. Chipped and currently unusable.',
    'valuables#165': 'Afterword calls this definitive edition, but sequel ships this summer.',
    'valuables#263': 'Jewel left in a room on Van Eltia for a long time for unknown reasons.',
    'valuables#186': 'A supreme, scrumptious dish. A single bite will bring you to tears.',
    'valuables#136': 'Blowing it creates a shockwave shattering windows in 100-meter radius.',
    'valuables#107': 'Writing spaces are stark white; looking at it fills one with ennui.',
    'valuables#113': 'Illuminates dark places. Being oil is no excuse for weird things.',
    'valuables#124': 'Slime from a Polwiggle. Used in medicine, cosmetics, and industry.',
    'valuables#72': 'Recipe for "Commonly Known as Delicious-Delicious" that Coda craves.',
    'valuables#98': 'Favorite item of unfortunate girl. She is alive, so there is no curse.',
    'valuables#133': 'As one grows up, contents become plentiful, and it becomes a chore.',
    'valuables#198': 'The kind of ordinary thing you recognize as happiness only once gone.',
    'valuables#92': 'Rope for luggage, well regarded by those who enjoy being tied up.',
    'valuables#127': 'Doctors use it to hear heartbeats. If pointed at you, you must undress.',
    'valuables#139': 'Comes with grandiose note claiming the board is the entire world.',
    'valuables#159': 'Belonged to a woman who met a mishap. She has since bought a new set.',
    'valuables#118': 'Many women drink this to end the day feeling true to themselves.',
    'valuables#180': 'For summer vacation memories, it can be wielded as a lethal weapon.',
    'valuables#204': 'Charred doll found in dense forest. Its eyeballs have been gouged out.',
    'valuables#101': 'Party gag item; getting a laugh with it is a formidable feat.',
    'valuables#174': 'Extremely fragile; putting weight on it shatters it into tiny pieces.',
    'valuables#195': 'Horrifying item you can never escape. Beware its sudden strikes.',
    'valuables#207': 'Portrait of a child. Face is blacked out, but eyes can be seen.',
    'valuables#144': 'Tool used to crush ice. If found near a bed, proceed with caution.',
    'valuables#210': 'Decorated with countless eyes; mirror surfaces are painted black.',
    'valuables#130': 'Purpose unknown. Rumor says you die peering through it like a telescope.',
    'valuables#142': 'Nice pocket watch, but hands move at startling speed. Harmless.',
    'valuables#75': 'Recipe for "Mountain and Sea Delicacy Soup" that Coda craves.',
    'valuables#116': 'Lavish item made with mellow grapes. Grape lovers ascend to heaven.',
    'valuables#162': 'Invention devised by humankind to proceed through shopping quickly.',
    'valuables#104': 'Seals a demon that once drove heaven, earth, and demon realm to ruin.',
    'valuables#121': 'Part from antique clock destroyed by grandfather in a fit of rage.',
    'valuables#213': 'Spherical compass shaped like an eyeball. Needle spins ceaselessly.',
    'valuables#95': 'Reverts skin age to before infancy. Risks vanishing you completely.',
    'valuables#156': 'Picture of adorable kitten. Contains clues on eliminating war.',
    'valuables#168': 'Banner bearing tiger pattern. Exudes nobility of the Beast King.',
    'valuables#275': 'Green jewel from a green chest in the Holy Land of Langriths.',
    'valuables#150': 'Lets you see at night as in daylight. Not for weird uses.',
    'valuables#222': 'Tablet inscribed with numbers, encrypting all past history.',
    'valuables#81': 'Recipe for "Manchu-Han Imperial Feast" that Coda craves.',
    'valuables#84': 'Passionately builds a romantic mood between couples... or not.',
    'valuables#266': 'White jewel from a green chest in the Rhubarb Mountains.',
    'valuables#272': 'Blue jewel from a green chest in the Sifno Spring Cave.',
    'valuables#219': 'Two-handed sword favored by a legendary hero.',
    'valuables#16': "Allows listening to 'Meeting at Fountain Plaza' at Claire's.",
    'valuables#177': 'Features image sketch looking far creepier than needed.',
    'valuables#89': 'In other words, a candle. How it is used depends on the user.',
    'valuables#192': 'Photo so embarrassing it makes even strangers blush.',
    'valuables#216': 'Proof obtained only by one who conquered the sealed land.',
    'valuables#37': "Key to DL Quest 'A Closed Heart, A Continuing Future'.",
    'valuables#78': 'Recipe for "Medicinal Champuru" that Coda craves.',
    'valuables#69': 'Recipe for "Black Tea Cookies" that Coda craves.',
    'valuables#171': 'So nutritious it keeps you awake for a whole week.',
    'valuables#269': 'Red jewel from a green chest in the Almanac Ruins.',
    'valuables#13': "Allows listening to 'have a good rest time' at Claire's.",
    'valuables#153': 'Astonishingly, used to nail plywood and the like.',
    'valuables#54': 'Recipe for "Pineapple Rice" that Coda craves.',
    'valuables#34': "Key to DL Quest 'The Wall That Must Be Overcome'.",
    'valuables#40': "Key to DL Quest 'In Search of the Ultimate Dish'.",
    'valuables#66': 'Recipe for "Cheese Fondue" that Coda craves.',
    'valuables#61': 'Recipe for "Okonomiyaki" that Coda craves.',
    'valuables#31': "Key to DL Quest 'A Fight That Cannot Be Lost'.",
    'valuables#56': 'Recipe for "Mabo Curry" that Coda craves.',
    'valuables#2499': 'Title for one dedicated to living as an adventurer.',

    # Specific Artes
    'valuables#1281': 'Arcane arte: thrust launch into Tempest, Demon Fang.',
    'valuables#885': 'Arcane arte: leaves gifts at foe feet after Explosive Thrust Raid.',
    'valuables#1886': 'Arcane arte: slices up-slashed foes in air, impaling down.',
    'valuables#571': 'Arte: restores nearby ally TP, curing status ailments.',
    'valuables#1194': 'Space-time sword secret arte: distorts space to cleave foes in two.',
    'valuables#763': 'Arcane arte: impales foes at speed into aerial slashes.',
    'valuables#817': 'Arcane arte: fires 1 straight and 4 homing arrows.',
    'valuables#824': 'Secret arte: draws foes with coiling water snake strikes.',
    'valuables#971': 'Deploys barrier felling foes while healing allies.',
    'valuables#1455': 'Arcane arte: shield bash launch into sharp thrusts.',
    'valuables#1573': 'Fires arrows above foes, bursting on those below.',
    'valuables#1651': 'Arcane arte: captures foes, detonating with magic.',
    'valuables#1802': 'Unleashes 3 attacks (slash, strike, slash) like an enraged beast.',
    'valuables#731': 'Secret arte: heavy thrust halts foes, launching up.',
    'valuables#1293': 'Arcane arte: flame fist punch, boiling lava around.',
    'valuables#1650': 'Arcane arte: open-book pages fly to slice foes.',
    'valuables#1785': 'Arcane arte: strikes with axe, sword, then cleaves.',
    'valuables#567': 'Arte: raises ally magic defense, curing debuffs.',
    'valuables#630': 'Secret arte: slashes up, forming tornado with spin slash.',
    'valuables#883': 'Arcane arte: advancing slashes into shockwaves.',
    'valuables#1677': 'Secret arte: punches vitals with pommels to fell foes.',
    'valuables#1715': 'Secret arte: repeatedly slashes aerial foes after up-slashes.',
    'valuables#1739': 'Arcane arte: launches, spin-ascends, firing blasts.',
    'valuables#1758': 'Slashes foes like swallow, kicking up at the end.',
    'valuables#1791': 'Arcane arte: water slashes, finishing with shockwaves.',
    'valuables#1813': 'Arcane arte: binds slashed foes to sky with fierce flash.',
    'valuables#1930': 'Secret arte: fires lightning daggers to call thunder.',
    'valuables#563': 'Arte: raises ally magic attack, curing debuffs.',
    'valuables#634': 'Secret arte: lifts foes with sword pressure to finish.',
    'valuables#674': 'Executes two slashes connecting downward and upward slashes.',
    'valuables#1313': 'Arcane arte: shockwaves, punching aerial foes.',
    'valuables#1443': 'Arcane arte: launches foes into spin kicks and air slashes.',
    'valuables#1727': 'Secret arte: slashes foes high into dive kicks.',
    'valuables#301': 'Arte: restores moderate HP to allies (in battle).',
    'valuables#807': 'Creates rock masses from arrows hitting ground.',
    'valuables#848': 'Arcane arte: godspeed thrusts stir gusts to fell foes.',
    'valuables#908': 'Thrusts sword into ground for rock lances.',
    'valuables#924': 'Secret arte: teleports above foe with flame slashes.',
    'valuables#980': 'Arcane arte: thrusts spear into ground for water pillar.',
    'valuables#982': 'Arcane arte: launches foes skyward to flame thrusts.',
    'valuables#1333': 'Arcane arte: pulls foes from downward swing, rushing.',
    'valuables#1667': 'Secret arte: drops from leap, impacting on landing.',
    'valuables#1901': 'Secret arte: photon swords in iai draws.',
    'valuables#1985': 'Short-range skill: bow launch, following up.',
    'valuables#1008': 'Arcane arte: two slashes from Crescent Flash.',
    'valuables#1024': 'Takes atmospheric qi into body to restore HP.',
    'valuables#1050': 'Arcane arte: swings weapons to blast rock shards.',
    'valuables#1449': 'Arcane arte: biting fang punches crush foes.',
    'valuables#1457': 'Distances, rushes forward, and attacks with thrusts.',
    'valuables#1857': 'Arcane arte: fires shot skyward piercing even gods.',
    'valuables#1994': 'Secret arte: jumps, firing arrows to ground.',
    'valuables#1998': 'Arcane arte: fires fan arrows, focused forward.',
    'valuables#2055': 'Arcane arte: jumps, shooting spheres at diagonal foes.',
    'valuables#2063': 'Arcane arte: detonates fighting spirit to fell nearby foes.',
    'valuables#341': 'Arte: wind blades around foes slice touchers.',
    'valuables#370': 'Arte: rock masses surge beneath target.',
    'valuables#608': 'Arcane arte: leaps into air, attacking with rapid dive.',
    'valuables#785': 'Arcane arte: thrusts and charges forward with spear.',
    'valuables#873': 'Secret arte: rapid air slashes after Soaring Blade.',
    'valuables#875': 'Secret arte: throws bombs, closing in with thrusts.',
    'valuables#912': 'Secret arte: sword flash while closing in instantly.',
    'valuables#951': 'Secret arte: crescent moon slashes, up and down.',
    'valuables#1061': 'Wind secret arte: slams weapons down from air.',
    'valuables#1476': 'Secret arte: slashes through foes, chasing again.',
    'valuables#1596': 'Arcane arte: uppercuts and triangle kicks fell foes.',
    'valuables#1598': 'Arcane arte: slaps back and forth with feet to fell foes.',
    'valuables#1637': "Pins foe's shadow to ground to increase stagger time.",
    'valuables#1686': 'Alters aerial trajectory, dropping knees onto foes.',
    'valuables#1754': 'Arcane arte: dances skyward with slashes, kicking down.',
    'valuables#1777': 'Connects spin axe slashes into sword strikes.',
    'valuables#1783': 'Arcane arte: sweeps feet, launching foes with blasts.',
    'valuables#1823': 'Arcane arte: impales foes with light blades.',
    'valuables#1855': 'Fires buckshot bursting above foes, raining down.',
    'valuables#2030': 'Arcane arte: lightning launch, dropping steel.',
    'valuables#787': 'Arcane arte: follows Flying Ruin Spear with tornadoes.',
    'valuables#918': "Teleports above enemy's head to deliver surprise attack.",
    'valuables#1216': 'Arcane arte: attacks nearby foes with spinning chakrams.',
    'valuables#1459': 'Secret arte: steep thrusts after dash thrust.',
    'valuables#1684': 'Arcane arte: launches foes, slamming them to ground.',
    'valuables#1750': 'Releases cherry blossom slashes, launching foes skyward.',
    'valuables#1815': 'Slices foes with vacuum waves and swift up-slashes.',
    'valuables#1851': 'Refines storm thoughts, firing them as wind masses.',
    'valuables#378': 'Arte: torrent of water surges around target.',
    'valuables#561': 'Arte: raises ally attack, curing ailments briefly.',
    'valuables#565': 'Arte: raises ally defense, curing debuffs briefly.',
    'valuables#871': 'Secret arte: rapid air slashes after Fang Thrust.',
    'valuables#1006': 'Arcane arte: cold shockwaves trace cross to attack.',
    'valuables#1049': 'Secret arte: blasts rock shards away with impacts.',
    'valuables#1084': 'Arcane arte: leaps, sending shockwaves to ground.',
    'valuables#1104': 'Secret arte: follows with up-thrust after Flashing Impact.',
    'valuables#1453': 'Shreds foes with thrusts, repelling with shield.',
    'valuables#1503': 'Arcane arte: increases foe stagger time briefly.',
    'valuables#1635': 'Arcane arte: kicks foes up, shredding with sickles.',
    'valuables#1659': "Dives into foe's pocket, kicking upward.",
    'valuables#1915': 'Arcane arte: wings of light chase aerial foes.',
    'valuables#353': 'Arte: thrusts lightning sword into ground to strike.',
    'valuables#684': 'Secret arte: swings weapons to fell foes.',
    'valuables#727': 'Secret arte: throws downed foes for heavy damage.',
    'valuables#1026': 'Arcane arte: freezing palm strike fells foes.',
    'valuables#1053': 'Secret arte: swings weapons with momentum rapidly.',
    'valuables#1141': 'Arcane arte: steps back, executing cross slashes.',
    'valuables#1301': 'Secret arte: dive bombing with cool hip.',
    'valuables#1544': 'Summons lightning from training, unleashing power.',
    'valuables#1554': 'Secret arte: flings foes forward with shockwaves.',
    'valuables#1592': 'Arcane arte: gathers qi for qigong bullets.',
    'valuables#1618': 'Arcane arte: calls giant ice blocks from ground.',
    'valuables#1673': 'Secret arte: slashes foes up with up-swings.',
    'valuables#1888': 'Arcane arte: merciless follow-ups on impaled foes.',
    'valuables#2053': 'Arcane arte: attacks with close Charge Bullets.',
    'valuables#418': 'Arte: flame spheres cause explosions on ground.',
    'valuables#467': 'Arte: countless bubbles surge beneath target.',
    'valuables#598': 'Arcane arte: countless thrusts, following in air.',
    'valuables#678': 'Unleashes a sharp thrust followed by upward fist strike.',
    'valuables#869': 'Secret arte: launches foes into three strikes.',
    'valuables#894': 'Secret arte: throws daggers down with shockwaves.',
    'valuables#976': 'Arcane arte: launches foes skyward into thrusts.',
    'valuables#1030': 'Arcane arte: thrusts powered fist to blast foes.',
    'valuables#1111': 'Swings swords at speed to shred falling leaves.',
    'valuables#1147': "Circles to enemy's back with thrust to attack.",
    'valuables#1275': 'Arcane arte: dives from air onto foes like meteor.',
    'valuables#1394': 'Secret arte: rapid air slashes after Wing Edge.',
    'valuables#1405': 'Arcane arte: shoots guns, distracting with Pow Hammer.',
    'valuables#1441': 'Arcane arte: shreds foes with weapons after 3 strikes.',
    'valuables#1587': 'Arcane arte: pins foes to ground with axe kick.',
    'valuables#1696': 'Leaps, firing arrows that detonate near foes.',
    'valuables#1713': 'Slashes foes up with kodachi, chasing with arrows.',
    'valuables#1717': 'Secret arte: finishes up-slashed foes with bow.',
    'valuables#1876': 'Secret: swift forward lunges pierce anything.',
    'valuables#1880': 'Arcane arte: iai slashes, slipping behind foe.',
    'valuables#2032': 'Executes three kicks, raises sword overhead, and slashes.',
    'valuables#380': 'Arte: magic circle in sky summons mighty winds.',
    'valuables#478': 'Arte: magnificent hammer above target attacks.',
    'valuables#551': 'Arte: slightly reduces enemy defense briefly.',
    'valuables#836': 'Arcane arte: fiery flash pierces numerous foes.',
    'valuables#914': 'Secret arte: leaps back, throwing kunai forward.',
    'valuables#984': 'Arcane arte: shatters foes with crystals.',
    'valuables#1018': 'Arcane arte: slashes ground, blasting rock shards.',
    'valuables#1186': 'Arcane arte: slashes down, launches up to spin slashes.',
    'valuables#1260': 'Secret arte: rapid-fire attacks after backstep.',
    'valuables#1835': 'Arcane arte: 6 aerial spin kicks while soaring.',
    'valuables#2001': 'Deals continuous damage with gunpowder arrows.',
    'valuables#317': "Arte: increases allies' physical defense briefly.",
    'valuables#347': 'Arte: sharp rocks from ground beneath target.',
    'valuables#382': 'Arte: sub-space near target foes deals damage.',
    'valuables#1066': 'Wind secret arte: swings weapons swiftly.',
    'valuables#1115': 'Vacuum waves from slashes vortex into flash.',
    'valuables#1348': 'Secret arte: bangs frying pan for sound attacks.',
    'valuables#1376': 'Secret arte: up-kick into a lightning strike.',
    'valuables#1392': 'Secret arte: up-kicks and slashes after Fang Edge.',
    'valuables#1416': 'Secret arte: qi crushing punches from stompings.',
    'valuables#1509': 'Arte: attacks foes with shower of blessed swords.',
    'valuables#1847': 'Refines thoughts, firing arrows through foes.',
    'valuables#1874': 'Secret arte: leaps, thrusting down lightning sword.',
    'valuables#1964': 'Arcane arte: earth shockwaves trigger upon hit.',
    'valuables#2084': 'Arcane arte: rushes with gunblade, shooting gravel.',
    'valuables#437': "Arte: raises allies' stats, slightly restoring HP.",
    'valuables#493': 'Arte: reduces magic damage taken by ally briefly.',
    'valuables#596': 'Secret arte: thrusts followed by extra hit.',
    'valuables#676': 'Slams palm strike, detonating qi to fell foes.',
    'valuables#916': 'Knocks down foes, releasing fighting spirit.',
    'valuables#992': 'Arcane arte: shatters crystals with sword strikes.',
    'valuables#1100': 'Secret arte: shockwaves up after Sky Soaring Slash.',
    'valuables#1102': 'Secret arte: fire slashes after Explosion Sword.',
    'valuables#1159': "Secret arte: dives into foe pocket, felling them.",
    'valuables#1214': 'Secret arte: attacks nearby foes with chakrams.',
    'valuables#1220': 'Arcane: throws chakrams to call lightning.',
    'valuables#1243': 'Secret arte: attacks nearbys, raising icicles.',
    'valuables#1325': 'Unleashes high-power slashes from downward swings.',
    'valuables#1342': 'Unleashes the terror of a frying pan in air.',
    'valuables#1350': 'Arcane arte: found answer to handling sunfish.',
    'valuables#1407': 'Secret arte: shoots at foe feet, raising water pillar.',
    'valuables#1581': 'Arcane arte: fires qigong bullets at distant foes.',
    'valuables#1819': 'Secret arte: charges weapons, slicing foes.',
    'valuables#1837': 'Secret: fires fire thought in rings from above.',
    'valuables#1913': 'Arcane arte: aerial kicks into rapid attacks.',
    'valuables#1936': 'Arcane arte: rains freezing daggers around foe.',
    'valuables#335': 'Arte: lava stream appears around target.',
    'valuables#345': 'Arte: gravel surges up from around target.',
    'valuables#416': 'Arte: gravity field crushes earth together.',
    'valuables#527': 'Arte: wind arrows attack foes multiple times.',
    'valuables#757': 'Arcane arte: attacks foes with light orbs.',
    'valuables#775': 'Rushes forward, sweeping spear left and right.',
    'valuables#779': 'Launches foes, follows in air, and knocks down.',
    'valuables#809': 'Arcane arte: fires 8 arrows skyward at once.',
    'valuables#1004': 'Arcane arte: Phoenix aura cloaked, attacking up.',
    'valuables#1317': 'Arcane arte: focuses qi, inflating massively.',
    'valuables#1430': 'Cleaves through foes and slashes from behind.',
    'valuables#1590': 'Arcane arte: kicks endlessly, slamming down.',
    'valuables#1700': 'Arcane arte: sky-fired arrows rain all around.',
    'valuables#1706': 'Secret arte: brandishes weapons to slash foes.',
    'valuables#1800': 'Arcane arte: rapid three-hit combo into Beast.',
    'valuables#2044': 'Secret arte: shoots spheres from crossed muzzles.',
    'valuables#2057': 'Secret arte: punches with soul to knock foes down.',
    'valuables#640': 'Secret arte: flame-cloaked aerial spin kicks.',
    'valuables#705': 'Unleashes a fist flash while advancing forward.',
    'valuables#717': 'Steps into pocket and launches foes high into air.',
    'valuables#723': 'Secret arte: throws downed foes for damage.',
    'valuables#937': 'Secret arte: slashes through after dash thrust.',
    'valuables#1129': 'Arcane arte: cold slashes spread in V-shape.',
    'valuables#1190': 'Arcane arte: slashes up, releasing fire power.',
    'valuables#1299': 'Launches foes with shoulder tackle into uppercut.',
    'valuables#1579': 'Arcane arte: piercing shots from up-kick.',
    'valuables#1680': 'Arcane arte: leaps, delivering accelerated dive kick.',
    'valuables#1733': 'Secret arte: dances into air, unleashing shockwaves.',
    'valuables#1781': 'Temporarily boosts stats after hitting with icicles.',
    'valuables#1882': 'Arcane arte: rapid kicks, stepping into foes.',
    'valuables#1984': 'Fires several arrows in blink of an eye.',
    'valuables#357': 'Arte: sharp blocks of ice beneath target.',
    'valuables#394': "Arte: raises single ally's attack briefly.",
    'valuables#515': 'Wind arte: slices foes with giant vacuum claws.',
    'valuables#517': 'Fire arte: barrage of scalding shots at foes.',
    'valuables#547': 'Arte: reduces enemy physical attack briefly.',
    'valuables#582': 'Secret arte: two shockwave slashes rapidly.',
    'valuables#659': 'Arcane arte: draws and releases flame power.',
    'valuables#707': 'Delivers full-powered thrust to fell enemies.',
    'valuables#887': 'Secret arte: lifts foes with up-thrust.',
}

rules = [
    (r'^A skill that attaches a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Attaches talisman lowering enemy \1 by chance.'),
    (r'^Attaches a talisman briefly lowering enemy (\w+) by chance\.$',
     r'Attaches talisman lowering enemy \1 by chance.'),
    (r'^Secret arte: flings a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Secret arte: flings talisman lowering enemy \1 by chance.'),
    (r'^Secret arte: flings a talisman briefly lowering enemy (\w+) by chance\.$',
     r'Secret arte: flings talisman lowering enemy \1 by chance.'),
]

out = {}
for x in itens:
    item_id = x['id']
    en = x['en']
    if item_id in overrides:
        s = overrides[item_id]
        out[item_id] = s

print(f"Total entries in out: {len(out)} / {len(itens)}")
ok = validate_dict('lotes_corte3/VAL3-01.json', out)
if ok:
    with open('lotes_corte3/VAL3-01_out.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
    print("SAVED lotes_corte3/VAL3-01_out.json!")
