import csv

T = {
    'ui#0': ('Would you like to save?', ''),
    'ui#1': ('Continue playing?', ''),
    'ui#2': ('P. Atk', ''),
    'ui#3': ('P. Atk 2', ''),
    'ui#4': ('M. Atk', ''),
    'ui#5': ('P. Def', ''),
    'ui#6': ('M. Def', ''),
    'ui#7': ('Agility', ''),
    'ui#8': ('Level', ''),
    'ui#9': ('EXP', ''),
    'ui#10': ('Base P. Atk', ''),
    'ui#11': ('Base M. Atk', ''),
    'ui#12': ('Base P. Def', ''),
    'ui#13': ('Base M. Def', ''),
    'ui#14': ('Base Agility', ''),
    'ui#15': ('Req. Lv', ''),
    'ui#16': ('P. Atk', ''),
    'ui#17': ('M. Atk', ''),
    'ui#18': ('Agi', ''),
    'ui#19': ('Slots Left', ''),
    'ui#20': ('P. Def', ''),
    'ui#21': ('M. Def', ''),
    'ui#22': ('Required level to equip.', ''),
    'ui#23': ('Remaining upgrade slots.', ''),
    'ui#24': ('Obtained', ''),
    'ui#25': ('Inventory full.', ''),
    'ui#26': ('Could not obtain anything.', ''),
    'ui#27': (' World Map', ''),
    'ui#28': ('Install Game Data', ''),
    'ui#29': ('Delete Data', ''),
    'ui#30': ('Delete data saved on Memory Stick.', ''),
    'ui#31': ('Melee class attacking with powerful weapons.', ''),
    'ui#32': ('A class with varied sword skills.', ''),
    'ui#33': ('All-rounder wielding both swords and attack artes.', ''),
    'ui#34': ('Brawler class specializing in hand-to-hand combat.', ''),
    'ui#35': ('Class skilled in fast dagger attacks and stealing.', ''),
    'ui#36': ('Class adept in special martial arts called ninjutsu.', ''),
    'ui#37': ('A class specializing in offensive spells.', ''),
    'ui#38': ('A class skilled in healing and support spells.', ''),
    'ui#39': ('All-rounder proficient in attack and healing artes.', ''),
    'ui#40': ('Dual-wielding swordsman fighting with two blades.', ''),
    'ui#41': ('Power fighter wielding a massive greatsword.', ''),
    'ui#42': ('Brawler class equipped with ki healing techniques.', ''),
    'ui#43': ('Combines ranged gun attacks with close-range daggers.', ''),
    'ui#44': ('Versatile class combining greatswords and support.', ''),
    'ui#45': ('A class unleashing rapid attacks with dual guns.', ''),
    'ui#46': ('Select the class you want to change to.', ''),
    'ui#47': ('Class change requirements not met.', ''),
    'ui#48': ('Class Level:', ''),
    'ui#49': ('Current class. Please select another class.', ''),
    'ui#50': ('Cannot change class while on a quest.', ''),
    'ui#51': ('Cannot remove gear because inventory is full.', ''),
    'ui#52': ('Could not change class.', ''),
    'ui#53': ('Cannot hold any more.', ''),
    'ui#54': ('Not enough materials.', ''),
    'ui#55': ('Food effects only work inside dungeons.', ''),
    'ui#56': ('That dish effect is already active.', ''),
    'ui#57': ('How many to make?', ''),
    'ui#58': ('Loading data......', ''),
    'ui#59': ('Select member to swap or remove.', ''),
    'ui#60': ('Select member to add to party.', ''),
    'ui#61': ('Disband party?', ''),
    'ui#62': ('Disbanded party.', ''),
    'ui#63': ('Exceeds quest member limit.', ''),
    'ui#64': ('Name', ''),
    'ui#65': ('Class', ''),
    'ui#66': ('Level', ''),
    'ui#67': ('Battles', ''),
    'ui#68': ('Event Player', ''),
    'ui#69': ('Skit Player', ''),
    'ui#70': ('Event Replay', ''),
    'ui#71': ('Choose from All', ''),
    'ui#72': ('Choose by Character', ''),
    'ui#73': ('Story Events', ''),
    'ui#74': ('Other Events', ''),
    'ui#75': ('001-100', ''),
    'ui#76': ('101-200', ''),
    'ui#77': ('201-300', ''),
    'ui#78': ('301-400', ''),
    'ui#79': ('401-500', ''),
    'ui#80': ('501-600', ''),
    'ui#81': ('601~', ''),
    'ui#82': ('Main 1', ''),
    'ui#83': ('Main 2', ''),
    'ui#84': ('Main 3', ''),
    'ui#85': ('Main 4', ''),
    'ui#86': ('Quest 1', ''),
    'ui#87': ('Quest 2', ''),
    'ui#88': ('Quest 3', ''),
    'ui#89': ('Quest 4', ''),
    'ui#90': ('Other', ''),
    'ui#91': ('Prologue - Ch. 8', ''),
    'ui#92': ('Ch. 9 - 16', ''),
    'ui#93': ('Ch. 17 - Ending', ''),
    'ui#94': ('Ch. 13 - 16', ''),
    'ui#95': ('Ch. 17 - 20', ''),
    'ui#96': ('Ch. 20 - 24', ''),
    'ui#97': ('Ch. 25 - Ending', ''),
    'ui#98': ('Chapter 9', ''),
    'ui#99': ('Chapter 10', ''),
    'ui#100': ('Chapter 11', ''),
    'ui#101': ('Chapter 12', ''),
    'ui#102': ('Chapter 13', ''),
    'ui#103': ('Chapter 14', ''),
    'ui#104': ('Chapter 15', ''),
    'ui#105': ('Chapter 16', ''),
    'ui#106': ('Chapter 17', ''),
    'ui#107': ('Chapter 18', ''),
    'ui#108': ('Chapter 19', ''),
    'ui#109': ('Chapter 20', ''),
    'ui#110': ('Chapter 21', ''),
    'ui#111': ('Chapter 22', ''),
    'ui#112': ('Chapter 23', ''),
    'ui#113': ('Chapter 24', ''),
    'ui#114': ('Tales of Phantasia', ''),
    'ui#115': ('Tales of Destiny', ''),
    'ui#116': ('Tales of Eternia', ''),
    'ui#117': ('Tales of Destiny 2', ''),
    'ui#118': ('Tales of Symphonia', ''),
    'ui#119': ('Tales of Rebirth', ''),
    'ui#120': ('Tales of Legendia', ''),
    'ui#121': ('Tales of the Abyss', ''),
    'ui#122': ('Tales of the Tempest', ''),
    'ui#123': ('Tales of Innocence', ''),
    'ui#124': ('Tales of Vesperia', ''),
    'ui#125': ('TOS: Dawn of New World', ''),
    'ui#126': ('Tales of Hearts', ''),
    'ui#127': ('Tales of Graces', ''),
    'ui#128': ('Radiant Mythology', ''),
    'ui#129': ('----------', ''),
    'ui#130': ('To Next Level', ''),
    'ui#131': ('SLOT 1', ''),
    'ui#132': ('SLOT 2', ''),
    'ui#133': ('SLOT 3', ''),
    'ui#134': ('Auto', ''),
    'ui#135': ('Semi-Auto', ''),
    'ui#136': ('Manual', ''),
    'ui#137': ('Slot 1', ''),
    'ui#138': ('Slot 2', ''),
    'ui#139': ('Slot 3', ''),
    'ui#140': ('Auto Config', ''),
    'ui#141': ('All', ''),
    'ui#142': ('Merc', ''),
    'ui#143': ('By Highest Level', ''),
    'ui#144': ('By Most Battles', ''),
    'ui#145': ('Alphabetical', ''),
    'ui#146': ('Level gap is too big to invite.', ''),
    'ui#147': ('Equip', ''),
    'ui#148': ('If you quit without saving,', ''),
    'ui#149': ('current game progress will be lost.', ''),
    'ui#150': ('Are you sure?', ''),
    'ui#151': ('Cannot save here.', ''),
    'ui#152': ('Craft', ''),
    'ui#153': ('Cooking', ''),
    'ui#154': ('Smithing', ''),
    'ui#155': ('Tailoring', ''),
    'ui#156': ('Tools', ''),
    'ui#157': ('Proficiency', ''),
    'ui#158': ('Rank', ''),
    'ui#159': ('Required', ''),
    'ui#160': ('In Bag', ''),
    'ui#161': ('Current Meal Effect:', ''),
    'ui#162': ('None', ''),
    'ui#163': ('Confirm Synth', ''),
    'ui#164': ('Cancel', ''),
    'ui#165': ('Synthesized.', ''),
    'ui#166': ('Upgraded.', ''),
    'ui#167': ('Funds', ''),
    'ui#168': ('Fee', ''),
    'ui#169': ('Base', ''),
    'ui#170': ('▲Material', ''),
    'ui#171': ('Smith Rank', ''),
    'ui#172': ('Slots Left', ''),
    'ui#173': ('Focus on P. Stats', ''),
    'ui#174': ('Focus on M. Stats', ''),
    'ui#175': ('Remove All Equip', ''),
    'ui#176': ('Cancel', ''),
    'ui#177': ('Equipper:', ''),
    'ui#178': ('None', ''),
    'ui#179': ('Select base gear', ''),
    'ui#180': ('to synthesize equipment skills onto.', ''),
    'ui#181': ('Select material gear', ''),
    'ui#182': ('to synthesize into the base.', ''),
    'ui#183': ('*Material gear will be lost after synthesis!', ''),
    'ui#184': ('From material gear, select', ''),
    'ui#185': ('the equipment skill to synthesize.', ''),
    'ui#186': ('Select slot to set', ''),
    'ui#187': ('the skill you wish to synthesize.', ''),
    'ui#188': ('Confirm Synth', ''),
    'ui#189': ('Cannot select same item as base and material.', ''),
    'ui#190': ('Cannot select because remaining slots are 0.', ''),
    'ui#191': ('This equipment has no skill slots.', ''),
    'ui#192': ('This equipment has no synthesizable skills.', ''),
    'ui#193': ('Radiant equipment cannot be selected.', ''),
    'ui#194': ('Armor can only synthesize with same category.', ''),
    'ui#195': ('The same equipment skill exists on base.', ''),
    'ui#196': ('Inferior effect compared to skill on base.', ''),
    'ui#197': ('Base equipment skill has not been changed.', ''),
    'ui#198': ('Cannot confirm while selecting base slot.', ''),
    'ui#199': ('Insufficient Gald.', ''),
    'ui#200': ('Synthesis result is shown on right.', ''),
    'ui#201': ('Gald needed for synthesis:', ''),
    'ui#202': ('*If synthesized, material used', ''),
    'ui#203': ('will be permanently lost!', ''),
    'ui#204': ('Synthesize?', ''),
    'ui#205': ('Cannot use at current smithing rank.', ''),
    'ui#206': ('Please select.', ''),
    'ui#207': ('Used to upgrade base.', ''),
    'ui#208': ('Select upgrade material item.', ''),
    'ui#209': ('Confirm Upgrade', ''),
    'ui#210': ('Do not possess upgrade materials.', ''),
    'ui#211': ('Using', ''),
    'ui#212': ('to upgrade.', ''),
    'ui#213': ('Gald needed to upgrade:', ''),
    'ui#214': ('Upgrade?', ''),
    'ui#215': ('Req. Lv', ''),
    'ui#216': ('P. Atk', ''),
    'ui#217': ('M. Atk', ''),
    'ui#218': ('P. Def', ''),
    'ui#219': ('M. Def', ''),
    'ui#220': ('Agi', ''),
    'ui#221': ('Slots Left', ''),
    'ui#222': ('----', ''),
    'ui#223': ('Cannot use here.', ''),
    'ui#224': ('Use', ''),
    'ui#225': ('Check Skill', ''),
    'ui#226': ('Check Effect', ''),
    'ui#227': ('Remove', ''),
    'ui#228': ('Discard', ''),
    'ui#229': ('Cancel', ''),
    'ui#230': ('Remove gear?', ''),
    'ui#231': ('Discard this?', ''),
    'ui#232': ('How many to discard?', ''),
    'ui#233': ('Equippable Class', ''),
    'ui#234': ('Switch Page', ''),
    'ui#235': ('Mat. Rank', ''),
    'ui#236': ('Weapon Upgrade', ''),
    'ui#237': ('Armor Upgrade', ''),
    'ui#238': ('Req. Lv', ''),
    'ui#239': ('P. Atk', ''),
    'ui#240': ('M. Atk', ''),
    'ui#241': ('Agi', ''),
    'ui#242': ('P. Def', ''),
    'ui#243': ('M. Def', ''),
    'ui#244': ('All Party', ''),
    'ui#245': ('Before', ''),
    'ui#246': ('After', ''),
    'ui#247': ('Category:', ''),
    'ui#248': ('Newest', ''),
    'ui#249': ('Recently Added', ''),
    'ui#250': ('Items', ''),
    'ui#251': ('Craft Mat.', ''),
    'ui#252': ('Upgrade Mat.', ''),
    'ui#253': ('Trade Items', ''),
    'ui#254': ('Accessories', ''),
    'ui#255': ('Valuables', ''),
    'ui#256': ('???', ''),
    'ui#257': ('Weapon: 1H Sword', ''),
    'ui#258': ('Weapon: 2H Sword', ''),
    'ui#259': ('Weapon: Dagger', ''),
    'ui#260': ('Weapon: Axe', ''),
    'ui#261': ('Weapon: Staff', ''),
    'ui#262': ('Weapon: Fists', ''),
    'ui#263': ('Weapon: Bow', ''),
    'ui#264': ('Weapon: Gun', ''),
    'ui#265': ('Weapon: Spear', ''),
    'ui#266': ('Weapon: Tonfa', ''),
    'ui#267': ('Weapon: Chakram', ''),
    'ui#268': ('Weapon: Hammer', ''),
    'ui#269': ('Weapon: Rifle', ''),
    'ui#270': ('Weapon: Baton', ''),
    'ui#271': ('Weapon: Crossbow', ''),
    'ui#272': ('Weapon: Bag', ''),
    'ui#273': ('Weapon: Kendama', ''),
    'ui#274': ('Weapon: Mop', ''),
    'ui#275': ('Weapon: Ladle', ''),
    'ui#276': ('Weapon: Flute', ''),
    'ui#277': ('Weapon: Talisman', ''),
    'ui#278': ('Weapon: Straw', ''),
    'ui#279': ('Weapon: Pen', ''),
    'ui#280': ('Weapon: Sash', ''),
    'ui#281': ('Armor: Shield', ''),
    'ui#282': ('Armor: Head', ''),
    'ui#283': ('Armor: Face', ''),
    'ui#284': ('Armor: Body', ''),
    'ui#285': ('Armor: Arms', ''),
    'ui#286': ('Armor: Legs', ''),
    'ui#287': ('Standard Weapon', ''),
    'ui#288': ('Special Weapon', ''),
    'ui#289': ('Novelty Weapon', ''),
    'ui#290': ('Body Equip', ''),
    'ui#291': ('Head Equip', ''),
    'ui#292': ('Face Equip', ''),
    'ui#293': ('Arms Equip', ''),
    'ui#294': ('Legs Equip', ''),
    'ui#295': ('1H Sword', ''),
    'ui#296': ('2H Sword', ''),
    'ui#297': ('Dagger', ''),
    'ui#298': ('Gun', ''),
    'ui#299': ('Tonfa', ''),
    'ui#300': ('Chakram', ''),
    'ui#301': ('Hammer', ''),
    'ui#302': ('Rifle', ''),
    'ui#303': ('Baton', ''),
    'ui#304': ('Crossbow', ''),
    'ui#305': ('Bag', ''),
    'ui#306': ('Kendama', ''),
    'ui#307': ('Mop', ''),
    'ui#308': ('Ladle', ''),
    'ui#309': ('Straw', ''),
    'ui#310': ('Pen', ''),
    'ui#311': ('Robe', ''),
    'ui#312': ('Hat', ''),
    'ui#313': ('Gauntlets', ''),
    'ui#314': ('Bangle', ''),
    'ui#315': ('Material', ''),
    'ui#316': ('Recipe', ''),
    'ui#317': ('Thought', ''),
    'ui#318': ('Tablet Shard', ''),
    'ui#319': ('Standard', ''),
}

with open('lotes_p68/UI-01.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

missing = []
for r in rows:
    rid = r['id']
    if rid not in T:
        missing.append(rid)
    else:
        tr, nt = T[rid]
        r['traducao'] = tr
        if nt:
            r['nota_do_tradutor'] = nt

if missing:
    print("MISSING:", len(missing), missing[:5])
else:
    out_p = 'lotes_p68/UI-01_retorno.tsv'
    with open(out_p, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
        w.writeheader()
        w.writerows(rows)
    print("Wrote", out_p)
