import json, re
from val_check import validate_dict, nomes_proprios, CAUDA

d = json.load(open('dados/item_equip_shrink/VAL-03.json', encoding='utf-8'))
itens = d['itens']
meta = d['meta_bytes_a_cortar']

overrides = {
    # Recipes
    'valuables#54': 'Recipe for "Pineapple Rice" that Coda craves.',
    'valuables#66': 'Recipe for "Cheese Fondue" that Coda craves.',
    'valuables#61': 'Recipe for "Okonomiyaki" that Coda craves.',
    'valuables#56': 'Recipe for "Mabo Curry" that Coda craves.',
    'valuables#58': 'Recipe for "Mabo Pie" that Coda craves.',

    # Titles with Radiance
    'valuables#2372': "Title for obtaining the Paladin's Radiance.",
    'valuables#2376': "Title for obtaining the Fighter's Radiance.",
    'valuables#2380': "Title for obtaining the Priest's Radiance.",
    'valuables#2388': "Title for obtaining the Pirate's Radiance.",
    'valuables#2396': "Title for obtaining the Hunter's Radiance.",
    'valuables#2404': "Title for obtaining the Bishop's Radiance.",
    'valuables#2412': "Title for obtaining the Gunner's Radiance.",
    'valuables#2392': "Title for obtaining the Thief's Radiance.",
    'valuables#2408': "Title for obtaining the Ninja's Radiance.",
    'valuables#2384': "Title for obtaining the Monk's Radiance.",
    'valuables#2400': "Title for obtaining the Mage's Radiance.",

    # Other Titles
    'valuables#2472': 'Title for defeating the Colosseum manager.',
    'valuables#2468': 'Title for making a Colosseum debut.',
    'valuables#2464': 'Title for an invincible guild with no equals.',
    'valuables#2147': 'Title for looting a World Cultural Heritage site.',
    'valuables#2249': 'Title for someone said to steal anything.',
    'valuables#2308': 'Title for one thoroughly familiar with gathering.',
    'valuables#2312': 'Title for one thoroughly familiar with mining.',
    'valuables#2304': 'Title for one well-versed in upgrade materials.',
    'valuables#2300': 'Title for one challenging every dish.',
    'valuables#2324': 'Title for one seeking their way in life.',
    'valuables#2327': 'Title for opening the path to every class.',
    'valuables#2339': 'Dishonorable title for someone with many defeats.',
    'valuables#2159': 'Title for one resolved for new creation.',
    'valuables#2135': 'Title for one recognized as an enemy by Dawn Attendants.',
    'valuables#2331': 'Title for one who fights using only their own power.',
    'valuables#2155': 'Title for one who glimpsed the time of creation.',
    'valuables#2179': 'Title for one who saw inside all green chests.',

    # Proofs
    'valuables#2101': 'Proof of Tales of the World: Radiant Mythology 2.',
    'valuables#2097': 'Proof of Tales of the World: Radiant Mythology.',

    # Key / Special items
    'valuables#7': "Sorcerer's Ring. Halts enemies in their tracks.",
    'valuables#230': 'Allows receiving Radiant equipment from Rocks.',
    'valuables#2277': 'Battle count for a Tales character exceeded 1000.',
    'valuables#759': 'Obtains Gald from enemies by some method.',
    'valuables#19': "Key to DL Quest 'A Fight That Cannot Be Lost'.",
    'valuables#153': 'Astonishingly, used to nail plywood and similar.',

    # Specific battle artes / fixes
    'valuables#509': 'Fire arte: launches and detonates a small fireball.',
    'valuables#469': 'Arte: encases target foe in ice, then shatters.',
    'valuables#1921': "Arte: revives a KO'd ally (minor HP recovery).",
    'valuables#297': 'Arte: restores small HP to target ally.',
    'valuables#299': 'Arte: restores moderate HP to all allies.',
    'valuables#392': 'Arte: restores moderate HP to target ally.',
    'valuables#578': 'Arte: restores moderate HP to target ally.',
    'valuables#1096': 'Secret arte: extra slashes after Azure Edge.',
    'valuables#1182': 'Secret arte: executes Crescent Flash rapidly.',
    'valuables#688': 'Secret arte: upward slash after Talon Drop.',
    'valuables#867': 'Secret arte: rapid slashes after Fang Thrust.',
    'valuables#1098': 'Secret arte: sweeps foes away after Scattered Dust.',
    'valuables#1269': 'Arcane arte: connects dive into Three-Stage Flash.',
    'valuables#1961': 'Arcane arte: Negative Gate triggers upon hit.',
    'valuables#446': 'Arte: draws a demonic space to seal enemy movement.',
    'valuables#480': 'Arte: creates a giant lightning orb above foes.',
    'valuables#937': 'Secret arte: slashes up and through after dash thrust.',
    'valuables#939': 'Arcane arte: focuses dark power, thrusting forward.',
    'valuables#1692': 'Skill where shot arrows chase and heal low HP allies.',
    'valuables#1787': 'Arcane arte: two swift strikes using sword and axe.',
    'valuables#1911': 'Arcane arte: creates masses of qi, dealing damage.',
    'valuables#2084': 'Arcane arte: rushes with gunblade, attacking with gravel.',
    'valuables#431': 'Arte: reduces innate cast time of target ally.',
    'valuables#1348': 'Secret arte: bangs frying pan to launch acoustic attacks.',
    'valuables#1358': 'Secret arte: delivers juicy fire anti-air attack.',
    'valuables#1433': 'Secret arte: unleashes gale shockwaves twice rapidly.',
    'valuables#1530': 'Arte: summons sleeping earth ores to impale foes.',
    'valuables#1590': 'Arcane arte: kicks up endlessly, slamming down grandly.',
    'valuables#1622': 'Arcane arte: upheaves the ground to impale foes.',
    'valuables#1903': 'Secret arte: radiates photons like throwing knives.',
    'valuables#1944': 'Arte: brands impure hearts with holy seal to purify.',
    'valuables#2003': 'Arcane arte: jumps and fires wind arrows glidingly.',
    'valuables#2044': 'Secret arte: shoots light spheres from crossed muzzles.',
    'valuables#384': 'Arte powerful enough to instantly wipe out all foes.',
    'valuables#739': 'Arcane arte: unleashes giant shockwave impaling foes.',
    'valuables#990': 'Arcane arte: creates giant wind sickle to slice foes.',
    'valuables#1004': 'Arcane arte: cloaks in Phoenix aura, attacking skyward.',
    'valuables#1059': 'Secret arte: blows foes away with aerial combos.',
    'valuables#1127': 'Arcane arte: connects thrusts into freezing slashes.',
    'valuables#1227': 'Arcane arte: sometimes petrifies struck cold foes.',
    'valuables#1273': 'Arcane arte: rapidly slams in heightened qi.',
    'valuables#1407': 'Secret arte: shoots at enemy feet, raising water pillar.',
    'valuables#1539': 'Arte: conjures curse power, damaging touching foes.',
    'valuables#1600': 'Arcane arte: executes spread rapid-fire diagonally up.',
    'valuables#1706': 'Secret arte: brandishes weapons to smoothly slash foes.',
    'valuables#1821': 'Secret arte: shoots three rapid light sword shadows.',
    'valuables#2057': 'Secret arte: punches with full soul to knock foes down.',
    'valuables#503': 'Arte: stirs up a storm of destructive power.',
    'valuables#529': 'Arte: rains down rainbow swords blessed by light.',
    'valuables#665': 'Arcane arte: aerial combos like a fierce tiger.',
    'valuables#1010': 'Arcane arte: beast qi followed by thunderbolts.',
    'valuables#1047': 'Arcane arte: shreds foes from above with vacuum waves.',
    'valuables#1137': 'Arcane arte: delivers eight godspeed strikes.',
    'valuables#1680': 'Arcane arte: leaps and delivers accelerated dive kick.',
    'valuables#1892': 'Arcane arte: releases giant scorching heat waves.',
    'valuables#1959': 'Arcane arte: attacks with sharp rocks upon shot hits.',
    'valuables#2007': 'Arcane arte: fires homing piercing energy at foes.',
    'valuables#2009': 'Simultaneous shooting arcane arte covering wide area.',
    'valuables#444': 'Arte: creates gust of wind to lift and attack foes.',
    'valuables#482': 'Arte: whips up scalding gale, blowing foes away.',
    'valuables#513': 'Dark arte: distorted power tears from both sides.',
    'valuables#523': 'Dark arte: a roar of despair tears foes apart.',
    'valuables#1032': 'Arcane arte: generates shockwaves from slashes.',
    'valuables#1247': 'Arcane arte: crosses guns, firing water bullets.',
    'valuables#1760': 'Arcane arte: steps back, spin-unleashing combos.',
    'valuables#1955': 'Secret arte: attacks with dark power upon shot hits.',
    'valuables#501': 'Arte: hurls stone shards in an arc at foes.',
    'valuables#507': 'Arte: releases cursed waves from dark blades.',
    'valuables#661': 'Secret arte: blows foes away with powerful thrust.',
    'valuables#853': 'Secret arte: traces moon twice with weapon arcs.',
    'valuables#988': 'Arcane arte: stirs up vacuum waves to mow foes down.',
    'valuables#1532': 'Arte: engulfs and incinerates foes in raging flames.',
    'valuables#1682': 'Arcane arte: unleashes accelerated kick from leap.',
    'valuables#1989': 'Secret arte: fires arrows that incinerate with fire.',
    'valuables#2050': 'Arcane arte: shoots bullets exploding in wide area.',
    'valuables#2091': 'Secret arte: stirs up vacuum waves to mow foes down.',
    'valuables#511': 'Wind arte: continuously generates vacuum blades.',
    'valuables#584': 'Arcane arte: unleashes barrage of shockwave slashes.',
    'valuables#648': 'Arcane arte: commands raging flames in flurry combo.',
    'valuables#920': 'Secret arte: executes flame-cloaked rapid kicks.',
    'valuables#751': 'Secret arte: strikes thrust foes with lightning.',
    'valuables#1250': 'Arcane arte: launches numerous ice lances at foes.',
    'valuables#1319': 'Arcane arte: splits earth with a nice body press.',
    'valuables#1327': 'Secret arte: semicircular slashes in front.',
    'valuables#1470': 'A four-hit skill: swings dual swords alternately.',
    'valuables#1694': 'Skill: shot arrows track foes at low speed.',
    'valuables#1853': 'Arcane arte: rains down wind arrows in wide area.',
    'valuables#1946': 'Arte: shoots purifying lightning in radial pattern.',
    'valuables#309': 'Arte: cures status ailments of allies in range.',
    'valuables#497': 'Arte: calls down meteors in wide area to attack.',
    'valuables#614': 'Arcane arte: follows spin slash with a thrust.',
    'valuables#1153': 'Arcane arte: delivers cold-cloaked slashes.',
    'valuables#1234': 'Secret arte: conjures vacuum waves to shred foes.',
    'valuables#1323': 'Secret arte: bestows mid-day paralysis.',
    'valuables#1702': 'Arcane arte: fires arrows that accelerate.',
    'valuables#1932': 'Arcane arte: throws 5 blessed daggers vertically.',
    'valuables#1953': 'Secret arte: attacks with gravel upon shot hits.',
    'valuables#329': 'Arte: compresses water power and shoots skyward.',
    'valuables#505': 'Arte: compresses and releases earth power.',
    'valuables#539': 'Arte: rains countless swords blessed by light.',
}

rules = [
    (r'^Arcane arte: combines (.*)$', r'Arcane arte: \1'),
    (r'^A skill that attaches a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Attaches talisman lowering enemy \1 by chance.'),
    (r'^Secret arte: flings a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Secret arte: flings talisman lowering enemy \1 by chance.'),
    (r'^An arcane arte where ', 'Arcane arte: '),
    (r'^An arcane arte that, ', 'Arcane arte: '),
    (r'^An arcane arte that ', 'Arcane arte: '),
    (r'^An arcane arte with ', 'Arcane arte: '),
    (r'^An arcane arte of ', 'Arcane arte: '),
    (r'^An arcane arte ', 'Arcane arte: '),
    (r'^A wind-element secret arte that ', 'Wind secret arte: '),
    (r'^A fire arte that ', 'Fire arte: '),
    (r'^An arte where ', 'Arte: '),
    (r'^Title given to someone who ', 'Title for one who '),
    (r'^Title given to someone ', 'Title for someone '),
    (r'^Title given to ', 'Title for '),
    (r'^Title for one who has ', 'Title for one who '),
    (r'\(area of effect in battle\)', '(in battle)'),
    (r'area of effect in battle', 'in battle'),
    (r'for a single target ally', 'for an ally'),
    (r'for a single ally', 'for an ally'),
    (r'for a target ally', 'for an ally'),
    (r'for a set time\.', 'briefly.'),
    (r'for a set time', 'briefly'),
    (r'for a short time', 'briefly'),
    (r'beneath the target enemy\.', 'beneath target foe.'),
    (r'around the target enemy\.', 'around target foe.'),
    (r'at the target enemy\'s position\.', 'at target foe.'),
    (r'toward the target enemy\.', 'toward target foe.'),
]

extra_trims = [
    (r'closing distance', 'closing in'),
    (r'spinning slashes', 'spin slashes'),
    (r'spinning kicks', 'spin kicks'),
    (r'spinning impacts', 'spin impacts'),
    (r'through enemies', 'through foes'),
    (r'enemies with', 'foes with'),
    (r'into enemies', 'into foes'),
    (r'attacks enemies', 'attacks foes'),
    (r'slashes enemies', 'slashes foes'),
    (r'launches enemies', 'launches foes'),
    (r'surrounding foes', 'nearby foes'),
    (r'surrounding enemies', 'nearby foes'),
    (r'the surroundings', 'nearby area'),
    (r'toward the heavens', 'skyward'),
    (r'high into the sky', 'skyward'),
    (r'consecutive attacks', 'rapid attacks'),
    (r'consecutive slashes', 'rapid slashes'),
    (r'consecutive thrusts', 'rapid thrusts'),
    (r'in an instant', 'instantly'),
    (r'on enemies', 'on foes'),
    (r'to enemies', 'to foes'),
    (r'striking enemies', 'striking foes'),
    (r'impales enemies', 'impales foes'),
    (r'draws enemies', 'draws foes'),
    (r'draw in enemies', 'draw foes in'),
    (r'sweeps enemies', 'sweeps foes'),
    (r'and strikes with shockwaves', 'with shockwaves'),
    (r'and finishes with ', ', finishing with '),
    (r'and connects into ', ', connecting into '),
    (r'to attack foes\.', 'to attack.'),
    (r'to attack enemies\.', 'to attack.'),
    (r'follows up with ', 'follows with '),
    (r'follows up on ', 'follows '),
    (r'follows up in ', 'follows in '),
    (r'follows up,', 'follows,'),
    (r'two-stage strikes', 'two strikes'),
    (r'from impact points', 'on impact'),
    (r'in rapid succession', 'rapidly'),
    (r'in midair', 'in air'),
    (r'from midair', 'from air'),
    (r'into the air', 'into air'),
    (r'into midair', 'in air'),
    (r'sky-high', 'high'),
    (r'to the ground', 'to ground'),
    (r'into the ground', 'into ground'),
    (r'from the ground', 'from ground'),
    (r'on the ground', 'on ground'),
    (r'at the ground', 'at ground'),
    (r'super fighting spirit', 'fighting spirit'),
    (r'with the power of ', 'with '),
    (r'multi-hitting', 'multi-hit'),
    (r'wind pressure strikes', 'wind strikes'),
    (r'a sharp thrust', 'a thrust'),
    (r'a heavy thrust', 'a thrust'),
    (r'an extra strike', 'an extra hit'),
    (r'an upward slash', 'an up-slash'),
    (r'an upward thrust', 'an up-thrust'),
    (r'an upward kick', 'an up-kick'),
    (r'upward kicks', 'up-kicks'),
    (r'upward thrusts', 'up-thrusts'),
    (r'upward slashes', 'up-slashes'),
    (r'downward slashes', 'down-slashes'),
    (r'downward impacts', 'down-impacts'),
    (r'all at once', 'at once'),
    (r'the opponent', 'the foe'),
    (r'to the foe', 'to foe'),
    (r'the enemy', 'the foe'),
    (r'target enemies', 'target foes'),
    (r'target enemy', 'target foe'),
    (r'around enemies', 'around foes'),
    (r'nearby enemies', 'nearby foes'),
    (r'distant enemies', 'distant foes'),
    (r'airborne enemies', 'airborne foes'),
    (r'captured enemies', 'captured foes'),
    (r'knocked-down enemies', 'knocked-down foes'),
    (r'impaled enemies', 'impaled foes'),
    (r'downward enemies', 'downward foes'),
    (r'enemy heads', 'foe heads'),
    (r'numerous enemies', 'numerous foes'),
]

out = {}
for x in itens:
    item_id = x['id']
    en = x['en']
    if item_id in overrides:
        s = overrides[item_id]
    else:
        # Don't touch stats lines like Base Physical Attack...
        if en.startswith('Result TP') or en.startswith('Monster Symbol') or en.startswith('Max TP') or en.startswith('Base Physical') or en.startswith('TP Consumption'):
            continue
            
        s = en
        for pat, rep in rules:
            s = re.sub(pat, rep, s)
        if s.startswith('A skill that '):
            rest = s[len('A skill that '):]
            s = rest[0].upper() + rest[1:]
    
    for pat, rep in extra_trims:
        s = re.sub(pat, rep, s)
    
    s = re.sub(r'\s+,', ',', s)
    s = re.sub(r'\s+', ' ', s).strip()
    
    if s != en:
        out[item_id] = s

print(f"Total entries in out: {len(out)} / {len(itens)}")
ok = validate_dict('dados/item_equip_shrink/VAL-03.json', out)
if ok:
    with open('dados/item_equip_shrink/VAL-03_out.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
    print("SAVED VAL-03_out.json!")
