import csv

# Translation mapping for ARENA.tsv (248 lines)
T = {
    'arena#0': ('None', ''),
    'arena#1': ('Exhibition Match (1P)', ''),
    'arena#2': ('A challenger is calling you out! Will you face them?', ''),
    'arena#3': ('Exhibition Match (2P)', ''),
    'arena#4': ('Two challengers are calling you out! Will you face them?', ''),
    'arena#5': ('Exhibition Match (3P)', ''),
    'arena#6': ('Three challengers are calling you out! Will you face them?', ''),
    'arena#7': ('Exhibition Match (4P)', ''),
    'arena#8': ('Four challengers are calling you out! Will you face them?', ''),
    'arena#9': ('Battle-Hardened Heroes', ''),
    'arena#10': ('Mask of Truth and Lies', ''),
    'arena#11': ('One Justice and Chivalry', ''),
    'arena#12': ('Meaning of Life', ''),
    'arena#13': ('Guardians of Tree', ''),
    'arena#14': ('Cherry Blossoms!', ''),
    'arena#15': ('Items? I have them too!', ''),
    'arena#16': ('2010! Heroes Top 3', ''),
    'arena#17': ('2010! Heroines Top 3', ''),
    'arena#18': ('Otherworld Descender', ''),
    'arena#19': ('King of Filth', ''),
    'arena#20': ('Clash! Spacetime Hero!', ''),
    'arena#21': ('Blazing Sword', '爆炎の剣 (max 17)'),
    'arena#22': ('Bearer of Aurora', ''),
    'arena#23': ('Hero Aspirants!', ''),
    'arena#24': ('Twin Swords = 2x Power!', ''),
    'arena#25': ('Cold Flame', ''),
    'arena#26': ('Radiant Souga', ''),
    'arena#27': ('Hidden Power', ''),
    'arena#28': ('Wild Spirit!', ''),
    'arena#29': ('Gentle Flame Warrior', ''),
    'arena#30': ('The Other Me', ''),
    'arena#31': ('Justice Upheld', ''),
    'arena#32': ('Kindhearted Swordsman', ''),
    'arena#33': ("Knight's Wish", ''),
    'arena#34': ('Girl of the Future', ''),
    'arena#35': ('Splendid Challenger', ''),
    'arena#36': ('The Champion Arrives!', ''),
    'arena#37': ('War-Crazy: Deathmatch', ''),
    'arena#38': ('White Devil', ''),
    'arena#39': ('The Other Descender', ''),
    'arena#40': ('Fight on! Bakers!', ''),
    'arena#41': ('Legend Scion', ''),
    'arena#42': ('A textbook, classic hero and heroine team enters the fray!', ''),
    'arena#43': ('Destiny Warriors', ''),
    'arena#44': ('Two fated warriors wielding mysterious swords enter the ring!', ''),
    'arena#45': ('Eternal Nostalgia', ''),
    'arena#46': ('In perfect battle sync! Two childhood friends enter the ring!', ''),
    'arena#47': ('Goddess-Chosen Heroes', ''),
    'arena#48': ('A pair of hero hopefuls from another world enter the fray!', ''),
    'arena#49': ('World Renewal Travelers', ''),
    'arena#50': ('A wondrous pair: a dual-wielding swordsman and an angel enter!!', ''),
    'arena#51': ('Rime', ''),
    'arena#52': ('Two masters of ice and rain have arrived at the colosseum!', ''),
    'arena#53': ('Raging Souga', ''),
    'arena#54': ('A brother and sister testing their skill! An unusual pair joins!', ''),
    'arena#55': ('Resonating Duo', ''),
    'arena#56': ('A spoiled rich boy and a stoic beauty join forces in the arena!', ''),
    'arena#57': ('Beauty and the Beast?', ''),
    'arena#58': ("They constantly bicker, but today they're cooperating in the ring!", ''),
    'arena#59': ('Inherited Past Life', ''),
    'arena#60': ('Knight of Ratatosk', ''),
    'arena#61': ('A date at the colosseum? A couple (maybe?) enters the fray!', ''),
    'arena#62': ('Faith in Justice', ''),
    'arena#63': ('Touching Hearts', ''),
    'arena#64': ('Two pure-hearted warriors enter the ring to test their mettle!', ''),
    'arena#65': ('Things to Protect', ''),
    'arena#66': ('As Friends and Rivals', ''),
    'arena#67': ('Best friends and fierce rivals! The ultimate match enters the ring!', ''),
    'arena#68': ('Pierce! A Century Love', ''),
    'arena#69': ('Fighting like cats and dogs! But do they secretly care? They join!', ''),
    'arena#70': ('Team Phantasia', ''),
    'arena#71': ('Their teamwork is spot-on! This inseparable quartet joins the fight!', ''),
    'arena#72': ('Irreconcilable Duo', ''),
    'arena#73': ('Polar opposites in style and personality tag up for battle!', ''),
    'arena#74': ('Heartbreaking Crush', ''),
    'arena#75': ("At least when fighting together! A poignant pair joins the fray!", ''),
    'arena#76': ('Heartbreaking Crush 2', ''),
    'arena#77': ('Endless Yearning', ''),
    'arena#78': ('These two trained under the same archery master! They join the fray!', ''),
    'arena#79': ('Team Destiny', ''),
    'arena#80': ('Drawn together by destiny, this heroic quartet enters the arena!', ''),
    'arena#81': ('Aurora of Light and Dark', ''),
    'arena#82': ('Light and darkness combine! Two powers assemble in the colosseum!', ''),
    'arena#83': ('Nostalgic Friends', ''),
    'arena#84': ('Together since childhood! This trio steps into the ring!', ''),
    'arena#85': ('Captain and Crew', ''),
    'arena#86': ('The Van Eltia captain arrives with her loyal crew in tow!', ''),
    'arena#87': ('Team Eternia', ''),
    'arena#88': ('Always lively and easygoing, this quartet gets serious today!', ''),
    'arena#89': ('Sworn Bros', '義兄弟 (max 13)'),
    'arena#90': ('Warmhearted and fiery in technique, two sworn brothers join!', ''),
    'arena#91': ('Cobra Twist of Love', ''),
    'arena#92': ('Team Destiny 2', ''),
    'arena#93': ('Hailing from another world, this quartet joins the arena!', ''),
    'arena#94': ('Clash! Like Father & Son', ''),
    'arena#95': ('Looking just like father and son, this duo enters the fight!', ''),
    'arena#96': ('Chosen of World Tree', ''),
    'arena#97': ('Blessed by mana, this mysterious duo joins the fray!', ''),
    'arena#98': ('Another World', ''),
    'arena#99': ('Totally different fighting styles and personalities! A unique trio!', ''),
    'arena#100': ('Hellish Extra Class', ''),
    'arena#101': ('Is this even allowed? A teacher and student enter the colosseum!', ''),
    'arena#102': ('Team Symphonia', ''),
    'arena#103': ('Showing off resonating teamwork, this four-person squad enters!', ''),
    'arena#104': ('Hot-Blooded Buddies', ''),
    'arena#105': ('With the power of friendship forged through fists, this duo joins!', ''),
    'arena#106': ('Tragic Destiny', ''),
    'arena#107': ('Wielding rain and iron, this duo takes on the challenge!', ''),
    'arena#108': ('Team Rebirth', ''),
    'arena#109': ('All the way from Hazel Village, four mysterious powerhouses join!', ''),
    'arena#110': ('Start of the Story', ''),
    'arena#111': ('Two warriors who once worked as sheriff-like officers enter!', ''),
    'arena#112': ('Light Dragon & Fire', ''),
    'arena#113': ('A double punch of martial artist and ninja steps up to fight!', ''),
    'arena#114': ('Sene-Sene and Me', ''),
    'arena#115': ('In a sense, a strange blend of still and storm joins the fray!', ''),
    'arena#116': ('Stone Princess & Water', ''),
    'arena#117': ("One is a pro swimmer, the other sinks like a stone! They join!", ''),
    'arena#118': ('Hero & Double Heroines', ''),
    'arena#119': ('Martial artist Senel Coolidge enters with a girl on each arm!', ''),
    'arena#120': ('Team Legendia', ''),
    'arena#121': ('Their bond is legendary! Today this quartet enters the arena!', ''),
    'arena#122': ('Fresh Blood & Wishes', ''),
    'arena#123': ('Chasing noble ideals, two aristocratic warriors join the battle!', ''),
    'arena#124': ('Royal Luke enters the fray today with his bodyguard in tow!', ''),
    'arena#125': ('Master and Disciple', ''),
    'arena#126': ('Practitioners of the Albert style enter as master and pupil!', ''),
    'arena#127': ('Conflicting Bloodline', ''),
    'arena#128': ('Brother and sister stand against you! A mysterious sibling duo!', ''),
    'arena#129': ('Team Abyss', ''),
    'arena#130': ('Royalty from the Raima Kingdom arrives with bodyguards in tow!', ''),
    'arena#131': ('Overlord and His Blade', ''),
    'arena#132': ('An honor student and a delinquent make an eccentric duo! They enter!', ''),
    'arena#133': ('Mercenary & Client', ''),
    'arena#134': ('A clergywoman and a mercenary form an odd team! They enter the fray!', ''),
    'arena#135': ('Team Innocence', ''),
    'arena#136': ('The Ad Libitum leader arrives with members ready for battle!', ''),
    'arena#137': ('Blade of Secret Longing', ''),
    'arena#138': ('Carrying mysterious karma on their shoulders, this duo enters!', ''),
    'arena#139': ('Team Ratatosk', ''),
    'arena#140': ('They seem out of harmony, yet click perfectly! This trio enters!', ''),
    'arena#141': ('Sword and Sorcery', ''),
    'arena#142': ('Sharp-tongued, yet their teamwork fits like a glove! They enter!', ''),
    'arena#143': ('Pierce with Justice!', ''),
    'arena#144': ('Exuding relaxed, mature confidence, this duo enters the fight!', ''),
    'arena#145': ('Princess Guard', ''),
    'arena#146': ('The princess of Garbanzo and her loyal guard enter the arena!', ''),
    'arena#147': ('I Love You, Babe!', ''),
    'arena#148': ('Caught up in the strange mood, this unusual quartet enters!', ''),
    'arena#149': ('Team Vesperia', ''),
    'arena#150': ('Sharply and passionately upholding justice, this quartet arrives!', ''),
    'arena#151': ('Overprotective Guardian', ''),
    'arena#152': ('Crashing the fight to protect his sis! A gorgeous sibling duo!', ''),
    'arena#153': ('Team Hearts', ''),
    'arena#154': ('Bound by connected hearts, this trio steps up to fight!', ''),
    'arena#155': ('Childhood Friends', ''),
    'arena#156': ('Team Graces', ''),
    'arena#157': ('Searching for the answer to true strength, this trio joins!', ''),
    'arena#158': ('My Sister!', ''),
    'arena#159': ("Start them bragging about their sisters and they never stop! They join!", ''),
    'arena#160': ('Mercenaries', ''),
    'arena#161': ('Renowned mercenaries form a tag team and enter the colosseum!', ''),
    'arena#162': ('Like Father and Child?', ''),
    'arena#163': ('Bread & PANG!', ''),
    'arena#164': ('RING! RING!', ''),
    'arena#165': ('Thou Shalt Not Anger', ''),
    'arena#166': ('They look timid, but take up arms and they transform! They enter!', ''),
    'arena#167': ('Serious Duel', ''),
    'arena#168': ('Different paths, but both wish to help the weak! This duo enters!', ''),
    'arena#169': ('Cherry Blossom Fists', ''),
    'arena#170': ('Slender bodies packing go-go punch power! Brawler girls join!', ''),
    'arena#171': ('Rogue Knight Fierce Cut', ''),
    'arena#172': ('Even if they walk no knightly path, chivalry burns in their hearts!', ''),
    'arena#173': ('Those in Shadow', ''),
    'arena#174': ('A colosseum first!! A shinobi trio enters the arena!!', ''),
    'arena#175': ('Neo Generations', ''),
    'arena#176': ('Neo-Gen for short! A three-person squad from Ad Libitum arrives!', ''),
    'arena#177': ('Pocket Generation', ''),
    'arena#178': ('Poke-Gen for short! A three-person squad from Ad Libitum arrives!', ''),
    'arena#179': ('Royal Team', ''),
    'arena#180': ('A dazzling trio of royal celebrities enters the arena!', ''),
    'arena#181': ('Enigmatic Trio', ''),
    'arena#182': ('A mysterious trio shrouded in secrecy steps into the fray!', ''),
    'arena#183': ('Hot-Blooded Siscons!', ''),
    'arena#184': ('Piercing Spear', ''),
    'arena#185': ('Sometimes bold, sometimes sharp, a trio of spearmen enters!', ''),
    'arena#186': ('Strongest Sisters', ''),
    'arena#187': ("We won't lose to our big brothers! The ultimate sisters enter!", ''),
    'arena#188': ('Inhuman Beings', ''),
    'arena#189': ('Somewhat eerie? A trio with an exotic aura steps up to fight!', ''),
    'arena#190': ('Mad Science', ''),
    'arena#191': ('MONEY!', ''),
    'arena#192': ('Three gold-loving misers step up in search of cash!', ''),
    'arena#193': ('March of the Saints', ''),
    'arena#194': ('Will god take their side?! An evangelical clash by three clergy!', ''),
    'arena#195': ('Silent Warriors', ''),
    'arena#196': ('True power lies in silence! Three wordless warriors throw down!', ''),
    'arena#197': ('Chivalric Spirit', ''),
    'arena#198': ('Smash evil and aid the weak! Chivalric trio enters the fray!', ''),
    'arena#199': ('Lovely Fists', ''),
    'arena#200': ('Impregnable', ''),
    'arena#201': ('A daunting hero quartet! Who dare challenge this impregnable team?!', ''),
    'arena#202': ('Second Generation', ''),
    'arena#203': ('Seca-Gen for short! A four-person team from Ad Libitum enters!', ''),
    'arena#204': ('Pervert King Tourney', ''),
    'arena#205': ('All-time pervert kings assemble! Win and join their filthy ranks?', ''),
    'arena#206': ('Legendary Warrior', ''),
    'arena#207': ('Legendary Swordsman', ''),
    'arena#208': ('Legendary Fighter', ''),
    'arena#209': ('Legendary Hunter', ''),
    'arena#210': ('Legendary Thief', ''),
    'arena#211': ('Legendary Mage', ''),
    'arena#212': ('Legendary Priest', ''),
    'arena#213': ('Legendary Twin-Sword', ''),
    'arena#214': ('Legendary Greatsword', ''),
    'arena#215': ('Legendary Monk', ''),
    'arena#216': ('Legendary Pirate', ''),
    'arena#217': ('Legendary Bishop', ''),
    'arena#218': ('Legendary Spellblade', ''),
    'arena#219': ('Legendary Ninja', ''),
    'arena#220': ('Legendary Paladin', ''),
    'arena#221': ('Legendary Gunner', ''),
    'arena#222': ('VS Otaota', ''),
    'arena#223': ('VS Axe Beak', ''),
    'arena#224': ('VS Killer Bee', ''),
    'arena#225': ('Envoy of Light', ''),
    'arena#226': ('Guardian from Old Times', ''),
    'arena#227': ('Roaring Tsunami', ''),
    'arena#228': ('Light Beast Roar', ''),
    'arena#229': ('Wings from the Dark', ''),
    'arena#230': ('Revenge of Otaota', ''),
    'arena#231': ('Trio the Pan', ''),
    'arena#232': ('Fish Festival', ''),
    'arena#233': ('Crab Carnival', ''),
    'arena#234': ('Gigantic Plant', ''),
    'arena#235': ('Lineage of Otaota', ''),
    'arena#236': ('Lineage of Gekogeko', ''),
    'arena#237': ('Gekogeko gathered from all over the world! Who dare challenge them?', ''),
    'arena#238': ('Lineage of Chunchun', ''),
    'arena#239': ('Lineage of Bat 1', ''),
    'arena#240': ('Lineage of Bat 2', ''),
    'arena#241': ('Lineage of Lizard 1', ''),
    'arena#242': ('Lineage of Lizard 2', ''),
    'arena#243': ('Demon Plant', ''),
    'arena#244': ('Puppet Corps', ''),
    'arena#245': ('Captive Spirit', ''),
    'arena#246': ('Servant Spirit', ''),
    'arena#247': ('Max', ''),
}

with open('lotes_p68/ARENA.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

missing = []
for r in rows:
    rid = r['id']
    if rid not in T:
        missing.append(rid)
    else:
        tr, nt = T[rid]
        r['traducao'] = tr
        if nt:
            r['nota_do_tradutor'] = nt

if missing:
    print("MISSING:", len(missing), missing[:5])
else:
    out_p = 'lotes_p68/ARENA_retorno.tsv'
    with open(out_p, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
        w.writeheader()
        w.writerows(rows)
    print("Wrote", out_p)
