import json, re, sys
from val_check import nomes_proprios, CAUDA

# Load VAL-01
d = json.load(open('dados/item_equip_shrink/VAL-01.json', encoding='utf-8'))
itens = d['itens']
orig = {x['id']: x for x in itens}

MANUAL_VAL01 = {
    'valuables#910': 'Secret arte: follows dual slashes by slamming the ground with shockwaves.',
    'valuables#1028': 'Arcane arte: slashes foes skyward with spinning impacts and flashing thrusts.',
    'valuables#1560': 'Where God resides, what shatters is person. In other words, Me: Arcane Arte.',
    'valuables#227': 'A key to contact other worlds. It seems to have lost its magic power for now.',
    'valuables#783': 'Arcane arte: whirlwinds vortex from thrusting a spear into the ground.',
    'valuables#87': 'A letter torn to shreds. The writing is illegible, but the grudge is palpable.',
    'valuables#110': 'Paper that breeds money. In a sense, the most terrifying monster of all.',
    'valuables#1483': 'Attaches a talisman briefly reducing enemy defense by chance.',
    'valuables#1489': 'Attaches a talisman briefly reducing enemy agility by chance.',
    'valuables#1934': 'Infinite dagger arcane arte that restores inorganic matter to its proper form.',
    'valuables#147': 'Protects wearer from splattering water and oil with divine power. Detachable.',
    'valuables#189': 'Hot spring egg made in an active volcano at great risk. Reasonably tasty.',
    'valuables#201': 'Mirror surface bears an eye pattern scratched into it by its previous owner.',
    'valuables#763': 'Arcane arte: impales enemies at high speed, drawing them into aerial slashes.',
    'valuables#1487': 'Attaches a talisman briefly reducing enemy attack by chance.',
    'valuables#1556': 'Secret arte: impales foes with freezing spears and thrusts again upon landing.',
    'valuables#224': 'Key unlocking the door to the sealed land. Chipped in places and unusable.',
    'valuables#521': 'Fire arte: scalding orbs detonate on enemies as if with a will of their own.',
    'valuables#1485': 'Secret arte: flings a talisman briefly reducing enemy defense by chance.',
    'valuables#1497': 'Secret arte: flings a talisman briefly reducing enemy agility by chance.',
    'valuables#165': 'Afterword calls this the definitive edition, but a sequel ships this summer.',
    'valuables#263': 'A jewel left in a room on the Van Eltia for a long time for some reason.',
    'valuables#842': 'Arcane arte: sweeps foes with flaming fists and showers them with slashes.',
    'valuables#928': 'Arcane arte: closes in with Demon Flame Slash and Demon Flame Barrage.',
    'valuables#945': 'Arcane arte: follows Crouching Dragon Flash with two vacuum strikes in air.',
    'valuables#953': 'Arcane arte: high-speed slashes that cannot be tracked by ordinary eyes.',
    'valuables#960': 'Arcane arte: two-stage thrust with the ability to slip behind the enemy.',
    'valuables#1493': 'Secret arte: flings a talisman briefly reducing enemy attack by chance.',
    'valuables#1558': 'Explosive arcane arte: explicitly slams fighting spirit into enemies.',
    'valuables#793': 'Arcane arte: launches foes high, impales with a spear, and slams them down.',
    'valuables#1281': 'Arcane arte: launches up from rapid thrusts, chasing with Tempest and Demon Fang.',
    'valuables#824': 'Secret arte: draws enemies with combo strikes coiling like water snakes.',
    'valuables#1165': 'Arcane arte: enters enemy pocket and delivers heavy slashes, knocking them down.',
    'valuables#1287': 'Secret arte: slashes up with Crescent Slash and chases airborne foes with Tempest.',
    'valuables#1696': 'Fires arrows that detonate when enemies approach that position.',
    'valuables#186': 'A scrumptious dish. So delicious that a single bite will bring you to tears.',
    'valuables#606': 'Arcane arte: draws foes into a spinning slash, slamming with fighting spirit.',
    'valuables#1285': 'Executes attacks from a clearing slash into an upward slash.',
    'valuables#1594': 'Arcane arte: dives in, fires water pressure shots, and creates distance.',
    'valuables#136': 'Blowing it creates a shockwave shattering windows in a 100-meter radius.',
    'valuables#471': 'Arte: releases frozen energy in the earth to strike with a giant ice arrow.',
    'valuables#602': 'Secret arte: executes high-speed spin slashes, juggling foes in the air.',
    'valuables#908': 'Thrusts a sword into the ground, summoning rock lances with shockwaves.',
    'valuables#1352': 'Arcane arte: amidst a flash, does unmentionable things to neighboring wives.',
    'valuables#1839': 'Arcane arte: raging flames turn to dragons, enveloping self to slay foes.',
    'valuables#745': 'Arcane arte: thrusts foes skyward, cloaks in flame, dives, and knocks them down.',
    'valuables#795': 'Arcane arte: launches foes with lightning, tossing up minerals to follow up.',
    'valuables#904': 'Delivers left and right slashes followed by a reverse roundhouse kick.',
    'valuables#916': 'Knocks down opponents by releasing gathered fighting spirit into them.',
    'valuables#1216': 'Arcane arte: attacks surrounding foes with chakrams while continuously spinning.',
    'valuables#1748': 'Moves broadly while slicing enemies as if dancing through the heavens.',
    'valuables#1758': 'Slashes enemies like a fluttering swallow, kicking them up at the end.',
    'valuables#1890': 'Arcane arte: launches foes with combos, transitioning to sheathed stance.',
    'valuables#107': 'The writing spaces are stark white; looking at it fills one with ennui.',
    'valuables#113': 'Used to illuminate dark places. Being oil is no excuse for weird things.',
    'valuables#124': 'Slime extracted from a Polwiggle. Used in medicine, cosmetics, and industry.',
    'valuables#741': 'Arcane arte: closes instantly, striking repeatedly and launching enemies.',
    'valuables#789': 'Arcane arte: follows Roaring Spear with shockwaves forward and backward.',
    'valuables#890': 'Slams a hammer into enemies with a high probability of stunning them.',
    'valuables#971': 'Deploys a barrier blowing enemies away while slightly healing allies.',
    'valuables#1022': 'Arcane arte: launches upward from rapid thrusts, chasing with heavy slashes.',
    'valuables#1030': 'Arcane arte: unleashes thrusts at high speed, striking with a finishing blow.',
    'valuables#1277': 'Arcane arte: slashes enemies with thrusts, launching up and slicing downward.',
    'valuables#1702': 'Fires ice-cloaked arrows that freeze enemies upon impact.',
    'valuables#72': 'Recipe for "Commonly Known as Delicious-Delicious" that Coda craves.',
    'valuables#98': 'A favorite item of an unfortunate girl. She is alive, so there is no curse.',
    'valuables#133': 'As one grows up, contents become plentiful, and gradually it becomes a chore.',
    'valuables#198': 'The kind of ordinary thing you realize was happiness only after losing it.',
    'valuables#585': 'Arte: envelops a targeted ally in holy light, restoring their physical status.',
    'valuables#610': 'Arcane arte: kicks up enemies from rapid thrusts and finishes with a dive.',
    'valuables#614': 'Arcane arte: dives from midair, strikes with shockwaves, and kicks foes up.',
    'valuables#834': 'Arcane arte: boasts tremendous homing capabilities against attacking enemies.',
    'valuables#994': 'Arcane arte: shockwaves trace a cross, attacking with slashes and blasts.',
    'valuables#1024': 'Arcane arte: draws enemies to slashes and strikes them with spinning impacts.',
    'valuables#1167': 'Arcane arte: enters enemy pocket and launches them with a violent slash.',
    'valuables#1245': 'Arcane arte: launches upward from rapid thrusts and strikes with lightning.',
    'valuables#1273': 'Arcane arte: strikes with thrusts, launching skyward and slicing downward.',
    'valuables#1344': 'Arcane arte: slashes enemies with three hits, then kicks them down from air.',
    'valuables#1624': 'Arcane arte: calls up lightning from the ground to attack after Shadow Run Blast.',
    'valuables#92': 'Rope meant for luggage, but well regarded by those who enjoy being tied up.',
    'valuables#127': 'Doctors use it to hear heartbeats. If pointed at you, you must undress.',
    'valuables#139': 'Comes with a pointlessly grandiose note saying, "The board is the world!"',
    'valuables#159': 'Belonged to a woman who met an unfortunate mishap. She bought a new one.',
    'valuables#301': 'Arte: restores a moderate amount of HP to all allies (in battle).',
    'valuables#645': 'Arcane arte: knocks foes down with a roundhouse kick, striking with lightning.',
    'valuables#739': 'Arcane arte: launches foes into the air, impaling them with a freezing spear.',
    'valuables#761': 'Arcane arte: launches foes with kicks and smashes down with flaming fists.',
    'valuables#785': 'Arcane arte: delivers consecutive thrusts and charges forward with a spear.',
    'valuables#844': 'Arcane arte: blows foes away with a spin kick, finishing with fiery blasts.',
    'valuables#848': 'Arcane arte: godspeed thrusts stir up sudden gusts to blow enemies away.',
    'valuables#941': 'Arcane arte: knocks foes down with a sliding kick, striking with lightning.',
    'valuables#988': 'Arcane arte: follows three consecutive thrusts with a heavy leaping thrust.',
    'valuables#990': 'Arcane arte: follows three consecutive thrusts with a diving thrust from air.',
    'valuables#1008': 'Arcane arte: executes upward and downward two-stage slashes from Crescent Flash.',
    'valuables#1026': 'Arcane arte: draws enemies to slashes, striking them with flashing thrusts.',
    'valuables#1196': 'Space-time sword arcane arte: shreds enemies with intense fighting spirit.',
    'valuables#1214': 'Arcane arte: spins chakrams at high speed, striking surrounding enemies.',
    'valuables#1247': 'Arcane arte: launches foes skyward and strikes with a heavy downward slash.',
    'valuables#1275': 'Arcane arte: strikes with thrusts, launching skyward and kicking downward.',
    'valuables#1475': 'Calls up a rock spear beneath enemy feet to launch them into the air.',
    'valuables#1479': 'Arte: fires arrows of light that pierce through enemies in a straight line.',
    'valuables#1733': 'Arcane arte: slashes foes skyward, following with an aerial finishing blow.',
    'valuables#118': 'Many women drink this as a sleep aid to end the day feeling true to self.',
    'valuables#180': 'In exchange for summer vacation memories, can be wielded as a lethal weapon.',
    'valuables#204': 'A charred doll found in a dense forest. Its eyeballs have been gouged out.',
    'valuables#427': 'Arte: surrounds an ally with a barrier that continuously restores their HP.',
    'valuables#589': 'Arte: surrounds an ally with holy light, restoring their physical status.',
    'valuables#612': 'Arcane arte: closes in with a sliding kick and launches foes with a dive kick.',
    'valuables#767': 'Arcane arte: launches foes with thrusts, cloaks in flame, and dives to attack.',
    'valuables#775': 'Arcane arte: launches foes skyward with kicks, following with a diving thrust.',
    'valuables#777': 'Arcane arte: launches foes skyward with kicks, following with an aerial kick.',
    'valuables#822': 'Secret arte: draws enemies in with a water whip, following with heavy slashes.',
    'valuables#826': 'Secret arte: draws enemies in with a water whip, slamming them to the ground.',
    'valuables#846': 'Arcane arte: slashes enemies with fire-cloaked fists and kicks them down.',
    'valuables#887': 'Arcane arte: launches enemies skyward, follows with thrusts, and knocks down.',
    'valuables#906': 'Delivers left and right slashes followed by a high-speed roundhouse kick.',
    'valuables#2261': 'Title for one who knows the world\'s unexplored regions inside and out.',
    'valuables#101': 'A party gag item, but getting a laugh with it is considered a feat.',
    'valuables#174': 'Extremely fragile; putting weight on it will shatter it into tiny pieces.',
    'valuables#195': 'A horrifying item you can never escape. Beware, as it strikes suddenly.',
    'valuables#207': 'A portrait of a child. The face is blacked out, but the eyes can be seen.',
    'valuables#649': 'Arcane arte: knocks foes down with a sliding kick, striking with lightning.',
    'valuables#747': 'Arcane arte: launches foes skyward, jumps into midair, and kicks them down.',
    'valuables#765': 'Arcane arte: strikes foes with a spear, spins at high speed, and blasts away.',
    'valuables#787': 'Arcane arte: follows Flying Ruin Spear by conjuring tornadoes from ground.',
    'valuables#930': 'Arcane arte: closes distance, unleashes kicks, and strikes with shockwaves.',
    'valuables#937': 'Arcane arte: launches foes skyward, jumps into midair, and kicks them down.',
    'valuables#943': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#955': 'Arcane arte: closes in with a thrust, jumps into midair, and kicks foes down.',
    'valuables#957': 'Arcane arte: launches foes into the air, follows with slashes, and knocks down.',
    'valuables#992': 'Arcane arte: follows three consecutive thrusts with a heavy downward slash.',
    'valuables#1032': 'Arcane arte: delivers thrusts at high speed, finishing with a jumping strike.',
    'valuables#1177': 'Arcane arte: closes distance instantly, striking with consecutive slashes.',
    'valuables#1218': 'Arcane arte: leaps backward, fires chakrams, and strikes surrounding foes.',
    'valuables#1243': 'Arcane arte: launches foes skyward and strikes with a heavy diving thrust.',
    'valuables#1346': 'Arcane arte: delivers three consecutive slashes and kicks foes into the air.',
    'valuables#1620': 'Arcane arte: calls up flames from the ground to attack after Shadow Run Blast.',
    'valuables#1698': 'Fires arrows skyward that rain down upon enemies in the targeted area.',
    'valuables#1740': 'Arcane arte: launches foes skyward with an uppercut and kicks them downward.',
    'valuables#1750': 'Releases slashes like fluttering cherry blossoms, launching foes skyward.',
    'valuables#144': 'A tool used to crush ice. If found near a bed, proceed with caution.',
    'valuables#210': 'Decorated with countless eyes, though mirror surfaces are painted black.',
    'valuables#647': 'Arcane arte: knocks foes down with a sliding kick, striking with flames.',
    'valuables#651': 'Arcane arte: launches foes skyward, jumps into midair, and kicks them down.',
    'valuables#749': 'Arcane arte: launches foes skyward, jumps into midair, and kicks them down.',
    'valuables#771': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#779': 'Arcane arte: launches foes skyward with kicks, following with a dive kick.',
    'valuables#885': 'Arcane arte: leaves five presents at enemy feet after Explosive Thrust Raid.',
    'valuables#932': 'Arcane arte: Flashing Fang, Severing Moon Flower, and Ruinous Palm combo.',
    'valuables#939': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
    'valuables#973': 'Deploys a barrier blowing enemies away while greatly healing allies.',
    'valuables#1006': 'Arcane arte: cold-cloaked shockwaves trace a cross to attack enemies.',
    'valuables#1061': 'Wind secret arte: slams weapons down with momentum from midair.',
    'valuables#1194': 'Space-time sword secret arte: distorts space to cleave enemies in two.',
    'valuables#1200': 'Space-time sword arcane arte: teleports in front of enemies to attack.',
    'valuables#1283': 'Arcane arte: blows foes away with Fierce Claw and chases with Demon Fang.',
    'valuables#1350': 'Arcane arte: slashes enemies with four hits, then strikes with shockwaves.',
    'valuables#1650': 'Arcane arte: countless pages fly from an open book to slice enemies.',
    'valuables#1827': 'Arcane arte: magnificent five-hit combos unleashed by a fighting maiden.',
}

# Let's count bytes cut so far from MANUAL_VAL01
out = {}
for k, v in MANUAL_VAL01.items():
    out[k] = v

print(f"Manual entries in VAL01: {len(out)}")
from val_check import validate_dict
validate_dict('dados/item_equip_shrink/VAL-01.json', out)
