import csv

T = {
    'bloco_08B2EFC0#0': ('???', ''),
    'bgm#0': ('Battle Artist', ''),
    'bgm#1': ('Seeking Victory', ''),
    'bgm#2': ('Encounter', ''),
    'bgm#3': ('War Begins', ''),
    'bgm#4': ('Carve Path with Sword', ''),
    'bgm#5': ('Crush with the Sword', ''),
    'bgm#6': ('Raging Souga', ''),
    'bgm#7': ('Scattering Sparks', ''),
    'bgm#8': ('Burn More Fighting Spirit', ''),
    'bgm#9': ('Indomitable', ''),
    'bgm#10': ('Formidable Foe', ''),
    'bgm#11': ('Mysterious Armament Soma', ''),
    'bgm#12': ('Unwavering Spiria', ''),
    'bgm#13': ('Draw Blade! Sharpen!', ''),
    'bgm#14': ('Sword of Urgency', ''),
    'bgm#15': ('Decisive Battle! Arise!', ''),
    'bgm#16': ('Birds Sing, and I Sing', ''),
    'bgm#17': ('Whisper of Crystal', ''),
    'bgm#18': ('Deep Trees, Quiet Grass', ''),
    'bgm#19': ('Sky Fantasia', ''),
    'bgm#20': ('Endless Journey', ''),
    'bgm#21': ('Fountain Plaza Meet', ''),
    'bgm#22': ('Song of the Scallop', ''),
    'bgm#23': ('Plenty of Jam on Toast', ''),
    'bgm#24': ('Rocking Chair and Cat', ''),
    'bgm#25': ('Event General Theme (Reserved)', ''),
    'bgm#26': ('Shooting Star', ''),
    'bgm#27': ('Battle End', ''),
    'bloco_08CD989C#0': ('None', ''),
    'avisos#0': ('Character Remake', ''),
    'avisos#1': ('Adds Character Remake to the Infirmary.', ''),
    'avisos#2': ('Add Battle Voice', ''),
    'avisos#3': ('Increases battle voice variations.', ''),
    'avisos#4': ('Stg Exp.', 'Warehouse expansion (max 9)'),
    'avisos#5': ('Expands storage space.', ''),
    'avisos#6': ('Skit Player', ''),
    'avisos#7': ('Niata can now replay skits for you.', ''),
    'avisos#8': ('Diff: Hard', ''),
    'avisos#9': ('Adds Hard to battle difficulty in Options.', ''),
    'avisos#10': ('Allows obtaining stronger equipment and skills.', ''),
    'avisos#11': ('Diff: Mania', ''),
    'avisos#12': ('Adds Mania to battle difficulty in Options.', ''),
    'avisos#13': ('Top-tier rewards are now eligible quest reward choices.', ''),
    'avisos#14': ('Sound: Final Battle 1', ''),
    'avisos#15': ('Adds Final Battle 1 to Sound Select in Options.', ''),
    'avisos#16': ('Sound: Final Battle 2', ''),
    'avisos#17': ('Adds Final Battle 2 to Sound Select in Options.', ''),
    'avisos#18': ('Item Capacity Up 1', ''),
    'avisos#19': ('Item Capacity Up 2', ''),
    'avisos#20': ('Completed Quest List', ''),
    'avisos#21': ('Adds a list in the Guild to freely select completed quests.', ''),
    'avisos#22': ('Recent Quest List', ''),
    'avisos#23': ('Adds a list in the Guild to choose from recently completed quests.', ''),
    'avisos#24': ('Minimap Info Plus', ''),
    'avisos#25': ('Increases info on the minimap.', ''),
    'avisos#26': ('Karma Bell', ''),
    'avisos#27': ('A bell echoing in time. Sends owner to time beyond.', ''),
    'lugares#0': ('Luminasia', ''),
    'lugares#1': ('Gildia', ''),
    'lugares#2': ('Pecan', 'Pecan Village (max 9)'),
    'lugares#3': ('Mt. Rhubarb', ''),
    'lugares#4': ('Hazel', 'Hazel Village (max 11)'),
    'lugares#5': ('Urizn Empire', ''),
    'lugares#6': ('Emp.', 'Empire curto (max 4)'),
    'lugares#7': ('Confeito Forest', ''),
    'lugares#8': ('Garbanzo', 'Garbanzo Kingdom (max 13)'),
    'lugares#9': ('Garbanzo', ''),
    'lugares#10': ('Mt. Alterata', ''),
    'lugares#11': ('Morado', 'Morado Village (max 11)'),
    'lugares#12': ('Brownie Mine', ''),
    'lugares#13': ('Kadaif Desert', ''),
    'lugares#14': ('Mibuna Vil.', ''),
    'lugares#15': ('Mibuna', ''),
    'lugares#16': ('Raima', 'Raima Kingdom (max 9)'),
    'lugares#17': ('Raima', ''),
    'lugares#18': ('Almanac Ruins', ''),
    'lugares#19': ('Mt. Absol', ''),
    'lugares#20': ('Veratropa', ''),
    'lugares#21': ('Pasca', ''),
    'lugares#22': ('Granide', ''),
    'lugares#23': ('Sifno Spring', ''),
    'lugares#24': ('Vortex', ''),
    'lugares#25': ('Holy Langriths', ''),
    'lugares#26': ('Elan Vital', ''),
    'questfiltro#0': ('By Location', ''),
    'questfiltro#1': ('By Purpose', ''),
    'questfiltro#2': ('By Client', ''),
    'questfiltro#3': ('By Difficulty', ''),
    'questfiltro#4': ('By Delivery Item', ''),
    'questfiltro#5': ('By Target Monster 1', ''),
    'questfiltro#6': ('By Target Monster 2', ''),
    'questfiltro#7': ('By Mining', ''),
    'questfiltro#8': ('By Harvesting', ''),
    'questfiltro#9': ('By Drops', ''),
    'questfiltro#10': ('By Blue Chest 1', ''),
    'questfiltro#11': ('By Blue Chest 2', ''),
    'questfiltro#12': ('By Male', ''),
    'questfiltro#13': ('By Female', ''),
    'questfiltro#14': ('Boy Jean', ''),
    'questfiltro#15': ('Peddler Gamel', ''),
    'questfiltro#16': ('Novice Hunter Geronimo', ''),
    'questfiltro#17': ('Local Lord Raymond', ''),
    'questfiltro#18': ('Shopkeeper Hundakur', ''),
    'questfiltro#19': ('Collector Herald', ''),
    'questfiltro#20': ('Blacksmith Alex', ''),
    'questfiltro#21': ('Sr. Researcher Nicholas', ''),
    'questfiltro#22': ('Captain Daniel', ''),
    'questfiltro#23': ('Miner Ramon', ''),
    'questfiltro#24': ('Entrepreneur Egoitz', ''),
    'questfiltro#25': ('Landowner Maui', ''),
    'questfiltro#26': ('Girl Lucia', ''),
    'questfiltro#27': ('Dreamer Rina', ''),
    'questfiltro#28': ('Craftsman Diana', ''),
    'questfiltro#29': ('Fortune Aida', ''),
    'questfiltro#30': ('Celebrity Sylvia', ''),
    'questfiltro#31': ('Gourmet Carolina', ''),
    'questfiltro#32': ('Pharmacist Gemma', ''),
    'questfiltro#33': ('Therapist Teresa', ''),
    'questfiltro#34': ('By 1-Star', ''),
    'questfiltro#35': ('By 2-Star', ''),
    'questfiltro#36': ('By 3-Star', ''),
    'questfiltro#37': ('By 4-Star', ''),
    'questfiltro#38': ('By 5-Star 1', ''),
    'questfiltro#39': ('By 5-Star 2', ''),
    'questfiltro#40': ('OO', ''),
    'questfiltro#41': ('<Count>', ''),
    'questfiltro#42': ('<Dungeon Name>', ''),
    'questfiltro#43': ('<Item Name>', ''),
    'questfiltro#44': ('<Destination>', ''),
    'questfiltro#45': ('<Monster Name>', ''),
    'questfiltro#46': ('<Blue Chest>', ''),
    'questfiltro#47': ('<Client>', ''),
    'questfiltro#48': ('<Left>', ''),
    'questfiltro#49': ('<Area>', ''),
    'questfiltro#50': ('Exp Rate', ''),
    'questfiltro#51': ('Cleared', ''),
    'bonus#0': ('Item Drop Up', ''),
    'bonus#1': ('Gald Gain Up', ''),
    'bonus#2': ('Grade Gain Up', ''),
    'bonus#3': ('Specific Item Gain', ''),
    'bonus#4': ('Max', ''),
    'bonus#5': ('None', ''),
    'bonus#6': ('Makes drop items easier to obtain.', ''),
    'bonus#7': ('Increases the amount of Gald earned.', ''),
    'bonus#8': ('Increases the amount of Grade earned.', ''),
    'bonus#9': ('Obtains a specific item.', ''),
    'bonus#10': ('Battle Artist', ''),
    'bonus#11': ('Seeking Victory', ''),
    'bonus#12': ('Encounter', ''),
    'bonus#13': ('War Begins', ''),
    'bonus#14': ('Carve Path with Sword', ''),
    'bonus#15': ('Crush with the Sword', ''),
    'bonus#16': ('Raging Souga', ''),
    'bonus#17': ('Scattering Sparks', ''),
    'bonus#18': ('Burn More Fighting Spirit', ''),
    'bonus#19': ('Indomitable', ''),
    'bonus#20': ('Formidable Foe', ''),
    'bonus#21': ('Mysterious Armament Soma', ''),
    'bonus#22': ('Unwavering Spiria', ''),
    'bonus#23': ('Draw Blade! Sharpen!', ''),
    'bonus#24': ('Sword of Urgency', ''),
    'bonus#25': ('Decisive Battle! Arise!', ''),
}

with open('lotes_p68/MISC.tsv', encoding='utf-8') as f:
    reader = csv.DictReader(f, delimiter='\t')
    fieldnames = reader.fieldnames
    rows = list(reader)

missing = []
for r in rows:
    rid = r['id']
    if rid not in T:
        missing.append(rid)
    else:
        tr, nt = T[rid]
        r['traducao'] = tr
        if nt:
            r['nota_do_tradutor'] = nt

if missing:
    print("MISSING:", missing)
else:
    out_p = 'lotes_p68/MISC_retorno.tsv'
    with open(out_p, 'w', encoding='utf-8', newline='') as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter='\t')
        w.writeheader()
        w.writerows(rows)
    print("Wrote", out_p)
