import json, re
from val_check import validate_dict, nomes_proprios, CAUDA

d = json.load(open('dados/item_equip_shrink/VAL-02.json', encoding='utf-8'))
itens = d['itens']
meta = d['meta_bytes_a_cortar']

overrides = {
    'valuables#16': "Allows listening to 'Meeting at the Fountain Plaza' at Claire's.",
    'valuables#13': "Allows listening to '...have a good rest time' at Claire's.",
    'valuables#37': "Key activating DL Quest 'A Closed Heart, A Continuing Future'.",
    'valuables#25': "Key to DL Quest 'A Closed Heart, A Continuing Future'.",
    'valuables#34': "Key activating DL Quest 'The Wall That Must Be Overcome'.",
    'valuables#22': "Key to DL Quest 'The Wall That Must Be Overcome'.",
    'valuables#40': "Key activating DL Quest 'In Search of the Ultimate Dish'.",
    'valuables#28': "Key to DL Quest 'In Search of the Ultimate Dish'.",
    'valuables#31': "Key activating DL Quest 'A Fight That Cannot Be Lost'.",
    'valuables#81': 'Recipe for "Manchu-Han Imperial Feast" that Coda craves.',
    'valuables#78': 'Recipe for "Medicinal Champuru" that Coda craves.',
    'valuables#69': 'Recipe for "Black Tea Cookies" that Coda craves.',
    'valuables#266': 'White jewel from a green chest in the Rhubarb Mountains.',
    'valuables#272': 'Blue jewel from a green chest in the Sifno Spring Cave.',
    'valuables#269': 'Red jewel from a green chest in the Almanac Ruins.',
    'valuables#2156': 'Heard voice of the Origin World Tree and learned beginnings.',
    'valuables#2368': "Title for one who obtained the Great Swordsman's Radiance.",
    'valuables#2420': "Title for one who obtained the Twin Swordsman's Radiance.",
    'valuables#2416': "Title for one who obtained the Magic Knight's Radiance.",
    'valuables#2364': "Title for one who obtained the Swordsman's Radiance.",
    'valuables#2257': "Title for one who adventures in world's unexplored regions.",
    'valuables#2253': "Title for one who travels to world's unexplored regions.",
    'valuables#2346': 'Title for one who repeatedly flees in the face of enemies.',
    'valuables#2276': 'Title for one who gained an irreplaceable comrade-in-arms.',
    'valuables#2280': 'Title for one who seems to have no financial worries.',
    'valuables#150': 'Lets you see at night as in daylight. Not for weird uses.',
    'valuables#84': 'Passionately builds a romantic mood between couples... or not.',
    'valuables#89': 'In other words, a candle. How it is used depends on the user.',
    'valuables#216': 'Proof obtained only by one who conquered the sealed land.',
    'valuables#177': 'Features an image sketch looking far creepier than needed.',
    'valuables#2329': 'Becomes extremely prone to monster symbol ambushes.',
    'valuables#222': 'A tablet with numbers encrypting the world\'s entire "past".',
    'valuables#1305': "Slams in super fighting spirit to revive a KO'd companion.",
    'valuables#1806': 'Arcane arte: three-hit combos that cleave through evil.',
    'valuables#1094': 'Arcane arte: Twin Spinning Fangs and Crouching Dragon Strike.',
    'valuables#1020': 'Arcane arte: Explosive Shatter Slash and Twin Soaring Moon.',
    'valuables#1088': 'Arcane arte: Twin Spinning Fangs and Flowing Shadow Strike.',
    'valuables#1279': 'Secret arte: slashes up with Crescent Slash and unleashes Beast.',
    'valuables#1800': 'Arcane arte: connects rapid three-hit combos into Beast.',
    'valuables#620': 'Arcane arte: unleashes rapid thrusts, finishing with Beast.',
    'valuables#1405': 'Arcane arte: shoots guns while distracting with Pow Hammer.',
    'valuables#735': 'Arcane arte: follows Dragon Swarm with spin kicks.',
    'valuables#873': 'Secret arte: delivers rapid slashes in air after Soaring Blade.',
    'valuables#1100': 'Secret arte: shockwaves skyward after Sky Soaring Slash.',
    'valuables#2053': 'Arcane arte: attacks with Charge Bullets exploding up close.',
    'valuables#1102': 'Secret arte: fire-infused slashes after Explosion Sword.',
    'valuables#737': 'Arcane arte: combines Whirling Tornado, Geyser Dragon Strike.',
    'valuables#871': 'Secret arte: delivers rapid slashes in air after Fang Thrust.',
    'valuables#1202': 'Arcane arte: Spatial Flight Shift and Void Azure Slash combo.',
    'valuables#743': 'Arcane arte: combines Whirling Tornado, Explosive Fang Shot.',
    'valuables#1064': 'Arcane arte: Explosive Shatter Slash and Talon Strike.',
    'valuables#1184': 'Arcane arte: connects Tempest into Crescent Flash continuously.',
    'valuables#1392': 'Secret arte: delivers upward kicks and slashes after Fang Edge.',
    'valuables#1204': 'Arcane arte: Lightning Claw Slash and Flashing Blast combo.',
    'valuables#1394': 'Secret arte: executes rapid slashes in air after Wing Edge.',
    'valuables#1445': 'Arcane arte: combines Biting Assault and War Swift Wolf Blast.',
    'valuables#926': 'Arcane arte: combines Wind Blade Binding, Fire Wheel Drop.',
    'valuables#1583': 'Arcane arte: executes three rapid shots of Tree Cannon Flash.',
    'valuables#1575': 'Arcane arte: connects roundhouse kicks into Roaring Shatter.',
    'valuables#1675': 'Arcane arte: Flying Swallow Moon Flower, Crushing Moon Kick.',
    'valuables#1735': 'Arcane arte: follows with downward slashes after Tiger Chaos Kick.',
    'valuables#667': 'Arcane arte: executes a rapid combo on foes after Flashing Blast.',
    'valuables#669': 'Arcane arte: follows with an extra strike after Flashing Blast.',
    'valuables#1104': 'Secret arte: follows with an upward thrust after Flashing Impact.',
    'valuables#219': 'Two-handed sword favored by a legendary hero.',
    'valuables#192': 'Photo so embarrassing it makes strangers blush.',
    'valuables#171': 'So nutritious it keeps you awake for a week.',
    'valuables#1307': 'Arcane arte: grabs and hurls the opponent.',
    'valuables#1843': 'Front kick skill that repels opponents.',
    'valuables#1870': 'Swift secret arte: slashes tracing a full moon arc.',
    'valuables#1878': 'Godspeed iai arcane arte: catches distant foes.',
    'valuables#1773': 'Crossed weapons slash and vacuum blades follow up.',
    'valuables#1115': 'Vacuum waves from high-speed slashes vortex into a flash.',
    'valuables#1794': 'Follows three consecutive thrusts with a shield bash.',
    'valuables#1847': 'Refines thoughts, firing arrows that pierce through foes.',
    'valuables#2032': 'Executes three kicks, raises a sword overhead, and slashes.',
    'valuables#1808': 'Awakens light thoughts, generating nearby shockwaves.',
    'valuables#1845': 'Fires six arrows at high speed from both hands.',
    'valuables#1907': 'Blocks enemy physical attacks and delivers counterattacks.',
    'valuables#2038': 'Shoots downward enemies while jumping backward.',
    'valuables#586': 'Slashes upward at the enemy and follows with a strike.',
    'valuables#777': 'Launches foes with a spear and strikes with lightning.',
    'valuables#863': 'Leaps into air and attacks foes with a rapid dive.',
    'valuables#1254': 'Launches foes with a kick and follows with gunfire.',
    'valuables#1299': 'Launches foes with a shoulder tackle into an uppercut.',
    'valuables#1571': 'Fires arrows along the ground to target enemies.',
    'valuables#1663': 'Draws in foes, ascends while spinning, and kicks down.',
    'valuables#949': 'Vacuum wave slashes trace a crescent moon trajectory.',
    'valuables#495': 'Arte: multiple fire lances from sky impale target.',
    'valuables#453': 'Arte: dark blades rising from ground impale foes.',
    'valuables#569': 'Arte: gradually restores ally HP and cures ailments.',
    'valuables#437': 'Arte: raises all allies\' stats and slightly restores HP.',
    'valuables#390': 'Arte: attacks around target foe with judgment light.',
    'valuables#416': 'Arte: creates a gravity field, crushing earth together.',
    'valuables#1350': 'Arcane arte: figured out the answer to handling sunfish.',
    'valuables#1018': 'Arcane arte: slashes the ground, blowing away rock shards.',
    'valuables#894': 'Secret arte: throws daggers down to attack with shockwaves.',
    'valuables#1505': 'Arcane arte: generates wind pressure to blow foes away.',
    'valuables#517': 'Fire arte: fires a barrage of scalding shots at foes.',
    'valuables#596': 'Secret arte: unleashes thrusts followed by an extra strike.',
    'valuables#836': 'Arcane arte: creates a fiery flash piercing numerous foes.',
    'valuables#1876': 'Secret arte: swift forward lunges that pierce anything.',
    'valuables#1491': 'Arcane arte: blows foes away with attached talismans.',
    'valuables#1581': 'Arcane arte: fires qigong bullets that hit distant foes.',
    'valuables#1743': 'Arcane arte: delivers explosive kicks after a combo.',
    'valuables#351': 'Arte: calls a lightning bolt from above target foe.',
    'valuables#380': 'Arte: weaves a magic circle in sky to summon mighty winds.',
    'valuables#1190': 'Arcane arte: slashes up, releasing fire power at once.',
    'valuables#725': 'Secret arte: throws knocked-down foes, dealing damage.',
    'valuables#723': 'Secret arte: throws knocked-down foes, dealing damage.',
    'valuables#727': 'Secret arte: throws knocked-down foes, dealing heavy damage.',
    'valuables#1329': 'Arcane arte: unleashes vacuum waves to shred foes.',
    'valuables#1159': 'Secret arte: dives into foe\'s pocket, blowing them away.',
    'valuables#604': 'Secret arte: slams fighting spirit into foes, blowing them away.',
    'valuables#1579': 'Arcane arte: unleashes piercing shots from an up-kick.',
    'valuables#1866': 'Secret arte: combo strikes of physical hits and shocks.',
    'valuables#1109': 'Arcane arte: anti-air attacks transitioning to rapid combos.',
    'valuables#1991': 'Arcane arte: attacks foes with impact of jump arrows.',
    'valuables#341': 'Arte: creates wind blades around foes, slicing those who touch.',
    'valuables#1435': 'Secret arte: slashes foes skyward with spun weapons, slamming down.',
    'valuables#887': 'Secret arte: lifts foes with an up-thrust from below.',
    'valuables#1819': 'Secret arte: charges weapons, piercing and slicing foes.',
    'valuables#667': 'Arcane arte: executes a rapid combo after Flashing Blast.',
    'valuables#1030': 'Arcane arte: thrusts a powered fist to blast captured foes.',
    'valuables#1476': 'Secret arte: passes through foes while slashing, chasing again.',
    'valuables#1882': 'Arcane arte: delivers rapid kicks, stepping into foes.',
    'valuables#984': 'Arcane arte: shatters foes along with manifested crystals.',
    'valuables#1629': 'Arcane arte: throws kunai, calling explosive flames from ground.',
    'valuables#1899': 'Secret arte: swings photons to create light walls, overwhelming foes.',
    'valuables#353': 'Arte: thrusts lightning sword into ground to strike thunder.',
    'valuables#422': 'Arte: creates vacuum blades regardless of distance.',
    'valuables#753': 'Arcane arte: follows a thrust with lightning and wind strikes.',
    'valuables#1044': 'Secret arte: vanishes with afterimages to deliver surprise attacks.',
    'valuables#1133': 'Arcane arte: distances self with a heavy thrust after cross slashes.',
    'valuables#1416': 'Secret arte: delivers qi crushing punches from stompings.',
    'valuables#1901': 'Secret arte: shapes photons into swords, swinging like iai draws.',
    'valuables#819': 'Secret arte: follows an up-slash, calling down lightning bolts.',
    'valuables#1317': 'Arcane arte: focuses qi intensely, inflating massively.',
    'valuables#1994': 'Secret arte: jumps and fires multiple arrows from above to ground.',
    'valuables#1998': 'Arcane arte: fires arrows in fan shape, focusing arrows forward.',
    'valuables#1049': 'Secret arte: blows rock shards away with down and up impacts.',
    'valuables#1177': 'Secret arte: approaches with rapid thrusts, attacking rapidly.',
    'valuables#1635': 'Arcane arte: kicks foes skyward, shredding with wind sickles.',
    'valuables#2042': 'Secret arte: shoots luminous bullets at ground to flinch foes.',
    'valuables#1303': 'Arcane arte: slams in a high-speed rush defying user\'s physique.',
    'valuables#1432': 'Secret arte: dives in, thrusting sharply after a 3-punch combo.',
    'valuables#1459': 'Secret arte: delivers steep skyward thrusts after dash thrust.',
    'valuables#2040': 'Secret arte: showers bullets sweeping around.',
    'valuables#337': 'Arte: drops a fire sphere from sky, triggering huge explosions.',
    'valuables#465': 'Arte: rains down ice strikes from above target foe.',
    'valuables#914': 'Secret arte: leaps back, throwing kunai forward to attack.',
    'valuables#1449': 'Arcane arte: punches like biting fangs to crush foes repeatedly.',
    'valuables#1618': 'Arcane arte: calls giant tree-shaped ice blocks from ground.',
    'valuables#1872': 'Secret arte: thrusts a sword down, detonating shockwaves forward.',
    'valuables#527': 'Arte: wind arrows targeting foes attack multiple times.',
    'valuables#846': 'Arcane arte: impacts earth to blow away rock shards.',
    'valuables#992': 'Arcane arte: shatters giant crystals with sword strikes.',
    'valuables#1376': 'Secret arte: launches an up-kick into a lightning strike.',
    'valuables#1587': 'Arcane arte: pins foes to the ground with a ferocious axe kick.',
    'valuables#1598': 'Arcane arte: slaps back and forth using feet to blow foes away.',
    'valuables#1880': 'Arcane arte: executes iai slashes, slipping behind the foe.',
    'valuables#1874': 'Secret arte: leaps up and thrusts down a lightning sword.',
    'valuables#1919': 'Arcane arte: condenses photons to deliver long-range attacks.',
    'valuables#1928': 'Secret arte: lunges in with a holy blade, thrusting at once.',
    'valuables#424': 'Arte: traps foes in an ice coffin, delivering their \'demise\'.',
    'valuables#1592': 'Arcane arte: gathers qi to produce multi-hit qigong bullets.',
    'valuables#1789': 'Arcane arte: rushes toward opponent with the power of water.',
    'valuables#1876': 'Secret arte: delivers swift forward lunges that pierce anything.',
    'valuables#1915': 'Arcane arte: manifests wings of light to chase airborne foes.',
    'valuables#537': 'Arte: traps foes in demonic space to drain their vitality.',
    'valuables#1026': 'Arcane arte: slams a freezing palm strike to blow foes away.',
    'valuables#1260': 'Secret arte: executes rapid-fire attacks after a backstep.',
    'valuables#1554': 'Secret arte: flings foes forward while launching shockwaves.',
    'valuables#1888': 'Arcane arte: unleashes merciless follow-ups on impaled foes.',
    'valuables#2088': 'Arcane arte: launches with kicks, chasing with light spheres.',
    'valuables#478': 'Arte: creates a magnificent hammer above target to attack.',
    'valuables#659': 'Arcane arte: draws flame power, releasing it at once.',
    'valuables#1141': 'Arcane arte: takes distance, executing vacuum cross slashes.',
    'valuables#1301': 'Secret arte: delivers downward dive bombing with a cool hip.',
    'valuables#1764': 'Arcane arte: combos and slams in qi stored in hands.',
    'valuables#1220': 'Arcane arte: throws crossing chakrams to call down lightning.',
    'valuables#1837': 'Secret arte: fires fire thought as circular rings from above.',
    'valuables#1964': 'Arcane arte: triggers earth-cleaving shockwaves upon hit.',
    'valuables#1129': 'Arcane arte: cold-cloaked slashes spread in a V-shape.',
    'valuables#1271': 'Arcane arte: follow-up combos from aerial spin kicks.',
    'valuables#1297': 'Secret arte: blows foes sky-high with dual uppercuts.',
    'valuables#1441': 'Arcane arte: shreds foes with spun weapons after 3 strikes.',
    'valuables#1810': 'Arcane arte: peerless ultra-godspeed rapid slashes.',
    'valuables#1909': 'Arcane arte: shoots photon lasers downward from air.',
    'valuables#493': 'Arte: reduces magic damage taken by an ally temporarily.',
    'valuables#582': 'Secret arte: unleashes two shockwave slashes rapidly.',
    'valuables#653': 'Secret arte: unleashes a fiery strike reaching skyward.',
    'valuables#1275': 'Arcane arte: dives from air onto ground foes like a meteor.',
}

rules = [
    (r'^A skill that attaches a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Attaches a talisman briefly lowering enemy \1 by chance.'),
    (r'^Secret arte: flings a talisman reducing enemy (\w+) for a short time with a set chance\.$',
     r'Secret arte: flings a talisman briefly lowering enemy \1 by chance.'),
    (r'^An arcane arte where ', 'Arcane arte: '),
    (r'^An arcane arte that, ', 'Arcane arte: '),
    (r'^An arcane arte that ', 'Arcane arte: '),
    (r'^An arcane arte with ', 'Arcane arte: '),
    (r'^An arcane arte of ', 'Arcane arte: '),
    (r'^An arcane arte ', 'Arcane arte: '),
    (r'^A wind-element secret arte that ', 'Wind secret arte: '),
    (r'^Title given to someone who ', 'Title for one who '),
    (r'^Title given to someone ', 'Title for someone '),
    (r'^Title given to ', 'Title for '),
    (r'\(area of effect in battle\)', '(in battle)'),
    (r'area of effect in battle', 'in battle'),
    (r'for a single target ally', 'for an ally'),
    (r'for a single ally', 'for an ally'),
    (r'for a target ally', 'for an ally'),
    (r'for a set time\.', 'temporarily.'),
    (r'for a set time', 'temporarily'),
    (r'for a short time', 'briefly'),
    (r'beneath the target enemy\.', 'beneath target foe.'),
    (r'around the target enemy\.', 'around target foe.'),
    (r'at the target enemy\'s position\.', 'at target foe.'),
    (r'toward the target enemy\.', 'toward target foe.'),
    (r'absorbs HP from enemies in range to restore the caster\'s own HP\.',
     'absorbs HP from nearby enemies to restore caster\'s HP.'),
    (r'calls up explosive flames from the ground\.', 'calls explosive flames from ground.'),
    (r'calls up giant tree-shaped ice blocks from the ground\.', 'calls giant tree ice blocks from ground.'),
    (r'thrusts a lightning sword into the ground to strike with thunder\.',
     'thrusts lightning sword into ground to strike thunder.'),
    (r'creates vacuum blades regardless of the distance to the opponent\.',
     'creates vacuum blades regardless of distance to opponent.'),
    (r'follows a thrust with lightning and wind pressure strikes\.',
     'follows a thrust with lightning and wind strikes.'),
    (r'delivers qi-infused crushing punches from grand stompings\.',
     'delivers qi crushing punches from grand stompings.'),
    (r'shapes photons into swords and swings them like iai draws\.',
     'shapes photons into swords, swinging like iai draws.'),
    (r'throws daggers down from above to attack with shockwaves\.',
     'throws daggers down to attack with shockwaves.'),
    (r'intensely focuses qi and inflates it to an absurd degree\.',
     'intensely focuses qi, inflating to an absurd degree.'),
    (r'jumps and fires multiple arrows from above to the ground\.',
     'jumps, firing multiple arrows from above to ground.'),
    (r'fires arrows in a fan shape, then focuses arrows forward\.',
     'fires arrows in fan shape, focusing arrows forward.'),
    (r'blows away rock shards with downward and upward impacts\.',
     'blows rock shards away with down and up impacts.'),
    (r'kicks enemies skyward and shreds them with wind sickles\.',
     'kicks foes skyward, shredding with wind sickles.'),
    (r'charges energy in weapons, piercing and slicing enemies\.',
     'charges energy in weapons, piercing and slicing foes.'),
    (r'shoots luminous bullets at the ground to flinch enemies\.',
     'shoots luminous bullets at the ground to flinch foes.'),
    (r'creates a sub-space near target enemies, dealing heavy damage\.',
     'creates sub-space near target foes, dealing damage.'),
    (r'slams in a high-speed rush defying the user\'s physique\.',
     'slams in high-speed rush defying user\'s physique.'),
    (r'dives in and thrusts sharply after a three-punch combo\.',
     'dives in, thrusting sharply after 3-punch combo.'),
    (r'delivers steep skyward thrusts following a dash thrust\.',
     'delivers steep skyward thrusts after dash thrust.'),
    (r'showers bullets sweeping back and forth left and right\.',
     'showers bullets sweeping back and forth.'),
    (r'drops a fire sphere from the sky to trigger a huge explosion\.',
     'drops fire sphere from sky, triggering explosions.'),
    (r'rains down countless ice strikes from above the target enemy\.',
     'rains countless ice strikes from above target foe.'),
    (r'leaps backward while throwing kunai forward to attack\.',
     'leaps backward, throwing kunai forward to attack.'),
    (r'shatters enemies along with crystals manifested ahead\.',
     'shatters foes along with crystals manifested ahead.'),
    (r'repeatedly punches like biting fangs to crush enemies\.',
     'repeatedly punches like biting fangs to crush foes.'),
    (r'thrusts a sword down and detonates shockwaves forward\.',
     'thrusts sword down, detonating shockwaves forward.'),
    (r'throws knocked-down enemies, dealing moderate damage\.',
     'throws knocked-down foes, dealing moderate damage.'),
    (r'impacts the earth to blow away countless rock shards\.',
     'impacts earth to blow away countless rock shards.'),
    (r'launches an upward kick into a lightning-like strike\.',
     'launches upward kick into a lightning-like strike.'),
    (r'unleashes piercing shots from a spirited upward kick\.',
     'unleashes piercing shots from spirited upward kick.'),
    (r'pins enemies to the ground with a ferocious axe kick\.',
     'pins foes to the ground with ferocious axe kick.'),
    (r'slaps back and forth using feet to blow enemies away\.',
     'slaps back and forth using feet to blow foes away.'),
    (r'executes iai slashes while slipping behind the enemy\.',
     'executes iai slashes, slipping behind the enemy.'),
    (r'traps enemies in an ice coffin, delivering their \'demise\'\.',
     'traps foes in an ice coffin, delivering \'demise\'.'),
    (r'gathers qi to produce multi-hitting qigong bullets\.',
     'gathers qi to produce multi-hit qigong bullets.'),
    (r'rushes toward the opponent with the power of water\.',
     'rushes toward opponent with the power of water.'),
    (r'executes combo strikes of physical hits and shocks\.',
     'executes combo strikes of physical hits and shock.'),
    (r'delivers swift forward lunges that pierce anything\.',
     'delivers swift forward lunges piercing anything.'),
    (r'manifests wings of light to chase airborne enemies\.',
     'manifests wings of light to chase airborne foes.'),
    (r'traps enemies in a demonic space to drain their vitality\.',
     'traps foes in demonic space to drain their vitality.'),
    (r'slams a freezing palm strike to blow enemies away\.',
     'slams freezing palm strike to blow foes away.'),
    (r'transitions from anti-air attacks to rapid combos\.',
     'transitions from anti-air attack to rapid combos.'),
    (r'executes overwhelming rapid-fire after a backstep\.',
     'executes overwhelming rapid fire after backstep.'),
    (r'flings enemies forward while launching shockwaves\.',
     'flings foes forward while launching shockwaves.'),
    (r'unleashes merciless follow-ups on impaled enemies\.',
     'unleashes merciless follow-ups on impaled foes.'),
    (r'launches with kicks and chases with light spheres\.',
     'launches with kicks, chasing with light spheres.'),
    (r'creates a magnificent hammer above the target to attack\.',
     'creates a magnificent hammer above target to attack.'),
    (r'draws in flame power and releases it all at once\.',
     'draws flame power and releases it all at once.'),
    (r'takes distance and executes vacuum cross slashes\.',
     'takes distance, executing vacuum cross slashes.'),
    (r'unleashes combos and slams in qi stored in hands\.',
     'combos and slams in qi stored in hands.'),
    (r'delivers a downward dive bombing with a cool hip\.',
     'delivers downward dive bomb with a cool hip.'),
]

extra_trims = [
    (r'moderately restores HP to all allies \(in battle\)\.',
     'moderately restores allies\' HP (in battle).'),
    (r'slightly restores HP to all allies \(in battle\)\.',
     'slightly restores allies\' HP (in battle).'),
    (r'greatly restores HP to all allies \(in battle\)\.',
     'greatly restores allies\' HP (in battle).'),
    (r'absorbs HP from nearby enemies to restore caster\'s HP\.',
     'absorbs HP from nearby foes to restore own HP.'),
    (r'the opponent', 'the foe'),
    (r'to the foe', 'to foe'),
    (r'the enemy', 'the foe'),
    (r'target enemies', 'target foes'),
    (r'target enemy', 'target foe'),
    (r'around enemies', 'around foes'),
    (r'nearby enemies', 'nearby foes'),
    (r'distant enemies', 'distant foes'),
    (r'airborne enemies', 'airborne foes'),
    (r'captured enemies', 'captured foes'),
    (r'knocked-down enemies', 'knocked-down foes'),
    (r'impaled enemies', 'impaled foes'),
    (r'downward enemies', 'downward foes'),
    (r'enemy heads', 'foe heads'),
    (r'numerous enemies', 'numerous foes'),
    (r'closing distance', 'closing in'),
    (r'spinning slashes', 'spin slashes'),
    (r'spinning kicks', 'spin kicks'),
    (r'spinning impacts', 'spin impacts'),
    (r'through enemies', 'through foes'),
    (r'enemies with', 'foes with'),
    (r'into enemies', 'into foes'),
    (r'attacks enemies', 'attacks foes'),
    (r'slashes enemies', 'slashes foes'),
    (r'launches enemies', 'launches foes'),
    (r'surrounding foes', 'nearby foes'),
    (r'surrounding enemies', 'nearby foes'),
    (r'the surroundings', 'nearby area'),
    (r'toward the heavens', 'skyward'),
    (r'high into the sky', 'skyward'),
    (r'consecutive attacks', 'rapid attacks'),
    (r'consecutive slashes', 'rapid slashes'),
    (r'consecutive thrusts', 'rapid thrusts'),
    (r'in an instant', 'instantly'),
    (r'on enemies', 'on foes'),
    (r'to enemies', 'to foes'),
    (r'striking enemies', 'striking foes'),
    (r'impales enemies', 'impales foes'),
    (r'draws enemies', 'draws foes'),
    (r'draw in enemies', 'draw foes in'),
    (r'sweeps enemies', 'sweeps foes'),
    (r'and strikes with shockwaves', 'with shockwaves'),
    (r'and finishes with ', ', finishing with '),
    (r'and connects into ', ', connecting into '),
    (r'to attack foes\.', 'to attack.'),
    (r'to attack enemies\.', 'to attack.'),
    (r'follows up with ', 'follows with '),
    (r'follows up on ', 'follows '),
    (r'follows up in ', 'follows in '),
    (r'follows up,', 'follows,'),
    (r'two-stage strikes', 'two strikes'),
    (r'from impact points', 'on impact'),
    (r'in rapid succession', 'rapidly'),
    (r'in midair', 'in air'),
    (r'from midair', 'from air'),
    (r'into the air', 'into air'),
    (r'into midair', 'in air'),
    (r'sky-high', 'high'),
    (r'at high speed', 'at high speed'),
    (r'a lightning-like', 'a lightning'),
    (r'three-hit combos', 'three-hit combo'),
    (r'and unleashes ', ', unleashing '),
    (r'and slashes ', ', slashing '),
    (r'and kicks ', ', kicking '),
    (r'and strikes ', ', striking '),
    (r'and sweeps ', ', sweeping '),
    (r'and dives ', ', diving '),
    (r'and fires ', ', firing '),
    (r'to the ground', 'to ground'),
    (r'into the ground', 'into ground'),
    (r'from the ground', 'from ground'),
    (r'on the ground', 'on ground'),
    (r'at the ground', 'at ground'),
    (r'super fighting spirit', 'fighting spirit'),
    (r'with the power of ', 'with '),
    (r'multi-hitting', 'multi-hit'),
    (r'wind pressure strikes', 'wind strikes'),
    (r'a sharp thrust', 'a thrust'),
    (r'a heavy thrust', 'a thrust'),
    (r'an extra strike', 'an extra hit'),
    (r'an upward slash', 'an up-slash'),
    (r'an upward thrust', 'an up-thrust'),
    (r'an upward kick', 'an up-kick'),
    (r'upward kicks', 'up-kicks'),
    (r'upward thrusts', 'up-thrusts'),
    (r'upward slashes', 'up-slashes'),
    (r'downward slashes', 'down-slashes'),
    (r'downward impacts', 'down-impacts'),
    (r'A fire arte that ', 'Fire arte: '),
    (r'An arte where ', 'Arte: '),
    (r'and triggers ', ', triggering '),
    (r'and summons ', ', summoning '),
    (r'and calls down ', ', calling down '),
    (r'and shoots ', ', shooting '),
    (r'and throws ', ', throwing '),
    (r'and shreds ', ', shredding '),
    (r'and crushes ', ', crushing '),
    (r'and pierces ', ', piercing '),
    (r'and creates ', ', creating '),
    (r'and captures ', ', capturing '),
    (r'and pulls ', ', pulling '),
    (r'and knocks ', ', knocking '),
    (r'and leaps ', ', leaping '),
    (r'and ascends ', ', ascending '),
    (r'and detonates ', ', detonating '),
    (r'and focuses ', ', focusing '),
    (r'and follows with ', ', following with '),
    (r'and follows ', ', following '),
    (r'moderately restores HP to a single target ally\.', 'moderately restores target ally\'s HP.'),
    (r'while stepping into foes', 'stepping into foes'),
    (r'while stepping into the foe', 'stepping into the foe'),
    (r'while jumping backward', 'jumping backward'),
    (r'while spinning', 'spinning'),
    (r'all at once', 'at once'),
    (r'to strike with thunder\.', 'to strike thunder.'),
    (r'leaving afterimages', 'with afterimages'),
    (r'blows them away grandly\.', 'blows them away.'),
    (r'from grand stompings\.', 'from stompings.'),
    (r'to an absurd degree\.', 'massively.'),
    (r'a multitude of arrows', 'multiple arrows'),
    (r'sweeping back and forth\.', 'sweeping around.'),
    (r'to trigger a huge explosion\.', 'triggering huge explosions.'),
    (r'to summon mighty wind power\.', 'summoning mighty winds.'),
    (r'rains down countless ice strikes', 'rains ice strikes'),
    (r'to slice those who touch them\.', 'slicing those who touch.'),
    (r'regardless of distance to opponent\.', 'regardless of distance.'),
    (r'regardless of the distance to the opponent\.', 'regardless of distance.'),
    (r'attacks with the impact of arrows shot from a jump\.', 'attacks with the impact of jump arrows.'),
    (r'creates countless dark-element bubbles', 'creates dark bubbles'),
    (r'triggers a small flame explosion', 'triggers a flame explosion'),
    (r'stirs up a storm cloaked in dark clouds', 'stirs up a dark storm'),
    (r'intensely focuses qi', 'focuses qi intensely'),
    (r'generates wind pressure to blow foes away\.', 'generates wind gusts, blowing foes away.'),
]

out = {}
for x in itens:
    item_id = x['id']
    en = x['en']
    if item_id in overrides:
        s = overrides[item_id]
    else:
        s = en
        for pat, rep in rules:
            s = re.sub(pat, rep, s)
        if s.startswith('A skill that '):
            rest = s[len('A skill that '):]
            s = rest[0].upper() + rest[1:]
    
    for pat, rep in extra_trims:
        s = re.sub(pat, rep, s)
    
    s = re.sub(r'\s+,', ',', s)
    s = re.sub(r'\s+', ' ', s).strip()
    
    if s != en:
        out[item_id] = s

print(f"Total entries in out: {len(out)} / {len(itens)}")
ok = validate_dict('dados/item_equip_shrink/VAL-02.json', out)
if ok:
    with open('dados/item_equip_shrink/VAL-02_out.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
    print("SAVED VAL-02_out.json!")
