import json, re
from val_check import validate_dict, nomes_proprios, CAUDA

d = json.load(open('dados/item_equip_shrink/VAL-04.json', encoding='utf-8'))
itens = d['itens']
meta = d['meta_bytes_a_cortar']

overrides = {
    # Recipes & Key items
    'valuables#64': 'Recipe for "Oden" that Coda craves.',
    'valuables#1': "Sorcerer's Ring. It has no power yet.",
    'valuables#4': "Sorcerer's Ring. Expands accessible places.",
    'valuables#10': "Sorcerer's Ring. Now all areas can be entered.",
    'valuables#43': 'Magical item to increase Blacksmith rank.',
    'valuables#183': 'Newt burnt pitch black. Purpose unknown.',

    # Titles
    'valuables#2167': 'Title for sharing bonds with three Kanonnos.',
    'valuables#2096': 'Title for saving otherworldly Terresia.',
    'valuables#2100': 'Title for saving otherworldly Granide.',
    'valuables#2104': 'Title for breaking rules of this world.',
    'valuables#2123': 'Title for official member of Ad Libitum.',
    'valuables#2124': 'Learned ropes of working in Ad Libitum.',
    'valuables#2127': 'Title for one rivaled by Saleh.',
    'valuables#2131': "Title for becoming Joan's benefactor.",
    'valuables#2139': 'Title for one becoming beacon of freedom.',
    'valuables#2143': 'Title for one rivaled by Barbatos.',
    'valuables#2151': 'Title for one wounding Saleh severely.',
    'valuables#2171': 'Title for mastering a single class.',
    'valuables#2175': 'Title for mastering all classes.',
    'valuables#2187': 'Title for investigating monsters.',
    'valuables#2191': 'Title for knowing all monsters thoroughly.',
    'valuables#2195': 'Title for knowing all equipment thoroughly.',
    'valuables#2199': 'Title for accomplishing numerous quests.',
    'valuables#2203': 'Title for instantly slaying enemies.',
    'valuables#2219': 'Title for using skills like a demon.',
    'valuables#2223': 'Title for using spells like a demon.',
    'valuables#2227': 'Title for using Pow Hammer like a demon.',
    'valuables#2242': 'Title for one who dabbled in thievery.',
    'valuables#2245': 'Title for a full-fledged thief.',
    'valuables#2265': 'Title for one who bullies Polwiggles.',
    'valuables#2268': 'Title for one feared by Polwiggles.',
    'valuables#2288': 'Title for one versed in gummy recipes.',
    'valuables#2292': 'Title for one versed in bottle recipes.',
    'valuables#2296': 'Title for one versed in dish recipes.',
    'valuables#2316': 'Title for regular patron of the smithy.',
    'valuables#2320': 'Title for one pursuing character makeover.',
    'valuables#2335': 'Title for one who found great matchmate.',
    'valuables#2343': 'Title for one doing half-hearted work.',
    'valuables#2350': 'Title for one who never takes detours.',
    'valuables#2357': 'Title for one obtaining Radiant gear.',
    'valuables#2475': 'Title exclusive to Colosseum Champion.',
    'valuables#2479': 'Title for one who defeated Dhaos.',
    'valuables#2483': 'Title for facing Barbatos directly.',
    'valuables#2487': 'Title for one sitting atop the world.',
    'valuables#2495': 'Title for an experienced adventurer.',
    'valuables#2503': 'Title for one obtaining all titles.',
    'valuables#2119': 'Title for one knowing battle victory.',

    # Specific battle/milestone events
    'valuables#2108': 'Title for defeating Widdershin.',
    'valuables#2109': 'Defeated Widdershin in Colosseum.',
    'valuables#2160': 'Resolved for final battle to save world.',
    'valuables#2192': 'Discovered 90%+ of Monster Book.',
    'valuables#2196': 'Discovered 90%+ of Equipment Book.',
    'valuables#2220': 'Exceeded 999 uses of specific skill.',
    'valuables#2224': 'Exceeded 999 uses of specific spell.',
    'valuables#2228': 'Exceeded 999 uses of Pow Hammer as Priest.',
    'valuables#2235': 'Total monsters slain topped 1,000.',
    'valuables#2239': 'Total monsters slain topped 10,000.',
    'valuables#2243': 'Successfully used Rover Item for first time.',
    'valuables#2246': 'Successfully used Rover Item 100 times.',
    'valuables#2250': 'Successfully used Rover Item 300 times.',
    'valuables#2254': 'Dungeon exploration exceeded 30%.',
    'valuables#2258': 'Dungeon exploration exceeded 60%.',
    'valuables#2262': 'Dungeon exploration exceeded 90%.',
    'valuables#2273': 'Battle count for all Tales characters exceeded 50.',
    'valuables#2328': 'Unlocked all classes for class swap.',
    'valuables#2332': 'Fought 100 battles with only player character.',
    'valuables#2336': 'Cleared showdown quest against Tales character.',
    'valuables#2369': 'Obtained Great Swordsman Radiant set.',
    'valuables#2421': 'Obtained Twin Swordsman Radiant set.',
    'valuables#2469': 'Won a Colosseum mission for first time.',
    'valuables#2473': "Defeated Colosseum's White Devil.",
    'valuables#2480': 'Defeated Dhaos in Mine of Reminiscence.',
    'valuables#2484': 'Defeated Barbatos without using items.',
    'valuables#2488': 'Defeated Yggdrasill in Mine of Reminiscence.',

    # Specific Artes
    'valuables#51': "Arche's secret treasure... seemingly.",
    'valuables#305': 'Arte: revives target ally from KO.',
    'valuables#307': 'Arte: cures status ailments for an ally.',
    'valuables#311': 'Arte: dispels status changes on an ally.',
    'valuables#313': 'Arte: dispels status changes on all allies.',
    'valuables#319': 'Arte: shares own TP with a single ally.',
    'valuables#349': 'Arte: awakens earth energy.',
    'valuables#363': 'Arte: summons meteors from afar.',
    'valuables#376': 'Arte: causes falling rocks from above.',
    'valuables#400': 'Arte: greatly restores HP to target ally.',
    'valuables#420': 'Arte: fires spin compressed water rapidly.',
    'valuables#439': 'Arte: attacks with light purging evil beings.',
    'valuables#448': 'Arte: awakens ancient flames of purification.',
    'valuables#451': 'Arte: drops stone spears from above foes.',
    'valuables#455': 'Arte: fires 3 light spheres simultaneously.',
    'valuables#474': 'Arte: fires sacred bolts of judgment.',
    'valuables#499': 'Arte: gradually restores damage over time.',
    'valuables#525': "Arte: creates wind arrows above caster's head.",
    'valuables#531': 'Arte: drags foes into pitch-black abyss.',
    'valuables#533': 'Arte: fires lightning at foes ahead.',
    'valuables#549': 'Arte: slightly increases Overlimit gauge.',
    'valuables#559': 'Arte: moderately restores HP to all allies.',
    'valuables#575': 'Arte: fires multitude of ice lances.',
    'valuables#616': 'Arcane arte: Tempest and Beast.',
    'valuables#747': 'Secret arte: unleashes large shockwave.',
    'valuables#797': 'Arcane arte: manifests steel to launch foes.',
    'valuables#815': 'Arcane arte: fires full-powered arrow.',
    'valuables#857': 'Arcane arte: hurls bottles all around.',
    'valuables#1022': 'Secret arte: executes flame-cloaked Tempest.',
    'valuables#1034': 'Arcane arte: delivers rapid shots from sky.',
    'valuables#1117': 'Slashes inward with cold.',
    'valuables#1163': 'Skewers and draws foes close.',
    'valuables#1210': 'Secret arte: hurls powered chakrams twice.',
    'valuables#1212': 'Arcane arte: hurls chakrams forward.',
    'valuables#1218': 'Arcane arte: rains down hammers.',
    'valuables#1226': 'Secret arte: tosses a multitude of hammers.',
    'valuables#1249': 'Arcane arte: fires large water bullets.',
    'valuables#1277': 'Arcane arte: executes godspeed rapid attacks.',
    'valuables#1315': 'Arcane arte: increases own physical attack.',
    'valuables#1346': 'Casually kicks a stone.',
    'valuables#1354': 'Arcane arte: attacks with a companion sunfish.',
    'valuables#1378': 'Arcane arte: Dragon Swarm and Beast.',
    'valuables#1412': 'Secret arte: rains ice lances from above.',
    'valuables#1418': 'Arcane arte: delivers a furious 10-hit combo.',
    'valuables#1426': 'Slams fist from a sharp thrust.',
    'valuables#1501': "Arte: revives a KO'd ally in battle.",
    'valuables#1535': 'Arte: generates ice beneath enemy feet.',
    'valuables#1608': 'Sprints soundlessly to attack.',
    'valuables#1647': "Attacks sweeping at foe's feet.",
    'valuables#1698': 'Arcane arte: swings dual swords to shred foes.',
    'valuables#1825': 'Memorable skill taught by older brother.',
    'valuables#1938': 'Arte: slightly restores HP in range.',
    'valuables#1940': 'Arte: greatly restores HP in range.',
    'valuables#1942': 'Arte: calls lightning over a small area.',
    'valuables#1957': 'Secret arte: executes rapid shooting.',
    'valuables#1963': 'Arcane arte: executes rapid shooting.',
    'valuables#1996': 'Secret arte: rains down many arrows.',
    'valuables#2005': 'Secret arte: calls lightning upon impact.',
    'valuables#2065': 'Arte: greatly restores HP to target ally.',
}

rules = [
    (r'^Arcane arte: combines (.*)$', r'Arcane arte: \1'),
    (r'^Total level of all members exceeded (\d+)\.$', r'Total member level topped \1.'),
    (r'^Title given to a guild with Fame Level (\d+)\.$', r'Title: guild with Fame Level \1.'),
    (r'^Title given to someone who has ', 'Title for one who '),
    (r'^Title given to someone who ', 'Title for one who '),
    (r'^Title given to someone ', 'Title for one '),
    (r'^Title given to an? ', 'Title for an? '),
    (r'^Title given to ', 'Title for '),
    (r'^An arte where ', 'Arte: '),
    (r'\(area of effect in battle\)', '(in battle)'),
    (r'area of effect in battle', 'in battle'),
    (r'for a single target ally', 'for an ally'),
    (r'for a single ally', 'for an ally'),
    (r'for a target ally', 'for an ally'),
    (r'for a set time\.', 'briefly.'),
    (r'for a set time', 'briefly'),
    (r'for a short time', 'briefly'),
    (r'beneath the target enemy\.', 'beneath target foe.'),
    (r'around the target enemy\.', 'around target foe.'),
    (r'at the target enemy\'s position\.', 'at target foe.'),
    (r'toward the target enemy\.', 'toward target foe.'),
    (r'the target enemy\.', 'target foe.'),
    (r'the target enemy\'s', 'target foe\'s'),
    (r'the target enemy', 'target foe'),
]

extra_trims = [
    (r'closing distance', 'closing in'),
    (r'spinning slashes', 'spin slashes'),
    (r'spinning kicks', 'spin kicks'),
    (r'spinning impacts', 'spin impacts'),
    (r'through enemies', 'through foes'),
    (r'enemies with', 'foes with'),
    (r'into enemies', 'into foes'),
    (r'attacks enemies', 'attacks foes'),
    (r'slashes enemies', 'slashes foes'),
    (r'launches enemies', 'launches foes'),
    (r'surrounding foes', 'nearby foes'),
    (r'surrounding enemies', 'nearby foes'),
    (r'the surroundings', 'nearby area'),
    (r'toward the heavens', 'skyward'),
    (r'high into the sky', 'skyward'),
    (r'consecutive attacks', 'rapid attacks'),
    (r'consecutive slashes', 'rapid slashes'),
    (r'consecutive thrusts', 'rapid thrusts'),
    (r'in an instant', 'instantly'),
    (r'on enemies', 'on foes'),
    (r'to enemies', 'to foes'),
    (r'striking enemies', 'striking foes'),
    (r'impales enemies', 'impales foes'),
    (r'draws enemies', 'draws foes'),
    (r'draw in enemies', 'draw foes in'),
    (r'sweeps enemies', 'sweeps foes'),
    (r'and strikes with shockwaves', 'with shockwaves'),
    (r'and finishes with ', ', finishing with '),
    (r'and connects into ', ', connecting into '),
    (r'to attack foes\.', 'to attack.'),
    (r'to attack enemies\.', 'to attack.'),
    (r'follows up with ', 'follows with '),
    (r'follows up on ', 'follows '),
    (r'follows up in ', 'follows in '),
    (r'follows up,', 'follows,'),
    (r'two-stage strikes', 'two strikes'),
    (r'from impact points', 'on impact'),
    (r'in rapid succession', 'rapidly'),
    (r'in midair', 'in air'),
    (r'from midair', 'from air'),
    (r'into the air', 'into air'),
    (r'into midair', 'in air'),
    (r'sky-high', 'high'),
    (r'to the ground', 'to ground'),
    (r'into the ground', 'into ground'),
    (r'from the ground', 'from ground'),
    (r'on the ground', 'on ground'),
    (r'at the ground', 'at ground'),
    (r'super fighting spirit', 'fighting spirit'),
    (r'with the power of ', 'with '),
    (r'multi-hitting', 'multi-hit'),
    (r'wind pressure strikes', 'wind strikes'),
    (r'a sharp thrust', 'a thrust'),
    (r'a heavy thrust', 'a thrust'),
    (r'an extra strike', 'an extra hit'),
    (r'an upward slash', 'an up-slash'),
    (r'an upward thrust', 'an up-thrust'),
    (r'an upward kick', 'an up-kick'),
    (r'upward kicks', 'up-kicks'),
    (r'upward thrusts', 'up-thrusts'),
    (r'upward slashes', 'up-slashes'),
    (r'downward slashes', 'down-slashes'),
    (r'downward impacts', 'down-impacts'),
    (r'all at once', 'at once'),
    (r'the opponent', 'the foe'),
    (r'to the foe', 'to foe'),
    (r'the enemy', 'the foe'),
    (r'target enemies', 'target foes'),
    (r'around enemies', 'around foes'),
    (r'nearby enemies', 'nearby foes'),
    (r'distant enemies', 'distant foes'),
    (r'airborne enemies', 'airborne foes'),
    (r'captured enemies', 'captured foes'),
    (r'knocked-down enemies', 'knocked-down foes'),
    (r'impaled enemies', 'impaled foes'),
    (r'downward enemies', 'downward foes'),
    (r'enemy heads', 'foe heads'),
    (r'numerous enemies', 'numerous foes'),
]

out = {}
for x in itens:
    item_id = x['id']
    en = x['en']
    if item_id in overrides:
        s = overrides[item_id]
    else:
        # Don't touch stats lines like Base Physical Attack...
        if en.startswith('Result TP') or en.startswith('Monster Symbol') or en.startswith('Max TP') or en.startswith('Max HP') or en.startswith('Base Physical') or en.startswith('Base Phys') or en.startswith('Base Magic') or en.startswith('Base Arte') or en.startswith('Base Agility') or en.startswith('TP Consumption') or en.startswith('Items From') or en.startswith('Enemy Target') or en.startswith('Prevent Back') or en.startswith('Rare Find') or en.startswith('Skill Slots') or en.startswith('Escape Time') or en.startswith('Gathering +') or en.startswith('Restores 2%') or en.startswith('More easily'):
            continue
            
        s = en
        for pat, rep in rules:
            s = re.sub(pat, rep, s)
        if s.startswith('A skill that '):
            rest = s[len('A skill that '):]
            s = rest[0].upper() + rest[1:]
    
    for pat, rep in extra_trims:
        s = re.sub(pat, rep, s)
    
    s = re.sub(r'\s+,', ',', s)
    s = re.sub(r'\s+', ' ', s).strip()
    
    if s != en:
        out[item_id] = s

print(f"Total entries in out: {len(out)} / {len(itens)}")
ok = validate_dict('dados/item_equip_shrink/VAL-04.json', out)
if ok:
    with open('dados/item_equip_shrink/VAL-04_out.json', 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=1, ensure_ascii=True)
    print("SAVED VAL-04_out.json!")
