CAPITULO_2 = {
    'capitulo#320': 'Fearing relapse, they expected',
    'capitulo#321': 'banishment from the village.',
    'capitulo#322': 'To find a haven for them, the party',
    'capitulo#323': 'returned to the ship.',
    'capitulo#324': 'Unable to return, Joan and Miguel',
    'capitulo#325': 'joined building Olta Village.',
    'capitulo#326': 'Examining the beetle and Joan confirmed',
    'capitulo#327': 'mutations caused by the red smoke.',
    'capitulo#328': 'Proving that red smoke was indeed',
    'capitulo#329': 'the cause of biological mutations.',
    'capitulo#330': 'Yet the healing and mutation process',
    'capitulo#331': 'remained completely unexplained.',
    'capitulo#332': 'Civilian contact had to cease,',
    'capitulo#333': 'yet its next emergence was unknown.',
    'capitulo#334': 'Expecting more requests, Ange',
    'capitulo#335': 'waited for reports of smoke sightings.',
    'capitulo#336': 'Soon, a new recruit boarded the ship.',
    'capitulo#337': 'It was Arche, an old friend of Mint.',
    'capitulo#338': "Arche brought the Sorcerer's Ring,",
    'capitulo#339': 'an artifact opening sealed paths.',
    'capitulo#340': 'Mint gave it to Ange with a quest.',
    'capitulo#341': 'Presently, the ring possessed no power.',
    'capitulo#342': 'To awaken it, natural energy',
    'capitulo#343': 'had to be infused directly.',
    'capitulo#344': 'Infusion sites were Ring Spots,',
    'capitulo#345': 'and OO was chosen to venture forth.',
    'capitulo#346': 'At Altata Volcano, OO',
    'capitulo#347': 'infused the ring with primal energy,',
    'capitulo#348': 'activating its power.',
    'capitulo#349': "The Sorcerer's Ring could still gain",
    'capitulo#350': 'greater power through infusions.',
    'capitulo#351': 'Whenever new Ring Spots are found,',
    'capitulo#352': 'further guidance would follow.',
    'capitulo#353': 'Ange entrusted the ring to OO,',
    'capitulo#354': 'granting authority to wield it.',
    'capitulo#355': 'Intel on red smoke',
    'capitulo#356': 'remained elusive.',
    'capitulo#357': 'When someone wondered if spirits knew,',
    'capitulo#358': 'Kratos spoke up thoughtfully.',
    'capitulo#359': 'He mentioned Mibuna Village, a haven',
    'capitulo#360': 'communing with spirits.',
    'capitulo#361': 'Kratos offered to act as a guide,',
    'capitulo#362': 'submitting a quest.',
    'capitulo#363': 'Did a village tied to spirits truly exist?',
    'capitulo#364': 'If it aided investigation into smoke,',
    'capitulo#365': 'there was no room for hesitation.',
    'capitulo#366': 'To seek info on the smoke,',
    'capitulo#367': 'OO accepted the quest, traveling through',
    'capitulo#368': 'Brownie Mine toward Mibuna Village.',
    'capitulo#369': 'Guided by Kratos alongside Harold,',
    'capitulo#370': 'OO advanced deep inside.',
    'capitulo#371': 'Along the path, Harold found a flier.',
    'capitulo#372': 'It was recruitment for a cult calling',
    'capitulo#373': 'Servants of the Dawn.',
    'capitulo#374': 'Amidst war, new cults awaiting',
    'capitulo#375': 'the Descender arose everywhere.',
    'capitulo#376': 'Servants of the Dawn was fiercest.',
    'capitulo#377': 'Countless souls sought salvation.',
    'capitulo#378': 'OO felt great frustration',
    'capitulo#379': 'weighing upon the heart.',
    'capitulo#380': 'Suddenly, a distant shout echoed out.',
    'capitulo#381': 'Rushing over, a beast rampaged.',
    'capitulo#382': 'Upon defeat, it vanished without trace.',
    'capitulo#383': 'In its place appeared a lone woman.',
    'capitulo#384': 'She was Sheena, an acquaintance of Kratos.',
    'capitulo#385': 'The beast was an artificial spirit crafted',
    'capitulo#386': 'with the art of Light Qi.',
    'capitulo#387': 'Kratos sought an audience with spirits,',
    'capitulo#388': 'yet mining drove them away.',
    'capitulo#389': 'Spirits had vanished from the land.',
    'capitulo#390': 'Advancing would not yield a spirit.',
    'capitulo#391': 'However, Sheena promised to deliver texts',
    'capitulo#392': 'detailing spirit locations later,',
    'capitulo#393': 'so the party returned to the ship.',
    'capitulo#394': 'Hope was not entirely lost.',
    'capitulo#395': 'The research crew was thrilled by news',
    'capitulo#396': 'of artificial spirits and Light Qi.',
    'capitulo#397': 'Rita was especially intrigued by Light Qi,',
    'capitulo#398': 'hypothesizing links to the ancient',
    'capitulo#399': 'discipline known as Soul Alchemy,',
    'capitulo#400': 'growing immensely excited.',
    'capitulo#401': 'Soon Sheena arrived alongside Lloyd,',
    'capitulo#402': 'delivering literature on spirits.',
    'capitulo#403': 'Rita questioned Sheena on Light Qi.',
    'capitulo#404': 'Though secret to Mibuna Village,',
    'capitulo#405': 'persuaded that it might solve mutations,',
    'capitulo#406': 'Sheena shared the scriptures.',
    'capitulo#407': 'Examining them confirmed artificial spirits',
    'capitulo#408': 'was a branch of Soul Alchemy,',
    'capitulo#409': 'the very art Rita pursued.',
    'capitulo#410': 'Soul Alchemy alters blueprints',
    'capitulo#411': 'known as Documents, bodies of pure energy.',
    'capitulo#412': 'Perhaps biological mutations operated through',
    'capitulo#413': 'alterations to those very Documents.',
    'capitulo#414': 'Yet Rita noted manipulating such arts',
    'capitulo#415': 'was impossible for ordinary mortals.',
    'capitulo#416': 'An escort quest reached the guild',
    'capitulo#417': 'requesting passage to meet the entity.',
    'capitulo#418': 'The red smoke, rumored to grant wishes.',
    'capitulo#419': 'The client said it was at Rhubarb.',
    'capitulo#420': 'Ange declined, deploying',
    'capitulo#421': 'members to Rhubarb directly.',
    'capitulo#422': 'To prevent further civilian contact...',
    'capitulo#423': 'OO led Tytree and Meredy,',
    'capitulo#424': 'for Rhubarb Mountains with Tytree and Meredy.',
    'capitulo#425': 'En route, they turned back civilians',
    'capitulo#426': 'seeking the wish-granting entity.',
    'capitulo#427': 'Before long, Tytree spotted a red figure.',
    'capitulo#428': 'Had red smoke assumed humanoid form?',
    'capitulo#429': 'Was this the wish-granting existence?',
    'capitulo#430': 'When Tytree questioned it, the red figure',
    'capitulo#431': 'merely swayed and gazed at OO and allies.',
    'capitulo#432': 'It seemed instinctively studying OO,',
    'capitulo#433': 'Servants of the Dawn appeared.',
    'capitulo#434': 'Suddenly, Servants of the Dawn appeared.',
    'capitulo#435': 'Hailing the entity as their Lord Descender,',
    'capitulo#436': 'they bypassed OO and spirited it away.',
    'capitulo#437': 'Such a horrifying being was no savior.',
    'capitulo#438': 'If worshiped widely and touched by masses,',
    'capitulo#439': 'catastrophe would inevitably ensue.',
    'capitulo#440': "Rita's research showed that the beetle's",
    'capitulo#441': 'Document was heavily corroded.',
    'capitulo#442': 'Its Document was rewritten into something',
    'capitulo#443': 'deviating completely from organic life.',
    'capitulo#444': 'Its rewritten Document belonged to no world.',
    'capitulo#445': 'Whenever red smoke touched organisms,',
    'capitulo#446': 'their Documents were forcibly overwritten.',
    'capitulo#447': 'Meanwhile, the smoke itself evolved.',
    'capitulo#448': 'Red smoke reacted to wishes.',
    'capitulo#449': 'The red smoke reacted to desperate wishes.',
    'capitulo#450': 'It resonated with powerful desires.',
    'capitulo#451': "Touching desires, it learned from a target's",
    'capitulo#452': 'Document, evolving and transforming.',
    'capitulo#453': 'Yet its ultimate goal remained unknown.',
    'capitulo#454': 'While grappling with these mysteries,',
    'capitulo#455': 'new allies arrived aboard the ship.',
    'capitulo#456': 'Asbel and Sophie arrived to retrieve Estelle.',
    'capitulo#457': 'Princess Natalia of Lima took refuge,',
    'capitulo#458': 'guarded by Jade and Tear.',
    'capitulo#459': 'The riots in Lima were instigated directly',
    'capitulo#460': 'by Servants of the Dawn.',
    'capitulo#461': 'Deprived of Star Crystal concessions,',
    'capitulo#462': 'the populace of Lima suffered hardship.',
    'capitulo#463': 'Servants of the Dawn exploited this misery,',
    'capitulo#464': 'preaching salvation and inciting unrest,',
    'capitulo#465': 'causing public anger to erupt violently.',
    'capitulo#466': 'When Ange said they pursued the cult,',
    'capitulo#467': 'at Almanac Ruins.',
    'capitulo#468': 'within the Almanac Ruins.',
    'capitulo#469': 'Revering that red entity as savior,',
    'capitulo#470': 'They had to act quickly',
    'capitulo#471': 'They had to sever the entity quickly',
    'capitulo#472': 'before disaster unfolded.',
    'capitulo#473': 'Leading Ange and Jade, OO entered',
    'capitulo#474': 'into the Almanac Ruins.',
    'capitulo#475': 'The cultists blocking the way wielded power,',
    'capitulo#476': 'displaying superhuman strength.',
    'capitulo#477': 'It was unearthly power bestowed by that entity',
    'capitulo#478': 'whom they hailed as Descender.',
    'capitulo#479': 'Fighting fanatically to protect their savior,',
    'capitulo#480': 'grotesque mutations overtook their bodies.',
    'capitulo#481': 'Horrified by deformities, they begged',
    'capitulo#482': 'an entity named Lazaris for salvation.',
    'capitulo#483': 'Lazaris... was that the identity of the smoke?',
    'capitulo#484': 'Yet Lazaris coldly rejected the cultists.',
    'capitulo#485': 'Lazaris claimed to be an unborn world,',
    'capitulo#486': 'destined to exist just like Luminasia.',
    'capitulo#487': 'Venting fury at the state of Luminasia,',
    'capitulo#488': 'Lazaris departed alone.',
    'capitulo#489': 'Just as with Joan, OO extended gentle hands,',
    'capitulo#490': 'restoring the mutated cultists to normal form.',
    'capitulo#491': 'Restored yet forsaken by their idol,',
    'capitulo#492': 'The entity was no Descender.',
    'capitulo#493': 'That entity was certainly no Descender.',
    'capitulo#494': 'Restoring Joan and cultists from mutations',
    'capitulo#495': "displayed OO's miraculous power.",
    'capitulo#496': 'To researchers, this phenomenon seemed',
    'capitulo#497': 'just like miracles of Soul Alchemy.',
    'capitulo#498': 'Yet OO possessed no explanation.',
    'capitulo#499': 'While planning future strategies, OO',
    'capitulo#500': 'enjoyed a brief respite in the hall.',
    'capitulo#501': 'Kanonno invited all to view her art.',
    'capitulo#502': 'Kanonno was fond of OO viewing her art,',
    'capitulo#503': 'as Rocks noted with warmth.',
    'capitulo#504': "Rocks shared that he served Kanonno's parents",
    'capitulo#505': 'before they passed away, raising Kanonno',
    'capitulo#506': 'ever since their demise.',
    'capitulo#507': 'Meanwhile, Lazaris observed Luminasia,',
    'capitulo#508': 'lamenting bitterly.',
    'capitulo#509': 'Mortals devoured the world she could not birth,',
    'capitulo#510': 'endlessly driven by boundless greed.',
    'capitulo#511': 'She vowed never to craft such a world.',
    'capitulo#512': 'Soon royals Luke and Asch of Lima arrived',
    'capitulo#513': 'alongside their sword instructor Van,',
    'capitulo#514': 'boarding the Van Eltia.',
    'capitulo#515': 'The ship unlocked the ability to touch down',
    'capitulo#516': 'Next destination: Mt. Absoule.',
    'capitulo#517': 'The next destination: Mt. Absoule.',
    'capitulo#518': 'At last, meeting spirits was possible.',
    'capitulo#519': 'To ask spirits about Lazaris, OO set out',
    'capitulo#520': 'seeking answers to world creation.',
    'capitulo#521': 'Leading Emil and Caius, they climbed Absoule.',
    'capitulo#522': 'Trudging through harsh snow and freezing gales,',
    'capitulo#523': 'they encountered a solitary swordsman.',
    'capitulo#524': 'Learning that OO sought spirits, the warrior',
    'capitulo#525': 'drew his blade and attacked.',
    'capitulo#526': 'OO and allies neutralized the swordsman,',
    'capitulo#527': 'sincerely explaining their desire to meet spirits.',
    'capitulo#528': 'Then Celsius, spirit of ice, appeared from mist,',
    'capitulo#529': 'addressing OO as the Descender.',
    'capitulo#530': 'Caius and Emil gasped in sheer astonishment.',
    'capitulo#531': "OO's lack of memories matched ancient lore:",
    'capitulo#532': 'born from the Tree, knowing nothing of worldly ways.',
    'capitulo#533': 'Though Celsius knew little of primordial genesis,',
    'capitulo#534': 'she told of a great calamity sealed away',
    'capitulo#535': 'beneath Star Crystals.',
    'capitulo#536': 'Did that calamity refer to Lazaris?',
    'capitulo#537': 'Richter and Celsius chose to assist the savior,',
    'capitulo#538': 'descending the peak alongside OO and friends.',
    'capitulo#539': 'They walked together.',
    'capitulo#540': 'Returning aboard, news that OO was Descender',
    'capitulo#541': 'spread rapidly, leaving everyone stunned.',
    'capitulo#542': 'Iria noted that OO possessed a power',
    'capitulo#543': 'unlike any ordinary mortal.',
    'capitulo#544': 'Reverting mutated beings to normal form.',
    'capitulo#545': 'That was the true power of the Descender.',
    'capitulo#546': 'While spirits knew little of world genesis,',
    'capitulo#547': 'they knew one entity witnessed the creation.',
    'capitulo#548': 'The witness was not mortal.',
    'capitulo#549': 'That witness was neither human nor spirit.',
    'capitulo#550': 'Learning the tale of genesis from that witness',
    'capitulo#551': 'was the legendary Progenitor of Man.',
    'capitulo#552': 'Long ago, humans existed as immaterial spirits.',
    'capitulo#553': 'Designing physical forms through Soul Alchemy,',
    'capitulo#554': 'they flourished upon the material realm.',
    'capitulo#555': 'Though the Progenitor who knew genesis was gone,',
    'capitulo#556': 'relics left behind still endured somewhere,',
    'capitulo#557': 'such as the fabled Veratropa.',
    'capitulo#558': 'Yet those ruins remained immaterial.',
    'capitulo#559': 'Harold racked brains to materialize them,',
    'capitulo#560': 'accidentally summoning Kyle from another world',
    'capitulo#561': 'in an amusing uproar.',
    'capitulo#562': 'Meanwhile, Eugene and Veigue approached Ange',
    'capitulo#563': 'bringing a deeply urgent request.',
    'capitulo#564': 'Laborers from Hazel Village were captured',
    'capitulo#565': 'by the Urizen Empire.',
    'capitulo#566': 'After mining nearby crystals, they were dragged',
    'capitulo#567': 'to distant mines for forced labor.',
    'capitulo#568': 'While Eugene and Veigue set out to liberate them,',
    'capitulo#569': 'villagers remaining in Hazel could not survive,',
    'capitulo#570': 'so Annie and Tytree departed to help them migrate',
    'capitulo#571': 'to Olta Village, currently under construction.',
    'capitulo#572': 'They coordinated the relocation.',
    'capitulo#573': 'To reach Olta Village, both groups needed',
    'capitulo#574': 'to cross the dangerous Kadaif Desert.',
    'capitulo#575': 'To ensure Hazel villagers crossed safely, OO',
    'capitulo#576': 'took on a critical hunting commission:',
    'capitulo#577': 'locating and slaying the ferocious Tyrannpion,',
    'capitulo#578': 'a deadly menace stalking the desert sands.',
    'capitulo#579': "Through OO's valiant efforts, the beast was felled,",
    'capitulo#580': 'allowing Hazel villagers to reach their new home.',
    'capitulo#581': 'They arrived safely.',
    'capitulo#582': 'Yet Olta Village had only just begun operating.',
    'capitulo#583': 'Countless challenges still lay ahead.',
    'capitulo#584': "To materialize Veratropa, the ancient ruins'",
    'capitulo#585': 'Document was strictly required.',
    'capitulo#586': 'The researchers held their heads in despair',
    'capitulo#587': 'over this seemingly impossible barrier.',
    'capitulo#588': 'Meanwhile, Kanonno shared her sketchbook',
    'capitulo#589': 'with Celsius, showing drawings.',
    'capitulo#590': 'They showed lands never visited yet felt.',
    'capitulo#591': 'She wondered if spirits might recognize',
    'capitulo#592': 'any of the vistas depicted within.',
    'capitulo#593': 'Among numerous sketches, Celsius recognized one:',
    'capitulo#594': 'it depicted the sacred ruins of Veratropa.',
    'capitulo#595': 'Why had Kanonno sketched Veratropa?',
    'capitulo#596': 'Kanonno herself could not fathom the reason.',
    'capitulo#597': "Examining Kanonno's Document, Rita discovered",
    'capitulo#598': 'an extraordinary Document never seen in humans.',
    'capitulo#599': 'Embedded within it was the Document of Veratropa.',
    'capitulo#600': 'It held the missing pattern.',
    'capitulo#601': 'Deploying a Document strains the physical body.',
    'capitulo#602': 'Aware of risks, Kanonno asked Rita to extract it,',
    'capitulo#603': 'securing the Document of Veratropa,',
    'capitulo#604': 'an unexpected discovery.',
    'capitulo#605': 'Thus Veratropa was materialized into reality,',
    'capitulo#606': 'opening the path to mysteries of world genesis.',
    'capitulo#607': 'Stepping into Veratropa, OO explored alongside',
    'capitulo#608': 'scholars Keele and Judith.',
    'capitulo#609': 'To understand Lazaris, they investigated genesis,',
    'capitulo#610': 'groping completely in the dark regarding methods.',
    'capitulo#611': 'They searched carefully.',
    'capitulo#612': 'Hence Keele, versed in ancient texts, and Judith,',
    'capitulo#613': 'able to read memories from relics, came along.',
    'capitulo#614': 'They investigated together.',
    'capitulo#615': 'From four murals inside Veratropa, they learned',
    'capitulo#616': "that Luminasia's World Tree had assimilated",
    'capitulo#617': 'another entire world during genesis.',
    'capitulo#618': 'That other world was none other than Lazaris,',
    'capitulo#619': 'the sealed calamity spoken of by Celsius.',
    'capitulo#620': 'As for what kind of calamity it was, Judith',
    'capitulo#621': 'could only sense that its underlying laws',
    'capitulo#622': 'were entirely incompatible with this realm.',
    'capitulo#623': 'Proceeding onward, OO met Niata Monad,',
    'capitulo#624': 'the witness who beheld the dawn of genesis.',
    'capitulo#625': 'Yet while Niata recounted the birth of worlds,',
    'capitulo#626': 'Lazaris materialized, mercilessly shattering',
    'capitulo#627': 'Niata to pieces.',
    'capitulo#628': 'Raising sky-piercing colossal fangs, Lazaris',
    'capitulo#629': 'vanished into the firmament.',
    'capitulo#630': 'Lazaris targeted this realm of Luminasia.',
    'capitulo#631': 'She sought to create her world, Zirdia,',
    'capitulo#632': 'by usurping the Hall of Life.',
    'capitulo#633': 'The Hall of Life generates mana, serving as heart',
    'capitulo#634': 'and prime Document of the World Tree itself.',
    'capitulo#635': 'Only the World Tree or its Descender avatar',
    'capitulo#636': 'could command and manipulate that sacred space.',
    'capitulo#637': 'Yet OO knew nothing about the Hall of Life.',
    'capitulo#638': 'Memory offered no answers.',
    'capitulo#639': 'If the world were remade, all living beings would',
}
