CAPITULO_4 = {
    'capitulo#960': 'to enable Document transcription of abilities.',
    'capitulo#961': 'However, failure meant bodily dissolution,',
    'capitulo#962': 'making this a dangerous gamble.',
    'capitulo#963': 'This trial relied on advanced machinery.',
    'capitulo#964': 'To complete circuits, the rare mineral',
    'capitulo#965': 'Gibeon was strictly required.',
    'capitulo#966': 'Gibeon was meteoric iron from space.',
    'capitulo#967': 'Years ago a meteorite fell atop Rhubarb,',
    'capitulo#968': 'raising hopes of finding Gibeon there,',
    'capitulo#969': 'so OO and allies climbed the summit.',
    'capitulo#970': 'Reaching the harsh peak, a celestial gift',
    'capitulo#971': 'awaited them: the Gibeon ore.',
    'capitulo#972': 'Promptly, OO and party harvested Gibeon,',
    'capitulo#973': 'pondering this mysterious matter.',
    'capitulo#974': 'This mineral arrived in Luminasia',
    'capitulo#975': 'from some distant forgotten realm.',
    'capitulo#976': 'Across voids and worlds, life supports life,',
    'capitulo#977': 'as Asbel thoughtfully realized.',
    'capitulo#978': 'This brought immense hope to OO,',
    'capitulo#979': 'who longed for coexistence with Lazaris.',
    'capitulo#980': 'Preparations to transcribe the Descender',
    'capitulo#981': 'Document were finalized.',
    'capitulo#982': 'Yet fearing fatal accidents, no candidate',
    'capitulo#983': 'stepped forward to participate.',
    'capitulo#984': 'Then Kanonno volunteered bravely.',
    'capitulo#985': 'Though failure risked death, Kanonno smiled',
    'capitulo#986': 'fearlessly and stepped into the machine.',
    'capitulo#987': "The test began, weaving OO's Document",
    'capitulo#988': "deep into Kanonno's pattern.",
    'capitulo#989': "Kanonno's trembling showed terrible pain.",
    'capitulo#990': 'Agony racked her small frame.',
    'capitulo#991': 'Yet through agony, Kanonno smiled gently,',
    'capitulo#992': "welcoming OO's Document completely.",
    'capitulo#993': 'The experiment ended safely.',
    'capitulo#994': 'Now they needed to verify whether',
    'capitulo#995': 'the transcription succeeded.',
    'capitulo#996': "To test Kanonno's transcribed power,",
    'capitulo#997': 'they headed for Sifno Cave, where',
    'capitulo#998': 'a new spike had sprouted.',
    'capitulo#999': 'If successful, power could spread to all,',
    'capitulo#1000': 'allowing everyone to halt corruption.',
    'capitulo#1001': 'Wars to claim uncorrupted territory',
    'capitulo#1002': 'erupted across lands again.',
    'capitulo#1003': 'Yet sharing this power could unite hearts',
    'capitulo#1004': 'to confront the crisis as one.',
    'capitulo#1005': 'Reaching the fang, corruption was severe.',
    'capitulo#1006': 'They found fallen victims collapsed nearby.',
    'capitulo#1007': 'Kanonno restored the victims and the land,',
    'capitulo#1008': 'proving the experiment a complete success.',
    'capitulo#1009': 'Yet the victims remained terribly frail,',
    'capitulo#1010': 'resting unconscious on the ground.',
    'capitulo#1011': 'Their robes belonged to the cult,',
    'capitulo#1012': 'Servants of the Dawn.',
    'capitulo#1013': 'Carrying the cultists, they returned to ship.',
    'capitulo#1014': 'Soon the cultists woke in the infirmary.',
    'capitulo#1015': 'They had sought contact with Ad Libitum.',
    'capitulo#1016': 'To discover their motives,',
    'capitulo#1017': 'OO and allies visited the medical bay.',
    'capitulo#1018': 'Moved by Ad Libitum battling crisis,',
    'capitulo#1019': 'they wished to assist by providing clues',
    'capitulo#1020': 'regarding the Spiral Gall,',
    'capitulo#1021': 'traveling far to deliver intel.',
    'capitulo#1022': 'When fangs rose, cave-ins trapped them',
    'capitulo#1023': 'within Sifno Cave.',
    'capitulo#1024': 'The clue was a stump where Spiral Gall',
    'capitulo#1025': 'once flourished in the past.',
    'capitulo#1026': 'Though decayed, faint Document data might',
    'capitulo#1027': 'remain, yielding a vital breakthrough.',
    'capitulo#1028': "Through Rita's formula, Descender power",
    'capitulo#1029': 'transferred through Kanonno to the cultists.',
    'capitulo#1030': 'Merely touching others would now share',
    'capitulo#1031': 'restorative power across the world.',
    'capitulo#1032': 'Partial Document was obtained from the stump,',
    'capitulo#1033': 'yet this fungus reproduced asexually,',
    'capitulo#1034': 'leaving no modern descendants behind.',
    'capitulo#1035': 'The approach from before would not work.',
    'capitulo#1036': 'Then Kanonno remembered:',
    'capitulo#1037': 'life eaten as food is passed down.',
    'capitulo#1038': 'Will researched ancient beasts alive',
    'capitulo#1039': 'before Spiral Gall went extinct.',
    'capitulo#1040': 'Records showed the Cavelex consumed it',
    'capitulo#1041': 'as part of its regular diet.',
    'capitulo#1042': 'The Cavelex might hold its Document.',
    'capitulo#1043': 'Hope returned once more.',
    'capitulo#1044': 'Tracking the Cavelex that fed on the fungus,',
    'capitulo#1045': 'OO traversed Confeito Great Forest.',
    'capitulo#1046': 'Could food Documents truly endure in predators?',
    'capitulo#1047': 'Uncertainty lingered in their minds.',
    'capitulo#1048': 'Yet no other option remained.',
    'capitulo#1049': 'Neutralizing the Cavelex, OO obtained',
    'capitulo#1050': 'the coveted Document of Spiral Gall.',
    'capitulo#1051': 'All three components were finally assembled:',
    'capitulo#1052': 'Salt Crystal, Dragonfly Grass, Spiral Gall.',
    'capitulo#1053': 'Synthesized together, they formed the seal',
    'capitulo#1054': 'to imprison Zirdia and Lazaris.',
    'capitulo#1055': 'Meanwhile, cultists spread purification,',
    'capitulo#1056': 'uniting people in solidarity worldwide.',
    'capitulo#1057': 'From a single Descender, hope ignited',
    'capitulo#1058': 'across the entire globe.',
    'capitulo#1059': 'The synthetic crystal Document was infused',
    'capitulo#1060': 'into mana streams toward the Tree.',
    'capitulo#1061': 'Thus the Sealing Dimension would manifest.',
    'capitulo#1062': 'Once formed, Lazaris and Zirdia would',
    'capitulo#1063': 'be channeled into the dimensional prison.',
    'capitulo#1064': 'Though technical for OO to grasp,',
    'capitulo#1065': 'trusting Harold and Rita, they awaited final',
    'capitulo#1066': 'preparations to seal Zirdia at last.',
    'capitulo#1067': 'Near was the day OO must return to the Tree...',
    'capitulo#1068': 'Another Vortex in holy ground Langrees.',
    'capitulo#1069': 'To channel the seal into the World Tree,',
    'capitulo#1070': 'OO, Rita, and Kanonno departed the ship.',
    'capitulo#1071': 'They journeyed forth.',
    'capitulo#1072': 'Sensing farewell, Kanonno timidly asked OO',
    'capitulo#1073': 'if completion meant returning to the Tree',
    'capitulo#1074': 'forevermore.',
    'capitulo#1075': 'Yet OO harbored no such desire.',
    'capitulo#1076': 'Countless tasks still remained unfinished.',
    'capitulo#1077': 'Even after sealing Lazaris, people across',
    'capitulo#1078': 'the world still needed help.',
    'capitulo#1079': 'Departing alone was unthinkable.',
    'capitulo#1080': 'Finally, the Sealing Dimension unfolded.',
    'capitulo#1081': 'Three fangs dissolved into the seal.',
    'capitulo#1082': 'Yet joy was brief; the seal shattered,',
    'capitulo#1083': 'and a massive new fang pierced the Tree.',
    'capitulo#1084': 'Feeling the shared agony, OO collapsed.',
    'capitulo#1085': 'When OO awakened, they were back on ship.',
    'capitulo#1086': "Corruption spread, warping the Tree's laws.",
    'capitulo#1087': 'Time was running out.',
    'capitulo#1088': 'They wished to reach the Tree immediately,',
    'capitulo#1089': 'yet entering warped space was suicidal.',
    'capitulo#1090': 'Niata promised a way forward, yet',
    'capitulo#1091': 'preparations required precious time.',
    'capitulo#1092': 'Corruption altered reality continuously.',
    'capitulo#1093': 'Finally, through Rita and Niata, entry',
    'capitulo#1094': 'into Elan Vital within the Tree opened.',
    'capitulo#1095': 'What could be accomplished inside?',
    'capitulo#1096': 'What awaited upon meeting Lazaris?',
    'capitulo#1097': 'Heavy anxieties filled every companion.',
    'capitulo#1098': 'To the fearless and resolute Descender,',
    'capitulo#1099': 'they entrusted the future of the world.',
    'capitulo#1100': 'Then Ange issued the ultimate quest...',
    'capitulo#1101': "Ange's quest called to breach Elan Vital",
    'capitulo#1102': 'and defend Luminasia from ruin.',
    'capitulo#1103': 'Before the Hall of Life at the core,',
    'capitulo#1104': 'Lazaris stood waiting for OO.',
    'capitulo#1105': 'Lazaris sought to seize the Hall of Life,',
    'capitulo#1106': 'stripping Luminasia of creation itself.',
    'capitulo#1107': 'Lazaris viewed creation as selfish sin.',
    'capitulo#1108': "Despite OO's pleas to live together,",
    'capitulo#1109': 'Lazaris chose bitter warfare.',
    'capitulo#1110': 'Though weakened, Lazaris fought fiercely.',
    'capitulo#1111': 'Then unbirthed souls of Zirdia manifested',
    'capitulo#1112': 'as a protective Document around Lazaris.',
    'capitulo#1113': 'Souls wishing to defend Lazaris clashed,',
    'capitulo#1114': 'resisting her desire to spare them.',
    'capitulo#1115': 'Colliding wills erupted into chaotic fury.',
    'capitulo#1116': 'Dark vortex surged.',
    'capitulo#1117': 'OO challenged Lazaris with all conviction.',
    'capitulo#1118': 'wagering the future of both worlds.',
    'capitulo#1119': "Lazaris's power exhausted, diffusing outward.",
    'capitulo#1120': 'Lazaris accepted inevitable defeat.',
    'capitulo#1121': 'Mourning the unborn souls of Zirdia,',
    'capitulo#1122': 'she dissolved into gentle luminescence.',
    'capitulo#1123': 'Gathering the gentle light of Lazaris, OO',
    'capitulo#1124': 'walked peacefully toward the Hall of Life.',
    'capitulo#1125': 'Together, to create a new tomorrow.',
}
