CAPITULO_3 = {
    'capitulo#640': 'perish or twist into hideous alien abominations.',
    'capitulo#641': 'or become denizens of Zirdia.',
    'capitulo#642': 'Lazaris could not easily control it,',
    'capitulo#643': 'risking mutual annihilation at worst.',
    'capitulo#644': 'Fangs manifested by Lazaris corroded',
    'capitulo#645': "Luminasia's Document, rewriting reality.",
    'capitulo#646': 'Furthermore, Lazaris and her realm, Zirdia,',
    'capitulo#647': 'were sealed within a dimensional prison',
    'capitulo#648': 'fashioned from Star Crystals.',
    'capitulo#649': 'To reseal Lazaris, crystals were vital,',
    'capitulo#650': 'yet overmining left the world depleted.',
    'capitulo#651': 'Niata revealed three Document materials',
    'capitulo#652': 'could forge a substitute crystal matrix',
    'capitulo#653': 'via Soul Alchemy, requiring retrieval',
    'capitulo#654': 'of the rare Salt Crystal.',
    'capitulo#655': 'Salt Crystal was needed for sealing,',
    'capitulo#656': 'along with two rare organic components.',
    'capitulo#657': 'To gather Salt Crystal, OO went',
    'capitulo#658': 'into the depths of Brownie Mine.',
    'capitulo#659': 'Suddenly, a brute blocked OO and friends,',
    'capitulo#660': 'barring their forward path.',
    'capitulo#661': 'It was Barbatos, infamous as a warrior',
    'capitulo#662': 'who attacked any strong opponent.',
    'capitulo#663': 'He had been hurled to Luminasia',
    'capitulo#664': 'along with Kyle from another world.',
    'capitulo#665': 'OO and Sheena stood watchful,',
    'capitulo#666': 'yet reckless Kyle charged ahead.',
    'capitulo#667': "Through OO's strength, they drove Barbatos",
    'capitulo#668': 'away, leaving reckless Kyle',
    'capitulo#669': "facing Sheena's stern reprimand.",
    'capitulo#670': 'Securing the precious Salt Crystal,',
    'capitulo#671': "OO's party returned to the ship.",
    'capitulo#672': 'The remaining two sealing items were found.',
    'capitulo#673': 'Bell-Dragonfly Grass and Spiral Gall.',
    'capitulo#674': "Both appeared in Kanonno's sketches,",
    'capitulo#675': 'matching lore provided by Niata,',
    'capitulo#676': 'as Judith discerned.',
    'capitulo#677': 'Yet both species were long extinct.',
    'capitulo#678': 'Why she envisioned unseen landscapes',
    'capitulo#679': 'weighed heavily on Kanonno.',
    'capitulo#680': 'OO was troubled by doubts as well.',
    'capitulo#681': 'Zirdia was destined to wither alone.',
    'capitulo#682': 'The tragic world of Lazaris.',
    'capitulo#683': 'Why did the Tree assimilate it?',
    'capitulo#684': 'Why absorb a realm that brought ruin',
    'capitulo#685': 'and seal it away?',
    'capitulo#686': 'Kanonno and OO sought',
    'capitulo#687': "to understand the Tree's true intent.",
    'capitulo#688': 'Judith and Rocks shared curious tales',
    'capitulo#689': 'regarding Kanonno.',
    'capitulo#690': 'Landscapes and Documents seen by Kanonno alone.',
    'capitulo#691': 'Kanonno held a profound secret.',
    'capitulo#692': 'Jade requested an inspection of the fangs.',
    'capitulo#693': 'He submitted a quest.',
    'capitulo#694': 'To investigate the fangs raised by Lazaris,',
    'capitulo#695': "they utilized a Copyist's Rod to extract",
    'capitulo#696': "the fang's Document directly.",
    'capitulo#697': 'Accompanied by Judas and Lloyd, OO headed',
    'capitulo#698': 'for Altata Volcano where the fang sprouted.',
    'capitulo#699': 'Deeper in, beasts twisted unnaturally.',
    'capitulo#700': 'Mutations spread everywhere.',
    'capitulo#701': "Zirdia's alien Document seemed flowing",
    'capitulo#702': 'outward through the colossal fang.',
    'capitulo#703': 'Reaching the fang, they were breathless',
    'capitulo#704': 'at the bizarrely beautiful vista.',
    'capitulo#705': "Sampling the fang's Document, OO gazed",
    'capitulo#706': 'at open palms and unleashed rainbow light.',
    'capitulo#707': 'The corrupted surroundings were restored.',
    'capitulo#708': 'Yet the fang itself resisted even',
    'capitulo#709': "the Descender's radiant power.",
    'capitulo#710': 'Refugees from Hazel Village and Joan',
    'capitulo#711': 'worked alongside settlers in Olta Village,',
    'capitulo#712': 'sending letters to Ange.',
    'capitulo#713': 'Yet the news was not entirely bright.',
    'capitulo#714': 'Diverse backgrounds caused friction',
    'capitulo#715': 'and clashes of cultural values.',
    'capitulo#716': 'Rocks suggested guiding through affirmation,',
    'capitulo#717': 'supporting Ange warmly.',
    'capitulo#718': "Analysis of the fang's Document concluded.",
    'capitulo#719': 'It revealed the fang acted as a conduit',
    'capitulo#720': 'pumping Zirdian data into Luminasia.',
    'capitulo#721': "This matched Niata's earlier findings.",
    'capitulo#722': 'Corruption radiated from around the fang,',
    'capitulo#723': 'spreading continuously as long as it stood.',
    'capitulo#724': 'Though OO possessed restorative powers,',
    'capitulo#725': 'mortal limits loomed.',
    'capitulo#726': 'To halt corruption, the crystal seal',
    'capitulo#727': 'had to be constructed immediately.',
    'capitulo#728': 'Two essential ingredients remained.',
    'capitulo#729': 'Will suggested retrieving a fossil',
    'capitulo#730': 'of Bell-Dragonfly Grass.',
    'capitulo#731': 'To retrieve this ancient fossil,',
    'capitulo#732': 'OO set out for Almanac Ruins.',
    'capitulo#733': 'Even a fossil might yield faint traces',
    'capitulo#734': 'of the original Document.',
    'capitulo#735': "The fossil rested in the ruins' sanctum,",
    'capitulo#736': 'the Hall of the Ode to Life.',
    'capitulo#737': 'Ruca felt deeply hesitant to disturb',
    'capitulo#738': 'a designated world heritage site.',
    'capitulo#739': 'Delivered to the lab, analysis began.',
    'capitulo#740': 'Meanwhile, social friction in Olta Village',
    'capitulo#741': "eased through Rocks's thoughtful proposal.",
    'capitulo#742': 'Ange and Rocks rejoiced gladly.',
    'capitulo#743': "Ad Libitum's long-cherished dream advanced.",
    'capitulo#744': 'Estelle and Natalia celebrated Olta Village,',
    'capitulo#745': 'confident that distinct nations could unite',
    'capitulo#746': 'in mutual harmony and peace.',
    'capitulo#747': 'Meanwhile, Kanonno sought answers for why',
    'capitulo#748': 'she envisioned unseen vistas and wrote',
    'capitulo#749': 'ancient scripts unconsciously.',
    'capitulo#750': 'Judith thought Niata might comprehend.',
    'capitulo#751': 'Niata was the sage who witnessed genesis',
    'capitulo#752': 'and surveyed countless different realms.',
    'capitulo#753': 'Kanonno longed to consult Niata directly.',
    'capitulo#754': 'Even if communication seemed difficult,',
    'capitulo#755': 'Kanonno pleaded to journey to Veratropa.',
    'capitulo#756': 'Escorting Kanonno to Veratropa,',
    'capitulo#757': 'OO ventured into the ancient ruins.',
    'capitulo#758': 'En route, OO recalled words from Judith.',
    'capitulo#759': 'Reflections on the past.',
    'capitulo#760': 'Kanonno resembled the ancient Descender',
    'capitulo#761': 'whom Niata had served, sharing a name.',
    'capitulo#762': 'Reaching Niata and calling out, the shattered',
    'capitulo#763': 'relic began self-repairing to wholeness.',
    'capitulo#764': 'Niata rejoiced at reuniting with Kanonno.',
    'capitulo#765': 'As Kanonno stood bewildered, OO shared',
    'capitulo#766': 'the lore learned from Judith.',
    'capitulo#767': 'Though confused, Kanonno presented',
    'capitulo#768': 'her sketchbook to Niata.',
    'capitulo#769': 'Niata recognized that the painted scenes',
    'capitulo#770': 'were realms Niata had visited long ago.',
    'capitulo#771': 'Niata deduced that Kanonno inherited factors',
    'capitulo#772': 'from a vanished primeval world.',
    'capitulo#773': 'As they spoke, footsteps approached rapidly.',
    'capitulo#774': 'The voice belonged to Rocks.',
    'capitulo#775': 'The Van Eltia lost altitude and plunged.',
    'capitulo#776': 'OO and allies were stranded on Veratropa.',
    'capitulo#777': 'Isolation threatened the group.',
    'capitulo#778': 'Yet Niata enveloped OO and allies in light,',
    'capitulo#779': 'returning them safely to the vessel.',
    'capitulo#780': "The ship recovered under Niata's counsel.",
    'capitulo#781': 'Crucially, they discovered the Van Eltia',
    'capitulo#782': 'ran on a semi-perpetual engine instead',
    'capitulo#783': 'of consuming Star Crystals.',
    'capitulo#784': 'This discovery offered a beacon of hope',
    'capitulo#785': 'for resource-depleted Luminasia.',
    'capitulo#786': 'Another breakthrough soon followed.',
    'capitulo#787': 'A new Ring Spot was located.',
    'capitulo#788': "To amplify the Sorcerer's Ring,",
    'capitulo#789': 'OO headed for the Kadaif Desert.',
    'capitulo#790': 'The Ring Spot lay within the Red Oasis,',
    'capitulo#791': 'a spring rich in iron minerals.',
    'capitulo#792': 'Spring water gushed out red.',
    'capitulo#793': 'Finding the spot, OO empowered the ring',
    'capitulo#794': 'and returned to the Van Eltia.',
    'capitulo#795': 'Meanwhile, analysis of the fossil revealed',
    'capitulo#796': 'mostly mineralized data, yielding almost',
    'capitulo#797': 'no original organic Document.',
    'capitulo#798': 'Rita shared this obstacle with Niata.',
    'capitulo#799': 'Niata noted environmental shifts altered',
    'capitulo#800': 'species through evolution and hybridization,',
    'capitulo#801': 'feeling deep disappointment.',
    'capitulo#802': 'Yet this sparked an epiphany for Rita:',
    'capitulo#803': 'gathering Documents from descendant species',
    'capitulo#804': 'to reconstruct the ancestral plant.',
    'capitulo#805': 'With roughly 2,000 descendant species,',
    'capitulo#806': 'allies and global guilds assisted',
    'capitulo#807': 'in harvesting safer varieties.',
    'capitulo#808': 'Assistance was rallied worldwide.',
    'capitulo#809': 'Ad Libitum targeted perilous specimens',
    'capitulo#810': 'obtainable only by elite members.',
    'capitulo#811': 'Starting with the Oil Tree on Mt. Absoule,',
    'capitulo#812': 'OO set out with Veigue and Spada.',
    'capitulo#813': 'En route, a faint cry carried on the wind.',
    'capitulo#814': "it was Claire's desperate scream.",
    'capitulo#815': 'Rushing forward, they found Saleh holding',
    'capitulo#816': 'Claire captive as a hostage.',
    'capitulo#817': 'Spurred by grudge against Ad Libitum, Saleh',
    'capitulo#818': 'intended to lure Veigue into a trap,',
    'capitulo#819': 'yet Veigue arrived coincidentally.',
    'capitulo#820': 'Saleh attacked with immense confidence,',
    'capitulo#821': "yet fell before OO's guild allies.",
    'capitulo#822': 'Ignoring Saleh, Veigue collected',
    'capitulo#823': "the Oil Tree's Document,",
    'capitulo#824': 'and OO escorted Claire safely back.',
    'capitulo#825': 'Aboard the ship, descendant specimens',
    'capitulo#826': 'arrived steadily from across lands.',
    'capitulo#827': 'Data was prepared for the next target.',
    'capitulo#828': 'Plans advanced smoothly.',
    'capitulo#829': 'The next objective was a rare flower',
    'capitulo#830': 'capable of gliding smoothly over water.',
    'capitulo#831': 'Briefings were finalized.',
    'capitulo#832': 'Ange registered it as a quest,',
    'capitulo#833': 'awaiting suitable candidates.',
    'capitulo#834': 'This plant was the Yulung Tree, located',
    'capitulo#835': 'deep within Sifno Cave.',
    'capitulo#836': 'Accepting the extraction quest, OO',
    'capitulo#837': 'departed alongside Natalia and Asch.',
    'capitulo#838': 'They harvested the Document of this tree,',
    'capitulo#839': 'which adapted without crowding rivals.',
    'capitulo#840': 'Seeing this resilient tree, OO realized',
    'capitulo#841': 'peoples and realms could evolve in harmony,',
    'capitulo#842': 'returning with renewed hope.',
    'capitulo#843': 'More specimens arrived aboard the vessel.',
    'capitulo#844': 'Together, Ad Libitum processed Documents,',
    'capitulo#845': 'extracting essential data diligently.',
    'capitulo#846': 'Watching everyone unite against hardship,',
    'capitulo#847': 'Ange felt profoundly grateful for founding',
    'capitulo#848': 'this extraordinary guild.',
    'capitulo#849': 'Facing adversity, Ad Libitum pushed onward.',
    'capitulo#850': 'Observing this, Niata mentioned Ad Libitum',
    'capitulo#851': 'also existed in the parallel world Granide.',
    'capitulo#852': 'The Van Eltia and its companions existed',
    'capitulo#853': 'within the parallel realm of Granide.',
    'capitulo#854': 'Kanonno pondered why worlds were born',
    'capitulo#855': 'and why memories endured across time,',
    'capitulo#856': 'lost in deep thought.',
    'capitulo#857': 'Meanwhile, regional wars ceased worldwide.',
    'capitulo#858': "The emergence of Zirdia's colossal fangs",
    'capitulo#859': 'convinced rulers war was futile.',
    'capitulo#860': 'Natalia noted that shared peril taught',
    'capitulo#861': 'mankind to clasp hands across borders.',
    'capitulo#862': 'She spoke with deep conviction.',
    'capitulo#863': 'With this awareness, nations could unite,',
    'capitulo#864': 'fostering a truly integrated world.',
    'capitulo#865': 'A civilization where all share resources',
    'capitulo#866': 'equitably with one another.',
    'capitulo#867': 'Specimen collection reached its finale as OO',
    'capitulo#868': 'headed to Kadaif Desert with Stahn and Loni',
    'capitulo#869': 'to harvest the Wandering Grass.',
    'capitulo#870': 'Entering the grove, harsh air irritated',
    'capitulo#871': 'their eyes and parched their throats.',
    'capitulo#872': 'Venturing deeper, Lazaris stood waiting.',
    'capitulo#873': 'She was reshaping the environment',
    'capitulo#874': 'to sustain life from her lost world.',
    'capitulo#875': 'Among the mutant beasts stood former humans.',
    'capitulo#876': 'When OO approached to restore them,',
    'capitulo#877': 'they shrank back toward Lazaris in fear.',
    'capitulo#878': 'refusing to return to human form.',
    'capitulo#879': 'Despairing of Luminasia, those souls',
    'capitulo#880': 'chose mutation willingly.',
    'capitulo#881': 'Though they pleaded, Lazaris departed,',
    'capitulo#882': 'leaving words echoing in vain.',
    'capitulo#883': 'Purifying the blighted soil, OO hung',
    'capitulo#884': 'a head in bitter grief.',
    'capitulo#885': 'Returning with the grass Document, news came',
    'capitulo#886': 'that two more fangs had sprouted.',
    'capitulo#887': 'Unless halted quickly, corruption would',
    'capitulo#888': 'accelerate drastically.',
    'capitulo#889': 'Fortunately, the grass Document allowed',
    'capitulo#890': 'reconstruction of Bell-Dragonfly Grass.',
    'capitulo#891': 'Only the Spiral Gall remained to locate.',
    'capitulo#892': 'Could a surviving specimen truly exist',
    'capitulo#893': 'somewhere in the world?',
    'capitulo#894': 'Zirdia was an unborn twin realm within Luminasia.',
    'capitulo#895': 'Different worlds with contrasting laws.',
    'capitulo#896': 'Witnessing genesis, Niata reflected on history.',
    'capitulo#897': 'Absorbing Zirdia triggered upheaval',
    'capitulo#898': 'beyond all human description.',
    'capitulo#899': 'Without the seal, the world could not',
    'capitulo#900': 'have sustained its existence.',
    'capitulo#901': 'Had the seal shattered completely, primordial',
    'capitulo#902': 'upheaval would have recurred instantly.',
    'capitulo#903': 'Yet no catastrophic collapse had occurred.',
    'capitulo#904': 'Perhaps the World Tree gained stability',
    'capitulo#905': 'over eons, prompting endless speculation.',
    'capitulo#906': 'The party sought the true intentions',
    'capitulo#907': 'OO and companions sought the true motive.',
    'capitulo#908': 'Kanonno learned from Rocks that she painted',
    'capitulo#909': 'her parents without knowing.',
    'capitulo#910': 'To uncover memories hidden within herself,',
    'capitulo#911': 'Kanonno asked to deploy her Document.',
    'capitulo#912': 'Yet detailed deployment carried grave risk.',
    'capitulo#913': 'drawing immediate objections from all.',
    'capitulo#914': 'Niata pondered and proposed an alternative.',
    'capitulo#915': 'Besides deployment, one other method',
    'capitulo#916': 'could access past memories.',
    'capitulo#917': 'Though still perilous, it was far safer.',
    'capitulo#918': 'It required visiting the Vortex where',
    'capitulo#919': 'World Tree mana churned intensely.',
    'capitulo#920': "To uncover Kanonno's gifts, OO and Kanonno",
    'capitulo#921': 'journeyed to holy ground Langrees.',
    'capitulo#922': 'At the Vortex where potent mana swirled,',
    'capitulo#923': "OO dove deep into Kanonno's consciousness.",
    'capitulo#924': 'The mental dive commenced.',
    'capitulo#925': 'Tracing paths of memory through worlds,',
    'capitulo#926': 'they encountered Original Kanonno, embodiment',
    'capitulo#927': 'of the primeval World Tree itself.',
    'capitulo#928': 'Original Kanonno revealed that Luminasia,',
    'capitulo#929': 'and Zirdia were siblings of shared root.',
    'capitulo#930': 'The Tree sealed Zirdia to reshape Luminasia',
    'capitulo#931': 'until both realms could harmoniously coexist.',
    'capitulo#932': 'Such was the primordial design.',
    'capitulo#933': 'Star Crystals acted both as a firm seal,',
    'capitulo#934': 'and a nurturing cradle for Zirdia.',
    'capitulo#935': 'So both could aid each other in distant days.',
    'capitulo#936': 'To create tomorrow together...',
    'capitulo#937': 'Yet for now, Lazaris had to be sealed.',
    'capitulo#938': 'The seal remained imperative.',
    'capitulo#939': 'Their conflicting laws were too disparate',
    'capitulo#940': 'for mutual survival at present.',
    'capitulo#941': 'Bathed in dense mana, Kanonno felt discord',
    'capitulo#942': 'between body and spirit even back on ship.',
    'capitulo#943': 'Sitting for a meal, Kanonno perceived',
    'capitulo#944': 'Documents glowing within companions.',
    'capitulo#945': 'Not just mortals, but food possessed Documents.',
    'capitulo#946': "The food's Document integrated inside",
    'capitulo#947': 'those partaking of nourishment.',
    'capitulo#948': 'Documents were life, and life sustained life.',
    'capitulo#949': 'This proved a profound realization.',
    'capitulo#950': 'Soon, the grass Document was completed.',
    'capitulo#951': 'Yet celebration was premature.',
    'capitulo#952': 'Sprouting fangs hastened world corruption.',
    'capitulo#953': 'Nations resumed fighting over dwindling soil.',
    'capitulo#954': 'Fragile unity shattered before sheer panic.',
    'capitulo#955': 'Terror triumphed over reason.',
    'capitulo#956': 'Even a Descender could not destroy fangs,',
    'capitulo#957': 'though corruption could be cleansed.',
    'capitulo#958': 'Sophie wished everyone held that power.',
    'capitulo#959': "Inspired by Sophie's words, Harold set out",
}
