import json, re
from val_check import nomes_proprios, CAUDA

def build_val01():
    d = json.load(open('dados/item_equip_shrink/VAL-01.json', encoding='utf-8'))
    itens = d['itens']
    
    custom_map = {
        'valuables#910': 'Secret arte: follows dual slashes by slamming the ground with shockwaves.',
        'valuables#1028': 'Arcane arte: slashes foes skyward with spinning impacts and flashing thrusts.',
        'valuables#1560': 'Where God resides, what shatters is person. In other words, Me: Arcane Arte.',
        'valuables#227': 'A key to contact other worlds. It seems to have lost its magic power.',
        'valuables#783': 'Arcane arte: whirlwinds vortex from thrusting a spear into the ground.',
        'valuables#87': 'A letter torn to shreds. The writing is illegible, but the grudge is real.',
        'valuables#110': 'Paper that breeds money. In a sense, the most terrifying monster of all.',
        'valuables#1934': 'Infinite dagger arcane arte that restores inorganic matter to proper form.',
        'valuables#147': 'Protects wearer from splattering water and oil with divine power. Detachable.',
        'valuables#189': 'Hot spring egg made in an active volcano at great risk. Reasonably tasty.',
        'valuables#201': 'Mirror surface bears an eye pattern scratched into it by previous owner.',
        'valuables#763': 'Arcane arte: impales enemies at high speed, drawing into aerial slashes.',
        'valuables#1556': 'Secret arte: impales foes with freezing spears, thrusting upon landing.',
        'valuables#224': 'Key unlocking the door to the sealed land. Chipped and unusable.',
        'valuables#521': 'Fire arte: scalding orbs detonate on enemies as if with a will of their own.',
        'valuables#165': 'Afterword calls this the definitive edition, but a sequel ships this summer.',
        'valuables#263': 'A jewel left in a room on the Van Eltia for a long time for some reason.',
        'valuables#842': 'Arcane arte: sweeps foes with flaming fists and showers them with slashes.',
        'valuables#928': 'Arcane arte: closes in with Demon Flame Slash and Demon Flame Barrage.',
        'valuables#945': 'Arcane arte: follows Crouching Dragon Flash with two vacuum strikes in air.',
        'valuables#953': 'Arcane arte: high-speed slashes that cannot be tracked by ordinary eyes.',
        'valuables#960': 'Arcane arte: two-stage thrust with ability to slip behind the enemy.',
        'valuables#1558': 'Explosive arcane arte: explicitly slams fighting spirit into enemies.',
        'valuables#793': 'Arcane arte: launches foes high, impales with a spear, and slams them down.',
        'valuables#1281': 'Arcane arte: launches from thrusts, chasing with Tempest and Demon Fang.',
        'valuables#824': 'Secret arte: draws enemies with combo strikes coiling like water snakes.',
        'valuables#1165': 'Arcane arte: enters enemy pocket and slashes heavily, knocking them down.',
        'valuables#1287': 'Secret arte: slashes up with Crescent Slash, chasing foes with Tempest.',
        'valuables#1696': 'Leaps and fires arrows that detonate when enemies approach.',
        'valuables#186': 'A scrumptious dish. So delicious that a single bite brings tears.',
        'valuables#606': 'Arcane arte: draws foes to a spinning slash, slamming with fighting spirit.',
        'valuables#1285': 'Attacks consecutively from a clearing slash into an upward slash.',
        'valuables#1594': 'Arcane arte: dives in, fires water pressure shots, and creates distance.',
        'valuables#136': 'Blowing it creates a shockwave shattering windows in a 100m radius.',
        'valuables#471': 'Arte: releases frozen energy in the earth, striking with an ice arrow.',
        'valuables#602': 'Secret arte: executes high-speed spin slashes, juggling foes in the air.',
        'valuables#908': 'Thrusts sword into ground, summoning rock lances with shockwaves.',
        'valuables#1352': 'Arcane arte: amidst a flash, does unmentionable things to neighboring wives.',
        'valuables#1839': 'Arcane arte: raging flames turn to dragons, enveloping self to slay foes.',
        'valuables#745': 'Arcane arte: thrusts foes skyward, cloaks in flame, dives, and knocks down.',
        'valuables#795': 'Arcane arte: launches foes with lightning, then tosses minerals to follow.',
        'valuables#904': 'Delivers dual slashes followed by a reverse roundhouse kick.',
        'valuables#916': 'Knocks down foes by releasing fighting spirit into them.',
        'valuables#1216': 'Arcane arte: attacks surrounding foes with chakrams while spinning.',
        'valuables#1748': 'Slices enemies as if dancing through the heavens.',
        'valuables#1758': 'Slashes foes like a fluttering swallow, kicking them up at the end.',
        'valuables#1890': 'Arcane arte: launches foes with combos, transitioning to sheathed stance.',
        'valuables#107': 'The writing spaces are stark white; looking at them fills one with ennui.',
        'valuables#113': 'Used to illuminate dark places. Being oil is no excuse for weird things.',
        'valuables#124': 'Slime extracted from a Polwiggle. Used in medicine and cosmetics.',
        'valuables#741': 'Arcane arte: closes instantly, striking repeatedly and launching foes.',
        'valuables#789': 'Arcane arte: follows Roaring Spear with shockwaves front and back.',
        'valuables#890': 'Slams hammer into enemies with high stun chance.',
        'valuables#971': 'Deploys a barrier blowing enemies away while slightly healing allies.',
        'valuables#72': 'Recipe for "Commonly Known as Delicious-Delicious" that Coda craves.',
        'valuables#98': 'Favorite item of an unfortunate girl. She is alive; no curse.',
        'valuables#133': 'As one grows up, contents become plentiful, gradually becoming a chore.',
        'valuables#198': 'The kind of ordinary thing you realize was happiness only after losing it all.',
        'valuables#1624': 'Arcane arte: calls lightning from ground to attack after Shadow Run Blast.',
        'valuables#92': 'Rope meant for luggage, but liked by those who enjoy being tied up.',
        'valuables#127': 'Doctors use it to hear heartbeats. If pointed at you, you must undress.',
        'valuables#139': 'Comes with a grandiose note saying, "The board is the entire world".',
        'valuables#159': 'Belonged to a woman who met a mishap. She bought a replacement.',
        'valuables#301': 'Arte: restores a moderate amount of HP to all allies (in battle).',
        'valuables#645': 'Arcane arte: knocks foes down with a kick, striking with lightning.',
        'valuables#739': 'Arcane arte: launches foes into air, impaling with an ice spear.',
        'valuables#761': 'Arcane arte: launches foes with kicks, smashing down with flaming fists.',
        'valuables#785': 'Arcane arte: delivers thrusts and charges forward with a spear.',
        'valuables#844': 'Arcane arte: blows foes away with a spin kick, finishing with fire.',
        'valuables#848': 'Arcane arte: godspeed thrusts stir up gusts to blow enemies away.',
        'valuables#941': 'Arcane arte: knocks foes down with a sliding kick, striking lightning.',
        'valuables#988': 'Arcane arte: follows three thrusts with a heavy leaping thrust.',
        'valuables#990': 'Arcane arte: follows three thrusts with a diving thrust from air.',
        'valuables#1008': 'Arcane arte: two-stage slashes from Crescent Flash, up and down.',
        'valuables#1026': 'Arcane arte: draws enemies to slashes, striking with flashing thrusts.',
        'valuables#1196': 'Space-time sword arcane arte: shreds enemies with intense fighting spirit.',
        'valuables#1214': 'Arcane arte: spins chakrams at high speed, striking surrounding enemies.',
        'valuables#1247': 'Arcane arte: launches foes skyward, striking with a downward slash.',
        'valuables#1275': 'Arcane arte: strikes with thrusts, launching skyward and kicking down.',
        'valuables#1475': 'Calls a rock spear beneath enemy feet to launch them into the air.',
        'valuables#1479': 'Arte: fires arrows of light piercing enemies in a straight line.',
        'valuables#1733': 'Arcane arte: slashes foes skyward, following with an aerial finish.',
        'valuables#118': 'Many women drink this as a sleep aid to end the day as themselves.',
        'valuables#180': 'In exchange for vacation memories, can be wielded as a lethal weapon.',
        'valuables#204': 'A charred doll found in a dense forest. Its eyeballs have been gouged out.',
        'valuables#612': 'Arcane arte: closes in with a sliding kick, launching foes with a dive kick.',
        'valuables#767': 'Arcane arte: launches foes with thrusts, cloaks in flame, and dives to attack.',
        'valuables#775': 'Arcane arte: launches foes skyward with kicks, following with a diving thrust.',
        'valuables#777': 'Arcane arte: launches foes skyward with kicks, following with an aerial kick.',
        'valuables#822': 'Secret arte: draws enemies with water whip, following with heavy slashes.',
        'valuables#826': 'Secret arte: draws enemies with water whip, slamming them to the ground.',
        'valuables#846': 'Arcane arte: slashes foes with flaming fists and kicks them down.',
        'valuables#887': 'Arcane arte: launches foes skyward, follows with thrusts, and knocks down.',
        'valuables#906': 'Delivers dual slashes followed by a high-speed roundhouse kick.',
        'valuables#2261': 'Title for one who knows the world\'s unexplored regions inside and out.',
        'valuables#101': 'A party gag item, but getting a laugh with it is considered a feat.',
        'valuables#174': 'Extremely fragile; putting weight on it shatters it to tiny pieces.',
        'valuables#195': 'Horrifying item you cannot escape. Beware, as it strikes suddenly.',
        'valuables#207': 'Portrait of a child. Face is blacked out, but the eyes can be seen.',
        'valuables#649': 'Arcane arte: knocks foes down with a sliding kick, striking with lightning.',
        'valuables#747': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
        'valuables#765': 'Arcane arte: strikes foes with a spear, spins at high speed, and blasts away.',
        'valuables#787': 'Arcane arte: follows Flying Ruin Spear by conjuring tornadoes.',
        'valuables#930': 'Arcane arte: closes in, unleashes kicks, and strikes with shockwaves.',
        'valuables#937': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
        'valuables#943': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
        'valuables#955': 'Arcane arte: closes in with a thrust, jumps into air, and kicks foes down.',
        'valuables#957': 'Arcane arte: launches foes into air, follows with slashes, and knocks down.',
        'valuables#992': 'Arcane arte: follows three thrusts with a heavy downward slash.',
        'valuables#1032': 'Arcane arte: delivers thrusts at high speed, finishing with a jump strike.',
        'valuables#1177': 'Arcane arte: closes instantly, striking with consecutive slashes.',
        'valuables#1218': 'Arcane arte: leaps back, fires chakrams, and strikes surrounding foes.',
        'valuables#1243': 'Arcane arte: launches foes skyward, striking with a diving thrust.',
        'valuables#1346': 'Arcane arte: delivers three slashes and kicks foes into the air.',
        'valuables#1620': 'Arcane arte: calls flames from ground to attack after Shadow Run Blast.',
        'valuables#1698': 'Fires arrows skyward that rain down upon enemies in targeted area.',
        'valuables#1740': 'Arcane arte: launches foes skyward with an uppercut, kicking downward.',
        'valuables#1750': 'Releases slashes like cherry blossoms, launching foes skyward.',
        'valuables#144': 'A tool to crush ice. If found near a bed, proceed with caution.',
        'valuables#210': 'Decorated with countless eyes; mirror surfaces are painted black.',
        'valuables#647': 'Arcane arte: knocks foes down with a sliding kick, striking with flames.',
        'valuables#651': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
        'valuables#749': 'Arcane arte: launches foes skyward, jumps into air, and kicks them down.',
        'valuables#771': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
        'valuables#779': 'Arcane arte: launches foes skyward with kicks, following with a dive kick.',
        'valuables#885': 'Arcane arte: leaves five presents at enemy feet after Explosive Thrust Raid.',
        'valuables#932': 'Arcane arte: combines Flashing Fang, Severing Moon Flower, Ruinous Palm.',
        'valuables#939': 'Arcane arte: launches foes skyward, follows with slashes, and knocks down.',
        'valuables#973': 'Deploys a barrier blowing enemies away while greatly healing allies.',
        'valuables#1006': 'Arcane arte: cold-cloaked shockwaves trace a cross to attack enemies.',
        'valuables#1061': 'Wind secret arte: slams weapons down with momentum from midair.',
        'valuables#1194': 'Space-time sword secret arte: distorts space to cleave enemies in two.',
        'valuables#1200': 'Space-time sword arcane arte: teleports in front of enemies to attack.',
        'valuables#1283': 'Arcane arte: blows foes away with Fierce Claw, chasing with Demon Fang.',
        'valuables#1350': 'Arcane arte: slashes foes four times, then strikes with shockwaves.',
        'valuables#1650': 'Arcane arte: countless pages fly from an open book to slice enemies.',
        'valuables#1827': 'Arcane arte: magnificent five-hit combos unleashed by a fighting maiden.',
        'valuables#130': 'Purpose unknown. Rumor says you die peering through it like a telescope.',
        'valuables#142': 'A nice pocket watch, but hands move at startling speed. It is harmless.',
        'valuables#657': 'Arcane arte: godspeed thrusts turn to light and impale the enemy.',
        'valuables#1993': 'Arcane arte: arrows shot skyward rain down as countless ice blades.',
        'valuables#2272': 'Title for one who walked a storied battle history with companions.',
        'valuables#75': 'Recipe for "Mountain and Sea Delicacy Soup" that Coda craves.',
        'valuables#116': 'Made with mellow grapes. Grape lovers will ascend to heaven.',
        'valuables#162': 'An invention devised by humankind to shop efficiently.',
        'valuables#1985': 'Short-range skill: launches foes with bow attacks and follows up.',
        'valuables#104': 'Seals a demon that drove heaven, earth, and the demon realm to ruin.',
        'valuables#121': 'Part from an antique clock destroyed by a grandfather in a fit of rage.',
        'valuables#213': 'A compass shaped like an eyeball. The needle spins ceaselessly.',
        'valuables#1356': 'Secret arte: reminiscent of sprinkling water during intense summer heat.',
        'valuables#1700': 'Arcane arte: arrows fired high into the sky rain down all around.',
        'valuables#1884': 'Arcane arte: wide-range multi-hit iai slash with vacuum waves.',
        'valuables#95': 'Reverts skin age to near infancy. Risks vanishing you completely.',
        'valuables#156': 'Picture of an adorable kitten. Contains clues on eliminating war.',
        'valuables#168': 'Banner bearing a tiger pattern. Exudes nobility of the Beast King.',
        'valuables#275': 'Green jewel obtained from a green chest in the Holy Land of Langriths.',
        'valuables#429': 'Arte: cures status ailments and moderately restores HP for an ally.',
        'valuables#733': 'Arcane arte: follows Phantom Dragon Fist with spinning kicks.',
        'valuables#571': 'Arte: slightly restores TP of nearby allies and cures status ailments.',
        'valuables#1090': 'Arcane arte: Crouching Dragon Strike and Flowing Shadow Strike combo.',
        'valuables#1924': 'Secret arte: replicates the skill of a snake to draw enemies closer.',
    }

    rules = [
        # Skill prefix
        (r'^A skill that attaches a talisman reducing enemy (\w+) for a short time with a set chance\.$',
         r'Attaches a talisman briefly lowering enemy \1 by chance.'),
        (r'^Secret arte: flings a talisman reducing enemy (\w+) for a short time with a set chance\.$',
         r'Secret arte: flings a talisman briefly lowering enemy \1 by chance.'),
        
        # Recipes
        (r'^The recipe for "(.*?)" that Coda is yearning for\.$',
         r'Recipe for "\1" that Coda craves.'),
        
        # Prefixes
        (r'^An arcane arte where ', 'Arcane arte: '),
        (r'^An arcane arte that, ', 'Arcane arte: '),
        (r'^An arcane arte that ', 'Arcane arte: '),
        (r'^An arcane arte with ', 'Arcane arte: '),
        (r'^An arcane arte of ', 'Arcane arte: '),
        (r'^An arcane arte ', 'Arcane arte: '),
        (r'^A space-time sword arcane arte that ', 'Space-time sword arcane arte: '),
        (r'^A space-time sword secret arte that ', 'Space-time sword secret arte: '),
        (r'^A wind-element secret arte that ', 'Wind secret arte: '),
        (r'^A fire arte where ', 'Fire arte: '),
        (r'^A short-range skill that ', 'Short-range skill: '),
        (r'^An explosive arcane arte that explicitly ', 'Explosive arcane arte: '),
        (r'^An infinite dagger arcane arte that ', 'Infinite dagger arcane arte: '),
        
        # Titles
        (r'^Title given to someone who ', 'Title for one who '),
        (r'^Title given to someone ', 'Title for someone '),
        (r'^Title given to ', 'Title for '),
        
        # Common word / phrase compressions
        (r'for a short time with a set chance', 'briefly by chance'),
        (r'with a high probability of stunning them', 'with high stun chance'),
        (r'while moving at high speed', 'at high speed'),
        (r'high-speed movement', 'high speed'),
        (r'featuring the ability to ', 'able to '),
        (r'\(area of effect in battle\)', '(in battle)'),
        (r'area of effect in battle', 'in battle'),
        (r'for a single target ally', 'for an ally'),
        (r'for a single ally', 'for an ally'),
        (r'for a target ally', 'for an ally'),
        (r'releases gathered fighting spirit', 'releases fighting spirit'),
        (r'in rapid succession', 'rapidly'),
        (r'two more vacuum wave strikes', 'two vacuum strikes'),
        (r'from rapid thrusts', 'from thrusts'),
        (r'three consecutive thrusts', 'three thrusts'),
        (r'consecutive spinning kicks', 'spinning kicks'),
        (r'two-stage slashes', 'two-stage strikes'),
        (r'left and right slashes', 'dual slashes'),
        (r'closes distance while unleashing', 'closes in, unleashing'),
        (r'closes distance instantly,', 'closes instantly,'),
        (r'closes distance,', 'closes in,'),
        (r'slashes enemies skyward with', 'slashes foes skyward with'),
        (r'slashes enemies skyward,', 'slashes foes skyward,'),
        (r'attacks surrounding enemies with', 'attacks surrounding foes with'),
        (r'delivers consecutive attacks from', 'attacks consecutively from'),
        (r'executes consecutive attacks from', 'attacks consecutively from'),
        (r'executes high-speed spinning slashes', 'executes high-speed spin slashes'),
        (r'sweeps enemies away with', 'sweeps enemies with'),
        (r'draws enemies into', 'draws enemies to'),
        (r'knocks down opponents by', 'knocks down foes by'),
        (r'follows up with ', 'follows with '),
        (r'rushes forward swiftly and ', 'rushes forward and '),
        (r'attacks enemies by slamming them with ', 'attacks by slamming foes with '),
        (r'attacks enemies with air pressure generated from ', 'attacks foes with air pressure from '),
        (r'halts enemy movement with a heavy thrust and launches them skyward\.', 'halts enemy with a heavy thrust and launches them skyward.'),
        (r'launches enemies with combos and slams them down with vacuum blades\.', 'launches with combos and slams down with vacuum blades.'),
        (r'rushes forward, launches enemies, and unleashes consecutive slashes\.', 'rushes forward, launches foes, and unleashes rapid slashes.'),
        (r'sweeps enemy feet, launching and following up with explosive blasts\.', 'sweeps enemy feet, launching with explosive blasts.'),
        (r'delivers a single sword flash while closing distance in an instant\.', 'delivers a sword flash while closing distance instantly.'),
        (r'slashes continuously like flowing water, finishing with shockwaves\.', 'slashes like flowing water, finishing with shockwaves.'),
        (r'launches with lightning and drops giant manifested steel onto foes\.', 'launches with lightning, dropping steel onto foes.'),
        (r'thrusts a spear into the ground, raising a water pillar to attack\.', 'thrusts a spear into ground, raising a water pillar.'),
        (r'launches enemies with shockwave slashes and slams down with a cut\.', 'launches with shockwave slashes and slams down with a cut.'),
        (r'launches enemies, then lands spinning kicks and slashes in midair\.', 'launches foes, landing spinning kicks and slashes in air.'),
        (r'launches enemies with a shield bash and chases with sharp thrusts\.', 'launches with a shield bash, chasing with sharp thrusts.'),
        (r'launches enemies sky-high from godspeed upward slashes into kicks\.', 'launches foes high from godspeed upward slashes into kicks.'),
        (r'launches enemies, ascends with spinning slashes, and fires blasts\.', 'launches, ascends with spinning slashes, and fires blasts.'),
        (r'draw enemies in\.', 'draw enemies closer.'),
        (r'in midair', 'in air'),
        (r'sky-high', 'high'),
        (r'consecutive slashes', 'rapid slashes'),
        (r'consecutive upward slashes', 'rapid upward slashes'),
        (r'consecutive downward slashes', 'rapid downward slashes'),
        (r'slashes enemies with ', 'slashes foes with '),
        (r'launches enemies with ', 'launches foes with '),
        (r'launches enemies into the air,', 'launches foes into the air,'),
        (r'launches enemies,', 'launches foes,'),
        (r'attacks enemies with ', 'attacks foes with '),
        (r'blows enemies away with ', 'blows foes away with '),
        (r'blows enemies away and ', 'blows foes away and '),
        (r'blow away surrounding foes', 'blow away nearby foes'),
        (r'blows everything away indiscriminately with ', 'blows all away with '),
        (r'slashes upward and downward', 'slashes up and down'),
        (r'upward and downward', 'up and down'),
        (r'into enemies to blow them away', 'into foes, blowing them away'),
        (r'swings weapons to sweep enemies away along with fighting spirit', 'swings weapons to sweep foes away with fighting spirit'),
        (r'stacks high-speed sword clashes to produce windstorm shockwaves', 'stacks sword clashes at high speed, creating windstorms'),
        (r'increases stagger time for a single target enemy for a set time', 'increases stagger time for an enemy temporarily'),
        (r'blows enemies away with uppercuts and mysterious triangle kicks', 'blows foes away with uppercuts and triangle kicks'),
        (r'drops vertically from a leap and attacks with impact on landing', 'drops from a leap, attacking with impact on landing'),
        (r'unleashes shockwaves from two sharp sword strikes after thrusts', 'unleashes shockwaves from two sword strikes after thrusts'),
        (r'binds upward-slashed enemies to the heavens with a fierce flash', 'binds slashed foes to the heavens with a fierce flash'),
        (r'lion roars that slaughter fierce tigers', 'lion roars that slay fierce tigers'),
        (r'thrusts at enemies in the back while sweeping aside front foes', 'thrusts at rear enemies while sweeping aside front foes'),
        (r'repeatedly swings weapons to blow enemies away with momentum', 'repeatedly swings weapons to blow foes away with momentum'),
        (r'repeatedly swings weapons to blow away numerous rock shards', 'repeatedly swings weapons to blow away rock shards'),
        (r'creates countless icicles from the impact of upward slashes', 'creates icicles from the impact of upward slashes'),
        (r'steps into the enemy pocket while attacking and rapid-fires', 'steps into enemy pocket while attacking and rapid-fires'),
        (r'punches enemy vitals with weapon pommels to knock them down', 'punches vitals with weapon pommels to knock enemies down'),
        (r'slashes enemies into the air and unleashes spinning slashes', 'slashes foes into the air and unleashes spinning slashes'),
        (r'fires a powerful shot skyward capable of piercing even gods', 'fires a shot skyward capable of piercing even gods'),
        (r'delivers aerial kicks and connects into consecutive attacks', 'delivers aerial kicks, connecting into consecutive attacks'),
        (r'throws daggers blessed with water three times in succession', 'throws water-blessed daggers three times in succession'),
        (r'dances into the air and fires twelve bullets while spinning', 'dances into air and fires twelve bullets while spinning'),
        (r'sweeps enemies away while releasing fire power all at once', 'sweeps foes away, releasing fire power all at once'),
        (r'executes high-speed sword strikes cleaving through enemies', 'executes high-speed sword strikes cleaving foes'),
        (r'attacks surroundings and raises icicles from impact points', 'attacks surroundings, raising icicles from impact points'),
        (r'hits four times with dual swords, launches, and follows up', 'hits four times with dual swords, launches, and follows'),
        (r'causes countless bubbles to surge from the ground beneath the target enemy\.',
         'Arte: causes countless bubbles to surge beneath the target enemy.'),
        (r'causes a massive torrent of water to surge around the target enemy\.',
         'Arte: causes a torrent of water to surge around target enemy.'),
        (r'creates sharp blocks of ice from the ground beneath the target enemy\.',
         'Arte: creates sharp blocks of ice beneath the target enemy.'),
        (r'rains down flame spheres causing powerful explosions on the ground\.',
         'Arte: rains flame spheres causing explosions on the ground.'),
        (r'traps targets in a magic circle and unleashes four pillars of flame\.',
         'Arte: traps targets in a circle, unleashing four flame pillars.'),
        (r'surrounds an ally with a barrier that continuously restores their HP\.',
         'Arte: surrounds an ally with a barrier continuously restoring HP.'),
        (r'surrounds an ally with holy light, restoring their physical status\.',
         'Arte: surrounds an ally with holy light, restoring physical status.'),
        (r'envelops a targeted ally in holy light, restoring their physical status\.',
         'Arte: envelops target ally in holy light, restoring physical status.'),
        (r'raises an ally\'s physical attack and cures status ailments for a set time\.',
         'Arte: raises an ally\'s attack and cures ailments for a set time.'),
        (r'raises an ally\'s physical defense and cures stat debuffs for a set time\.',
         'Arte: raises an ally\'s defense and cures debuffs for a set time.'),
        (r'raises an ally\'s magic attack and cures stat debuffs for a set time\.',
         'Arte: raises an ally\'s magic attack and cures debuffs temporarily.'),
        (r'raises an ally\'s magic defense and cures stat debuffs for a set time\.',
         'Arte: raises an ally\'s magic defense and cures debuffs temporarily.'),
        (r'slightly restores TP of allies in range and cures status ailments\.',
         'Arte: slightly restores TP of nearby allies and cures ailments.'),
    ]
    
    out = {}
    for x in itens:
        item_id = x['id']
        en = x['en']
        if item_id in custom_map:
            out[item_id] = custom_map[item_id]
            continue
        
        s = en
        for pat, rep in rules:
            s = re.sub(pat, rep, s)
        if s.startswith('A skill that '):
            rest = s[len('A skill that '):]
            s = rest[0].upper() + rest[1:]
            
        if s != en:
            out[item_id] = s
            
    return out

if __name__ == '__main__':
    out = build_val01()
    from val_check import validate_dict
    ok = validate_dict('dados/item_equip_shrink/VAL-01.json', out)
    if ok:
        with open('dados/item_equip_shrink/VAL-01_out.json', 'w', encoding='utf-8') as f:
            json.dump(out, f, indent=1, ensure_ascii=True)
        print("Wrote dados/item_equip_shrink/VAL-01_out.json")
