import re
from sinopse_dict2 import SINOPSE_2
from check_dict import check_dict

FIXES = {
    'sinopse#320': 'Fearing monstrous relapse, they expected',
    'sinopse#321': 'banishment from the village.',
    'sinopse#322': 'To find a haven for them, the party',
    'sinopse#323': 'returned to the ship.',
    'sinopse#324': 'Unable to return home, Joan and Miguel',
    'sinopse#325': 'joined construction of Olta Village.',
    'sinopse#326': 'Examining the beetle and Joan confirmed',
    'sinopse#327': 'mutations caused by the red smoke.',
    'sinopse#328': 'This proved that red smoke was indeed',
    'sinopse#329': 'the cause of biological mutations.',
    'sinopse#330': 'Yet the healing and mutation process',
    'sinopse#331': 'remained completely unexplained.',
    'sinopse#332': 'Further civilian contact had to cease,',
    'sinopse#333': 'yet its next emergence was unpredictable.',
    'sinopse#334': 'Expecting more escort requests, Ange',
    'sinopse#335': 'waited for reports of smoke sightings.',
    'sinopse#336': 'Soon, a new recruit boarded the ship.',
    'sinopse#337': 'It was Arche, an old friend of Mint.',
    'sinopse#338': "Arche brought the Sorcerer's Ring,",
    'sinopse#339': 'an artifact capable of unsealing paths.',
    'sinopse#340': 'Mint entrusted it to Ange with a quest.',
    'sinopse#341': 'Presently, the ring possessed no power.',
    'sinopse#342': 'To awaken it, natural elemental energy',
    'sinopse#343': 'had to be infused directly.',
    'sinopse#344': 'Such infusion sites were called Ring Spots,',
    'sinopse#345': 'and OO was chosen to venture forth.',
    'sinopse#346': 'At a Ring Spot within Altata Volcano, OO',
    'sinopse#347': 'infused the artifact with primal energy,',
    'sinopse#348': 'successfully activating its power.',
    'sinopse#349': "The Sorcerer's Ring could still gain",
    'sinopse#350': 'greater power through further infusions.',
    'sinopse#351': 'Whenever new Ring Spots are found,',
    'sinopse#352': 'further guidance would follow.',
    'sinopse#353': 'Ange entrusted the ring to OO,',
    'sinopse#354': 'granting authority to use it freely.',
    'sinopse#355': 'Meanwhile, concrete intel on red smoke',
    'sinopse#356': 'remained elusive.',
    'sinopse#357': 'When someone wondered if spirits knew,',
    'sinopse#358': 'Kratos spoke up thoughtfully.',
    'sinopse#359': 'He mentioned Mibuna Village, a haven',
    'sinopse#360': 'communing with spirits.',
    'sinopse#361': 'Kratos offered to act as a guide,',
    'sinopse#362': 'submitting a formal quest.',
    'sinopse#363': 'Did a village tied to spirits truly exist?',
    'sinopse#364': 'If it aided investigation into smoke,',
    'sinopse#365': 'there was no room for hesitation.',
    'sinopse#366': 'To seek knowledge of the red smoke,',
    'sinopse#367': 'OO accepted the quest, traveling through',
    'sinopse#368': 'Brownie Mine toward Mibuna Village.',
    'sinopse#369': 'Guided by Kratos alongside Harold,',
    'sinopse#370': 'OO advanced deep inside.',
    'sinopse#371': 'Along the path, Harold found a flier.',
    'sinopse#372': 'It was recruitment for a cult calling',
    'sinopse#373': 'itself Servants of the Dawn.',
    'sinopse#374': 'Amidst strife, new cults awaiting',
    'sinopse#375': 'the Descender arose everywhere.',
    'sinopse#376': 'Servants of the Dawn was fiercest.',
    'sinopse#377': 'Countless souls sought salvation.',
    'sinopse#378': 'OO felt an indescribable frustration',
    'sinopse#379': 'weighing upon the heart.',
    'sinopse#380': 'Suddenly, a distant shout echoed out.',
    'sinopse#381': 'Rushing over, they found a beast rampaging.',
    'sinopse#382': 'Upon defeat, it vanished without trace.',
    'sinopse#383': 'In its place appeared a lone woman.',
    'sinopse#384': 'She was Sheena, an acquaintance of Kratos.',
    'sinopse#385': 'The beast was an artificial spirit crafted',
    'sinopse#386': 'with the esoteric art of Light Qi.',
    'sinopse#387': 'Kratos sought an audience with spirits,',
    'sinopse#388': 'yet Imperial mining drove them away.',
    'sinopse#389': 'Spirits had vanished from the land.',
    'sinopse#390': 'Advancing would not yield a spirit.',
    'sinopse#391': 'However, Sheena promised to deliver texts',
    'sinopse#392': 'detailing spirit locations later,',
    'sinopse#393': 'so the party returned to the ship.',
    'sinopse#394': 'Hope was not entirely lost.',
    'sinopse#395': 'The research crew was thrilled by news',
    'sinopse#396': 'of artificial spirits and Light Qi.',
    'sinopse#397': 'Rita was especially intrigued by Light Qi,',
    'sinopse#398': 'hypothesizing links to the ancient',
    'sinopse#399': 'discipline known as Soul Alchemy,',
    'sinopse#400': 'growing immensely excited.',
    'sinopse#401': 'Soon Sheena arrived alongside Lloyd,',
    'sinopse#402': 'delivering literature on spirits.',
    'sinopse#403': 'Rita questioned Sheena on Light Qi.',
    'sinopse#404': 'Though secret to Mibuna Village,',
    'sinopse#405': 'persuaded that it might solve mutations,',
    'sinopse#406': 'Sheena shared the scriptures.',
    'sinopse#407': 'Examining them confirmed artificial spirits',
    'sinopse#408': 'represented a branch of Soul Alchemy,',
    'sinopse#409': 'the very art Rita pursued.',
    'sinopse#410': 'Soul Alchemy alters energy blueprints',
    'sinopse#411': 'known as Documents, bodies of pure energy.',
    'sinopse#412': 'Perhaps biological mutations operated through',
    'sinopse#413': 'alterations to those very Documents.',
    'sinopse#414': 'Yet Rita noted manipulating such arts',
    'sinopse#415': 'was impossible for ordinary mortals.',
    'sinopse#416': 'Just then, an escort quest reached the guild',
    'sinopse#417': 'requesting passage to meet the entity.',
    'sinopse#418': 'The red smoke, rumored to grant wishes.',
    'sinopse#419': 'The client said it was at Rhubarb.',
    'sinopse#420': 'Ange declined the quest, deploying',
    'sinopse#421': 'guild members to Rhubarb Mountains directly.',
    'sinopse#422': 'To prevent civilian contact, OO set out',
    'sinopse#423': 'for Rhubarb Mountains with Tytree and Meredy.',
    'sinopse#424': 'En route, they turned back civilians',
    'sinopse#425': 'seeking the wish-granting entity.',
    'sinopse#426': 'Before long, Tytree spotted a red figure.',
    'sinopse#427': 'Had red smoke assumed humanoid form?',
    'sinopse#428': 'Was this the wish-granting existence?',
    'sinopse#429': 'When Tytree questioned it, the red figure',
    'sinopse#430': 'merely swayed and gazed at OO and allies.',
    'sinopse#431': 'It seemed instinctively studying OO,',
    'sinopse#432': 'seeking to comprehend true nature.',
    'sinopse#433': 'Suddenly, Servants of the Dawn appeared.',
    'sinopse#434': 'Hailing the entity as their Lord Descender,',
    'sinopse#435': 'they bypassed OO and spirited it away.',
    'sinopse#436': 'Such a horrifying being was no savior.',
    'sinopse#437': 'If worshiped widely and touched by masses,',
    'sinopse#438': 'catastrophe would inevitably ensue.',
    'sinopse#439': "Rita's research showed that the beetle's",
    'sinopse#440': 'Document was heavily corroded.',
    'sinopse#441': 'Its Document was rewritten into something',
    'sinopse#442': 'deviating completely from organic life.',
    'sinopse#443': 'Its rewritten Document belonged to no world.',
    'sinopse#444': 'Whenever red smoke touched organisms,',
    'sinopse#445': 'their Documents were forcibly overwritten.',
    'sinopse#446': 'Meanwhile, the smoke itself evolved.',
    'sinopse#447': 'Observing this, Sheena formed a theory.',
    'sinopse#448': 'The red smoke reacted to desperate wishes.',
    'sinopse#449': 'It resonated with powerful desires.',
    'sinopse#450': "Touching desires, it learned from a target's",
    'sinopse#451': 'Document, evolving and transforming.',
    'sinopse#452': 'Yet its ultimate goal remained unknown.',
    'sinopse#453': 'While grappling with these mysteries,',
    'sinopse#454': 'new allies arrived aboard the ship.',
    'sinopse#455': 'Asbel and Sophie arrived to retrieve Estelle.',
    'sinopse#456': 'Princess Natalia of Lima took refuge,',
    'sinopse#457': 'guarded by Jade and Tear.',
    'sinopse#458': 'The riots in Lima were instigated directly',
    'sinopse#459': 'by Servants of the Dawn.',
    'sinopse#460': 'Deprived of Star Crystal concessions,',
    'sinopse#461': 'the populace of Lima suffered hardship.',
    'sinopse#462': 'Servants of the Dawn exploited this misery,',
    'sinopse#463': 'preaching salvation and inciting unrest,',
    'sinopse#464': 'causing public anger to erupt violently.',
    'sinopse#465': 'When Ange said they pursued the cult,',
    'sinopse#466': 'Jade revealed their base was located',
    'sinopse#467': 'within the Almanac Ruins.',
    'sinopse#468': 'Revering that red entity as savior,',
    'sinopse#469': 'the cult hailed it as Descender.',
    'sinopse#470': 'They had to sever the entity quickly',
    'sinopse#471': 'before disaster unfolded.',
    'sinopse#472': 'Leading Ange and Jade, OO entered',
    'sinopse#473': 'into the Almanac Ruins.',
    'sinopse#474': 'The cultists blocking the way wielded power,',
    'sinopse#475': 'displaying superhuman strength.',
    'sinopse#476': 'It was unearthly power bestowed by that entity',
    'sinopse#477': 'whom they hailed as Descender.',
    'sinopse#478': 'Fighting fanatically to protect their savior,',
    'sinopse#479': 'grotesque mutations overtook their bodies.',
    'sinopse#480': 'Horrified by deformities, they begged',
    'sinopse#481': 'an entity named Lazaris for salvation.',
    'sinopse#482': 'Lazaris... was that the identity of the smoke?',
    'sinopse#483': 'Yet Lazaris coldly rejected the cultists.',
    'sinopse#484': 'Lazaris claimed to be an unborn world,',
    'sinopse#485': 'destined to exist just like Luminasia.',
    'sinopse#486': 'Venting fury at the state of Luminasia,',
    'sinopse#487': 'Lazaris departed alone.',
    'sinopse#488': 'Just as with Joan, OO extended gentle hands,',
    'sinopse#489': 'restoring the mutated cultists to normal form.',
    'sinopse#490': 'Restored yet forsaken by their idol,',
    'sinopse#491': 'the bewildered cultists wandered away.',
    'sinopse#492': 'That entity was certainly no Descender.',
    'sinopse#493': 'Restoring Joan and cultists from mutations',
    'sinopse#494': "displayed OO's miraculous power.",
    'sinopse#495': 'To researchers, this phenomenon seemed',
    'sinopse#496': 'just like miracles of Soul Alchemy.',
    'sinopse#497': 'Yet OO possessed no explanation.',
    'sinopse#498': 'While planning future strategies, OO',
    'sinopse#499': 'enjoyed a brief respite in the hall.',
    'sinopse#500': 'Kanonno invited all to view her art.',
    'sinopse#501': 'Kanonno was fond of OO viewing her art,',
    'sinopse#502': 'as Rocks noted with warmth.',
    'sinopse#503': "Rocks shared that he served Kanonno's parents",
    'sinopse#504': 'before they passed away, raising Kanonno',
    'sinopse#505': 'ever since their demise.',
    'sinopse#506': 'Meanwhile, Lazaris observed Luminasia,',
    'sinopse#507': 'lamenting bitterly.',
    'sinopse#508': 'Mortals devoured the world she could not birth,',
    'sinopse#509': 'endlessly driven by boundless greed.',
    'sinopse#510': 'She vowed never to craft such a world.',
    'sinopse#511': 'Soon royals Luke and Asch of Lima arrived',
    'sinopse#512': 'alongside their sword instructor Van,',
    'sinopse#513': 'boarding the Van Eltia.',
    'sinopse#514': 'The ship unlocked the ability to touch down',
    'sinopse#515': 'in lands where spirits dwelt.',
    'sinopse#516': 'The next destination: Mt. Absoule.',
    'sinopse#517': 'At last, meeting spirits was possible.',
    'sinopse#518': 'To ask spirits about Lazaris, OO set out',
    'sinopse#519': 'seeking answers to world creation.',
    'sinopse#520': 'Leading Emil and Caius, they climbed Absoule.',
    'sinopse#521': 'Trudging through harsh snow and freezing gales,',
    'sinopse#522': 'they encountered a solitary swordsman.',
    'sinopse#523': 'Learning that OO sought spirits, the warrior',
    'sinopse#524': 'drew his blade and attacked.',
    'sinopse#525': 'OO and allies neutralized the swordsman,',
    'sinopse#526': 'sincerely explaining their desire to meet spirits.',
    'sinopse#527': 'Then Celsius, spirit of ice, appeared from mist,',
    'sinopse#528': 'addressing OO as the Descender.',
    'sinopse#529': 'Caius and Emil gasped in sheer astonishment.',
    'sinopse#530': "OO's lack of memories matched ancient lore:",
    'sinopse#531': 'born from the Tree, knowing nothing of worldly ways.',
    'sinopse#532': 'Though Celsius knew little of primordial genesis,',
    'sinopse#533': 'she told of a great calamity sealed away',
    'sinopse#534': 'beneath Star Crystals.',
    'sinopse#535': 'Did that calamity refer to Lazaris?',
    'sinopse#536': 'Richter and Celsius chose to assist the savior,',
    'sinopse#537': 'descending the peak alongside OO and friends.',
    'sinopse#538': 'They walked together.',
    'sinopse#539': "Returning aboard, news that OO was Descender",
    'sinopse#540': 'spread rapidly, leaving everyone stunned.',
    'sinopse#541': 'Iria noted that OO possessed a power',
    'sinopse#542': 'unlike any ordinary mortal.',
    'sinopse#543': 'Reverting mutated beings to normal form.',
    'sinopse#544': 'That was the true power of the Descender.',
    'sinopse#545': 'While spirits knew little of world genesis,',
    'sinopse#546': 'they knew one entity witnessed the creation.',
    'sinopse#547': 'That ancient being witnessed the world begin.',
    'sinopse#548': 'That witness was neither human nor spirit.',
    'sinopse#549': 'Learning the tale of genesis from that witness',
    'sinopse#550': 'was the legendary Progenitor of Man.',
    'sinopse#551': 'Long ago, humans existed as immaterial spirits.',
    'sinopse#552': 'Designing physical forms through Soul Alchemy,',
    'sinopse#553': 'they flourished upon the material realm.',
    'sinopse#554': 'Though the Progenitor who knew genesis was gone,',
    'sinopse#555': 'relics left behind still endured somewhere,',
    'sinopse#556': 'such as the fabled Veratropa.',
    'sinopse#557': 'Yet those ruins remained immaterial.',
    'sinopse#558': 'Harold racked brains to materialize them,',
    'sinopse#559': 'accidentally summoning Kyle from another world',
    'sinopse#560': 'in an amusing uproar.',
    'sinopse#561': 'Meanwhile, Eugene and Veigue approached Ange',
    'sinopse#562': 'bringing a deeply urgent request.',
    'sinopse#563': 'Laborers from Hazel Village were captured',
    'sinopse#564': 'by the Urizen Empire.',
    'sinopse#565': 'After mining nearby crystals, they were dragged',
    'sinopse#566': 'to distant mines for forced labor.',
    'sinopse#567': 'While Eugene and Veigue set out to liberate them,',
    'sinopse#568': 'villagers remaining in Hazel could not survive,',
    'sinopse#569': 'so Annie and Tytree departed to help them migrate',
    'sinopse#570': 'to Olta Village, currently under construction.',
    'sinopse#571': 'They coordinated the relocation.',
    'sinopse#572': 'To reach Olta Village, both groups needed',
    'sinopse#573': 'to cross the dangerous Kadaif Desert.',
    'sinopse#574': 'To ensure Hazel villagers crossed safely, OO',
    'sinopse#575': 'took on a critical hunting commission:',
    'sinopse#576': 'locating and slaying the ferocious Tyrannpion,',
    'sinopse#577': 'a deadly menace stalking the desert sands.',
    'sinopse#578': "Through OO's valiant efforts, the beast was felled,",
    'sinopse#579': 'allowing Hazel villagers to reach their new home.',
    'sinopse#580': 'They arrived safely.',
    'sinopse#581': 'Yet Olta Village had only just begun operating.',
    'sinopse#582': 'Countless challenges still lay ahead.',
    'sinopse#583': 'To materialize Veratropa, the ancient ruins\'',
    'sinopse#584': 'Document was strictly required.',
    'sinopse#585': 'The researchers held their heads in despair',
    'sinopse#586': 'over this seemingly impossible barrier.',
    'sinopse#587': 'Meanwhile, Kanonno shared her sketchbook',
    'sinopse#588': 'with Celsius, showing drawings.',
    'sinopse#589': 'They showed lands never visited yet felt.',
    'sinopse#590': 'She wondered if spirits might recognize',
    'sinopse#591': 'any of the vistas depicted within.',
    'sinopse#592': 'Among numerous sketches, Celsius recognized one:',
    'sinopse#593': 'it depicted the sacred ruins of Veratropa.',
    'sinopse#594': 'Why had Kanonno sketched Veratropa?',
    'sinopse#595': 'Kanonno herself could not fathom the reason.',
    'sinopse#596': "Examining Kanonno's Document, Rita discovered",
    'sinopse#597': 'an extraordinary Document never seen in humans.',
    'sinopse#598': 'Embedded within it was the Document of Veratropa.',
    'sinopse#599': 'It held the missing pattern.',
    'sinopse#600': 'Deploying a Document strains the physical body.',
    'sinopse#601': 'Aware of risks, Kanonno asked Rita to extract it,',
    'sinopse#602': 'securing the Document of Veratropa,',
    'sinopse#603': 'an unexpected discovery.',
    'sinopse#604': 'Thus Veratropa was materialized into reality,',
    'sinopse#605': 'opening the path to mysteries of world genesis.',
    'sinopse#606': 'Stepping into Veratropa, OO explored alongside',
    'sinopse#607': 'scholars Keele and Judith.',
    'sinopse#608': 'To understand Lazaris, they investigated genesis,',
    'sinopse#609': 'groping completely in the dark regarding methods.',
    'sinopse#610': 'They searched carefully.',
    'sinopse#611': 'Hence Keele, versed in ancient texts, and Judith,',
    'sinopse#612': 'able to read memories from relics, came along.',
    'sinopse#613': 'They investigated together.',
    'sinopse#614': 'From four murals inside Veratropa, they learned',
    'sinopse#615': "that Luminasia's World Tree had assimilated",
    'sinopse#616': 'another entire world during genesis.',
    'sinopse#617': 'That other world was none other than Lazaris,',
    'sinopse#618': 'the sealed calamity spoken of by Celsius.',
    'sinopse#619': 'As for what kind of calamity it was, Judith',
    'sinopse#620': 'could only sense that its underlying laws',
    'sinopse#621': 'were entirely incompatible with this realm.',
    'sinopse#622': 'Proceeding onward, OO met Niata Monad,',
    'sinopse#623': 'the witness who beheld the dawn of genesis.',
    'sinopse#624': 'Yet while Niata recounted the birth of worlds,',
    'sinopse#625': 'Lazaris materialized, mercilessly shattering',
    'sinopse#626': 'Niata to pieces.',
    'sinopse#627': 'Raising sky-piercing colossal fangs, Lazaris',
    'sinopse#628': 'vanished into the firmament.',
    'sinopse#629': 'Lazaris targeted this realm of Luminasia.',
    'sinopse#630': 'She sought to create her world, Zirdia,',
    'sinopse#631': 'by usurping the Hall of Life.',
    'sinopse#632': 'The Hall of Life generates mana, serving as heart',
    'sinopse#633': 'and prime Document of the World Tree itself.',
    'sinopse#634': 'Only the World Tree or its Descender avatar',
    'sinopse#635': 'could command and manipulate that sacred space.',
    'sinopse#636': 'Yet OO knew nothing about the Hall of Life.',
    'sinopse#637': 'Memory offered no answers.',
    'sinopse#638': 'If the world were remade, all living beings would',
    'sinopse#639': 'perish or twist into hideous alien abominations.',
}

SINOPSE_2.update(FIXES)

with open('sinopse_dict2.py', 'w', encoding='utf-8') as f:
    f.write("# Translation dictionary for SINOPSE-02 (ids 320 to 639)\n\nSINOPSE_2 = {\n")
    for k in sorted(SINOPSE_2.keys(), key=lambda x: int(x.split('#')[1])):
        f.write(f"    {repr(k)}: {repr(SINOPSE_2[k])},\n")
    f.write("}\n")

print("Updated sinopse_dict2.py, now running check_dict:")
check_dict(SINOPSE_2, 'lotes_bancos/SINOPSE-02.tsv')
