# Translation dictionary for SINOPSE-04 (ids 960 to 1124)

SINOPSE_4 = {
    'sinopse#960': 'However, failure meant bodily dissolution,',
    'sinopse#961': 'making this a dangerous gamble.',
    'sinopse#962': 'This trial relied on advanced machinery.',
    'sinopse#963': 'To complete circuits, the rare mineral',
    'sinopse#964': 'Gibeon was strictly required.',
    'sinopse#965': 'Gibeon was meteoric iron from space.',
    'sinopse#966': 'Years ago a meteorite fell atop Rhubarb,',
    'sinopse#967': 'raising hopes of finding Gibeon there,',
    'sinopse#968': 'so OO and allies climbed the summit.',
    'sinopse#969': 'Reaching the harsh peak, a celestial gift',
    'sinopse#970': 'awaited them: the Gibeon ore.',
    'sinopse#971': 'Promptly, OO and party harvested Gibeon,',
    'sinopse#972': 'pondering this mysterious matter.',
    'sinopse#973': 'This mineral arrived in Luminasia',
    'sinopse#974': 'from some distant forgotten realm.',
    'sinopse#975': 'Across voids and worlds, life supports life,',
    'sinopse#976': 'as Asbel thoughtfully realized.',
    'sinopse#977': 'This brought immense hope to OO,',
    'sinopse#978': 'who longed for coexistence with Lazaris.',
    'sinopse#979': 'Preparations to transcribe the Descender',
    'sinopse#980': 'Document were finalized.',
    'sinopse#981': 'Yet fearing fatal accidents, no candidate',
    'sinopse#982': 'stepped forward to participate.',
    'sinopse#983': 'Then Kanonno volunteered bravely.',
    'sinopse#984': 'Though failure risked death, Kanonno smiled',
    'sinopse#985': 'fearlessly and stepped into the machine.',
    'sinopse#986': "The test began, weaving OO's Document",
    'sinopse#987': "deep into Kanonno's pattern.",
    'sinopse#988': "Kanonno's trembling showed terrible pain.",
    'sinopse#989': 'Agony racked her small frame.',
    'sinopse#990': 'Yet through agony, Kanonno smiled gently,',
    'sinopse#991': "welcoming OO's Document completely.",
    'sinopse#992': 'The experiment ended safely.',
    'sinopse#993': 'Now they needed to verify whether',
    'sinopse#994': 'the transcription succeeded.',
    'sinopse#995': "To test Kanonno's transcribed power,",
    'sinopse#996': 'they headed for Sifno Cave, where',
    'sinopse#997': 'a new spike had sprouted.',
    'sinopse#998': 'If successful, power could spread to all,',
    'sinopse#999': 'allowing everyone to halt corruption.',
    'sinopse#1000': 'Wars to claim uncorrupted territory',
    'sinopse#1001': 'erupted across lands again.',
    'sinopse#1002': 'Yet sharing this power could unite hearts',
    'sinopse#1003': 'to confront the crisis as one.',
    'sinopse#1004': 'Reaching the fang, corruption was severe.',
    'sinopse#1005': 'They found fallen victims collapsed nearby.',
    'sinopse#1006': 'Kanonno restored the victims and the land,',
    'sinopse#1007': 'proving the experiment a complete success.',
    'sinopse#1008': 'Yet the victims remained terribly frail,',
    'sinopse#1009': 'resting unconscious on the ground.',
    'sinopse#1010': 'Their robes belonged to the cult,',
    'sinopse#1011': 'Servants of the Dawn.',
    'sinopse#1012': 'Carrying the cultists, they returned to ship.',
    'sinopse#1013': 'Soon the cultists woke in the infirmary.',
    'sinopse#1014': 'They had sought contact with Ad Libitum.',
    'sinopse#1015': 'To discover their motives,',
    'sinopse#1016': 'OO and allies visited the medical bay.',
    'sinopse#1017': 'Moved by Ad Libitum battling crisis,',
    'sinopse#1018': 'they wished to assist by providing clues',
    'sinopse#1019': 'regarding the Spiral Gall,',
    'sinopse#1020': 'traveling far to deliver intel.',
    'sinopse#1021': 'When fangs rose, cave-ins trapped them',
    'sinopse#1022': 'within Sifno Cave.',
    'sinopse#1023': 'The clue was a stump where Spiral Gall',
    'sinopse#1024': 'once flourished in the past.',
    'sinopse#1025': 'Though decayed, faint Document data might',
    'sinopse#1026': 'remain, yielding a vital breakthrough.',
    'sinopse#1027': "Through Rita's formula, Descender power",
    'sinopse#1028': 'transferred through Kanonno to the cultists.',
    'sinopse#1029': 'Merely touching others would now share',
    'sinopse#1030': 'restorative power across the world.',
    'sinopse#1031': 'Partial Document was obtained from the stump,',
    'sinopse#1032': 'yet this fungus reproduced asexually,',
    'sinopse#1033': 'leaving no modern descendants behind.',
    'sinopse#1034': 'The approach from before would not work.',
    'sinopse#1035': 'Then Kanonno remembered:',
    'sinopse#1036': 'life eaten as food is passed down.',
    'sinopse#1037': 'Will researched ancient beasts alive',
    'sinopse#1038': 'before Spiral Gall went extinct.',
    'sinopse#1039': 'Records showed the Cavelex consumed it',
    'sinopse#1040': 'as part of its regular diet.',
    'sinopse#1041': 'The Cavelex might hold its Document.',
    'sinopse#1042': 'Hope returned once more.',
    'sinopse#1043': 'Tracking the Cavelex that fed on the fungus,',
    'sinopse#1044': 'OO traversed Confeito Great Forest.',
    'sinopse#1045': 'Could food Documents truly endure in predators?',
    'sinopse#1046': 'Uncertainty lingered in their minds.',
    'sinopse#1047': 'Yet no other option remained.',
    'sinopse#1048': 'Neutralizing the Cavelex, OO obtained',
    'sinopse#1049': 'the coveted Document of Spiral Gall.',
    'sinopse#1050': 'All three components were finally assembled:',
    'sinopse#1051': 'Salt Crystal, Dragonfly Grass, Spiral Gall.',
    'sinopse#1052': 'Synthesized together, they formed the seal',
    'sinopse#1053': 'to imprison Zirdia and Lazaris.',
    'sinopse#1054': 'Meanwhile, cultists spread purification,',
    'sinopse#1055': 'uniting people in solidarity worldwide.',
    'sinopse#1056': 'From a single Descender, hope ignited',
    'sinopse#1057': 'across the entire globe.',
    'sinopse#1058': 'The synthetic crystal Document was infused',
    'sinopse#1059': 'into mana streams toward the Tree.',
    'sinopse#1060': 'Thus the Sealing Dimension would manifest.',
    'sinopse#1061': 'Once formed, Lazaris and Zirdia would',
    'sinopse#1062': 'be channeled into the dimensional prison.',
    'sinopse#1063': 'Though technical for OO to grasp,',
    'sinopse#1064': 'trusting Harold and Rita, they awaited final',
    'sinopse#1065': 'preparations to seal Zirdia at last.',
    'sinopse#1066': "Near was the day OO must return to the Tree...",
    'sinopse#1067': 'Another Vortex in holy ground Langrees.',
    'sinopse#1068': 'To channel the seal into the World Tree,',
    'sinopse#1069': 'OO, Rita, and Kanonno departed the ship.',
    'sinopse#1070': 'They journeyed forth.',
    'sinopse#1071': 'Sensing farewell, Kanonno timidly asked OO',
    'sinopse#1072': 'if completion meant returning to the Tree',
    'sinopse#1073': 'forevermore.',
    'sinopse#1074': 'Yet OO harbored no such desire.',
    'sinopse#1075': 'Countless tasks still remained unfinished.',
    'sinopse#1076': 'Even after sealing Lazaris, people across',
    'sinopse#1077': 'the world still needed help.',
    'sinopse#1078': 'Departing alone was unthinkable.',
    'sinopse#1079': 'Finally, the Sealing Dimension unfolded.',
    'sinopse#1080': 'Three fangs dissolved into the seal.',
    'sinopse#1081': 'Yet joy was brief; the seal shattered,',
    'sinopse#1082': 'and a massive new fang pierced the Tree.',
    'sinopse#1083': 'Feeling the shared agony, OO collapsed.',
    'sinopse#1084': 'When OO awakened, they were back on ship.',
    'sinopse#1085': "Corruption spread, warping the Tree's laws.",
    'sinopse#1086': 'Time was running out.',
    'sinopse#1087': 'They wished to reach the Tree immediately,',
    'sinopse#1088': 'yet entering warped space was suicidal.',
    'sinopse#1089': 'Niata promised a way forward, yet',
    'sinopse#1090': 'preparations required precious time.',
    'sinopse#1091': 'Corruption altered reality continuously.',
    'sinopse#1092': 'Finally, through Rita and Niata, entry',
    'sinopse#1093': 'into Elan Vital within the Tree opened.',
    'sinopse#1094': 'What could be accomplished inside?',
    'sinopse#1095': 'What awaited upon meeting Lazaris?',
    'sinopse#1096': 'Heavy anxieties filled every companion.',
    'sinopse#1097': 'To the fearless and resolute Descender,',
    'sinopse#1098': 'they entrusted the future of the world.',
    'sinopse#1099': 'Then Ange issued the ultimate quest...',
    'sinopse#1100': "Ange's quest called to breach Elan Vital",
    'sinopse#1101': 'and defend Luminasia from ruin.',
    'sinopse#1102': 'Before the Hall of Life at the core,',
    'sinopse#1103': 'Lazaris stood waiting for OO.',
    'sinopse#1104': 'Lazaris sought to seize the Hall of Life,',
    'sinopse#1105': 'stripping Luminasia of creation itself.',
    'sinopse#1106': 'Lazaris viewed creation as selfish sin.',
    'sinopse#1107': "Despite OO's pleas to live together,",
    'sinopse#1108': 'Lazaris chose bitter warfare.',
    'sinopse#1109': 'Though weakened, Lazaris fought fiercely.',
    'sinopse#1110': 'Then unbirthed souls of Zirdia manifested',
    'sinopse#1111': 'as a protective Document around Lazaris.',
    'sinopse#1112': 'Souls wishing to defend Lazaris clashed,',
    'sinopse#1113': 'resisting her desire to spare them.',
    'sinopse#1114': 'Colliding wills erupted into chaotic fury.',
    'sinopse#1115': 'Dark vortex surged.',
    'sinopse#1116': 'OO challenged Lazaris with all conviction.',
    'sinopse#1117': 'wagering the future of both worlds.',
    'sinopse#1118': "Lazaris's power exhausted, diffusing outward.",
    'sinopse#1119': 'Lazaris accepted inevitable defeat.',
    'sinopse#1120': 'Mourning the unborn souls of Zirdia,',
    'sinopse#1121': 'she dissolved into gentle luminescence.',
    'sinopse#1122': "Gathering the gentle light of Lazaris, OO",
    'sinopse#1123': 'walked peacefully toward the Hall of Life.',
    'sinopse#1124': 'Together, to create a new tomorrow.',
}
