# Translation dictionary for SINOPSE-01 (ids 0 to 319)

SINOPSE_1 = {}

# Titles 0-51
for i in range(52):
    SINOPSE_1[f'sinopse#{i}'] = f'Synopsis {i+1}'

# Narrative lines 52-319 (concise, direct narrative)
SINOPSE_1.update({
    'sinopse#52': 'Luminasia thrived by the World Tree.',
    'sinopse#53': 'In the lofty Rhubarb Mountains,',
    'sinopse#54': 'OO awakens.',
    'sinopse#55': 'Beside OO stood an unknown girl.',
    'sinopse#56': 'The girl, Kanonno, saw OO fall',
    'sinopse#57': 'from the sky and stayed near OO.',
    'sinopse#58': 'She offered to guide OO anywhere,',
    'sinopse#59': 'yet OO had nowhere to go.',
    'sinopse#60': 'No memory remained save a name.',
    'sinopse#61': 'Kanonno suggested heading to a ship.',
    'sinopse#62': 'They could decide plans once aboard.',
    'sinopse#63': 'With that, Kanonno set off with OO.',
    'sinopse#64': 'That ship was the sky vessel Van Eltia.',
    'sinopse#65': 'It serves as base for Ad Libitum,',
    'sinopse#66': 'a guild of freedom. Welcomed, OO meets',
    'sinopse#67': 'Ange, the guild leader, explaining all.',
    'sinopse#68': 'OO joined Ad Libitum to work',
    'sinopse#69': 'until memory returned.',
    'sinopse#70': 'Guided in duties by Kanonno,',
    'sinopse#71': 'OO bonded with guild companions.',
    'sinopse#72': 'Soon OO heard a curious tale.',
    'sinopse#73': 'The day OO fell, the World Tree',
    'sinopse#74': 'emitted a mysterious brilliant shine.',
    'sinopse#75': 'Falling when the Tree shone bright.',
    'sinopse#76': 'Mint likened OO to a Descender.',
    'sinopse#77': 'A Descender is a savior born from the Tree',
    'sinopse#78': 'whenever peril threatens the world.',
    'sinopse#79': 'Born anew from the World Tree,',
    'sinopse#80': 'a Descender knows neither fear nor limits,',
    'sinopse#81': 'pure and innocent.',
    'sinopse#82': 'Growing strong to guide people,',
    'sinopse#83': 'the savior brings peace.',
    'sinopse#84': 'Once peril ends, the savior returns;',
    'sinopse#85': 'prophecy long foretold this legend.',
    'sinopse#86': 'Yet few truly believe the prophecy,',
    'sinopse#87': 'taking it merely as ancient myth.',
    'sinopse#88': 'Meanwhile, Claire approached Ange',
    'sinopse#89': 'bringing a grave quest.',
    'sinopse#90': 'She asked to bring goods to Hazel Village,',
    'sinopse#91': 'her home, beside Veigue...',
    'sinopse#92': "Accepting Claire's quest, OO and Veigue",
    'sinopse#93': 'set out for Confeito Great Forest.',
    'sinopse#94': 'Hazel Village, home of Veigue and Claire,',
    'sinopse#95': 'endured forced Star Crystal mining by Urizen,',
    'sinopse#96': 'stopping villagers from farming or hunting.',
    'sinopse#97': 'Meeting village contacts in Confeito Forest',
    'sinopse#98': 'to deliver essential supplies was vital.',
    'sinopse#99': "Yet arriving there, OO's party found",
    'sinopse#100': 'no messenger from the village.',
    'sinopse#101': 'Instead stood Saleh, an Urizen knight,',
    'sinopse#102': 'and Princess Estelle of Garbanzo.',
    'sinopse#103': 'Saleh sought to capture Estelle',
    'sinopse#104': 'as political leverage for negotiation.',
    'sinopse#105': 'To rescue Estelle, OO and Veigue',
    'sinopse#106': 'fought Saleh and freed her safely.',
    'sinopse#107': 'Though the supply delivery failed,',
    'sinopse#108': 'they escorted Estelle, Yuri, and Rita',
    'sinopse#109': 'back to the guild ship.',
    'sinopse#110': 'Why did royal Estelle travel with mercenaries',
    'sinopse#111': 'like Yuri and Rita?',
    'sinopse#112': 'When Ange asked, Estelle explained',
    'sinopse#113': 'she tracked a bizarre event.',
    'sinopse#114': 'In Confeito Forest, Garbanzo mines crystals',
    'sinopse#115': 'where wildlife showed abnormal mutations.',
    'sinopse#116': 'Though the cause was unverified, rumors blamed',
    'sinopse#117': 'reckless overmining of Star Crystals.',
    'sinopse#118': 'Such talk spread widely.',
    'sinopse#119': 'Yet the kingdom launched no inquiry.',
    'sinopse#120': 'Growing impatient, Estelle set off alone,',
    'sinopse#121': 'hiring Yuri as bodyguard.',
    'sinopse#122': 'Many nations mined crystals around Confeito,',
    'sinopse#123': 'placing Urizen and Garbanzo',
    'sinopse#124': 'in tense conflict over crystals.',
    'sinopse#125': 'Saleh targeted Estelle for that reason.',
    'sinopse#126': 'Such were her circumstances.',
    'sinopse#127': 'After resting, Yuri and Rita asked',
    'sinopse#128': 'to join Ad Libitum.',
    'sinopse#129': 'Though hired as guards, they were branded',
    'sinopse#130': 'as kidnappers and wanted criminals,',
    'sinopse#131': 'unable to enter Garbanzo.',
    'sinopse#132': 'Estelle also joined to uncover',
    'sinopse#133': 'the truth behind the mine mutations.',
    'sinopse#134': 'Estelle promptly filed a quest with Ange',
    'sinopse#135': 'to inspect the creature anomalies',
    'sinopse#136': 'reported in Confeito Forest.',
    'sinopse#137': 'To inspect the creature mutations',
    'sinopse#138': 'in Confeito Forest, OO volunteered.',
    'sinopse#139': 'With client Estelle, escort Reid,',
    'sinopse#140': 'and researcher Philia, they sought',
    'sinopse#141': 'the abandoned crystal mine.',
    'sinopse#142': 'Star Crystals radiate life-giving mana.',
    'sinopse#143': 'Before mining, the forest brimmed with life.',
    'sinopse#144': 'Now monsters teemed while fauna dwindled.',
    'sinopse#145': 'Worst were the creature mutations...',
    'sinopse#146': 'Reports claimed beasts altered radically,',
    'sinopse#147': 'becoming entirely alien forms.',
    'sinopse#148': 'This happened whenever mines ran dry,',
    'sinopse#149': 'occurring here as well as',
    'sinopse#150': 'three other mining sites.',
    'sinopse#151': 'Reaching the mine, an eerie sight',
    'sinopse#152': 'greeted their eyes.',
    'sinopse#153': 'Plants turned mineral and soil decayed.',
    'sinopse#154': 'Before the stunned party, two men appeared.',
    'sinopse#155': 'They were Eugene and Tytree.',
    'sinopse#156': 'Having delivered supplies before,',
    'sinopse#157': 'Reid and Philia recognized both.',
    'sinopse#158': 'Eugene also investigated the phenomenon,',
    'sinopse#159': 'so the group invited them aboard',
    'sinopse#160': 'to converse thoroughly.',
    'sinopse#161': 'Eugene confirmed that creature changes',
    'sinopse#162': 'started whenever mining drew near its end.',
    'sinopse#163': 'That was the pattern.',
    'sinopse#164': 'First, crystal loss drained mana away,',
    'sinopse#165': 'withering soil so crops failed.',
    'sinopse#166': 'Then bizarre creature mutations followed.',
    'sinopse#167': 'Crops turned inedible and hunted game',
    'sinopse#168': 'lacked meat. Finding wholesome food',
    'sinopse#169': 'felt like a sheer miracle.',
    'sinopse#170': 'Lands lacking crystals or Tree roots exist,',
    'sinopse#171': 'yet low mana never prompted mutations',
    'sinopse#172': 'in wildlife in any of those lands',
    'sinopse#173': 'in known history.',
    'sinopse#174': 'Ad Libitum resolved to keep investigating.',
    'sinopse#175': 'That stood as guild policy.',
    'sinopse#176': 'Eugene and Tytree joined the guild',
    'sinopse#177': 'to support struggling Hazel Village',
    'sinopse#178': 'with greater efficiency.',
    'sinopse#179': 'Meanwhile, former guild members Keele',
    'sinopse#180': 'and Meredy came aboard.',
    'sinopse#181': 'They researched sustainable society,',
    'sinopse#182': 'yet their university closed from war.',
    'sinopse#183': 'Thus Keele and Meredy chose to resume',
    'sinopse#184': 'their work in Ad Libitum.',
    'sinopse#185': 'From street rumors Keele gathered info,',
    'sinopse#186': 'red smoke appeared wherever creature',
    'sinopse#187': 'mutations took place.',
    'sinopse#188': 'Altata Volcano just ceased mining,',
    'sinopse#189': 'making it ideal for inspection, so Ange',
    'sinopse#190': 'registered a new quest.',
    'sinopse#191': "Taking Ange's quest, OO ventured to the mine",
    'sinopse#192': 'at Altata Volcano alongside Will and Rubia.',
    'sinopse#193': 'Drained of mana by mining, the volcano',
    'sinopse#194': 'had turned increasingly volatile.',
    'sinopse#195': 'Before Star Crystals powered civilization,',
    'sinopse#196': 'people lived solely by World Tree mana.',
    'sinopse#197': 'Ancients revered the Tree for its bounty,',
    'sinopse#198': 'yet current society consumes crystals greedily.',
    'sinopse#199': 'Rubia prayed for a world without crystals.',
    'sinopse#200': 'To achieve this, Olta Village was vital.',
    'sinopse#201': 'It must succeed.',
    'sinopse#202': 'Keele studied sustainable society where',
    'sinopse#203': 'man lives in harmony with nature,',
    'sinopse#204': 'ensuring food and shelter.',
    'sinopse#205': 'Building Olta Village on such ideals',
    'sinopse#206': 'was the core purpose of Ad Libitum.',
    'sinopse#207': 'Reaching the mine, countless dead',
    'sinopse#208': 'Kokuyo jewel beetles lay around.',
    'sinopse#209': 'As Will mourned the precious insects,',
    'sinopse#210': 'red smoke rose from earth.',
    'sinopse#211': 'Moving willfully, the smoke wrapped',
    'sinopse#212': 'one living beetle and vanished.',
    'sinopse#213': 'Seeing it was no simple gas, Will collected',
    'sinopse#214': 'the beetle touched by the smoke.',
    'sinopse#215': 'The bug remained alive.',
    'sinopse#216': 'Perhaps red smoke triggered mutation.',
    'sinopse#217': 'They brought the bug back to observe.',
    'sinopse#218': 'The eerie red smoke.',
    'sinopse#219': 'Will noted that the smoke targeted',
    'sinopse#220': 'only the living beetle.',
    'sinopse#221': 'Inspecting the beetle showed no change,',
    'sinopse#222': 'so they kept it in the laboratory',
    'sinopse#223': 'for observation.',
    'sinopse#224': 'Some time later,',
    'sinopse#225': 'Joan of Morado Village arrived',
    'sinopse#226': 'seeking guild aid.',
    'sinopse#227': 'Joan coughed painfully and looked pale.',
    'sinopse#228': 'He could barely breathe.',
    'sinopse#229': 'Medicine could not treat his ailment.',
    'sinopse#230': 'Doctors had abandoned hope entirely.',
    'sinopse#231': "Joan's quest sought escort into Brownie Mine",
    'sinopse#232': 'to reach an entity rumored to heal sickness.',
    'sinopse#233': 'He begged for help.',
    'sinopse#234': "Ange hesitated, yet seeing Joan's agony,",
    'sinopse#235': 'she could not turn him away.',
    'sinopse#236': 'OO took charge of escorting Joan,',
    'sinopse#237': 'heading for Brownie Mine with Farah and Marta.',
    'sinopse#238': 'What was this healing entity?',
    'sinopse#239': 'In Morado Village, a man named Miguel',
    'sinopse#240': 'had suffered the same sickness.',
    'sinopse#241': 'Heading through the mine to seek a doctor,',
    'sinopse#242': 'Miguel collapsed along the route',
    'sinopse#243': 'and anticipated death.',
    'sinopse#244': 'Yet when Miguel wished fiercely to live,',
    'sinopse#245': 'red smoke materialized out of nowhere.',
    'sinopse#246': 'Engulfing Miguel, the smoke vanished,',
    'sinopse#247': 'curing his sickness instantly.',
    'sinopse#248': 'The party doubted such a tale.',
    'sinopse#249': "Yet OO's party witnessed the phenomenon.",
    'sinopse#250': 'Joan touched the red smoke.',
    'sinopse#251': "Joan's illness cleared instantly,",
    'sinopse#252': 'restoring him to energetic vitality.',
    'sinopse#253': 'Recalling the smoke and beetle, OO felt',
    'sinopse#254': 'unease rising swiftly.',
    'sinopse#255': 'They left the mine with troubled minds.',
    'sinopse#256': 'The red smoke might cause mutation.',
    'sinopse#257': 'Nothing was certain yet.',
    'sinopse#258': 'They only knew red smoke and mutations',
    'sinopse#259': 'actually existed.',
    'sinopse#260': 'The true link remained mystery.',
    'sinopse#261': 'Meanwhile, requests flooded Ad Libitum',
    'sinopse#262': 'seeking the miraculous healing entity.',
    'sinopse#263': 'Rumors spread far and wide.',
    'sinopse#264': 'Uncertain if the smoke posed danger,',
    'sinopse#265': 'Ange refused to expose civilians',
    'sinopse#266': 'and rejected those requests.',
    'sinopse#267': 'At Ange\'s call, Spada joined the guild.',
    'sinopse#268': 'He enlisted.',
    'sinopse#269': 'From intel Spada gathered earlier,',
    'sinopse#270': 'the red smoke was widely known.',
    'sinopse#271': 'Intriguingly, rumors claimed',
    'sinopse#272': 'the smoke appeared differently to each.',
    'sinopse#273': 'Why would formless smoke take shape?',
    'sinopse#274': 'Once plain smoke, it now appeared',
    'sinopse#275': 'like flowers, bugs, or fish.',
    'sinopse#276': 'Changes spread among the populace.',
    'sinopse#277': 'Perception shifted from healing sickness',
    'sinopse#278': 'to granting any wish imaginable.',
    'sinopse#279': 'The myth grew larger.',
    'sinopse#280': 'Hearing this, Ange sensed peril.',
    'sinopse#281': 'The threat felt real.',
    'sinopse#282': 'She feared countless people would seek it...',
    'sinopse#283': 'Danger approached.',
    'sinopse#284': 'Meanwhile, the captive beetle changed.',
    'sinopse#285': 'Spiracles vanished; eyes and mouth disappeared.',
    'sinopse#286': 'Its flesh transformed into rock-like mineral.',
    'sinopse#287': 'Was red smoke responsible?',
    'sinopse#288': 'Likely so, yet Harold wanted',
    'sinopse#289': 'to examine another specimen.',
    'sinopse#290': 'Then Thomas, chief of Morado Village,',
    'sinopse#291': 'arrived aboard.',
    'sinopse#292': 'He brought an unusual quest.',
    'sinopse#293': 'Thomas asked to abandon a beast',
    'sinopse#294': 'at an oasis in Kadaif Desert.',
    'sinopse#295': 'The monster invaded his village',
    'sinopse#296': 'and was trapped in a cage.',
    'sinopse#297': 'Why abandon it instead of slaying?',
    'sinopse#298': 'Thomas merely said they lacked heart',
    'sinopse#299': 'to execute it.',
    'sinopse#300': 'The terms: do not look inside,',
    'sinopse#301': 'haul cage to oasis, unlock, and leave.',
    'sinopse#302': 'Reaching the oasis revealed a shock.',
    'sinopse#303': 'Inside were humans, not beasts.',
    'sinopse#304': 'It was Joan, the former client,',
    'sinopse#305': 'and Miguel, also touched by smoke.',
    'sinopse#306': 'Their bodies suffered grotesque mutation,',
    'sinopse#307': 'just like the beetle.',
    'sinopse#308': 'They explained that mutation began',
    'sinopse#309': 'shortly after recovery.',
    'sinopse#310': 'Losing sanity, they attacked the town',
    'sinopse#311': 'and were cast out in cages.',
    'sinopse#312': 'They wept, unable to return home.',
    'sinopse#313': 'Suddenly, OO reached out toward them.',
    'sinopse#314': 'Even OO knew not why.',
    'sinopse#315': "Yet OO's outstretched hands shone",
    'sinopse#316': 'with rainbow light.',
    'sinopse#317': 'Wrapped in light, both regained human form.',
    'sinopse#318': 'Though joyous at their restoration,',
    'sinopse#319': 'their faces soon fell.',
})
