# Translation dictionary for SINOPSE-03 (ids 640 to 959)

SINOPSE_3 = {
    'sinopse#640': 'or become denizens of Zirdia.',
    'sinopse#641': 'Lazaris could not easily control it,',
    'sinopse#642': 'risking mutual annihilation at worst.',
    'sinopse#643': 'Fangs manifested by Lazaris corroded',
    'sinopse#644': "Luminasia's Document, rewriting reality.",
    'sinopse#645': 'Furthermore, Lazaris and her realm, Zirdia,',
    'sinopse#646': 'were sealed within a dimensional prison',
    'sinopse#647': 'fashioned from Star Crystals.',
    'sinopse#648': 'To reseal Lazaris, crystals were vital,',
    'sinopse#649': 'yet overmining left the world depleted.',
    'sinopse#650': 'Niata revealed three Document materials',
    'sinopse#651': 'could forge a substitute crystal matrix',
    'sinopse#652': 'via Soul Alchemy, requiring retrieval',
    'sinopse#653': 'of the rare Salt Crystal.',
    'sinopse#654': 'Salt Crystal was needed for sealing,',
    'sinopse#655': 'along with two rare organic components.',
    'sinopse#656': 'To gather Salt Crystal, OO went',
    'sinopse#657': 'into the depths of Brownie Mine.',
    'sinopse#658': 'Suddenly, a brute blocked OO and friends,',
    'sinopse#659': 'barring their forward path.',
    'sinopse#660': 'It was Barbatos, infamous as a warrior',
    'sinopse#661': 'who attacked any strong opponent.',
    'sinopse#662': 'He had been hurled to Luminasia',
    'sinopse#663': 'along with Kyle from another world.',
    'sinopse#664': 'OO and Sheena stood watchful,',
    'sinopse#665': 'yet reckless Kyle charged ahead.',
    'sinopse#666': "Through OO's strength, they drove Barbatos",
    'sinopse#667': 'away, leaving reckless Kyle',
    'sinopse#668': "facing Sheena's stern reprimand.",
    'sinopse#669': 'Securing the precious Salt Crystal,',
    'sinopse#670': "OO's party returned to the ship.",
    'sinopse#671': 'The remaining two sealing items were found.',
    'sinopse#672': 'Bell-Dragonfly Grass and Spiral Gall.',
    'sinopse#673': "Both appeared in Kanonno's sketches,",
    'sinopse#674': 'matching lore provided by Niata,',
    'sinopse#675': 'as Judith discerned.',
    'sinopse#676': 'Yet both species were long extinct.',
    'sinopse#677': 'Why she envisioned unseen landscapes',
    'sinopse#678': 'weighed heavily on Kanonno.',
    'sinopse#679': 'OO was troubled by doubts as well.',
    'sinopse#680': 'Zirdia was destined to wither alone.',
    'sinopse#681': 'The tragic world of Lazaris.',
    'sinopse#682': 'Why did the Tree assimilate it?',
    'sinopse#683': 'Why absorb a realm that brought ruin',
    'sinopse#684': 'and seal it away?',
    'sinopse#685': 'Kanonno and OO sought',
    'sinopse#686': "to understand the Tree's true intent.",
    'sinopse#687': 'Judith and Rocks shared curious tales',
    'sinopse#688': 'regarding Kanonno.',
    'sinopse#689': 'Landscapes and Documents seen by Kanonno alone.',
    'sinopse#690': 'Kanonno held a profound secret.',
    'sinopse#691': 'Jade requested an inspection of the fangs.',
    'sinopse#692': 'He submitted a quest.',
    'sinopse#693': 'To investigate the fangs raised by Lazaris,',
    'sinopse#694': "they utilized a Copyist's Rod to extract",
    'sinopse#695': "the fang's Document directly.",
    'sinopse#696': 'Accompanied by Judas and Lloyd, OO headed',
    'sinopse#697': 'for Altata Volcano where the fang sprouted.',
    'sinopse#698': 'Deeper in, beasts twisted unnaturally.',
    'sinopse#699': 'Mutations spread everywhere.',
    'sinopse#700': "Zirdia's alien Document seemed flowing",
    'sinopse#701': 'outward through the colossal fang.',
    'sinopse#702': 'Reaching the fang, they were breathless',
    'sinopse#703': 'at the bizarrely beautiful vista.',
    'sinopse#704': "Sampling the fang's Document, OO gazed",
    'sinopse#705': 'at open palms and unleashed rainbow light.',
    'sinopse#706': 'The corrupted surroundings were restored.',
    'sinopse#707': 'Yet the fang itself resisted even',
    'sinopse#708': "the Descender's radiant power.",
    'sinopse#709': 'Refugees from Hazel Village and Joan',
    'sinopse#710': 'worked alongside settlers in Olta Village,',
    'sinopse#711': 'sending letters to Ange.',
    'sinopse#712': 'Yet the news was not entirely bright.',
    'sinopse#713': 'Diverse backgrounds caused friction',
    'sinopse#714': 'and clashes of cultural values.',
    'sinopse#715': 'Rocks suggested guiding through affirmation,',
    'sinopse#716': 'supporting Ange warmly.',
    'sinopse#717': "Analysis of the fang's Document concluded.",
    'sinopse#718': 'It revealed the fang acted as a conduit',
    'sinopse#719': 'pumping Zirdian data into Luminasia.',
    'sinopse#720': "This matched Niata's earlier findings.",
    'sinopse#721': 'Corruption radiated from around the fang,',
    'sinopse#722': 'spreading continuously as long as it stood.',
    'sinopse#723': 'Though OO possessed restorative powers,',
    'sinopse#724': 'mortal limits loomed.',
    'sinopse#725': 'To halt corruption, the crystal seal',
    'sinopse#726': 'had to be constructed immediately.',
    'sinopse#727': 'Two essential ingredients remained.',
    'sinopse#728': 'Will suggested retrieving a fossil',
    'sinopse#729': 'of Bell-Dragonfly Grass.',
    'sinopse#730': 'To retrieve this ancient fossil,',
    'sinopse#731': 'OO set out for Almanac Ruins.',
    'sinopse#732': 'Even a fossil might yield faint traces',
    'sinopse#733': 'of the original Document.',
    'sinopse#734': "The fossil rested in the ruins' sanctum,",
    'sinopse#735': 'the Hall of the Ode to Life.',
    'sinopse#736': 'Ruca felt deeply hesitant to disturb',
    'sinopse#737': 'a designated world heritage site.',
    'sinopse#738': 'Delivered to the lab, analysis began.',
    'sinopse#739': 'Meanwhile, social friction in Olta Village',
    'sinopse#740': "eased through Rocks's thoughtful proposal.",
    'sinopse#741': 'Ange and Rocks rejoiced gladly.',
    'sinopse#742': "Ad Libitum's long-cherished dream advanced.",
    'sinopse#743': 'Estelle and Natalia celebrated Olta Village,',
    'sinopse#744': 'confident that distinct nations could unite',
    'sinopse#745': 'in mutual harmony and peace.',
    'sinopse#746': 'Meanwhile, Kanonno sought answers for why',
    'sinopse#747': 'she envisioned unseen vistas and wrote',
    'sinopse#748': 'ancient scripts unconsciously.',
    'sinopse#749': 'Judith thought Niata might comprehend.',
    'sinopse#750': 'Niata was the sage who witnessed genesis',
    'sinopse#751': 'and surveyed countless different realms.',
    'sinopse#752': 'Kanonno longed to consult Niata directly.',
    'sinopse#753': 'Even if communication seemed difficult,',
    'sinopse#754': 'Kanonno pleaded to journey to Veratropa.',
    'sinopse#755': 'Escorting Kanonno to Veratropa,',
    'sinopse#756': 'OO ventured into the ancient ruins.',
    'sinopse#757': 'En route, OO recalled words from Judith.',
    'sinopse#758': 'Reflections on the past.',
    'sinopse#759': 'Kanonno resembled the ancient Descender',
    'sinopse#760': 'whom Niata had served, sharing a name.',
    'sinopse#761': 'Reaching Niata and calling out, the shattered',
    'sinopse#762': 'relic began self-repairing to wholeness.',
    'sinopse#763': 'Niata rejoiced at reuniting with Kanonno.',
    'sinopse#764': 'As Kanonno stood bewildered, OO shared',
    'sinopse#765': 'the lore learned from Judith.',
    'sinopse#766': 'Though confused, Kanonno presented',
    'sinopse#767': 'her sketchbook to Niata.',
    'sinopse#768': 'Niata recognized that the painted scenes',
    'sinopse#769': 'were realms Niata had visited long ago.',
    'sinopse#770': 'Niata deduced that Kanonno inherited factors',
    'sinopse#771': 'from a vanished primeval world.',
    'sinopse#772': 'As they spoke, footsteps approached rapidly.',
    'sinopse#773': 'The voice belonged to Rocks.',
    'sinopse#774': 'The Van Eltia lost altitude and plunged.',
    'sinopse#775': 'OO and allies were stranded on Veratropa.',
    'sinopse#776': 'Isolation threatened the group.',
    'sinopse#777': 'Yet Niata enveloped OO and allies in light,',
    'sinopse#778': 'returning them safely to the vessel.',
    'sinopse#779': "The ship recovered under Niata's counsel.",
    'sinopse#780': 'Crucially, they discovered the Van Eltia',
    'sinopse#781': 'ran on a semi-perpetual engine instead',
    'sinopse#782': 'of consuming Star Crystals.',
    'sinopse#783': 'This discovery offered a beacon of hope',
    'sinopse#784': 'for resource-depleted Luminasia.',
    'sinopse#785': 'Another breakthrough soon followed.',
    'sinopse#786': 'A new Ring Spot was located.',
    'sinopse#787': "To amplify the Sorcerer's Ring,",
    'sinopse#788': 'OO headed for the Kadaif Desert.',
    'sinopse#789': 'The Ring Spot lay within the Red Oasis,',
    'sinopse#790': 'a spring rich in iron minerals.',
    'sinopse#791': 'Spring water gushed out red.',
    'sinopse#792': 'Finding the spot, OO empowered the ring',
    'sinopse#793': 'and returned to the Van Eltia.',
    'sinopse#794': 'Meanwhile, analysis of the fossil revealed',
    'sinopse#795': 'mostly mineralized data, yielding almost',
    'sinopse#796': 'no original organic Document.',
    'sinopse#797': 'Rita shared this obstacle with Niata.',
    'sinopse#798': 'Niata noted environmental shifts altered',
    'sinopse#799': 'species through evolution and hybridization,',
    'sinopse#800': 'feeling deep disappointment.',
    'sinopse#801': 'Yet this sparked an epiphany for Rita:',
    'sinopse#802': 'gathering Documents from descendant species',
    'sinopse#803': 'to reconstruct the ancestral plant.',
    'sinopse#804': 'With roughly 2,000 descendant species,',
    'sinopse#805': 'allies and global guilds assisted',
    'sinopse#806': 'in harvesting safer varieties.',
    'sinopse#807': 'Assistance was rallied worldwide.',
    'sinopse#808': 'Ad Libitum targeted perilous specimens',
    'sinopse#809': 'obtainable only by elite members.',
    'sinopse#810': 'Starting with the Oil Tree on Mt. Absoule,',
    'sinopse#811': 'OO set out with Veigue and Spada.',
    'sinopse#812': 'En route, a faint cry carried on the wind.',
    'sinopse#813': "it was Claire's desperate scream.",
    'sinopse#814': 'Rushing forward, they found Saleh holding',
    'sinopse#815': 'Claire captive as a hostage.',
    'sinopse#816': 'Spurred by grudge against Ad Libitum, Saleh',
    'sinopse#817': 'intended to lure Veigue into a trap,',
    'sinopse#818': 'yet Veigue arrived coincidentally.',
    'sinopse#819': 'Saleh attacked with immense confidence,',
    'sinopse#820': "yet fell before OO's guild allies.",
    'sinopse#821': 'Ignoring Saleh, Veigue collected',
    'sinopse#822': "the Oil Tree's Document,",
    'sinopse#823': 'and OO escorted Claire safely back.',
    'sinopse#824': 'Aboard the ship, descendant specimens',
    'sinopse#825': 'arrived steadily from across lands.',
    'sinopse#826': 'Data was prepared for the next target.',
    'sinopse#827': 'Plans advanced smoothly.',
    'sinopse#828': 'The next objective was a rare flower',
    'sinopse#829': 'capable of gliding smoothly over water.',
    'sinopse#830': 'Briefings were finalized.',
    'sinopse#831': 'Ange registered it as a quest,',
    'sinopse#832': 'awaiting suitable candidates.',
    'sinopse#833': 'This plant was the Yulung Tree, located',
    'sinopse#834': 'deep within Sifno Cave.',
    'sinopse#835': 'Accepting the extraction quest, OO',
    'sinopse#836': 'departed alongside Natalia and Asch.',
    'sinopse#837': 'They harvested the Document of this tree,',
    'sinopse#838': 'which adapted without crowding rivals.',
    'sinopse#839': 'Seeing this resilient tree, OO realized',
    'sinopse#840': 'peoples and realms could evolve in harmony,',
    'sinopse#841': 'returning with renewed hope.',
    'sinopse#842': 'More specimens arrived aboard the vessel.',
    'sinopse#843': 'Together, Ad Libitum processed Documents,',
    'sinopse#844': 'extracting essential data diligently.',
    'sinopse#845': 'Watching everyone unite against hardship,',
    'sinopse#846': 'Ange felt profoundly grateful for founding',
    'sinopse#847': 'this extraordinary guild.',
    'sinopse#848': 'Facing adversity, Ad Libitum pushed onward.',
    'sinopse#849': 'Observing this, Niata mentioned Ad Libitum',
    'sinopse#850': 'also existed in the parallel world Granide.',
    'sinopse#851': 'The Van Eltia and its companions existed',
    'sinopse#852': 'within the parallel realm of Granide.',
    'sinopse#853': 'Kanonno pondered why worlds were born',
    'sinopse#854': 'and why memories endured across time,',
    'sinopse#855': 'lost in deep thought.',
    'sinopse#856': 'Meanwhile, regional wars ceased worldwide.',
    'sinopse#857': "The emergence of Zirdia's colossal fangs",
    'sinopse#858': 'convinced rulers war was futile.',
    'sinopse#859': 'Natalia noted that shared peril taught',
    'sinopse#860': 'mankind to clasp hands across borders.',
    'sinopse#861': 'She spoke with deep conviction.',
    'sinopse#862': 'With this awareness, nations could unite,',
    'sinopse#863': 'fostering a truly integrated world.',
    'sinopse#864': 'A civilization where all share resources',
    'sinopse#865': 'equitably with one another.',
    'sinopse#866': 'Specimen collection reached its finale as OO',
    'sinopse#867': 'headed to Kadaif Desert with Stahn and Loni',
    'sinopse#868': 'to harvest the Wandering Grass.',
    'sinopse#869': 'Entering the grove, harsh air irritated',
    'sinopse#870': 'their eyes and parched their throats.',
    'sinopse#871': 'Venturing deeper, Lazaris stood waiting.',
    'sinopse#872': 'She was reshaping the environment',
    'sinopse#873': 'to sustain life from her lost world.',
    'sinopse#874': 'Among the mutant beasts stood former humans.',
    'sinopse#875': 'When OO approached to restore them,',
    'sinopse#876': 'they shrank back toward Lazaris in fear.',
    'sinopse#877': 'refusing to return to human form.',
    'sinopse#878': 'Despairing of Luminasia, those souls',
    'sinopse#879': 'chose mutation willingly.',
    'sinopse#880': 'Though they pleaded, Lazaris departed,',
    'sinopse#881': 'leaving words echoing in vain.',
    'sinopse#882': 'Purifying the blighted soil, OO hung',
    'sinopse#883': 'a head in bitter grief.',
    'sinopse#884': 'Returning with the grass Document, news came',
    'sinopse#885': 'that two more fangs had sprouted.',
    'sinopse#886': 'Unless halted quickly, corruption would',
    'sinopse#887': 'accelerate drastically.',
    'sinopse#888': 'Fortunately, the grass Document allowed',
    'sinopse#889': 'reconstruction of Bell-Dragonfly Grass.',
    'sinopse#890': 'Only the Spiral Gall remained to locate.',
    'sinopse#891': 'Could a surviving specimen truly exist',
    'sinopse#892': 'somewhere in the world?',
    'sinopse#893': 'Zirdia was an unborn twin realm within Luminasia.',
    'sinopse#894': 'Different worlds with contrasting laws.',
    'sinopse#895': 'Witnessing genesis, Niata reflected on history.',
    'sinopse#896': 'Absorbing Zirdia triggered upheaval',
    'sinopse#897': 'beyond all human description.',
    'sinopse#898': 'Without the seal, the world could not',
    'sinopse#899': 'have sustained its existence.',
    'sinopse#900': 'Had the seal shattered completely, primordial',
    'sinopse#901': 'upheaval would have recurred instantly.',
    'sinopse#902': 'Yet no catastrophic collapse had occurred.',
    'sinopse#903': 'Perhaps the World Tree gained stability',
    'sinopse#904': 'over eons, prompting endless speculation.',
    'sinopse#905': 'The party sought the true intentions',
    'sinopse#906': 'OO and companions sought the true motive.',
    'sinopse#907': 'Kanonno learned from Rocks that she painted',
    'sinopse#908': 'her parents without knowing.',
    'sinopse#909': 'To uncover memories hidden within herself,',
    'sinopse#910': 'Kanonno asked to deploy her Document.',
    'sinopse#911': 'Yet detailed deployment carried grave risk.',
    'sinopse#912': 'drawing immediate objections from all.',
    'sinopse#913': 'Niata pondered and proposed an alternative.',
    'sinopse#914': 'Besides deployment, one other method',
    'sinopse#915': 'could access past memories.',
    'sinopse#916': 'Though still perilous, it was far safer.',
    'sinopse#917': 'It required visiting the Vortex where',
    'sinopse#918': 'World Tree mana churned intensely.',
    'sinopse#919': "To uncover Kanonno's gifts, OO and Kanonno",
    'sinopse#920': 'journeyed to holy ground Langrees.',
    'sinopse#921': 'At the Vortex where potent mana swirled,',
    'sinopse#922': "OO dove deep into Kanonno's consciousness.",
    'sinopse#923': 'The mental dive commenced.',
    'sinopse#924': 'Tracing paths of memory through worlds,',
    'sinopse#925': 'they encountered Original Kanonno, embodiment',
    'sinopse#926': 'of the primeval World Tree itself.',
    'sinopse#927': 'Original Kanonno revealed that Luminasia,',
    'sinopse#928': 'and Zirdia were siblings of shared root.',
    'sinopse#929': 'The Tree sealed Zirdia to reshape Luminasia',
    'sinopse#930': 'until both realms could harmoniously coexist.',
    'sinopse#931': 'Such was the primordial design.',
    'sinopse#932': 'Star Crystals acted both as a firm seal,',
    'sinopse#933': 'and a nurturing cradle for Zirdia.',
    'sinopse#934': 'So both could aid each other in distant days.',
    'sinopse#935': 'To create tomorrow together...',
    'sinopse#936': 'Yet for now, Lazaris had to be sealed.',
    'sinopse#937': 'The seal remained imperative.',
    'sinopse#938': 'Their conflicting laws were too disparate',
    'sinopse#939': 'for mutual survival at present.',
    'sinopse#940': 'Bathed in dense mana, Kanonno felt discord',
    'sinopse#941': 'between body and spirit even back on ship.',
    'sinopse#942': 'Sitting for a meal, Kanonno perceived',
    'sinopse#943': 'Documents glowing within companions.',
    'sinopse#944': 'Not just mortals, but food possessed Documents.',
    'sinopse#945': "The food's Document integrated inside",
    'sinopse#946': 'those partaking of nourishment.',
    'sinopse#947': 'Documents were life, and life sustained life.',
    'sinopse#948': 'This proved a profound realization.',
    'sinopse#949': 'Soon, the grass Document was completed.',
    'sinopse#950': 'Yet celebration was premature.',
    'sinopse#951': 'Sprouting fangs hastened world corruption.',
    'sinopse#952': 'Nations resumed fighting over dwindling soil.',
    'sinopse#953': 'Fragile unity shattered before sheer panic.',
    'sinopse#954': 'Terror triumphed over reason.',
    'sinopse#955': 'Even a Descender could not destroy fangs,',
    'sinopse#956': 'though corruption could be cleansed.',
    'sinopse#957': 'Sophie wished everyone held that power.',
    'sinopse#958': "Inspired by Sophie's words, Harold set out",
    'sinopse#959': 'to enable Document transcription of abilities.',
}
