# SKITBDI-01 translation mapping (ids 0 to 319)
# All ASCII, <= 63 bytes, natural English Tales skit titles

SKITBDI_1 = {
    'skitbdi#0': 'Hope Arrives!',
    'skitbdi#1': 'Crossing Orb of Light',
    'skitbdi#2': 'Descending Light',
    'skitbdi#3': 'Awakening',
    'skitbdi#4': 'First Battle',
    'skitbdi#5': 'Amnesia and Stupefaction',
    'skitbdi#6': 'A Ship Approaches',
    'skitbdi#7': 'The Van Eltia Appears',
    'skitbdi#8': 'A Guild Called Freedom',
    'skitbdi#9': 'Introductions: Cress & Mint',
    'skitbdi#10': 'Introductions: Emil & Marta',
    'skitbdi#11': 'Introductions: Kratos',
    'skitbdi#12': 'Introductions: Stahn & Rutee',
    'skitbdi#13': 'Introductions: Philia',
    'skitbdi#14': 'Introductions: Senel & Shirley',
    'skitbdi#15': 'Introductions: Reid & Farah',
    'skitbdi#16': 'Introductions: Veigue',
    'skitbdi#17': 'Introductions: Caius & Rubia',
    'skitbdi#18': 'Introductions: Ruca & Iria',
    'skitbdi#19': 'Introductions: Shing & Kohaku',
    'skitbdi#20': 'Introductions: Chat',
    'skitbdi#21': 'Introductions: Annie',
    'skitbdi#22': 'Introductions: Will',
    'skitbdi#23': 'Introductions: Rocks & Claire',
    'skitbdi#24': 'What Is Ad Libitum?',
    'skitbdi#25': 'The Prophecy',
    'skitbdi#26': 'The World & Astral Crystals',
    'skitbdi#27': 'Scent of Cinnamon',
    'skitbdi#28': "Claire's Somber Look",
    'skitbdi#29': 'Harold & Nanaly Board the Ship',
    'skitbdi#30': 'Kanonno & the Sketchbook',
    'skitbdi#31': 'Kanonno & Drawings',
    'skitbdi#32': "Claire's Request",
    'skitbdi#33': 'Job in Hazele Village',
    'skitbdi#34': 'Imperial Tyranny',
    'skitbdi#35': 'A Man Named Saleh',
    'skitbdi#36': 'Estelle in Danger!',
    'skitbdi#37': 'Saleh Rematch (1)',
    'skitbdi#38': 'Yuri Appears',
    'skitbdi#39': 'Supplies Undelivered...',
    'skitbdi#40': "Estelle's Travel Motive",
    'skitbdi#41': 'Claire Thinking of Hazele',
    'skitbdi#42': 'Estelle Is Kind',
    'skitbdi#43': 'Yuri Joins the Guild!',
    'skitbdi#44': 'Request from Estelle',
    'skitbdi#45': 'To the Crystal Mine Ruins',
    'skitbdi#46': 'Altered Creatures?',
    'skitbdi#47': 'Great Powers & Economy',
    'skitbdi#48': 'Defeat the Mega Ota!',
    'skitbdi#49': 'Mega Ota Rematch',
    'skitbdi#50': 'Secret Path',
    'skitbdi#51': 'Tytree & Eugene Arrive',
    'skitbdi#52': 'Guiding Eugene and Tytree',
    'skitbdi#53': 'Hazele Village Anguish',
    'skitbdi#54': 'Estelle, How to Investigate?',
    'skitbdi#55': 'Keele & Meredy Arrive',
    'skitbdi#56': 'Rumors of Red Smoke',
    'skitbdi#57': 'Mine Ruins Survey: Part 2',
    'skitbdi#58': 'What Is the Red Smoke?',
    'skitbdi#59': 'World of Mana & World Tree',
    'skitbdi#60': 'Black Jewel Beetle & Smoke',
    'skitbdi#61': 'The Red Smoke Was Real',
    'skitbdi#62': 'Raven & Judith Board Ship',
    'skitbdi#63': "Joan's Request",
    'skitbdi#64': "Joan's Escort",
    'skitbdi#65': 'Curing Sickness?',
    'skitbdi#66': 'Joan Clears the Dead End',
    'skitbdi#67': 'Cured by Red Smoke',
    'skitbdi#68': 'Defeat the Stone Golem!',
    'skitbdi#69': 'Stone Golem Rematch',
    'skitbdi#70': 'Joan Fully Cured',
    'skitbdi#71': 'Is Joan All Right?',
    'skitbdi#72': 'Spada Appears',
    'skitbdi#73': 'Introductions: Spada',
    'skitbdi#74': 'Where Is the Scenery Seen?',
    'skitbdi#75': "Iria's Scream",
    'skitbdi#76': 'Black Jewel Beetle Change',
    'skitbdi#77': 'Molad Chief Request',
    'skitbdi#78': 'Abandoning Monsters?',
    'skitbdi#79': "Don't Look in the Cage",
    'skitbdi#80': 'Defeat the Sandworm!',
    'skitbdi#81': 'Sandworm Rematch',
    'skitbdi#82': 'Victory Over Sandworm',
    'skitbdi#83': 'A Groan',
    'skitbdi#84': 'Monsters Attack the Cage',
    'skitbdi#85': 'Sandfang Rematch',
    'skitbdi#86': 'Rainbow Light',
    'skitbdi#87': 'Cause of Creature Mutation',
    'skitbdi#88': 'Miguel & Joan: All Clear',
    'skitbdi#89': 'New Rumors',
    'skitbdi#90': 'Arche Appears',
    'skitbdi#91': 'Do Spirits Truly Exist?',
    'skitbdi#92': 'Awaiting the Descender',
    'skitbdi#93': 'To Mibuna Village',
    'skitbdi#94': 'Mibuna, Village of Shinobi',
    'skitbdi#95': 'Shinobi Secret Passage',
    'skitbdi#96': 'Voices in the Mine',
    'skitbdi#97': 'Defeat Stone Shisa!',
    'skitbdi#98': 'Stone Shisa Rematch',
    'skitbdi#99': 'Sheena Appears',
    'skitbdi#100': 'Kouki Arts & Soul Alchemy',
    'skitbdi#101': 'Introductions: Sheena',
    'skitbdi#102': 'Introductions: Lloyd, Colette, Suzu',
    'skitbdi#103': 'Kouki Sutra',
    'skitbdi#104': 'Theory of Soul Alchemy',
    'skitbdi#105': 'Something Called Docment',
    'skitbdi#106': 'How to Make Artificial Spirits',
    'skitbdi#107': 'Red Smoke in Rhubarb Range',
    'skitbdi#108': 'Investigating the Red Smoke',
    'skitbdi#109': 'Turning Climbers Back',
    'skitbdi#110': 'The Sealed Path',
    'skitbdi#111': "Tytree's Irritation",
    'skitbdi#112': 'Dawn Cultists Appear',
    'skitbdi#113': 'Smoke into Human Form...',
    'skitbdi#114': 'Anomalous Docment',
    'skitbdi#115': 'Consciousness Is a Docment',
    'skitbdi#116': 'Asbel & Sophie Board Ship',
    'skitbdi#117': 'Asbel & Sophie Join Battle',
    'skitbdi#118': 'Jade, Natalia, Tear Arrive',
    'skitbdi#119': 'Intel on the Dawn Cult',
    'skitbdi#120': 'Natalia & Estelle',
    'skitbdi#121': 'To the Dawn Cult Base',
    'skitbdi#122': 'Wish-Granting Descender',
    'skitbdi#123': 'Showdown! Dawn Cultists',
    'skitbdi#124': 'Dawn Cultists Rematch',
    'skitbdi#125': 'Cultists Take Bizarre Forms',
    'skitbdi#126': 'Lazaris Appears',
    'skitbdi#127': 'Who Is Lazaris?',
    'skitbdi#128': "Lazaris's Wrath",
    'skitbdi#129': "Lazaris's Solo March",
    'skitbdi#130': 'Mystery of Rainbow Light',
    'skitbdi#131': "Lazaris's Bitter Spite",
    'skitbdi#132': 'Snack Time',
    'skitbdi#133': "About Kanonno's Parents",
    'skitbdi#134': 'Kanonno Thinking of Parents',
    'skitbdi#135': "Jade's Comrades Arrived?",
    'skitbdi#136': 'Luke, Asch, Van Join In',
    'skitbdi#137': 'Where to Meet Spirits',
    'skitbdi#138': 'Snow Mountain of Spirits',
    'skitbdi#139': 'When Meeting a Spirit...',
    'skitbdi#140': 'Conditions for Rich Mana',
    'skitbdi#141': 'Richter, Guardian of Spirits',
    'skitbdi#142': 'Richter Rematch',
    'skitbdi#143': 'The Spirit of Ice',
    'skitbdi#144': 'You Are the Descender',
    'skitbdi#145': 'Truly the Descender?',
    'skitbdi#146': 'Richter & Celsius Join',
    'skitbdi#147': 'Ancestors of Humanity',
    'skitbdi#148': 'Is the Descender Powerless?',
    'skitbdi#149': 'How to Reach Veratropa',
    'skitbdi#150': 'Failed Test & Mystery Voice',
    'skitbdi#151': 'People Falling on Ship',
    'skitbdi#152': "Kyle's Party Hurled Across",
    'skitbdi#153': "Kyle's Party Joins Battle",
    'skitbdi#154': 'Barbatos Appears',
    'skitbdi#155': 'Parent and Child Meet',
    'skitbdi#156': "Eugene's Request",
    'skitbdi#157': 'New Land for Hazele Folk',
    'skitbdi#158': 'Learned After Leaving Home',
    'skitbdi#159': 'Suzu Opens the Door',
    'skitbdi#160': 'Where Is Tyrampion?',
    'skitbdi#161': 'Defeat Tyrampion!',
    'skitbdi#162': 'Tyrampion Rematch',
    'skitbdi#163': "Saleh's Shadow",
    'skitbdi#164': 'Grateful Eugene',
    'skitbdi#165': 'Harold Pondering',
    'skitbdi#166': 'Where Is Celsius?',
    'skitbdi#167': 'Painting of Veratropa',
    'skitbdi#168': 'Kanonno Paints a Mystery',
    'skitbdi#169': "Kanonno's Docment",
    'skitbdi#170': 'Dimensional Tuner Finished',
    'skitbdi#171': 'Veratropa Appears',
    'skitbdi#172': 'Who Goes to Veratropa?',
    'skitbdi#173': 'Reserve File',
    'skitbdi#174': 'Veratropa Expedition',
    'skitbdi#175': 'Ancestral Lands Reached',
    'skitbdi#176': 'The First Mural',
    'skitbdi#177': 'The Second Mural',
    'skitbdi#178': 'The Third Mural',
    'skitbdi#179': 'The Fourth Mural',
    'skitbdi#180': 'Deeper In',
    'skitbdi#181': 'Niata Appears',
    'skitbdi#182': 'Fangs Piercing the Heavens',
    'skitbdi#183': "Lazaris's War Declaration",
    'skitbdi#184': 'Cutoff Path',
    'skitbdi#185': 'People Who Witnessed Fangs',
    'skitbdi#186': 'Travel Tales for Kanonno',
    'skitbdi#187': "Lazaris's Goal",
    'skitbdi#188': 'Astral Crystal Substitute',
    'skitbdi#189': 'Seeking Salt Crystals',
    'skitbdi#190': 'How to Seal Lazaris?',
    'skitbdi#191': 'Shinobi Contraption',
    'skitbdi#192': 'Magic Is Soul Alchemy Too',
    'skitbdi#193': 'Barbatos Blocks the Way',
    'skitbdi#194': 'Barbatos Rematch',
    'skitbdi#195': 'Barbatos Departs',
    'skitbdi#196': 'Lecture from Sheena',
    'skitbdi#197': 'Salt Crystals Harvested!',
    'skitbdi#198': 'World Reaction to Fangs',
    'skitbdi#199': 'Sorrowful Lazaris',
    'skitbdi#200': 'Two Extinct Species',
    'skitbdi#201': "Kanonno's Doubts",
    'skitbdi#202': "Judith's Summons",
    'skitbdi#203': "Niata's Fragment",
    'skitbdi#204': "Rocks's Cry",
    'skitbdi#205': "Parents' Portrait",
    'skitbdi#206': 'Surveying the Fangs',
    'skitbdi#207': 'How to Examine the Fangs?',
    'skitbdi#208': "Lloyd on Lazaris's World",
    'skitbdi#209': 'Defeat the Lava Golem!',
    'skitbdi#210': 'Lava Golem Rematch',
    'skitbdi#211': "Celsius's Tears",
    'skitbdi#212': 'Anomalous Space',
    'skitbdi#213': 'Base of the Fangs',
    'skitbdi#214': 'While Unconscious...',
    'skitbdi#215': 'Letter from Alta Village',
    'skitbdi#216': 'Analyzing the Fangs',
    'skitbdi#217': 'Fossil Gathering Duty',
    'skitbdi#218': 'Thanks to the Descender?',
    'skitbdi#219': 'Mysterious Mechanism',
    'skitbdi#220': 'Chamber of Ode to Life',
    'skitbdi#221': 'Who Owns the Ruins?',
    'skitbdi#222': 'Good News from Alta Village',
    'skitbdi#223': 'Strange Script',
    'skitbdi#224': 'Wanting to Meet Niata',
    'skitbdi#225': 'Bringing Kanonno Along',
    'skitbdi#226': 'Kanonno Inside Veratropa',
    'skitbdi#227': 'Beyond the Severed Path',
    'skitbdi#228': 'Path Discovered',
    'skitbdi#229': 'World Born of Another',
    'skitbdi#230': 'Niata Revived',
    'skitbdi#231': 'Rocks in Great Panic',
    'skitbdi#232': 'Mysteries in Kanonno',
    'skitbdi#233': 'Semi-Perpetual Ship',
    'skitbdi#234': "Niata's Pledge",
    'skitbdi#235': 'Unexpected Hint',
    'skitbdi#236': 'Seeking Evolved Species',
    'skitbdi#237': 'Seeking Oil Trees',
    'skitbdi#238': 'What Are Oil Trees Like?',
    'skitbdi#239': 'Path Celsius Granted',
    'skitbdi#240': 'Scream in the Wind',
    'skitbdi#241': 'Captured Claire',
    'skitbdi#242': 'Saleh Rematch (2)',
    'skitbdi#243': "Saleh's Malice",
    'skitbdi#244': 'Evolved Species Gathered',
    'skitbdi#245': 'Next Thing to Gather?',
    'skitbdi#246': 'Harvest Field Notes',
    'skitbdi#247': 'Head for the Yurlung Tree',
    'skitbdi#248': 'Natalia Thinks of Home',
    'skitbdi#249': 'Seven-Colored Blossom',
    'skitbdi#250': 'Defeat the Ankyrabull!',
    'skitbdi#251': 'Ankyrabull Rematch',
    'skitbdi#252': 'Choice of the Yurlung Tree',
    'skitbdi#253': 'More Species Delivered',
    'skitbdi#254': 'Otherworldly Ad Libitum',
    'skitbdi#255': "Natalia's Plan",
    'skitbdi#256': 'Fresh Documents',
    'skitbdi#257': 'Seeking Tumblegrass',
    'skitbdi#258': "Loni's Worry",
    'skitbdi#259': 'By Pure Chance',
    'skitbdi#260': 'Meanwhile, Lazaris...',
    'skitbdi#261': 'Loni Quizzes Stahn',
    'skitbdi#262': 'Greenery in the Sands',
    'skitbdi#263': 'Anomalous Climate',
    'skitbdi#264': 'People of Zirdia',
    'skitbdi#265': 'Multiplying Fangs',
    'skitbdi#266': 'Harmony in Nature & Humankind',
    'skitbdi#267': "Niata's Query",
    'skitbdi#268': "Kanonno's Resolve",
    'skitbdi#269': 'Means to Know Memories',
    'skitbdi#270': 'To the Vortex',
    'skitbdi#271': "Descender's Hesitation",
    'skitbdi#272': 'Severing Mind and Flesh',
    'skitbdi#273': 'On Connections',
    'skitbdi#274': 'Defeat Decarabia!',
    'skitbdi#275': 'Decarabia Rematch',
    'skitbdi#276': 'Unused',
    'skitbdi#277': 'Into the Vortex',
    'skitbdi#278': 'Farthest Edge of Memory',
    'skitbdi#279': 'Time of Genesis',
    'skitbdi#280': 'Crystals Are a Cradle',
    'skitbdi#281': 'Return to the Present',
    'skitbdi#282': 'We Must Change',
    'skitbdi#283': 'In Everyday Scenery',
    'skitbdi#284': 'Docments Are Life',
    'skitbdi#285': 'Partaking of Life',
    'skitbdi#286': "Harold's Inspiration",
    'skitbdi#287': 'A Daring Hypothesis',
    'skitbdi#288': 'Seeking Gibeon',
    'skitbdi#289': 'Comrades Now',
    'skitbdi#290': 'Fog Clears',
    'skitbdi#291': 'Troubled Youth',
    'skitbdi#292': 'Defeat the Behemoth!',
    'skitbdi#293': 'Behemoth Rematch',
    'skitbdi#294': 'Gibeon Gathered',
    'skitbdi#295': 'Hand Gibeon to Harold',
    'skitbdi#296': 'To the Lab',
    'skitbdi#297': 'Transcriptor',
    'skitbdi#298': 'Ability Transcription',
    'skitbdi#299': 'Verifying Transcription',
    'skitbdi#300': "Kanonno's Gift Is...?",
    'skitbdi#301': 'War Rekindled',
    'skitbdi#302': 'Shirley & the Sea Breeze',
    'skitbdi#303': 'Shirley Thrives in Fresh Water',
    'skitbdi#304': 'No Time for Rest',
    'skitbdi#305': "Kanonno's Rainbow Light",
    'skitbdi#306': 'Two Who Remember',
    'skitbdi#307': 'Deliver the Light of Hope',
    'skitbdi#308': 'Thank You for Hope',
    'skitbdi#309': 'Docment on the Tree Stump',
    'skitbdi#310': 'Gift from the World',
    'skitbdi#311': 'Spiral Gall Docment',
    'skitbdi#312': 'The Wager',
    'skitbdi#313': 'Gibeon Chip (1)',
    'skitbdi#314': 'Defeat Caverex! (1)',
    'skitbdi#315': 'Caverex Rematch (1)',
    'skitbdi#316': 'Gibeon Chip (2)',
    'skitbdi#317': 'Defeat Caverex! (2)',
    'skitbdi#318': 'Caverex Rematch (2)',
    'skitbdi#319': 'Gibeon Chip (3)',
}
