# SKITBDI-02 translation mapping (ids 320 to 639)
# All ASCII, <= 63 bytes, natural English Tales skit titles

SKITBDI_2 = {
    'skitbdi#320': 'Defeat Caverex! (3)',
    'skitbdi#321': 'Caverex Rematch (3)',
    'skitbdi#322': 'Gibeon Chip (4)',
    'skitbdi#323': 'A Long Road',
    'skitbdi#324': "Iria's Apology",
    'skitbdi#325': 'All Prepared',
    'skitbdi#326': 'Now, to the Vortex',
    'skitbdi#327': "Let's Change Together",
    'skitbdi#328': 'Make a Path Unseen',
    'skitbdi#329': 'Reason for Yielding Power',
    'skitbdi#330': 'Reach the World Tree, Docment',
    'skitbdi#331': 'Sealed Dimension Deployed',
    'skitbdi#332': 'The Descender Falls',
    'skitbdi#333': 'World Tree Eroded',
    'skitbdi#334': 'Give Me Some Time',
    'skitbdi#335': 'A Path to the Future',
    'skitbdi#336': 'The Final Request',
    'skitbdi#337': "Lazaris's World",
    'skitbdi#338': "Guardian of Zirdia (1)",
    'skitbdi#339': "Guardian of Zirdia (2)",
    'skitbdi#340': "Guardian of Zirdia (3)",
    'skitbdi#341': "Guardian of Zirdia (4)",
    'skitbdi#342': "Guardian of Zirdia Rematch (1)",
    'skitbdi#343': "Guardian of Zirdia Rematch (2)",
    'skitbdi#344': "Guardian of Zirdia Rematch (3)",
    'skitbdi#345': "Guardian of Zirdia Rematch (4)",
    'skitbdi#346': 'Proceed with Care',
    'skitbdi#347': "Staking the World's Future",
    'skitbdi#348': 'Lazaris Rematch',
    'skitbdi#349': 'Power Toward Chaos',
    'skitbdi#350': 'Unused',
    'skitbdi#351': 'To the Field of Life',
    'skitbdi#352': 'One Who Knows No Limits',
    'skitbdi#353': 'A Brand-New World',
    'skitbdi#354': "Return of the Descender",
    'skitbdi#355': 'The Story Continues',
    'skitbdi#356': 'Transmission with Granide',
    'skitbdi#357': 'Earhart Arrives',
    'skitbdi#358': 'Adopting Alien Tech',
    'skitbdi#359': 'Kanonno & Kanonno',
    'skitbdi#360': 'Those Who Cannot Return',
    'skitbdi#361': 'Girl from Pasca',
    'skitbdi#362': 'Foreign Descender Enters',
    'skitbdi#363': 'Triple Kanonno',
    'skitbdi#364': 'Trial Play Commences',
    'skitbdi#365': 'More Allies Joined!',
    'skitbdi#366': 'More Like Tales',
    'skitbdi#367': 'Character Creation Fun',
    'skitbdi#368': 'Powered-Up Combat',
    'skitbdi#369': 'About the Sorcerer Ring',
    'skitbdi#370': 'Boss Spotted!',
    'skitbdi#371': 'Battle Victory!',
    'skitbdi#372': 'Regrettably, Time Is Up',
    'skitbdi#373': 'Wiped Out...',
    'skitbdi#374': 'Holding the Sorcerer Ring',
    'skitbdi#375': "Chat's Grievance",
    'skitbdi#376': 'Dread from Front and Rear',
    'skitbdi#377': 'Defeat the Fearbronck!',
    'skitbdi#378': 'Fearbronck Rematch',
    'skitbdi#379': 'Target Lies Ahead',
    'skitbdi#380': 'Red Ring Spot',
    'skitbdi#381': 'Sorcerer Ring Effect (1)',
    'skitbdi#382': 'Use the Ring as You Wish',
    'skitbdi#383': 'New Ring Spot Located',
    'skitbdi#384': 'Destination: Red Oasis',
    'skitbdi#385': 'What Is the Red Oasis?',
    'skitbdi#386': 'I Love Miso So Much',
    'skitbdi#387': 'Defeat Breeze Spirits!',
    'skitbdi#388': 'Breeze Spirits Rematch',
    'skitbdi#389': 'Bomb Planted!',
    'skitbdi#390': 'Yellow Ring Spot',
    'skitbdi#391': 'Sorcerer Ring Effect (2)',
    'skitbdi#392': 'Mysterious Black Orb',
    'skitbdi#393': 'Wish of the Black Orb',
    'skitbdi#394': 'Aim for the Summit',
    'skitbdi#395': 'Return of the Black Orb',
    'skitbdi#396': 'Three Treasure Chests',
    'skitbdi#397': 'Three White Brothers',
    'skitbdi#398': 'Wish of the White Orb',
    'skitbdi#399': 'Three-Colored Orbs',
    'skitbdi#400': 'Where the Three Orbs Wish',
    'skitbdi#401': 'Guide the Way for Us',
    'skitbdi#402': 'Role of the Three Orbs',
    'skitbdi#403': 'What Is Granide Like?',
    'skitbdi#404': 'Defeat Grossberva!',
    'skitbdi#405': 'Grossberva Rematch',
    'skitbdi#406': 'White Ring Spot',
    'skitbdi#407': 'Sorcerer Ring Effect (3)',
    'skitbdi#408': 'VS Dhaos (1)',
    'skitbdi#409': 'VS Dhaos (2)',
    'skitbdi#410': 'VS Dhaos (3)',
    'skitbdi#411': 'VS Yggdrasill (1)',
    'skitbdi#412': 'VS Yggdrasill (2)',
    'skitbdi#413': 'VS Yggdrasill (3)',
    'skitbdi#414': 'VS Dhaos & Yggdrasill (1)',
    'skitbdi#415': 'VS Dhaos & Yggdrasill (2)',
    'skitbdi#416': 'VS Dhaos & Yggdrasill (3)',
    'skitbdi#417': 'As Friend, As Rival (1)',
    'skitbdi#418': 'As Friend, As Rival (2)',
    'skitbdi#419': 'As Friend, As Rival (3)',
    'skitbdi#420': 'As Friend, As Rival (4)',
    'skitbdi#421': 'As Friend, As Rival (5)',
    'skitbdi#422': 'As Friend, As Rival (6)',
    'skitbdi#423': 'Crab Panic (1)',
    'skitbdi#424': 'Crab Panic (2)',
    'skitbdi#425': 'Crab Panic (3)',
    'skitbdi#426': 'Crab Panic (4)',
    'skitbdi#427': 'Crab Panic (5)',
    'skitbdi#428': 'Crab Panic (6)',
    'skitbdi#429': 'Crab Panic (7)',
    'skitbdi#430': 'Mutual Justice (1)',
    'skitbdi#431': 'Mutual Justice (2)',
    'skitbdi#432': 'Mutual Justice (3)',
    'skitbdi#433': 'Mutual Justice (4)',
    'skitbdi#434': 'Mutual Justice (5)',
    'skitbdi#435': 'Mutual Justice (6)',
    'skitbdi#436': 'Mutual Justice (7)',
    'skitbdi#437': 'Mutual Justice (8)',
    'skitbdi#438': 'A Wall to Overcome (1)',
    'skitbdi#439': 'A Wall to Overcome (2)',
    'skitbdi#440': 'A Wall to Overcome (3)',
    'skitbdi#441': 'A Wall to Overcome (4)',
    'skitbdi#442': 'A Wall to Overcome (5)',
    'skitbdi#443': 'A Wall to Overcome (6)',
    'skitbdi#444': 'A Wall to Overcome (7)',
    'skitbdi#445': 'A Wall to Overcome (8)',
    'skitbdi#446': 'A Wall to Overcome (9)',
    'skitbdi#447': 'Closed Hearts, Open Future (1)',
    'skitbdi#448': 'Closed Hearts, Open Future (2)',
    'skitbdi#449': 'Closed Hearts, Open Future (3)',
    'skitbdi#450': 'Closed Hearts, Open Future (4)',
    'skitbdi#451': 'Closed Hearts, Open Future (5)',
    'skitbdi#452': 'Closed Hearts, Open Future (6)',
    'skitbdi#453': 'Closed Hearts, Open Future (7)',
    'skitbdi#454': 'Closed Hearts, Open Future (8)',
    'skitbdi#455': 'Legendary Battle (1)',
    'skitbdi#456': 'Legendary Battle (2)',
    'skitbdi#457': 'Legendary Battle (3)',
    'skitbdi#458': 'Legendary Battle (4)',
    'skitbdi#459': 'Legendary Battle (5)',
    'skitbdi#460': 'Legendary Battle (6)',
    'skitbdi#461': 'Legendary Battle (7)',
    'skitbdi#462': 'Legendary Battle (8)',
    'skitbdi#463': 'Fateful Showdown (1)',
    'skitbdi#464': 'Fateful Showdown (2)',
    'skitbdi#465': 'Fateful Showdown (3)',
    'skitbdi#466': 'Fateful Showdown (4)',
    'skitbdi#467': 'Fateful Showdown (5)',
    'skitbdi#468': 'Fateful Showdown (6)',
    'skitbdi#469': 'Fateful Showdown (7)',
    'skitbdi#470': 'Fateful Showdown (8)',
    'skitbdi#471': 'Dark Dance of Angels (1)',
    'skitbdi#472': 'Dark Dance of Angels (2)',
    'skitbdi#473': 'Dark Dance of Angels (3)',
    'skitbdi#474': 'Dark Dance of Angels (4)',
    'skitbdi#475': 'Dark Dance of Angels (5)',
    'skitbdi#476': 'Dark Dance of Angels (6)',
    'skitbdi#477': 'Dark Dance of Angels (7)',
    'skitbdi#478': 'Dark Dance of Angels (8)',
    'skitbdi#479': 'Dark Dance of Angels (9)',
    'skitbdi#480': 'Final Decisive Battle (1)',
    'skitbdi#481': 'Final Decisive Battle (2)',
    'skitbdi#482': 'Final Decisive Battle (3)',
    'skitbdi#483': 'Final Decisive Battle (4)',
    'skitbdi#484': 'Final Decisive Battle (5)',
    'skitbdi#485': 'Final Decisive Battle (6)',
    'skitbdi#486': 'Final Decisive Battle (7)',
    'skitbdi#487': 'Final Decisive Battle (8)',
    'skitbdi#488': 'The Two Kings (1)',
    'skitbdi#489': 'The Two Kings (2)',
    'skitbdi#490': 'The Two Kings (3)',
    'skitbdi#491': 'The Two Kings (4)',
    'skitbdi#492': 'The Two Kings (5)',
    'skitbdi#493': 'The Two Kings (6)',
    'skitbdi#494': 'The Two Kings (7)',
    'skitbdi#495': 'The Two Kings (8)',
    'skitbdi#496': 'The Two Kings (9)',
    'skitbdi#497': 'A Battle We Cannot Lose (1)',
    'skitbdi#498': 'A Battle We Cannot Lose (2)',
    'skitbdi#499': 'A Battle We Cannot Lose (3)',
    'skitbdi#500': 'A Battle We Cannot Lose (4)',
    'skitbdi#501': 'A Battle We Cannot Lose (5)',
    'skitbdi#502': 'A Battle We Cannot Lose (6)',
    'skitbdi#503': 'A Battle We Cannot Lose (7)',
    'skitbdi#504': 'Truly Scary Fairy Tales (1)',
    'skitbdi#505': 'Truly Scary Fairy Tales (2)',
    'skitbdi#506': 'Truly Scary Fairy Tales (3)',
    'skitbdi#507': 'Truly Scary Fairy Tales (4)',
    'skitbdi#508': 'Truly Scary Fairy Tales (5)',
    'skitbdi#509': 'Truly Scary Fairy Tales (6)',
    'skitbdi#510': 'Truly Scary Fairy Tales (7)',
    'skitbdi#511': 'Truly Scary Fairy Tales (8)',
    'skitbdi#512': 'Truly Scary Fairy Tales (9)',
    'skitbdi#513': 'An Anxious Pair (1)',
    'skitbdi#514': 'An Anxious Pair (2)',
    'skitbdi#515': 'An Anxious Pair (3)',
    'skitbdi#516': 'An Anxious Pair (4)',
    'skitbdi#517': 'An Anxious Pair (5)',
    'skitbdi#518': 'An Anxious Pair (6)',
    'skitbdi#519': 'An Anxious Pair (7)',
    'skitbdi#520': 'An Anxious Pair (8)',
    'skitbdi#521': 'An Anxious Pair (9)',
    'skitbdi#522': 'Seeking the Finest Item (1)',
    'skitbdi#523': 'Seeking the Finest Item (2)',
    'skitbdi#524': 'Seeking the Finest Item (3)',
    'skitbdi#525': 'Seeking the Finest Item (4)',
    'skitbdi#526': 'Seeking the Finest Item (5)',
    'skitbdi#527': 'Seeking the Finest Item (6)',
    'skitbdi#528': 'Seeking the Finest Item (7)',
    'skitbdi#529': 'Seeking the Finest Item (8)',
    'skitbdi#530': "Richter's Combat Guide (1)",
    'skitbdi#531': "Richter's Combat Guide (2)",
    'skitbdi#532': "Richter's Combat Guide (3)",
    'skitbdi#533': "Richter's Combat Guide (4)",
    'skitbdi#534': "Richter's Combat Guide (5)",
    'skitbdi#535': "Richter's Combat Guide (6)",
    'skitbdi#536': 'Value of the Reward (1)',
    'skitbdi#537': 'Value of the Reward (2)',
    'skitbdi#538': 'Value of the Reward (3)',
    'skitbdi#539': 'Value of the Reward (4)',
    'skitbdi#540': 'Value of the Reward (5)',
    'skitbdi#541': 'Value of the Reward (6)',
    'skitbdi#542': 'The Trial to Overcome (1)',
    'skitbdi#543': 'The Trial to Overcome (2)',
    'skitbdi#544': 'The Trial to Overcome (3)',
    'skitbdi#545': 'The Trial to Overcome (4)',
    'skitbdi#546': 'The Trial to Overcome (5)',
    'skitbdi#547': 'The Trial to Overcome (6)',
    'skitbdi#548': 'The Trial to Overcome (7)',
    'skitbdi#549': 'The Trial to Overcome (8)',
    'skitbdi#550': 'The Trial to Overcome (9)',
    'skitbdi#551': 'Spirit of My Heart (1)',
    'skitbdi#552': 'Spirit of My Heart (2)',
    'skitbdi#553': 'Spirit of My Heart (3)',
    'skitbdi#554': 'Spirit of My Heart (4)',
    'skitbdi#555': 'Spirit of My Heart (5)',
    'skitbdi#556': 'Spirit of My Heart (6)',
    'skitbdi#557': 'Save the Keepsake Flower! (1)',
    'skitbdi#558': 'Save the Keepsake Flower! (2)',
    'skitbdi#559': 'Save the Keepsake Flower! (3)',
    'skitbdi#560': 'Save the Keepsake Flower! (4)',
    'skitbdi#561': 'Save the Keepsake Flower! (5)',
    'skitbdi#562': 'Save the Keepsake Flower! (6)',
    'skitbdi#563': 'Save the Keepsake Flower! (7)',
    'skitbdi#564': 'Gentle Big Bro (1)',
    'skitbdi#565': 'Gentle Big Bro (2)',
    'skitbdi#566': 'Gentle Big Bro (3)',
    'skitbdi#567': 'Gentle Big Bro (4)',
    'skitbdi#568': 'Gentle Big Bro (5)',
    'skitbdi#569': 'Gentle Big Bro (6)',
    'skitbdi#570': "Wise King's Tour (1)",
    'skitbdi#571': "Wise King's Tour (2)",
    'skitbdi#572': "Wise King's Tour (3)",
    'skitbdi#573': "Wise King's Tour (4)",
    'skitbdi#574': "Wise King's Tour (5)",
    'skitbdi#575': 'Solitary Boy Swordsman (1)',
    'skitbdi#576': 'Solitary Boy Swordsman (2)',
    'skitbdi#577': 'Solitary Boy Swordsman (3)',
    'skitbdi#578': 'Solitary Boy Swordsman (4)',
    'skitbdi#579': 'Solitary Boy Swordsman (5)',
    'skitbdi#580': 'Solitary Boy Swordsman (6)',
    'skitbdi#581': 'Solitary Boy Swordsman (7)',
    'skitbdi#582': 'Girl Living for Love (1)',
    'skitbdi#583': 'Girl Living for Love (2)',
    'skitbdi#584': 'Girl Living for Love (3)',
    'skitbdi#585': 'Girl Living for Love (4)',
    'skitbdi#586': 'Girl Living for Love (5)',
    'skitbdi#587': 'Girl Living for Love (6)',
    'skitbdi#588': 'A Teacher for the Guild (1)',
    'skitbdi#589': 'A Teacher for the Guild (2)',
    'skitbdi#590': 'A Teacher for the Guild (3)',
    'skitbdi#591': 'A Teacher for the Guild (4)',
    'skitbdi#592': 'A Teacher for the Guild (5)',
    'skitbdi#593': 'Emissary of Love Attacks (1)',
    'skitbdi#594': 'Emissary of Love Attacks (2)',
    'skitbdi#595': 'Emissary of Love Attacks (3)',
    'skitbdi#596': 'Emissary of Love Attacks (4)',
    'skitbdi#597': 'Emissary of Love Attacks (5)',
    'skitbdi#598': 'Emissary of Love Attacks (6)',
    'skitbdi#599': 'Together with You (1)',
    'skitbdi#600': 'Together with You (2)',
    'skitbdi#601': 'Together with You (3)',
    'skitbdi#602': 'Together with You (4)',
    'skitbdi#603': 'Together with You (5)',
    'skitbdi#604': 'Together with You (6)',
    'skitbdi#605': 'Hocus Pocus Magic (1)',
    'skitbdi#606': 'Hocus Pocus Magic (2)',
    'skitbdi#607': 'Hocus Pocus Magic (3)',
    'skitbdi#608': 'Hocus Pocus Magic (4)',
    'skitbdi#609': 'Hocus Pocus Magic (5)',
    'skitbdi#610': 'Hocus Pocus Magic (6)',
    'skitbdi#611': 'Defeat the Insolent Rogue! (1)',
    'skitbdi#612': 'Defeat the Insolent Rogue! (2)',
    'skitbdi#613': 'Defeat the Insolent Rogue! (3)',
    'skitbdi#614': 'Defeat the Insolent Rogue! (4)',
    'skitbdi#615': 'Defeat the Insolent Rogue! (5)',
    'skitbdi#616': 'Defeat the Insolent Rogue! (6)',
    'skitbdi#617': 'Defeat the Insolent Rogue! (7)',
    'skitbdi#618': 'Troublesome Dream Thief (1)',
    'skitbdi#619': 'Troublesome Dream Thief (2)',
    'skitbdi#620': 'Troublesome Dream Thief (3)',
    'skitbdi#621': 'Troublesome Dream Thief (4)',
    'skitbdi#622': 'Troublesome Dream Thief (5)',
    'skitbdi#623': 'Troublesome Dream Thief (6)',
    'skitbdi#624': 'Fluffy Fluffiness (1)',
    'skitbdi#625': 'Fluffy Fluffiness (2)',
    'skitbdi#626': 'Fluffy Fluffiness (3)',
    'skitbdi#627': 'Fluffy Fluffiness (4)',
    'skitbdi#628': 'Fluffy Fluffiness (5)',
    'skitbdi#629': "Master Luke's Entourage (1)",
    'skitbdi#630': "Master Luke's Entourage (2)",
    'skitbdi#631': "Master Luke's Entourage (3)",
    'skitbdi#632': "Master Luke's Entourage (4)",
    'skitbdi#633': "Master Luke's Entourage (5)",
    'skitbdi#634': "Master Luke's Entourage (6)",
    'skitbdi#635': 'Love Money :D (1)',
    'skitbdi#636': 'Love Money :D (2)',
    'skitbdi#637': 'Love Money :D (3)',
    'skitbdi#638': 'Love Money :D (4)',
    'skitbdi#639': 'Love Money :D (5)',
}
