# SKITBDI-03 translation mapping (ids 640 to 889)
# All ASCII, <= 63 bytes, natural English Tales skit titles

SKITBDI_3 = {
    'skitbdi#640': 'Love Money :D (6)',
    'skitbdi#641': 'The Missing Mercenary (1)',
    'skitbdi#642': 'The Missing Mercenary (2)',
    'skitbdi#643': 'The Missing Mercenary (3)',
    'skitbdi#644': 'The Missing Mercenary (4)',
    'skitbdi#645': 'The Missing Mercenary (5)',
    'skitbdi#646': 'Noble Knight Commander (1)',
    'skitbdi#647': 'Noble Knight Commander (2)',
    'skitbdi#648': 'Noble Knight Commander (3)',
    'skitbdi#649': 'Noble Knight Commander (4)',
    'skitbdi#650': 'Noble Knight Commander (5)',
    'skitbdi#651': 'Noble Knight Commander (6)',
    'skitbdi#652': 'Mysterious Missing Notice (1)',
    'skitbdi#653': 'Mysterious Missing Notice (2)',
    'skitbdi#654': 'Mysterious Missing Notice (3)',
    'skitbdi#655': 'Mysterious Missing Notice (4)',
    'skitbdi#656': 'Mysterious Missing Notice (5)',
    'skitbdi#657': 'Mysterious Missing Notice (6)',
    'skitbdi#658': 'Missing Childhood Friend (1)',
    'skitbdi#659': 'Missing Childhood Friend (2)',
    'skitbdi#660': 'Missing Childhood Friend (3)',
    'skitbdi#661': 'Missing Childhood Friend (4)',
    'skitbdi#662': 'Missing Childhood Friend (5)',
    'skitbdi#663': 'Missing Childhood Friend (6)',
    'skitbdi#664': 'To Meet the Radiant (1)',
    'skitbdi#665': 'To Meet the Radiant (2)',
    'skitbdi#666': 'To Meet the Radiant (3)',
    'skitbdi#667': 'To Meet the Radiant (4)',
    'skitbdi#668': 'To Meet the Radiant (5)',
    'skitbdi#669': 'To Meet the Radiant (6)',
    'skitbdi#670': 'To Meet the Radiant (7)',
    'skitbdi#671': 'To Meet the Radiant (8)',
    'skitbdi#672': 'Legendary Arms (1)',
    'skitbdi#673': 'Legendary Arms (2)',
    'skitbdi#674': 'Legendary Arms (3)',
    'skitbdi#675': 'Enter the Wonder Baker! (1)',
    'skitbdi#676': 'Enter the Wonder Baker! (2)',
    'skitbdi#677': 'Enter the Wonder Baker! (3)',
    'skitbdi#678': 'Enter the Wonder Baker! (4)',
    'skitbdi#679': 'Enter the Wonder Baker! (5)',
    'skitbdi#680': 'Wandering Baker (1)',
    'skitbdi#681': 'Wandering Baker (2)',
    'skitbdi#682': 'Wandering Baker (3)',
    'skitbdi#683': 'Wandering Baker (4)',
    'skitbdi#684': 'Wandering Baker (5)',
    'skitbdi#685': 'Roaming Baker (1)',
    'skitbdi#686': 'Roaming Baker (2)',
    'skitbdi#687': 'Roaming Baker (3)',
    'skitbdi#688': 'Roaming Baker (4)',
    'skitbdi#689': 'Roaming Baker (5)',
    'skitbdi#690': 'Twilight Baker (1)',
    'skitbdi#691': 'Twilight Baker (2)',
    'skitbdi#692': 'Twilight Baker (3)',
    'skitbdi#693': 'Twilight Baker (4)',
    'skitbdi#694': 'Twilight Baker (5)',
    'skitbdi#695': 'Legendary Baker (1)',
    'skitbdi#696': 'Legendary Baker (2)',
    'skitbdi#697': 'Legendary Baker (3)',
    'skitbdi#698': 'Legendary Baker (4)',
    'skitbdi#699': 'Legendary Baker (5)',
    'skitbdi#700': 'Legendary Baker (6)',
    'skitbdi#701': 'Legendary Baker (7)',
    'skitbdi#702': 'Find Poppo, Kyu! (1)',
    'skitbdi#703': 'Find Poppo, Kyu! (2)',
    'skitbdi#704': 'Find Poppo, Kyu! (3)',
    'skitbdi#705': 'Find Poppo, Kyu! (4)',
    'skitbdi#706': 'Find the Golden Hammer! (1)',
    'skitbdi#707': 'Find the Golden Hammer! (2)',
    'skitbdi#708': 'Find the Golden Hammer! (3)',
    'skitbdi#709': 'Find the Blazing Coke! (1)',
    'skitbdi#710': 'Find the Blazing Coke! (2)',
    'skitbdi#711': 'Find the Blazing Coke! (3)',
    'skitbdi#712': 'Find the Gale Bellows! (1)',
    'skitbdi#713': 'Find the Gale Bellows! (2)',
    'skitbdi#714': 'Find the Gale Bellows! (3)',
    'skitbdi#715': 'Find the Pure Garb! (1)',
    'skitbdi#716': 'Find the Pure Garb! (2)',
    'skitbdi#717': 'Find the Pure Garb! (3)',
    'skitbdi#718': "Coda's Recipe 1 (1)",
    'skitbdi#719': "Coda's Recipe 1 (2)",
    'skitbdi#720': "Coda's Recipe 1 (3)",
    'skitbdi#721': "Coda's Recipe 2 (1)",
    'skitbdi#722': "Coda's Recipe 2 (2)",
    'skitbdi#723': "Coda's Recipe 2 (3)",
    'skitbdi#724': "Coda's Recipe 3 (1)",
    'skitbdi#725': "Coda's Recipe 3 (2)",
    'skitbdi#726': "Coda's Recipe 3 (3)",
    'skitbdi#727': "Coda's Recipe 4 (1)",
    'skitbdi#728': "Coda's Recipe 4 (2)",
    'skitbdi#729': "Coda's Recipe 4 (3)",
    'skitbdi#730': "Coda's Recipe 5 (1)",
    'skitbdi#731': "Coda's Recipe 5 (2)",
    'skitbdi#732': "Coda's Recipe 5 (3)",
    'skitbdi#733': "Coda's Recipe 6 (1)",
    'skitbdi#734': "Coda's Recipe 6 (2)",
    'skitbdi#735': "Coda's Recipe 6 (3)",
    'skitbdi#736': "Coda's Recipe 7 (1)",
    'skitbdi#737': "Coda's Recipe 7 (2)",
    'skitbdi#738': "Coda's Recipe 7 (3)",
    'skitbdi#739': "Coda's Recipe 8 (1)",
    'skitbdi#740': "Coda's Recipe 8 (2)",
    'skitbdi#741': "Coda's Recipe 8 (3)",
    'skitbdi#742': "Coda's Recipe 9 (1)",
    'skitbdi#743': "Coda's Recipe 9 (2)",
    'skitbdi#744': "Coda's Recipe 9 (3)",
    'skitbdi#745': "Coda's Recipe 10 (1)",
    'skitbdi#746': "Coda's Recipe 10 (2)",
    'skitbdi#747': "Coda's Recipe 10 (3)",
    'skitbdi#748': "Coda's Recipe 11 (1)",
    'skitbdi#749': "Coda's Recipe 11 (2)",
    'skitbdi#750': "Coda's Recipe 11 (3)",
    'skitbdi#751': 'I Am a Champion',
    'skitbdi#752': 'The Strongest Sister',
    'skitbdi#753': 'Guild Review',
    'skitbdi#754': '(Unused)',
    'skitbdi#755': 'Storage',
    'skitbdi#756': 'Changing to New Classes',
    'skitbdi#757': 'Blacksmith: In Preparation',
    'skitbdi#758': 'Blacksmith: Open for Business',
    'skitbdi#759': 'Blacksmith Rank 2',
    'skitbdi#760': 'Blacksmith Rank 3 Upgrade',
    'skitbdi#761': 'Blacksmith Rank 4 Upgrade',
    'skitbdi#762': 'Blacksmith Rank 5 Upgrade',
    'skitbdi#763': 'Grade Shop: Open',
    'skitbdi#764': 'Event Player',
    'skitbdi#765': 'Character Creation',
    'skitbdi#766': 'Strategy & Formations',
    'skitbdi#767': 'Cooking',
    'skitbdi#768': 'Pattern Items',
    'skitbdi#769': 'DLC Mercenaries',
    'skitbdi#770': 'Wipeout Risks',
    'skitbdi#771': 'The Arena',
    'skitbdi#772': 'Overlimit',
    'skitbdi#773': 'Switching Battle Characters',
    'skitbdi#774': 'Mystic Artes',
    'skitbdi#775': 'Using Storage Tips',
    'skitbdi#776': 'Qualities of a Leader',
    'skitbdi#777': 'Save Point',
    'skitbdi#778': 'How to Attack and Defend',
    'skitbdi#779': 'Item Drops',
    'skitbdi#780': 'Building a Bridge',
    'skitbdi#781': 'How to Open the Menu',
    'skitbdi#782': 'Blocking Enemies (1)',
    'skitbdi#783': 'How to Use Artes',
    'skitbdi#784': 'Artes in the Menu',
    'skitbdi#785': 'Minimap',
    'skitbdi#786': 'Blocking Enemies (2)',
    'skitbdi#787': 'Battle Menu',
    'skitbdi#788': 'Encounters',
    'skitbdi#789': 'To the Meeting Point',
    'skitbdi#790': 'Not That Way (1)',
    'skitbdi#791': 'Red Chest',
    'skitbdi#792': 'Green Chest',
    'skitbdi#793': 'Back to Square One',
    'skitbdi#794': 'Not That Way (2)',
    'skitbdi#795': 'Ship Map',
    'skitbdi#796': 'Greet Everyone (1)',
    'skitbdi#797': 'Checking the Ship Map',
    'skitbdi#798': 'Check the Ship Map',
    'skitbdi#799': 'Observation Room Tour',
    'skitbdi#800': 'Wheelhouse Tour',
    'skitbdi#801': 'Skit Tutorial',
    'skitbdi#802': 'First Skit',
    'skitbdi#803': 'About Saving',
    'skitbdi#804': 'Deck Tour',
    'skitbdi#805': 'Closed for Now',
    'skitbdi#806': 'Greetings Complete (1)',
    'skitbdi#807': 'Hurry to Ange (1)',
    'skitbdi#808': 'Cannot Go There Yet (1)',
    'skitbdi#809': 'Accept a Quest (1)',
    'skitbdi#810': 'Accepting Quests',
    'skitbdi#811': 'Quest Overview',
    'skitbdi#812': 'Travel Menu',
    'skitbdi#813': 'Job Going Well? (1)',
    'skitbdi#814': 'Off to the Destination',
    'skitbdi#815': 'World Map',
    'skitbdi#816': 'Quest Goal Reminder (1)',
    'skitbdi#817': 'Dead End Warning (1)',
    'skitbdi#818': 'Encounter Attack',
    'skitbdi#819': 'Monster Book',
    'skitbdi#820': 'Quick Return Overview',
    'skitbdi#821': 'Quick Return Is Handy',
    'skitbdi#822': 'Hurry to Ange (2)',
    'skitbdi#823': 'Mission Complete (1)',
    'skitbdi#824': 'First Reward',
    'skitbdi#825': 'First Shopping Trip',
    'skitbdi#826': 'Shop Introduction',
    'skitbdi#827': 'Weapon Shop Intro',
    'skitbdi#828': 'Armor Shop Intro',
    'skitbdi#829': 'Item Shop Intro',
    'skitbdi#830': 'Blacksmith Not Yet Open',
    'skitbdi#831': 'Store Check Prompt',
    'skitbdi#832': 'Shopping Complete',
    'skitbdi#833': 'Greet Everyone (2)',
    'skitbdi#834': 'All Greeted Yet?',
    'skitbdi#835': 'Greetings Complete (2)',
    'skitbdi#836': 'Hurry to Ange (3)',
    'skitbdi#837': 'How About the Next Job? (1)',
    'skitbdi#838': 'Accept a Quest (2)',
    'skitbdi#839': 'Hurry to Ange (4)',
    'skitbdi#840': 'Cannot Go There Yet (2)',
    'skitbdi#841': 'Gathering Tutorial',
    'skitbdi#842': 'Job Going Well? (2)',
    'skitbdi#843': 'Now, the Travel Menu (1)',
    'skitbdi#844': 'Triangle on World Map',
    'skitbdi#845': 'Not Here (1)',
    'skitbdi#846': 'Quest Goal Reminder (2)',
    'skitbdi#847': 'Not That Way (3)',
    'skitbdi#848': 'Dead End Warning (2)',
    'skitbdi#849': 'Gald Drops',
    'skitbdi#850': 'Blocking Enemies (3)',
    'skitbdi#851': 'Target Change',
    'skitbdi#852': 'Door Switch',
    'skitbdi#853': 'Blocking Enemies (4)',
    'skitbdi#854': 'Free Run',
    'skitbdi#855': "That's a Mining Point",
    'skitbdi#856': 'Copper Obtained',
    'skitbdi#857': 'About Mining Points',
    'skitbdi#858': 'Hurry to Ange (5)',
    'skitbdi#859': 'Mission Complete (2)',
    'skitbdi#860': 'Greet Everyone (3)',
    'skitbdi#861': 'Cabin Tour',
    'skitbdi#862': 'Greetings Complete (3)',
    'skitbdi#863': 'Character Book',
    'skitbdi#864': 'Hurry to Ange (6)',
    'skitbdi#865': 'How About the Next Job? (2)',
    'skitbdi#866': 'Accept a Quest (3)',
    'skitbdi#867': 'Subjugation Tutorial',
    'skitbdi#868': 'Job Going Well? (3)',
    'skitbdi#869': 'Now, the Travel Menu (2)',
    'skitbdi#870': 'Not Here (2)',
    'skitbdi#871': 'Quest Goal Reminder (3)',
    'skitbdi#872': 'About Crafting',
    'skitbdi#873': 'Boss Appears',
    'skitbdi#874': 'Victory!',
    'skitbdi#875': 'Hurry to Ange (7)',
    'skitbdi#876': 'Mission Complete (3)',
    'skitbdi#877': 'Now You Are Too',
    'skitbdi#878': 'Dismissed for Now',
    'skitbdi#879': 'Guiding to Garuda',
    'skitbdi#880': 'Trial Play Commences',
    'skitbdi#881': 'More Allies Joined!',
    'skitbdi#882': 'More Like Tales',
    'skitbdi#883': 'Character Creation Fun',
    'skitbdi#884': 'Powered-Up Combat',
    'skitbdi#885': 'About the Sorcerer Ring',
    'skitbdi#886': 'Boss Spotted!',
    'skitbdi#887': 'Battle Victory!',
    'skitbdi#888': 'Regrettably, Time Is Up',
    'skitbdi#889': 'Wiped Out...',
}
